// AUTO-GENERATED by scripts/font-axis-survey.js — committed on purpose. DO NOT hand-edit.
//
// THE LIGHTEST WEIGHT EACH DESIGN ACTUALLY ASKED GOOGLE FOR, for the families whose answer is above
// the CSS default of 400. Google serves only the weights the request names, so a reference that
// asked for `Fraunces:opsz,wght@9..144,500;9..144,600` could not have rendered a single glyph at
// 400 — while our display type, which declares no weight, renders at exactly that. Measured on the
// chrome lockup (identical string, identical size, same polarity) the reference carries ~17% more
// ink than our render of it.
//
// This is a FLOOR, not a setting: a skin that declares its own displayWeight always wins, and a
// family absent from this table is left at the browser default, which is what its design used.
//
// Regenerate: node scripts/font-axis-survey.js

const WEIGHT_FLOOR = {
  "Alegreya Sans SC": 500,
  "Baloo 2": 500,
  "Barlow Condensed": 500,
  "Big Shoulders Display": 600,
  "Caveat": 500,
  "Cinzel": 500,
  "Cormorant Garamond": 500,
  "EB Garamond": 500,
  "Fraunces": 500,
  "Fredoka": 500,
  "Gelasio": 500,
  "Grandstander": 500,
  "Grenze Gotisch": 500,
  "Kanit": 500,
  "Libre Bodoni": 500,
  "Orbitron": 500,
  "Playfair Display": 500,
  "Syne": 600,
  "Unbounded": 500,
  "Vollkorn": 500,
  "Zilla Slab": 500,
};

// The weight display type should render at for this family, or null to leave it to the browser.
function weightFloor(family) {
  if (!family) return null;
  const key = Object.keys(WEIGHT_FLOOR).find((k) => k.toLowerCase() === String(family).toLowerCase().trim());
  return key ? WEIGHT_FLOOR[key] : null;
}

module.exports = { WEIGHT_FLOOR, weightFloor };
