// ABYSS DIVE — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-1.js, template "AbyssDive").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Krona One / body Overpass. Camera set ["zoomOut","pushD","drop","pushL","zoomIn","pushU"].
// Entrances: title "drowse", items "rise".
// Owns the Ring:ring, Scroll:feed, Typing:terminal, Notify:side mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "abyss-dive",
  label: "Abyss Dive",

  // ---- type ----
  display: "Krona One", displayFallback: "sans-serif",
  body: "Overpass", bodyFallback: "sans-serif",
  mono: null,
  em: 0.74,
  titleLine: 1.12, titleSpace: "0",
  titlePreset: "drowse", itemPreset: "rise",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ deep: t.deep || "#061c26", glow: t.glow || "#35d0d6", coral: "#ff7e67", sand: "#e8d9b0", ink: "#04141c" }),
  accents: ["glow","coral","deep"],
  groundKey: "deep", inkKey: "ink", paperKey: "sand",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "deep",
      "fg": "sand",
      "hi": "glow",
      "world": true,
      "top": 340,
      "size": 108,
      "upper": true,
      "kicker": {
        "v": "outline",
        "c": "glow"
      }
    },
    "statement": {
      "bg": "ink",
      "fg": "sand",
      "hi": "coral",
      "world": true,
      "top": 640,
      "size": 132,
      "upper": true
    },
    "feature": {
      "bg": "deep",
      "fg": "sand",
      "hi": "glow",
      "world": true,
      "top": 250,
      "size": 88,
      "upper": true,
      "card": {
        "v": "glow",
        "bg": "ink",
        "glow": "glow",
        "r": 26,
        "line": "sand"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "glow",
          "coral"
        ],
        "text": "ink"
      }
    },
    "montage": {
      "bg": "ink",
      "fg": "sand",
      "hi": "glow",
      "world": true,
      "top": 258,
      "size": 86,
      "upper": true,
      "tile": {
        "bg": "#07222e",
        "line": "sand",
        "label": "glow",
        "r": 20,
        "glow": "glow"
      },
      "tilts": [
        -1.5,
        1,
        1.5,
        -1
      ]
    },
    "stats": {
      "bg": "deep",
      "fg": "sand",
      "hi": "glow",
      "world": true,
      "cols": [
        "glow",
        "coral",
        "sand"
      ],
      "num": 146,
      "upper": true,
      "glowNums": true
    },
    "cta": {
      "bg": "ink",
      "fg": "sand",
      "hi": "glow",
      "world": true,
      "top": 500,
      "size": 106,
      "upper": true,
      "btn": {
        "v": "glow",
        "bg": "glow",
        "c": "ink"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "deep",
      "fg": "sand",
      "hi": "glow",
      "cardBg": "#07202c",
      "line": "sand",
      "world": true,
      "upper": true
    }
  },

  // ---- camera + motion ----
  cams: ["zoomOut","pushD","drop","pushL","zoomIn","pushU"], camMul: 5, camOff: 3,
  mag: {"rot":0.4,"driftY":12,"driftX":9,"inn":0.3,"driftZ":0.04},
  ambient: 1.4,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Ring":"ring","Scroll":"feed","Typing":"terminal","Notify":"side"},

  strings: {
    brandName: "Abyss Dive",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round" }, R2("circle", { cx: 12, cy: 12, r: 8 }), R2("circle", { cx: 12, cy: 12, r: 3 }), R2("path", { d: "M12 4v-2M12 22v-2" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      Array.from({ length: 10 }).map((_, i) => {
        const ph = (t * (0.1 + (i % 4) * 0.05) + i * 0.1) % 1;
        return R("circle", { key: i, cx: (i * 117 + 40) % u.W + Math.sin(t + i) * 20, cy: u.H - ph * (u.H + 100), r: 5 + (i % 3) * 5, fill: "none", stroke: rgba(theme.glow, 0.35 * (1 - ph) + 0.08), strokeWidth: 3 });
      }),
      (function () {
        const jx = u.W * 0.72 + Math.sin(t * 0.5) * 60, jy = 360 + Math.cos(t * 0.4) * 50;
        return R("g", { transform: "translate(" + jx + "," + jy + ")", opacity: 0.75 },
          R("path", { d: "M -60 0 a 60 60 0 0 1 120 0 q -12 " + (16 + Math.sin(t * 2.2) * 10) + " -30 0 q -15 " + (20 + Math.cos(t * 2) * 8) + " -30 0 q -15 " + (16 + Math.sin(t * 2.4) * 10) + " -30 0 q -18 14 -30 0 Z", fill: rgba(theme.coral, 0.5) }),
          [0, 1, 2].map((i) => R("path", { key: i, d: "M " + (-30 + i * 30) + " 20 q " + (Math.sin(t * 1.8 + i) * 18) + " 60 0 120", fill: "none", stroke: rgba(theme.coral, 0.4), strokeWidth: 5, strokeLinecap: "round" })));
      })(),
      R("circle", { cx: 170, cy: u.H - 480, r: 15 + Math.sin(t * 3) * 5, fill: rgba(theme.glow, 0.7 + Math.sin(t * 3) * 0.25) }),
      R("path", { d: "M 170 " + (u.H - 480) + " q -50 40 -40 110", fill: "none", stroke: rgba(theme.sand, 0.3), strokeWidth: 6, strokeLinecap: "round" }),
      Array.from({ length: 5 }).map((_, i) => R("g", { key: "r" + i },
        R("line", { x1: u.W - 60, y1: 200 + i * 180, x2: u.W - 30, y2: 200 + i * 180, stroke: rgba(theme.sand, 0.4), strokeWidth: 4 }),
        R("text", { x: u.W - 70, y: 208 + i * 180, textAnchor: "end", fontFamily: '"Overpass", sans-serif', fontSize: 22, fill: rgba(theme.sand, 0.4) }, (i + 1) * 100 + "m")))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
