// ALPINE POST — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-6.js, template "AlpinePost").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Alegreya Sans SC / body Barlow. Camera set ["pushL","pushR","zoomOut","hopU","zoomIn","drop"].
// Entrances: title "stamp", items "streak".
// Owns the Scroll:board, DragDrop:drag, Toggle:switch, Morph:flap mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "alpine-post",
  label: "Alpine Post",

  // ---- type ----
  display: "Alegreya Sans SC", displayFallback: "sans-serif",
  body: "Barlow", bodyFallback: "sans-serif",
  mono: null,
  em: 0.58,
  titleLine: 1.04, titleSpace: "0.05em",
  titlePreset: "stamp", itemPreset: "streak",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ snow: t.snow || "#eef4f8", post: t.post || "#c0392b", pine: "#2f4f43", slateb: "#4a6478", ink: "#1e2c36" }),
  accents: ["post","ink","snow"],
  groundKey: "snow", inkKey: "ink", paperKey: "snow",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "snow",
      "fg": "ink",
      "hi": "post",
      "world": true,
      "top": 320,
      "size": 118,
      "upper": true,
      "kicker": {
        "v": "tag",
        "bg": "post",
        "c": "snow"
      }
    },
    "statement": {
      "bg": "pine",
      "fg": "snow",
      "hi": "post",
      "world": false,
      "top": 630,
      "size": 144,
      "upper": true
    },
    "feature": {
      "bg": "snow",
      "fg": "ink",
      "hi": "post",
      "world": true,
      "top": 250,
      "size": 94,
      "upper": true,
      "card": {
        "v": "frame",
        "bg": "ink",
        "r": 12,
        "line": "snow"
      },
      "chips": {
        "v": "square",
        "colors": [
          "post",
          "pine",
          "slateb"
        ],
        "text": "snow"
      }
    },
    "montage": {
      "bg": "ink",
      "fg": "snow",
      "hi": "post",
      "world": false,
      "top": 258,
      "size": 90,
      "upper": true,
      "tile": {
        "bg": "snow",
        "line": "ink",
        "label": "ink",
        "r": 10
      },
      "tilts": [
        -2,
        1.5,
        2,
        -1.5
      ]
    },
    "stats": {
      "bg": "snow",
      "fg": "ink",
      "hi": "post",
      "world": true,
      "cols": [
        "post",
        "pine",
        "slateb"
      ],
      "num": 148,
      "upper": true,
      "rule": true
    },
    "cta": {
      "bg": "post",
      "fg": "snow",
      "hi": "ink",
      "world": false,
      "top": 500,
      "size": 114,
      "upper": true,
      "btn": {
        "v": "block",
        "bg": "ink",
        "c": "snow"
      },
      "logoShape": "rounded"
    },
    "app": {
      "bg": "snow",
      "fg": "ink",
      "hi": "post",
      "cardBg": "#ffffff",
      "line": "ink",
      "world": true,
      "upper": true
    }
  },

  // ---- camera + motion ----
  cams: ["pushL","pushR","zoomOut","hopU","zoomIn","drop"], camMul: 5, camOff: 2,
  mag: {"rot":0.5,"slide":0.3,"driftX":8},
  ambient: 1.7,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"board","DragDrop":"drag","Toggle":"switch","Morph":"flap"},

  strings: {
    brandName: "Alpine Post",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round", strokeLinejoin: "round" }, R2("rect", { x: 3, y: 6, width: 18, height: 12, rx: 2 }), R2("path", { d: "M3 8l9 6 9-6" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      R("path", { d: "M -20 " + u.H + " L " + (u.W * 0.26) + " " + (u.H - 700) + " L " + (u.W * 0.46) + " " + (u.H - 380) + " L " + (u.W * 0.68) + " " + (u.H - 780) + " L " + (u.W + 20) + " " + u.H + " Z", fill: rgba(theme.slateb, 0.4) }),
      R("path", { d: "M " + (u.W * 0.26 - 62) + " " + (u.H - 560) + " L " + (u.W * 0.26) + " " + (u.H - 700) + " L " + (u.W * 0.26 + 62) + " " + (u.H - 560) + " q -34 22 -62 0 q -28 -22 -62 0 Z", fill: theme.snow }),
      R("path", { d: "M " + (u.W * 0.68 - 70) + " " + (u.H - 620) + " L " + (u.W * 0.68) + " " + (u.H - 780) + " L " + (u.W * 0.68 + 70) + " " + (u.H - 620) + " q -36 24 -70 0 q -34 -24 -70 0 Z", fill: theme.snow }),
      R("line", { x1: -20, y1: 300, x2: u.W + 20, y2: 460, stroke: rgba(theme.ink, 0.45), strokeWidth: 5 }),
      (function () {
        const ph = ((t * 0.12) % 1);
        const cx = -60 + ph * (u.W + 120), cy = 300 + (cx + 20) / (u.W + 40) * 160;
        return R("g", { transform: "translate(" + cx + "," + cy + ")" },
          R("line", { x1: 0, y1: 0, x2: 0, y2: 44, stroke: theme.ink, strokeWidth: 6 }),
          R("rect", { x: -46, y: 44, width: 92, height: 72, rx: 12, fill: theme.post, stroke: theme.ink, strokeWidth: 4, transform: "rotate(" + Math.sin(t * 2) * 3 + " 0 44)" }),
          R("rect", { x: -32, y: 60, width: 64, height: 30, rx: 6, fill: rgba(theme.snow, 0.9), transform: "rotate(" + Math.sin(t * 2) * 3 + " 0 44)" }));
      })(),
      [0, 1, 2].map((i) => R("g", { key: "p" + i, transform: "translate(" + (140 + i * 240) + "," + (u.H - 300) + ")" },
        R("polygon", { points: "0,-110 44,0 -44,0", fill: theme.pine }),
        R("polygon", { points: "0,-160 34,-70 -34,-70", fill: theme.pine }),
        R("rect", { x: -7, y: 0, width: 14, height: 30, fill: rgba(theme.ink, 0.7) }))),
      Array.from({ length: 16 }).map((_, i) => {
        const ph = (t * (0.05 + (i % 4) * 0.02) + i * 0.07) % 1;
        return R("circle", { key: "s" + i, cx: (i * 79 + 30) % u.W + Math.sin(t * 0.9 + i) * 24, cy: ph * u.H, r: 3 + (i % 2) * 2, fill: rgba("#ffffff", 0.85 * (1 - ph * 0.3)) });
      }),
      R("g", { transform: "translate(" + (u.W - 170) + ",230) rotate(-12)" },
        R("circle", { r: 66, fill: "none", stroke: rgba(theme.post, 0.55), strokeWidth: 6, strokeDasharray: "12 9" }),
        R("text", { y: -6, textAnchor: "middle", fontFamily: '"Alegreya Sans SC", sans-serif', fontSize: 26, fill: rgba(theme.post, 0.7) }, "ALPINE"),
        R("text", { y: 26, textAnchor: "middle", fontFamily: '"Alegreya Sans SC", sans-serif', fontSize: 22, fill: rgba(theme.post, 0.55) }, "2,140 M"))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
