// ATLAS & INK — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-3.js, template "AtlasInk").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Young Serif / body Assistant. Camera set ["zoomOut","pushL","drop","pushR","zoomIn","hopU"].
// Entrances: title "drowse", items "rise".
// Owns the Typing:typewriter, DragDrop:assemble, Ring:gauge, Scroll:board mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "atlas-and-ink",
  label: "Atlas & Ink",

  // ---- type ----
  display: "Young Serif", displayFallback: "serif",
  body: "Assistant", bodyFallback: "sans-serif",
  mono: null,
  em: 0.56,
  titleLine: 1.08, titleSpace: "0",
  titlePreset: "drowse", itemPreset: "rise",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ parch: t.parch || "#efe4cf", sepia: "#4a3826", compass: t.compass || "#a8402e", sea: "#6a92a8", gold: "#c9a24b" }),
  accents: ["compass","gold","parch"],
  groundKey: "parch", inkKey: "sepia", paperKey: "parch",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "parch",
      "fg": "sepia",
      "hi": "compass",
      "world": true,
      "top": 330,
      "size": 118,
      "kicker": {
        "v": "bare",
        "c": "sea"
      }
    },
    "statement": {
      "bg": "sepia",
      "fg": "parch",
      "hi": "gold",
      "world": false,
      "top": 630,
      "size": 142
    },
    "feature": {
      "bg": "parch",
      "fg": "sepia",
      "hi": "compass",
      "world": true,
      "top": 250,
      "size": 94,
      "card": {
        "v": "paper",
        "bg": "parch",
        "r": 6,
        "line": "sepia"
      },
      "chips": {
        "v": "outline",
        "colors": [
          "compass",
          "sea"
        ],
        "text": "parch"
      }
    },
    "montage": {
      "bg": "sepia",
      "fg": "parch",
      "hi": "gold",
      "world": false,
      "top": 258,
      "size": 90,
      "tile": {
        "bg": "parch",
        "line": "sepia",
        "label": "parch",
        "r": 4
      },
      "tilts": [
        -1.5,
        1,
        1.5,
        -1
      ]
    },
    "stats": {
      "bg": "parch",
      "fg": "sepia",
      "hi": "compass",
      "world": true,
      "cols": [
        "compass",
        "sea",
        "sepia"
      ],
      "num": 146
    },
    "cta": {
      "bg": "compass",
      "fg": "parch",
      "hi": "gold",
      "world": false,
      "top": 500,
      "size": 114,
      "btn": {
        "v": "block",
        "bg": "parch",
        "c": "sepia"
      },
      "logoShape": "rounded"
    },
    "app": {
      "bg": "parch",
      "fg": "sepia",
      "hi": "compass",
      "cardBg": "#f8f0e0",
      "line": "sepia",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["zoomOut","pushL","drop","pushR","zoomIn","hopU"], camMul: 5, camOff: 1,
  mag: {"rot":0.4,"driftX":5,"inn":0.28},
  ambient: 1.5,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Typing":"typewriter","DragDrop":"assemble","Ring":"gauge","Scroll":"board"},

  strings: {
    brandName: "Atlas & Ink",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round", strokeLinejoin: "round" }, R2("circle", { cx: 12, cy: 12, r: 9 }), R2("path", { d: "M15.5 8.5l-2 5-5 2 2-5z" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      Array.from({ length: 5 }).map((_, i) => R("line", { key: "h" + i, x1: 0, y1: 200 + i * 340, x2: u.W, y2: 200 + i * 340, stroke: rgba(theme.sepia, 0.1), strokeWidth: 2 })),
      Array.from({ length: 4 }).map((_, i) => R("line", { key: "v" + i, x1: 140 + i * 280, y1: 0, x2: 140 + i * 280, y2: u.H, stroke: rgba(theme.sepia, 0.1), strokeWidth: 2 })),
      R("path", { d: "M -20 500 q 140 -60 240 20 q 90 70 30 150 q -50 70 -170 40 q -80 -20 -100 -90", fill: rgba(theme.sea, 0.16), stroke: rgba(theme.sepia, 0.35), strokeWidth: 3 }),
      (function () {
        const len = 1400, draw = u.seg(p, 0.06, 0.85);
        return R("g", null,
          R("path", { d: "M 150 620 q 220 -140 380 -60 q 200 100 300 -40 q 60 -90 60 -180", fill: "none", stroke: theme.compass, strokeWidth: 5, strokeDasharray: "18 14", strokeDashoffset: String(len * (1 - draw)), opacity: 0.8 }),
          R("circle", { cx: 150, cy: 620, r: 10, fill: theme.compass }),
          R("path", { d: "M 876 328 l 14 22 h -28 z", fill: theme.compass, opacity: draw > 0.95 ? 1 : 0 }));
      })(),
      R("g", { transform: "translate(" + (u.W - 190) + "," + (u.H - 330) + ") rotate(" + Math.sin(t * 0.5) * 8 + ")" },
        R("circle", { r: 84, fill: "none", stroke: rgba(theme.sepia, 0.5), strokeWidth: 3 }),
        R("circle", { r: 62, fill: "none", stroke: rgba(theme.sepia, 0.3), strokeWidth: 2 }),
        [0, 45, 90, 135].map((a) => R("g", { key: a, transform: "rotate(" + a + ")" },
          R("path", { d: "M 0 -80 L 10 0 L 0 12 L -10 0 Z", fill: a % 90 === 0 ? theme.compass : rgba(theme.sepia, 0.5) }))),
        R("circle", { r: 9, fill: theme.gold })),
      R("g", { transform: "translate(230," + (u.H - 200) + ")" },
        R("path", { d: "M -60 0 q 20 -34 50 -10 q 30 22 60 -8 q 20 -18 40 2", fill: "none", stroke: rgba(theme.sepia, 0.5), strokeWidth: 6, strokeLinecap: "round", transform: "translate(0," + Math.sin(t * 1.4) * 6 + ")" }),
        R("circle", { cx: -52, cy: -14, r: 4, fill: theme.sepia }),
        R("text", { x: 110, y: 8, fontFamily: '"Young Serif", serif', fontSize: 24, fontStyle: "italic", fill: rgba(theme.sepia, 0.55) }, "hic sunt dracones"))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
