// BLOOM MARKET — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/world-pack-3.js, template "BloomMarket").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display DM Serif Display / body Albert Sans. Camera set ["pushL","hopU","zoomOut","pushR","drop","spin"].
// Entrances: title "pop", items "stamp".
// Owns the DragDrop:drag, Toggle:switch, Cursor:slider, Ring:gauge mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "bloom-market",
  label: "Bloom Market",

  // ---- type ----
  display: "DM Serif Display", displayFallback: "serif",
  body: "Albert Sans", bodyFallback: "sans-serif",
  mono: null,
  em: 0.54,
  titleLine: 1.06, titleSpace: "0",
  titlePreset: "pop", itemPreset: "stamp",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ blush: t.blush || "#f6e7e9", magenta: t.magenta || "#c2477e", leaf: "#5d8f57", butter: "#f2cf6b", ink: "#322a2e", paper: "#fffbf7" }),
  accents: ["magenta","butter","leaf"],
  groundKey: "blush", inkKey: "ink", paperKey: "paper",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "blush",
      "fg": "ink",
      "hi": "magenta",
      "world": true,
      "top": 300,
      "size": 122,
      "kicker": {
        "v": "pill",
        "bg": "leaf",
        "c": "paper"
      }
    },
    "statement": {
      "bg": "magenta",
      "fg": "paper",
      "hi": "butter",
      "world": false,
      "top": 630,
      "size": 148
    },
    "feature": {
      "bg": "blush",
      "fg": "ink",
      "hi": "leaf",
      "world": true,
      "top": 246,
      "size": 96,
      "card": {
        "v": "tilt",
        "bg": "paper",
        "r": 26,
        "line": "ink"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "magenta",
          "leaf",
          "butter"
        ],
        "text": "paper"
      }
    },
    "montage": {
      "bg": "leaf",
      "fg": "paper",
      "hi": "butter",
      "world": false,
      "top": 258,
      "size": 94,
      "tile": {
        "bg": "paper",
        "line": "ink",
        "label": "paper",
        "r": 20
      },
      "tilts": [
        -3,
        2.5,
        2,
        -2.5
      ]
    },
    "stats": {
      "bg": "ink",
      "fg": "paper",
      "hi": "magenta",
      "world": false,
      "cols": [
        "magenta",
        "butter",
        "blush"
      ],
      "num": 152
    },
    "cta": {
      "bg": "blush",
      "fg": "ink",
      "hi": "magenta",
      "world": true,
      "top": 480,
      "size": 118,
      "btn": {
        "v": "pill",
        "bg": "magenta",
        "c": "paper"
      },
      "logoShape": "circle"
    }
  },

  // ---- camera + motion ----
  cams: ["pushL","hopU","zoomOut","pushR","drop","spin"], camMul: 5, camOff: 3,
  mag: {"rot":1,"driftY":9},
  ambient: 1.6,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"DragDrop":"drag","Toggle":"switch","Cursor":"slider","Ring":"gauge"},

  strings: {
    brandName: "Bloom Market",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 25, height: 25, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round", strokeLinejoin: "round" }, R2("circle", { cx: 12, cy: 8, r: 2.5 }), R2("path", { d: "M12 10.5V21M12 16c-2 0-5-1-5-5M12 18c2 0 5-1 5-5" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      [0, 1, 2, 3].map((i) => {
        const sx = 120 + i * 270, sway = Math.sin(t * 0.9 + i) * 14;
        const c = [theme.magenta, theme.butter, theme.magenta, "#e0685c"][i];
        return R("g", { key: "f" + i },
          R("path", { d: `M ${sx} ${u.H - 100} Q ${sx + sway} ${u.H - 300} ${sx + sway} ${u.H - 430 - i * 40}`, stroke: theme.leaf, strokeWidth: 9, fill: "none", strokeLinecap: "round" }),
          R("path", { d: `M ${sx + sway * 0.6} ${u.H - 280} q 50 -8 60 -54 q -52 6 -60 54`, fill: theme.leaf }),
          [0, 1, 2, 3, 4].map((k) => R("ellipse", { key: k, cx: sx + sway, cy: u.H - 430 - i * 40, rx: 16, ry: 34, fill: c, transform: `rotate(${k * 72 + t * 12} ${sx + sway} ${u.H - 430 - i * 40})` })),
          R("circle", { cx: sx + sway, cy: u.H - 430 - i * 40, r: 14, fill: theme.butter }));
      }),
      Array.from({ length: 10 }).map((_, i) => {
        const px = (i * 113 + Math.sin(t * 0.7 + i) * 60 + u.W) % u.W;
        const py = ((t * (44 + (i % 4) * 18) + i * 260) % (u.H + 160)) - 80;
        return R("ellipse", { key: "p" + i, cx: px, cy: py, rx: 9, ry: 15, fill: rgba(theme.magenta, 0.55), transform: `rotate(${t * 90 + i * 36} ${px} ${py})` });
      })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
