// BOARD PACK — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-06.js, template "BoardPack").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Schibsted Grotesk / body Red Hat Text. Camera set ["zoomIn","pushU","pushL","drop","zoomOut","pushR"].
// Entrances: title "rise", items "rise".
// Owns the Scroll:board, Typing:hand, Ring:bar mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "board-pack",
  label: "Board Pack",

  // ---- type ----
  display: "Schibsted Grotesk", displayFallback: "system-ui, sans-serif",
  body: "Red Hat Text", bodyFallback: "system-ui, sans-serif",
  mono: "IBM Plex Mono",
  chrome: false,
  devanagari: "Noto Sans Devanagari",
  maxScenes: 18,
  em: 0.54,
  titleLine: 1.06, titleSpace: "-0.02em",
  titlePreset: "rise", itemPreset: "rise",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({
      bg: t.bg || "#101726", surface: "#1a2336", rule: "#2f3c52", inkMuted: "#93a0b4",
      ink: "#f4f6fa", accent: t.accent || "#d8b45a", accent2: t.accent2 || "#5a9bd8", accentInk: "#0b1120",
    }),
  accents: ["accent","accent2","surface"],
  groundKey: "bg", inkKey: "accentInk", paperKey: "ink",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 108,
      "kicker": {
        "v": "outline",
        "c": "accent"
      }
    },
    "statement": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 610,
      "size": 120
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 540,
      "size": 80,
      "bodySize": 38,
      "ch": 54,
      "lh": 1.52,
      "weight": 400,
      "dim": 0.92,
      "kicker": {
        "v": "bare",
        "c": "accent2"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 360,
      "size": 88,
      "ch": 25,
      "lh": 1.16,
      "markSize": 220
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 255,
      "size": 90,
      "swap": "body",
      "card": {
        "v": "glow",
        "bg": "surface",
        "glow": "accent",
        "r": 12,
        "line": "inkMuted"
      },
      "chips": {
        "v": "outline",
        "colors": [
          "accent",
          "accent2",
          "ink"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 330,
      "size": 84,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 12,
        "h": 640,
        "labelSize": 42
      },
      "tilts": [
        0,
        0,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 390,
      "size": 86,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 150,
      "glowNums": true
    },
    "cta": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "surface",
      "world": true,
      "top": 470,
      "size": 102,
      "align": "left",
      "btn": {
        "v": "glow",
        "bg": "accentInk",
        "c": "ink"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["zoomIn","pushU","pushL","drop","zoomOut","pushR"], camMul: 7, camOff: 3,
  mag: {"rot":0.2,"driftX":5,"driftY":6,"driftZ":0.05,"slide":0.18,"inn":0.24,"zin":0.34,"zout":0.28},
  ambient: 1.4,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"board","Typing":"hand","Ring":"bar"},

  strings: {
    brandName: "Board Pack",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.4, strokeLinecap: "round", strokeLinejoin: "round" },
      R2("path", { d: "M4 20h16M7 20V9l5-4 5 4v11" }), R2("path", { d: "M11 20v-5h2v5" })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "radial-gradient(80% 45% at 50% 96%, " + rgba(theme.accent, 0.2) + " 0%, transparent 60%), " + bg),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, inv = theme.currentBg !== theme.bg;
      const tint = inv ? theme.surface : theme.inkMuted;
      const table = H - 290;
      const spin = (t * 18) % 360;
      const rad = spin * Math.PI / 180;
      return R("g", null,
        R("defs", null,
          R("pattern", { id: "bp-coffer", width: 150, height: 110, patternUnits: "userSpaceOnUse" },
            R("rect", { x: 10, y: 10, width: 130, height: 90, rx: 6, fill: "none", stroke: rgba(theme.rule, inv ? 0.5 : 0.7), strokeWidth: 3 })),
          R("radialGradient", { id: "bp-spot", cx: "50%", cy: "50%" },
            R("stop", { offset: "0%", stopColor: rgba(theme.accent, 0.3) }),
            R("stop", { offset: "100%", stopColor: rgba(theme.accent, 0) }))),
        R("rect", { x: 0, y: 0, width: W, height: 250, fill: "url(#bp-coffer)", opacity: 0.7 }),
        /* a city wall beyond the glass, lights switching */
        R("g", { opacity: 0.5 },
          [0, 1, 2, 3, 4, 5, 6].map((i) => {
            const bh = 74 + ((i * 47) % 4) * 40;
            return R("rect", { key: "ct" + i, x: 30 + i * 152, y: 250 - bh, width: 104, height: bh, fill: rgba(theme.accent2, 0.3) });
          }),
          [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].map((i) => R("rect", { key: "cw" + i, x: 54 + i * 104, y: 196 - (i % 3) * 34, width: 16, height: 20, fill: rgba(theme.accent, Math.sin(t * 0.6 + i * 1.9) > 0.35 ? 0.85 : 0.2) }))),
        /* pendant row */
        [0, 1, 2].map((i) => R("g", { key: "pn" + i, transform: "translate(" + (200 + i * 340) + ",250)" },
          R("line", { x1: 0, y1: -20, x2: 0, y2: 40, stroke: rgba(tint, 0.45), strokeWidth: 4 }),
          R("path", { d: "M -50 40 h 100 l -22 46 h -56 z", fill: rgba(theme.accent, 0.6) }),
          R("circle", { cx: 0, cy: 96, r: 14 + Math.sin(t * 1.3 + i) * 2, fill: rgba(theme.accent, 0.9) }))),
        /* a wall screen cycling the deck it replaced */
        R("g", { transform: "translate(" + (W - 160) + ",158) scale(0.66)" },
          R("rect", { x: -128, y: -160, width: 256, height: 300, rx: 10, fill: rgba(theme.accentInk, 0.9), stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          R("rect", { x: -106, y: -138, width: 212, height: 256, rx: 5, fill: rgba(theme.accent2, 0.16) }),
          (function () {
            const sl = Math.floor((t % 12) / 3);
            return R("g", null,
              R("rect", { x: -86, y: -114, width: 150 - sl * 22, height: 14, rx: 7, fill: rgba(theme.accent, 0.85) }),
              [0, 1, 2].map((i) => R("rect", { key: "sr" + i, x: -86, y: -80 + i * 26, width: 130 - i * 26 - sl * 10, height: 10, rx: 5, fill: rgba(theme.ink, 0.4) })),
              sl % 2 === 0
                ? R("g", null, [0, 1, 2, 3].map((i) => R("rect", { key: "bc" + i, x: -80 + i * 46, y: 60 - (14 + i * 16), width: 30, height: 14 + i * 16, rx: 3, fill: rgba(theme.accent, 0.5) })))
                : R("path", { d: "M -80 60 L -20 10 L 20 34 L 80 -20", fill: "none", stroke: rgba(theme.accent, 0.8), strokeWidth: 5 }));
          })(),
          R("circle", { cx: 0, cy: 128, r: 6, fill: rgba(theme.accent, 0.7) })),
        /* chair backs around the table */
        [0, 1, 2, 3, 4].map((i) => {
          const cx2 = 130 + i * 200;
          const lean = Math.sin(t * 0.5 + i * 1.3) * 1.5;
          return R("g", { key: "ch" + i, opacity: 0.55, transform: "translate(" + cx2 + "," + (table + 40) + ") rotate(" + lean.toFixed(2) + ")" },
            R("path", { d: "M -62 0 v -110 q 0 -30 62 -30 q 62 0 62 30 v 110 z", fill: rgba(theme.surface, 0.5), stroke: rgba(tint, 0.4), strokeWidth: 4 }),
            R("path", { d: "M -40 -70 h 80", stroke: rgba(tint, 0.3), strokeWidth: 4 }));
        }),
        R("ellipse", { cx: W * 0.5, cy: table - 80, rx: 520, ry: 300, fill: "url(#bp-spot)" }),
        /* the table */
        R("ellipse", { cx: W * 0.5, cy: table, rx: 520, ry: 90, fill: rgba(theme.surface, 0.95), stroke: rgba(tint, 0.5), strokeWidth: 5 }),
        R("ellipse", { cx: W * 0.5, cy: table, rx: 440, ry: 70, fill: "none", stroke: rgba(tint, 0.25), strokeWidth: 3 }),
        /* the model on its turntable */
        R("g", { transform: "translate(" + (W * 0.5) + "," + (table - 30) + ")" },
          R("ellipse", { cx: 0, cy: 0, rx: 230, ry: 60, fill: rgba(theme.accentInk, 0.5), stroke: rgba(theme.accent, 0.5), strokeWidth: 4 }),
          R("ellipse", { cx: Math.cos(rad) * 90, cy: 20 + Math.sin(rad) * 16, rx: 150, ry: 34, fill: rgba(theme.accentInk, 0.45) }),
          [[0, 0, 200], [-96, 26, 130], [92, 20, 96], [-40, -14, 156]].map((b, i) => {
            const bx = Math.cos(rad + i * 1.4) * b[0] * 0.7 + b[0] * 0.4;
            const by = Math.sin(rad + i * 1.4) * 14 + b[1] * 0.5;
            return R("g", { key: "bl" + i },
              R("path", { d: "M " + (bx - 34) + " " + by + " h 68 v " + (-b[2]) + " h -68 z", fill: rgba(i === 0 ? theme.accent : theme.surface, i === 0 ? 0.7 : 0.9), stroke: rgba(tint, 0.5), strokeWidth: 3 }),
              R("path", { d: "M " + (bx - 34) + " " + (by - b[2]) + " l 34 -22 l 34 22 z", fill: rgba(theme.accent, 0.5) }),
              [0, 1, 2].map((j) => R("line", { key: "fl" + j, x1: bx - 26, y1: by - 24 - j * 30, x2: bx + 26, y2: by - 24 - j * 30, stroke: rgba(tint, 0.3), strokeWidth: 3 })));
          })),
        /* jug and glasses */
        R("g", { transform: "translate(230," + (table - 20) + ")" },
          R("path", { d: "M -34 0 h 68 l -8 -110 h -52 z", fill: rgba(theme.accent2, 0.28), stroke: rgba(tint, 0.5), strokeWidth: 4 }),
          R("path", { d: "M 30 -84 q 30 6 26 30 q -6 22 -30 18", fill: "none", stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          [0, 1].map((i) => R("path", { key: "gl" + i, d: "M " + (70 + i * 60) + " 0 h 44 l -6 -60 h -32 z", fill: rgba(theme.accent2, 0.2), stroke: rgba(tint, 0.45), strokeWidth: 3 }))),
        /* a carafe cart parked by the wall */
        R("g", { opacity: 0.7, transform: "translate(" + (W - 400) + "," + (H - 150) + ")" },
          R("rect", { x: -90, y: -110, width: 180, height: 14, rx: 4, fill: rgba(tint, 0.6) }),
          R("rect", { x: -90, y: -40, width: 180, height: 12, rx: 4, fill: rgba(tint, 0.5) }),
          R("path", { d: "M -80 -96 v 56 M 80 -96 v 56 M -80 -28 v 20 M 80 -28 v 20", stroke: rgba(tint, 0.5), strokeWidth: 6 }),
          R("path", { d: "M -40 -110 h 52 l -6 -70 h -40 z", fill: rgba(theme.accent2, 0.4), stroke: rgba(tint, 0.45), strokeWidth: 3 }),
          [0, 1].map((i) => R("circle", { key: "cw" + i, cx: -60 + i * 120, cy: -2, r: 12, fill: "none", stroke: rgba(tint, 0.5), strokeWidth: 4 }))),
        /* motes in the beam */
        [0, 1, 2, 3, 4, 5].map((i) => {
          const ph = (t * (0.1 + i * 0.02) + i * 0.16) % 1;
          return R("circle", { key: "mt" + i, cx: W * 0.3 + i * 100 + Math.sin(t * 0.6 + i) * 30, cy: table - ph * 700, r: 3 + (i % 3) * 2, fill: rgba(theme.accent, 0.3 * (1 - ph)) });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
