// BYLINE RULE — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-03.js, template "BylineRule").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Oswald / body PT Sans. Camera set ["zoomIn","pushU","spin","pushR","drop","pushL"].
// Entrances: title "streak", items "slam".
// Owns the Scroll:feed, Typing:hand, Ring:bar mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "byline-rule",
  label: "Byline Rule",

  // ---- type ----
  display: "Oswald", displayFallback: "\"Helvetica Neue\", sans-serif",
  body: "PT Sans", bodyFallback: "system-ui, sans-serif",
  mono: "IBM Plex Mono",
  chrome: false,
  devanagari: "Noto Sans Devanagari",
  maxScenes: 18,
  em: 0.48,
  titleLine: 1.04, titleSpace: "0.005em",
  titlePreset: "streak", itemPreset: "slam",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({
      bg: t.bg || "#0e0f11", surface: "#191b1e", rule: "#2c3034", inkMuted: "#8b9095",
      ink: "#f7f8f9", accent: t.accent || "#f2d13c", accent2: t.accent2 || "#d0473c", accentInk: "#0b0c0d",
    }),
  accents: ["accent","accent2","bg"],
  groundKey: "bg", inkKey: "accentInk", paperKey: "ink",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 122,
      "upper": true,
      "kicker": {
        "v": "tag",
        "bg": "accent",
        "c": "accentInk"
      }
    },
    "statement": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "accent2",
      "world": true,
      "top": 610,
      "size": 132,
      "upper": true
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 540,
      "size": 82,
      "bodySize": 38,
      "ch": 54,
      "lh": 1.5,
      "weight": 400,
      "dim": 0.92,
      "kicker": {
        "v": "bare",
        "c": "accent"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 360,
      "size": 92,
      "ch": 24,
      "lh": 1.12,
      "markSize": 220,
      "altLine": true
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 255,
      "size": 96,
      "upper": true,
      "swap": "quote",
      "card": {
        "v": "frame",
        "bg": "surface",
        "r": 8,
        "line": "inkMuted"
      },
      "chips": {
        "v": "square",
        "colors": [
          "accent",
          "accent2",
          "ink"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 330,
      "size": 90,
      "upper": true,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 8,
        "h": 640,
        "labelSize": 42
      },
      "tilts": [
        0,
        0,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 390,
      "size": 92,
      "upper": true,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 152,
      "glowNums": true
    },
    "cta": {
      "bg": "ink",
      "fg": "accentInk",
      "hi": "accent2",
      "world": true,
      "top": 470,
      "size": 112,
      "upper": true,
      "align": "left",
      "btn": {
        "v": "block",
        "bg": "accent2",
        "c": "ink"
      },
      "logoShape": "rounded"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["zoomIn","pushU","spin","pushR","drop","pushL"], camMul: 5, camOff: 5,
  mag: {"rot":0.9,"skew":3,"driftX":7,"driftY":8,"driftZ":0.05,"slide":0.3,"inn":0.16,"zin":0.44,"zout":0.34},
  ambient: 1.8,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"feed","Typing":"hand","Ring":"bar"},

  strings: {
    brandName: "Byline Rule",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.4, strokeLinecap: "round", strokeLinejoin: "round" },
      R2("path", { d: "M3 8h4l2-3h6l2 3h4v11H3z" }), R2("circle", { cx: 12, cy: 13, r: 3.5 })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "radial-gradient(90% 50% at 50% 8%, " + rgba(theme.accent, 0.16) + " 0%, transparent 60%), " + bg),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, inv = theme.currentBg !== theme.bg;
      const tint = inv ? theme.surface : theme.inkMuted;
      const pit = H - 300;
      const fire = (t % 2.6) / 2.6;
      const flash = fire < 0.06 ? 1 - fire / 0.06 : 0;
      const sway = Math.sin(t * 1.5) * 12, lag = Math.sin(t * 1.5 - 0.6) * 12;
      return R("g", null,
        R("defs", null,
          R("linearGradient", { id: "bl-wall", x1: "0%", y1: "0%", x2: "0%", y2: "100%" },
            R("stop", { offset: "0%", stopColor: rgba(theme.accent, 0.2) }),
            R("stop", { offset: "100%", stopColor: rgba(theme.accent, 0) }))),
        R("rect", { x: 0, y: 0, width: W, height: pit, fill: "url(#bl-wall)", opacity: 0.5 + flash * 0.5 }),
        /* lighting truss above the copy */
        R("g", { opacity: 0.7 },
          R("line", { x1: -20, y1: 130, x2: W + 20, y2: 130, stroke: rgba(tint, 0.55), strokeWidth: 8 }),
          R("line", { x1: -20, y1: 186, x2: W + 20, y2: 186, stroke: rgba(tint, 0.4), strokeWidth: 5 }),
          [0, 1, 2, 3, 4, 5].map((i) => R("line", { key: "tx" + i, x1: 20 + i * 200, y1: 130, x2: 140 + i * 200, y2: 186, stroke: rgba(tint, 0.3), strokeWidth: 4 })),
          [0, 1, 2, 3].map((i) => {
            const on = 0.55 + 0.45 * Math.abs(Math.sin(t * (1.1 + i * 0.3) + i));
            return R("g", { key: "sl" + i, transform: "translate(" + (150 + i * 260) + ",192)" },
              R("path", { d: "M -34 0 h 68 l -14 54 h -40 z", fill: rgba(theme.accentInk, 0.9), stroke: rgba(tint, 0.45), strokeWidth: 3 }),
              R("circle", { cx: 0, cy: 58, r: 14, fill: rgba(theme.accent, on) }),
              R("path", { d: "M -60 58 L 60 58 L 150 " + (pit - 200) + " L -150 " + (pit - 200) + " Z", fill: rgba(theme.accent, 0.05 * on) }));
          })),
        R("rect", { x: 0, y: 0, width: W, height: H, fill: rgba(theme.accent, 0.22 * flash) }),
        /* backdrop step-and-repeat marks */
        R("g", { opacity: 0.24 },
          [0, 1, 2, 3, 4, 5, 6, 7].map((i) => R("rect", { key: "sr" + i, x: 40 + (i % 4) * 260, y: pit - 620 + Math.floor(i / 4) * 130, width: 150, height: 26, rx: 6, fill: rgba(theme.ink, 0.5) }))),
        /* crowd heads bobbing */
        [0, 1, 2, 3, 4, 5, 6].map((i) => {
          const hx = 60 + i * 155, bob = Math.sin(t * 1.6 + i * 1.1) * 9;
          return R("g", { key: "hd" + i },
            R("circle", { cx: hx, cy: pit - 120 + bob, r: 46, fill: rgba(theme.accentInk, 0.92) }),
            R("path", { d: "M " + (hx - 74) + " " + (pit + 40) + " q 74 -110 148 0 z", fill: rgba(theme.accentInk, 0.92) }),
            R("path", { d: "M " + (hx - 46) + " " + (pit - 122 + bob) + " a 46 46 0 0 1 92 0", fill: "none", stroke: rgba(tint, 0.35), strokeWidth: 4 }));
        }),
        /* monitor bank in the margin */
        [0, 1].map((i) => R("g", { key: "mn" + i, transform: "translate(" + (W - 112) + "," + (985 + i * 235) + ")" },
          R("line", { x1: 0, y1: -120, x2: 0, y2: -80, stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          R("rect", { x: -112, y: -70, width: 224, height: 160, rx: 10, fill: rgba(theme.accentInk, 0.9), stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          R("rect", { x: -94, y: -52, width: 188, height: 124, rx: 5, fill: rgba(theme.accent2, 0.24) }),
          R("rect", { x: -94, y: -52 + ((t * 90 + i * 70) % 124), width: 188, height: 12, fill: rgba(theme.accent, 0.35) }),
          [0, 1, 2].map((j) => R("rect", { key: "ln" + j, x: -78, y: -28 + j * 34, width: 116 - j * 26, height: 10, rx: 5, fill: rgba(theme.ink, 0.35) })))),
        /* the lectern, and a cluster of mics on it */
        R("g", { transform: "translate(" + (W * 0.42) + "," + (pit - 20) + ")" },
          R("path", { d: "M -110 0 h 220 l -26 -190 h -168 z", fill: rgba(theme.surface, 0.95), stroke: rgba(tint, 0.5), strokeWidth: 4 }),
          R("path", { d: "M -110 0 h 220 l -8 -40 h -204 z", fill: rgba(theme.accentInk, 0.25) }),
          R("rect", { x: -70, y: -150, width: 140, height: 46, rx: 6, fill: rgba(theme.accent, 0.75) }),
          [0, 1, 2].map((i) => R("g", { key: "lm" + i, transform: "translate(" + (-46 + i * 46) + ",-190) rotate(" + (-14 + i * 14 + Math.sin(t * 1.1 + i) * 2).toFixed(2) + ")" },
            R("line", { x1: 0, y1: 0, x2: 0, y2: -80, stroke: rgba(tint, 0.6), strokeWidth: 5 }),
            R("rect", { x: -13, y: -116, width: 26, height: 44, rx: 13, fill: rgba(theme.accentInk, 0.95), stroke: rgba(tint, 0.4), strokeWidth: 3 })))),
        /* flashes going off along the crowd line */
        [0, 1, 2, 3, 4].map((i) => {
          const ph = ((t * 0.9 + i * 0.37) % 1);
          const pop = ph < 0.1 ? 1 - ph / 0.1 : 0;
          if (pop <= 0) return null;
          const fx = 130 + i * 190;
          return R("g", { key: "cf" + i },
            R("circle", { cx: fx, cy: pit - 180, r: 18 + (1 - pop) * 90, fill: rgba(theme.ink, 0.5 * pop) }),
            R("circle", { cx: fx, cy: pit - 180, r: 10, fill: rgba(theme.ink, 0.9 * pop) }));
        }),
        /* cables snaking across the foreground */
        R("path", { d: "M -40 " + (H - 90) + " q 240 -60 480 10 q 240 66 500 -20", fill: "none", stroke: rgba(tint, 0.45), strokeWidth: 10, strokeLinecap: "round" }),
        R("path", { d: "M -40 " + (H - 40) + " q 300 -46 560 16 q 220 52 460 -14", fill: "none", stroke: rgba(theme.accent2, 0.35), strokeWidth: 8, strokeLinecap: "round" }),
        /* barrier rail */
        R("line", { x1: 0, y1: pit + 20, x2: W, y2: pit + 20, stroke: rgba(tint, 0.6), strokeWidth: 10, strokeLinecap: "round" }),
        [0, 1, 2, 3, 4].map((i) => R("line", { key: "bp" + i, x1: 80 + i * 240, y1: pit + 20, x2: 80 + i * 240, y2: H, stroke: rgba(tint, 0.45), strokeWidth: 8 })),
        /* boom mics leaning in */
        [0, 1, 2].map((i) => {
          const lean = Math.sin(t * 0.9 + i * 1.7) * 4;
          return R("g", { key: "bm" + i, transform: "translate(" + (90 + i * 420) + "," + (pit + 30) + ") rotate(" + (-28 + lean + i * 8).toFixed(2) + ")" },
            R("line", { x1: 0, y1: 0, x2: 0, y2: -420, stroke: rgba(tint, 0.6), strokeWidth: 8 }),
            R("rect", { x: -26, y: -516, width: 52, height: 104, rx: 24, fill: rgba(theme.accentInk, 0.95), stroke: rgba(tint, 0.45), strokeWidth: 4 }),
            [0, 1, 2].map((j) => R("line", { key: "gr" + j, x1: -18, y1: -496 + j * 22, x2: 18, y2: -496 + j * 22, stroke: rgba(tint, 0.4), strokeWidth: 4 })),
            R("rect", { x: -14, y: -412, width: 28, height: 34, rx: 6, fill: rgba(theme.accent2, 0.8) }));
        }),
        /* the camera on its strap */
        R("g", { transform: "translate(" + (W - 96) + ",-30)" },
          R("path", { d: "M 0 0 q " + (lag * 3).toFixed(1) + " 740 " + (sway * 2).toFixed(1) + " 1470", fill: "none", stroke: rgba(tint, 0.5), strokeWidth: 6 }),
          R("g", { transform: "translate(" + (sway * 2).toFixed(1) + ",1470) rotate(" + sway.toFixed(2) + ")" },
            R("rect", { x: -104, y: -66, width: 208, height: 132, rx: 12, fill: rgba(theme.surface, 0.98), stroke: rgba(tint, 0.5), strokeWidth: 4 }),
            R("rect", { x: -104, y: -66, width: 208, height: 34, rx: 10, fill: rgba(theme.ink, 0.12) }),
            R("circle", { cx: 10, cy: 4, r: 46, fill: rgba(theme.accentInk, 0.9), stroke: rgba(tint, 0.6), strokeWidth: 5 }),
            R("circle", { cx: 10, cy: 4, r: 20, fill: rgba(theme.accent2, 0.5 + 0.5 * flash) }),
            R("rect", { x: -96, y: -104, width: 74, height: 40, rx: 6, fill: rgba(theme.accent, 0.4 + 0.6 * flash) }),
            R("circle", { cx: -59, cy: -84, r: 30 + flash * 90, fill: rgba(theme.accent, 0.5 * flash) }))),
        /* sparks off the flash */
        [0, 1, 2, 3, 4].map((i) => {
          const ph = ((t * 0.9 + i * 0.2) % 1);
          return R("line", { key: "sk" + i, x1: W - 150 + i * 30, y1: 1390 - ph * 300, x2: W - 150 + i * 30, y2: 1430 - ph * 300, stroke: rgba(theme.accent, 0.3 * (1 - ph)), strokeWidth: 3, strokeLinecap: "round" });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
