// CHALK TALK — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/world-pack-4.js, template "ChalkTalk").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Gochi Hand / body Neucha. Camera set ["pushR","drop","pushL","zoomOut","hopU","spin"].
// Entrances: title "stamp", items "pop".
// Owns the Typing:hand, DragDrop:drag, Toggle:check, Morph:roll mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "chalk-talk",
  label: "Chalk Talk",

  // ---- type ----
  display: "Gochi Hand", displayFallback: "cursive",
  body: "Neucha", bodyFallback: "cursive",
  mono: null,
  em: 0.46,
  titleLine: 1.12, titleSpace: "0",
  titlePreset: "stamp", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ board: t.board || "#2e3d38", chalk: "#f2efe6", yellow: t.yellow || "#f2d478", pink: "#e8a0b4", wood: "#8a6a4a", ink: "#232f2b" }),
  accents: ["yellow","pink","board"],
  groundKey: "board", inkKey: "ink", paperKey: "chalk",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "board",
      "fg": "chalk",
      "hi": "yellow",
      "world": true,
      "top": 320,
      "size": 122,
      "kicker": {
        "v": "outline",
        "c": "pink"
      }
    },
    "statement": {
      "bg": "ink",
      "fg": "chalk",
      "hi": "pink",
      "world": false,
      "top": 630,
      "size": 146
    },
    "feature": {
      "bg": "board",
      "fg": "chalk",
      "hi": "yellow",
      "world": true,
      "top": 250,
      "size": 96,
      "card": {
        "v": "paper",
        "bg": "paper",
        "r": 8,
        "line": "ink"
      },
      "chips": {
        "v": "outline",
        "colors": [
          "yellow",
          "pink",
          "chalk"
        ],
        "text": "ink"
      }
    },
    "montage": {
      "bg": "ink",
      "fg": "chalk",
      "hi": "yellow",
      "world": false,
      "top": 258,
      "size": 94,
      "tile": {
        "bg": "board",
        "line": "chalk",
        "label": "chalk",
        "r": 8
      },
      "tilts": [
        -3,
        2.5,
        2,
        -2.5
      ]
    },
    "stats": {
      "bg": "board",
      "fg": "chalk",
      "hi": "yellow",
      "world": true,
      "cols": [
        "yellow",
        "pink",
        "chalk"
      ],
      "num": 152
    },
    "cta": {
      "bg": "ink",
      "fg": "chalk",
      "hi": "yellow",
      "world": false,
      "top": 500,
      "size": 120,
      "btn": {
        "v": "pill",
        "bg": "yellow",
        "c": "ink"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "board",
      "fg": "chalk",
      "hi": "yellow",
      "cardBg": "#26332f",
      "line": "chalk",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["pushR","drop","pushL","zoomOut","hopU","spin"], camMul: 3, camOff: 2,
  mag: {"rot":1.2,"driftX":7},
  ambient: 1.7,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Typing":"hand","DragDrop":"drag","Toggle":"check","Morph":"roll"},

  strings: {
    brandName: "Chalk Talk",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round" }, R2("path", { d: "M4 17L15 6l3 3L7 20l-4 1zM13 8l3 3" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      R("rect", { x: 0, y: u.H - 110, width: u.W, height: 110, fill: theme.wood }),
      R("rect", { x: 120, y: u.H - 128, width: 130, height: 26, rx: 6, fill: rgba(theme.chalk, 0.85) }),
      R("rect", { x: 290, y: u.H - 126, width: 60, height: 22, rx: 10, fill: theme.pink }),
      (function () {
        const len = 700, draw = u.seg(p, 0.05, 0.6);
        return R("path", { d: `M ${u.W - 320} 300 q 90 -60 180 0 q -90 70 -180 0 Z`, fill: "none", stroke: rgba(theme.yellow, 0.8), strokeWidth: 6, strokeDasharray: `${len}`, strokeDashoffset: `${len * (1 - draw)}`, strokeLinecap: "round" });
      })(),
      (function () {
        const len = 500, draw = u.seg(p, 0.3, 0.8);
        return R("path", { d: `M 120 ${u.H - 420} l 70 -90 l 70 90 Z`, fill: "none", stroke: rgba(theme.pink, 0.75), strokeWidth: 6, strokeDasharray: `${len}`, strokeDashoffset: `${len * (1 - draw)}`, strokeLinecap: "round" });
      })(),
      R("ellipse", { cx: u.W * 0.7 + Math.sin(t * 0.4) * 100, cy: u.H - 500, rx: 130, ry: 40, fill: rgba(theme.chalk, 0.05), transform: `rotate(-14 ${u.W * 0.7} ${u.H - 500})` }),
      [0, 1, 2, 3, 4].map((i) => R("circle", { key: i, cx: 100 + i * 210 + Math.sin(t + i) * 8, cy: 200 + (i % 2) * 40, r: 3, fill: rgba(theme.chalk, 0.4) }))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
