// CORNER SHOP — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-05.js, template "CornerShop").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Lobster Two / body Hind. Camera set ["hopU","pushR","spin","pushL","drop","zoomIn"].
// Entrances: title "slam", items "pop".
// Owns the Scroll:board, Typing:hand, Ring:bar mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "corner-shop",
  label: "Corner Shop",

  // ---- type ----
  display: "Lobster Two", displayFallback: "cursive",
  body: "Hind", bodyFallback: "system-ui, sans-serif",
  mono: "IBM Plex Mono",
  chrome: false,
  devanagari: "Noto Sans Devanagari",
  maxScenes: 18,
  em: 0.48,
  titleLine: 1.04, titleSpace: "0",
  titlePreset: "slam", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({
      bg: t.bg || "#f5ecd8", surface: "#fdf8ec", rule: "#d8c9a6", inkMuted: "#756a51",
      ink: "#1b1810", accent: t.accent || "#d1462f", accent2: t.accent2 || "#4f8a3c", accentInk: "#fdf8ec",
    }),
  accents: ["accent","accent2","ink"],
  groundKey: "bg", inkKey: "ink", paperKey: "accentInk",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 120,
      "kicker": {
        "v": "tag",
        "bg": "accent",
        "c": "accentInk"
      }
    },
    "statement": {
      "bg": "ink",
      "fg": "surface",
      "hi": "accent",
      "world": true,
      "top": 610,
      "size": 132
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 540,
      "size": 94,
      "bodySize": 38,
      "ch": 54,
      "lh": 1.54,
      "weight": 400,
      "dim": 0.9,
      "kicker": {
        "v": "bare",
        "c": "accent2"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 360,
      "size": 102,
      "ch": 26,
      "lh": 1.1,
      "markSize": 230
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 255,
      "size": 102,
      "swap": "quote",
      "card": {
        "v": "tilt",
        "bg": "surface",
        "r": 16,
        "line": "inkMuted"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "accent",
          "accent2",
          "inkMuted"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 330,
      "size": 96,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 16,
        "h": 640,
        "labelSize": 48
      },
      "tilts": [
        -2,
        2,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 390,
      "size": 98,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 150,
      "rule": true
    },
    "cta": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "ink",
      "world": true,
      "top": 470,
      "size": 114,
      "align": "left",
      "btn": {
        "v": "pill",
        "bg": "ink",
        "c": "accentInk"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["hopU","pushR","spin","pushL","drop","zoomIn"], camMul: 3, camOff: 1,
  mag: {"rot":0.9,"driftX":8,"driftY":8,"driftZ":0.04,"slide":0.26,"inn":0.18,"zin":0.36,"zout":0.3},
  ambient: 1.8,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"board","Typing":"hand","Ring":"bar"},

  strings: {
    brandName: "Corner Shop",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.4, strokeLinecap: "round", strokeLinejoin: "round" },
      R2("path", { d: "M4 8h16l-2 12H6zM8 8V5a4 4 0 018 0v3" })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "radial-gradient(100% 55% at 30% 4%, " + rgba(theme.accent2, 0.16) + " 0%, transparent 60%), " + bg),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, E = u.ease, inv = theme.currentBg !== theme.bg;
      const tint = inv ? theme.surface : theme.inkMuted;
      const kerb = H - 290;
      const cyc = (t % 11) / 11;
      const tx = -240 + E.inOut(Math.min(1, cyc / 0.9)) * (W + 480);
      const whl = (tx / 30) * 57.3;
      const lean = 12 + Math.sin(t * 2.4) * 2;
      return R("g", null,
        /* the building above, and a hanging sign */
        R("g", { opacity: 0.5 },
          R("rect", { x: 40, y: -40, width: W - 80, height: 300, fill: rgba(theme.accent2, 0.16) }),
          [0, 1, 2].map((i) => R("rect", { key: "wn" + i, x: 120 + i * 280, y: 40, width: 120, height: 150, rx: 6, fill: rgba(theme.surface, 0.5), stroke: rgba(tint, 0.4), strokeWidth: 4 }))),
        R("g", { transform: "translate(" + (W - 170) + ",270) rotate(" + (Math.sin(t * 1.1) * 6).toFixed(2) + ")" },
          R("line", { x1: 0, y1: -40, x2: 0, y2: 0, stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          R("rect", { x: -80, y: 0, width: 160, height: 90, rx: 8, fill: rgba(theme.accent, 0.85) }),
          R("rect", { x: -56, y: 30, width: 112, height: 14, rx: 7, fill: rgba(theme.accentInk, 0.55) }),
          R("rect", { x: -40, y: 54, width: 80, height: 10, rx: 5, fill: rgba(theme.accentInk, 0.35) })),
        /* bunting strung across the street, above the copy */
        R("g", null,
          R("path", { d: "M -20 130 q " + (W / 2) + " " + (90 + Math.sin(t * 0.7) * 12).toFixed(1) + " " + (W + 40) + " 20", fill: "none", stroke: rgba(tint, 0.5), strokeWidth: 4 }),
          Array.from({ length: 9 }).map((_, i) => {
            const bxp = 60 + i * ((W - 120) / 8);
            const byp = 130 + Math.sin((i / 8) * Math.PI) * (76 + Math.sin(t * 0.7) * 10) - (i / 8) * 110;
            const sway = Math.sin(t * 1.4 + i * 0.6) * 5;
            return R("path", { key: "bt" + i, d: "M -22 0 h 44 l -22 44 z", fill: rgba(i % 3 === 0 ? theme.accent : (i % 3 === 1 ? theme.accent2 : tint), 0.6), transform: "translate(" + bxp.toFixed(1) + "," + byp.toFixed(1) + ") rotate(" + sway.toFixed(2) + ")" });
          })),
        /* the awning */
        R("g", null,
          R("path", { d: "M 20 320 h " + (W - 40) + " l -40 120 h " + (-(W - 120)) + " z", fill: rgba(theme.accent, 0.5) }),
          Array.from({ length: 9 }).map((_, i) => R("path", { key: "aw" + i, d: "M " + (20 + i * ((W - 40) / 9)) + " 320 h " + ((W - 40) / 18) + " l -" + ((W - 40) / 18 - 20) + " 120 h -" + ((W - 40) / 18) + " z", fill: rgba(theme.surface, 0.35) })),
          R("path", { d: "M 60 440 h " + (W - 120), stroke: rgba(tint, 0.4), strokeWidth: 5 })),
        /* a chalkboard by the door, and a bike leaning on the wall */
        R("g", { transform: "translate(" + (W - 150) + ",1130) rotate(-2)" },
          R("rect", { x: -108, y: -170, width: 216, height: 340, rx: 8, fill: rgba(theme.ink, 0.82), stroke: rgba(theme.accent2, 0.5), strokeWidth: 6 }),
          [0, 1, 2, 3].map((i) => R("line", { key: "cb" + i, x1: -80, y1: -110 + i * 74, x2: 40 + (i % 2) * 40, y2: -110 + i * 74, stroke: rgba(theme.surface, 0.6 - i * 0.08), strokeWidth: 6, strokeLinecap: "round" })),
          R("path", { d: "M -70 130 q 60 -30 140 -8", fill: "none", stroke: rgba(theme.accent, 0.8), strokeWidth: 5 })),
        R("g", { opacity: 0.6, transform: "translate(150,1250) rotate(-6)" },
          [-64, 64].map((wx, i) => R("circle", { key: "bw" + i, cx: wx, cy: 0, r: 46, fill: "none", stroke: rgba(tint, 0.65), strokeWidth: 6 })),
          R("path", { d: "M -64 0 L -6 0 L 30 -74 L 64 0 M -6 0 L 30 -74 M -6 0 L 6 -70 L 30 -74", fill: "none", stroke: rgba(theme.accent2, 0.7), strokeWidth: 7, strokeLinejoin: "round" }),
          R("path", { d: "M 6 -70 q -30 -6 -40 8", fill: "none", stroke: rgba(tint, 0.6), strokeWidth: 6, strokeLinecap: "round" })),
        /* crates of produce with price cards */
        [0, 1, 2].map((i) => R("g", { key: "cr" + i, transform: "translate(" + (170 + i * 300) + "," + (kerb - 6) + ")" },
          R("path", { d: "M -84 0 h 168 v -84 h -168 z", fill: "none", stroke: rgba(tint, 0.55), strokeWidth: 5 }),
          R("path", { d: "M -84 -42 h 168", stroke: rgba(tint, 0.35), strokeWidth: 4 }),
          [0, 1, 2, 3, 4].map((j) => R("circle", { key: "fr" + j, cx: -60 + j * 30, cy: -100 - (j % 2) * 18, r: 22, fill: rgba(j % 2 ? theme.accent : theme.accent2, 0.7) })),
          R("g", { transform: "translate(70,-150) rotate(" + (Math.sin(t * 1.4 + i) * 5).toFixed(2) + ")" },
            R("rect", { x: -34, y: 0, width: 68, height: 44, rx: 4, fill: rgba(theme.surface, inv ? 0.5 : 0.96), stroke: rgba(tint, 0.4), strokeWidth: 3 }),
            R("rect", { x: -22, y: 14, width: 44, height: 10, rx: 5, fill: rgba(theme.accent, 0.8) })))),
        /* the pavement */
        R("line", { x1: 0, y1: kerb, x2: W, y2: kerb, stroke: rgba(tint, 0.6), strokeWidth: 7 }),
        R("rect", { x: 0, y: kerb, width: W, height: H - kerb, fill: rgba(theme.rule, 0.3) }),
        /* the sack trolley */
        R("g", { transform: "translate(" + tx.toFixed(1) + "," + kerb + ") rotate(" + (-lean).toFixed(2) + ")" },
          R("ellipse", { cx: 0, cy: 10, rx: 90, ry: 12, fill: rgba(theme.ink, 0.18) }),
          R("path", { d: "M -30 0 v -260 M 30 0 v -260", stroke: rgba(tint, 0.65), strokeWidth: 9 }),
          R("path", { d: "M -40 -10 h 80", stroke: rgba(tint, 0.6), strokeWidth: 9 }),
          R("path", { d: "M -30 -260 q 0 -40 40 -40", fill: "none", stroke: rgba(tint, 0.6), strokeWidth: 9 }),
          [0, 1, 2].map((i) => R("g", { key: "lc" + i },
            R("path", { d: "M -66 " + (-30 - i * 76) + " h 132 v -70 h -132 z", fill: rgba(theme.surface, inv ? 0.45 : 0.94), stroke: rgba(tint, 0.45), strokeWidth: 4 }),
            [0, 1, 2].map((j) => R("circle", { key: "pf" + j, cx: -40 + j * 40, cy: -66 - i * 76, r: 16, fill: rgba(j % 2 ? theme.accent2 : theme.accent, 0.6) })))),
          [-46, 46].map((wx, i) => R("g", { key: "wl" + i, transform: "translate(" + wx + ",-4) rotate(" + whl.toFixed(1) + ")" },
            R("circle", { r: 30, fill: "none", stroke: rgba(theme.ink, 0.8), strokeWidth: 8 }),
            R("path", { d: "M -30 0 h 60 M 0 -30 v 60", stroke: rgba(theme.ink, 0.4), strokeWidth: 4 })))),
        /* the shop window: a cat asleep on the sill, and the OPEN sign */
        R("g", { transform: "translate(" + (W * 0.62) + "," + (kerb - 240) + ")" },
          R("rect", { x: -200, y: -220, width: 400, height: 220, rx: 8, fill: rgba(theme.surface, inv ? 0.2 : 0.5), stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          R("line", { x1: 0, y1: -220, x2: 0, y2: 0, stroke: rgba(tint, 0.35), strokeWidth: 4 }),
          R("g", { transform: "translate(-96,-20) scale(1," + (1 + Math.sin(t * 0.9) * 0.03).toFixed(3) + ")" },
            R("path", { d: "M -70 0 q -9 -52 34 -60 q 50 -9 72 22 q 16 24 -5 38 z", fill: rgba(tint, 0.6) }),
            R("path", { d: "M 24 -40 l 8 -20 l 14 15 z", fill: rgba(tint, 0.6) }),
            R("path", { d: "M -70 0 q -34 -14 -44 5 q 20 8 44 -5 z", fill: rgba(tint, 0.5) })),
          R("g", { transform: "translate(96,-150) rotate(" + (Math.sin(t * 1.6) * 7).toFixed(2) + ")" },
            R("line", { x1: 0, y1: -30, x2: 0, y2: 0, stroke: rgba(tint, 0.5), strokeWidth: 4 }),
            R("rect", { x: -54, y: 0, width: 108, height: 54, rx: 5, fill: rgba(theme.accent, 0.85) }),
            R("rect", { x: -36, y: 20, width: 72, height: 12, rx: 6, fill: rgba(theme.accentInk, 0.6) }))),
        /* a pigeon and some leaves */
        (function () {
          const pc = (t % 8) / 8;
          const px = 700 + Math.sin(pc * Math.PI * 2) * 120;
          const bob = Math.abs(Math.sin(t * 4)) * 6;
          return R("g", { transform: "translate(" + px.toFixed(1) + "," + (kerb - 6 - bob).toFixed(1) + ")" },
            R("ellipse", { cx: 0, cy: -20, rx: 34, ry: 22, fill: rgba(tint, 0.6) }),
            R("circle", { cx: 26, cy: -40, r: 14, fill: rgba(tint, 0.65) }),
            R("path", { d: "M 40 -40 l 18 4 l -18 6 z", fill: rgba(theme.accent, 0.85) }),
            R("path", { d: "M -8 2 v 14 M 8 2 v 14", stroke: rgba(theme.accent, 0.7), strokeWidth: 4, strokeLinecap: "round" }));
        })(),
        [0, 1, 2, 3].map((i) => {
          const ph = (t * (0.22 + i * 0.04) + i * 0.23) % 1;
          const lx = 120 + i * 260 + Math.sin(t * 1.2 + i) * 50, ly = H - ph * (H + 160);
          return R("path", { key: "lv" + i, d: "M 0 0 q 24 -20 42 4 q -20 22 -42 -4 z", fill: rgba(theme.accent2, 0.4 * (1 - ph)), transform: "translate(" + lx.toFixed(1) + "," + ly.toFixed(1) + ") rotate(" + (ph * 340).toFixed(1) + ")" });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
