// CRUX CLIMB — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-2.js, template "CruxClimb").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Anton / body Asap. Camera set ["pushU","zoomIn","pushL","hopU","pushR","drop"].
// Entrances: title "slam", items "pop".
// Owns the Cursor:keys, Toggle:dial, Notify:drop, Swipe:swipe mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "crux-climb",
  label: "Crux Climb",

  // ---- type ----
  display: "Anton", displayFallback: "sans-serif",
  body: "Asap", bodyFallback: "sans-serif",
  mono: null,
  em: 0.44,
  titleLine: 1.04, titleSpace: "0.02em",
  titlePreset: "slam", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ wall: t.wall || "#2c2f33", hold: t.hold || "#ff8a3d", pad: "#3d7bff", chalk: "#f2f2ee", ink: "#191b1e" }),
  accents: ["hold","chalk","wall"],
  groundKey: "wall", inkKey: "ink", paperKey: "chalk",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "wall",
      "fg": "chalk",
      "hi": "hold",
      "world": true,
      "top": 310,
      "size": 126,
      "upper": true,
      "kicker": {
        "v": "tag",
        "bg": "hold",
        "c": "ink"
      }
    },
    "statement": {
      "bg": "ink",
      "fg": "chalk",
      "hi": "hold",
      "world": false,
      "top": 630,
      "size": 150,
      "upper": true
    },
    "feature": {
      "bg": "wall",
      "fg": "chalk",
      "hi": "hold",
      "world": true,
      "top": 248,
      "size": 98,
      "upper": true,
      "card": {
        "v": "frame",
        "bg": "ink",
        "r": 14,
        "line": "chalk"
      },
      "chips": {
        "v": "square",
        "colors": [
          "hold",
          "pad",
          "chalk"
        ],
        "text": "ink"
      }
    },
    "montage": {
      "bg": "ink",
      "fg": "chalk",
      "hi": "hold",
      "world": false,
      "top": 258,
      "size": 94,
      "upper": true,
      "tile": {
        "bg": "wall",
        "line": "chalk",
        "label": "hold",
        "r": 10
      },
      "tilts": [
        -3,
        2,
        2.5,
        -2
      ]
    },
    "stats": {
      "bg": "wall",
      "fg": "chalk",
      "hi": "hold",
      "world": true,
      "cols": [
        "hold",
        "pad",
        "chalk"
      ],
      "num": 152,
      "upper": true,
      "rule": true
    },
    "cta": {
      "bg": "hold",
      "fg": "ink",
      "hi": "chalk",
      "world": false,
      "top": 500,
      "size": 120,
      "upper": true,
      "btn": {
        "v": "block",
        "bg": "ink",
        "c": "chalk"
      },
      "logoShape": "rounded"
    },
    "app": {
      "bg": "wall",
      "fg": "chalk",
      "hi": "hold",
      "cardBg": "#25282d",
      "line": "chalk",
      "world": true,
      "upper": true
    }
  },

  // ---- camera + motion ----
  cams: ["pushU","zoomIn","pushL","hopU","pushR","drop"], camMul: 7, camOff: 1,
  mag: {"rot":0.9,"skew":3,"driftY":9},
  ambient: 1.9,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Cursor":"keys","Toggle":"dial","Notify":"drop","Swipe":"swipe"},

  strings: {
    brandName: "Crux Climb",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.75, strokeLinecap: "round", strokeLinejoin: "round" }, R2("path", { d: "M8 21l4-7-3-5 4-6 3 5-2 4 4 9" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      R("path", { d: "M " + (u.W - 380) + " -20 L " + (u.W - 200) + " " + (u.H * 0.4) + " L " + (u.W - 330) + " " + u.H + " L " + (u.W + 20) + " " + u.H + " L " + (u.W + 20) + " -20 Z", fill: rgba(theme.ink, 0.5) }),
      [[u.W - 300, 200, 0], [u.W - 240, 380, 1], [u.W - 290, 560, 2], [u.W - 210, 720, 3], [u.W - 280, 900, 4]].map(([x, y, i]) => {
        const e = u.ease.outBack(u.clamp01(u.seg(p, 0.08 + i * 0.09, 0.24 + i * 0.09)));
        const shapes = ["M -26 10 q 26 -34 52 0 z", "M -22 -14 h 44 v 28 h -44 z", "M 0 -24 l 24 40 h -48 z", "M -26 0 a 26 20 0 1 0 52 0 a 26 20 0 1 0 -52 0", "M -24 12 q 10 -40 48 -6 q -20 24 -48 6"];
        return R("path", { key: i, d: shapes[i], fill: [theme.hold, theme.pad, theme.chalk, theme.hold, theme.pad][i], transform: "translate(" + x + "," + y + ") scale(" + e + ") rotate(" + i * 24 + ")", opacity: 0.9 });
      }),
      (function () {
        const puff = (t * 0.5) % 1;
        return R("circle", { cx: u.W - 258, cy: 560, r: 10 + puff * 44, fill: rgba(theme.chalk, 0.25 * (1 - puff)) });
      })(),
      R("path", { d: "M 120 -20 q " + (Math.sin(t * 1.1) * 40) + " 300 0 560", fill: "none", stroke: rgba(theme.chalk, 0.3), strokeWidth: 6, strokeLinecap: "round" }),
      R("circle", { cx: 120 + Math.sin(t * 1.1) * 10, cy: 540, r: 16, fill: "none", stroke: theme.hold, strokeWidth: 6 }),
      Array.from({ length: 4 }).map((_, i) => R("rect", { key: "p" + i, x: 60 + i * 90, y: u.H - 160, width: 80, height: 34, rx: 8, fill: rgba(theme.pad, 0.4 + (i % 2) * 0.15) }))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
