// DAYLIGHT CONSOLE — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by the KEYFRAME admin template generator (src/templates/emit.js) from a validated
// TemplateSpec. Do not hand-edit: regenerating the template overwrites this file. To change the
// design, edit the spec on the template record and regenerate.
//
// Every executable line below was written by emit.js, not by the design model — the model
// supplied only the data (palette, per-beat look, camera set, world layer list). See the
// comment at the top of src/templates/emit.js for why that boundary exists.
//
//   slug        daylight-console
//   renderer    film-daylight-console
//   stage       landscape (1920x1080)
//   display     Instrument Serif / body Inter Tight
//   ground      #F7F4EE (paper), light
//   world       grid, beam, motes

const stage = require("../film_stage");

const SKIN = {
  id: "daylight-console",
  label: "Daylight Console",

  // The AUTHORED stage. film_stage.build() adopts it before emitting any geometry, so every
  // number below is in pixels of this frame and film_beats picks the matching layout family.
  stage: "landscape",

  // This template's own picture boxes, as fractions of the stage. film_beats.boxOf reads them when
  // it draws, and scripts/gen-film-packs derives the pack.json media contract from the same
  // numbers — so the manifest can never promise a box the film does not draw.
  boxes: {"feature":{"w":0.47,"h":0.54},"montage":{"h":0.34},"statement":{"h":0.4}},


  // ---- type ----
  display: "Instrument Serif", displayFallback: "Georgia, 'Times New Roman', serif",
  body: "Inter Tight", bodyFallback: "system-ui, sans-serif",
  mono: "JetBrains Mono",
  em: 0.47,
  titleLine: 1.07, titleSpace: "-0.005em",
  titlePreset: "drowse", itemPreset: "rise",

  // ---- palette ----
  // Called with {} for the authored defaults. film_stage.buildTheme then hue-maps the brand's
  // accents onto `accents` slot by slot at their authored luminance and rotates every other
  // stop onto the brand's lead hue — so a customer's brand recolours the whole design, not just
  // the headline. That is why every colour below is a ROLE the theme resolves, and why the
  // world and ground read `theme.<role>` rather than baking hexes.
  palette: (t) => ({ paper: t.paper || "#F7F4EE", linen: t.linen || "#EFEAE1", ink: t.ink || "#14161A", slate: t.slate || "#4A4F57", indigo: t.indigo || "#2A4BD8", clay: t.clay || "#B0532A" }),
  accents: ["indigo","clay","slate"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  dark: false,

  // ---- per-beat look ----
  // `world` is load-bearing, not decoration: each beat's copy colour is authored against its
  // OWN field, so a beat that says false is drawn on its flat bg and a beat that says true is
  // drawn over the animated backdrop.
  look: {
    "hook": {
      "bg": "paper",
      "fg": "ink",
      "hi": "indigo",
      "world": true,
      "top": 360,
      "size": 112,
      "upper": false,
      "align": "left",
      "kicker": {
        "v": "pill",
        "c": "indigo"
      }
    },
    "statement": {
      "bg": "linen",
      "fg": "ink",
      "hi": "indigo",
      "world": false,
      "top": 240,
      "size": 122,
      "upper": false,
      "align": "left"
    },
    "feature": {
      "bg": "paper",
      "fg": "ink",
      "hi": "indigo",
      "world": true,
      "top": 170,
      "size": 94,
      "upper": false,
      "align": "left",
      "card": {
        "v": "glow",
        "bg": "linen",
        "r": 24,
        "glow": "indigo"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "indigo",
          "clay",
          "slate"
        ],
        "text": "paper"
      }
    },
    "montage": {
      "bg": "linen",
      "fg": "ink",
      "hi": "indigo",
      "world": false,
      "top": 150,
      "size": 88,
      "upper": false,
      "align": "left",
      "tile": {
        "bg": "paper",
        "line": "indigo",
        "label": "ink",
        "r": 20,
        "labelSize": 26
      }
    },
    "stats": {
      "bg": "paper",
      "fg": "ink",
      "hi": "indigo",
      "world": true,
      "top": 230,
      "size": 90,
      "upper": false,
      "align": "left",
      "cols": [
        "indigo",
        "clay",
        "indigo"
      ],
      "num": 158
    },
    "cta": {
      "bg": "linen",
      "fg": "ink",
      "hi": "indigo",
      "world": false,
      "top": 200,
      "size": 100,
      "upper": false,
      "align": "left",
      "btn": {
        "v": "block",
        "bg": "indigo",
        "c": "paper"
      },
      "logoShape": "square"
    },
    "app": {
      "bg": "paper",
      "fg": "ink",
      "hi": "indigo",
      "world": false,
      "top": 210,
      "size": 88,
      "upper": false,
      "align": "left",
      "cardBg": "linen",
      "line": "indigo"
    }
  },

  // ---- camera + motion ----
  // Indexed (sceneIndex * camMul + camOff) % 6 by film_stage, so adjacent scenes take different
  // camera moves rather than the whole film sharing one.
  cams: ["pushR","pushL","pushD","pushU","zoomIn","pushR"], camMul: 2, camOff: 1,
  mag: {"x":0.5,"y":0.3,"rot":0.2,"skew":0,"zin":0.2,"zout":0.16,"driftX":5,"driftY":3,"driftZ":0.02,"slide":0.12,"inn":0.3,"out":0.9},
  ambient: 0.7,
  energy: 0.55,
  badge: "square",

  // ---- the mechanics this pack owns ----
  // A beat that ends up holding no picture is expressed as one of these instead of shipping a
  // bare text slide. A pack that declares none renders only the six authored acts.
  variants: {"feature":"Code","montage":"Scroll","stats":"Ring"},

  strings: {"brandName":"Daylight Console"},

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: theme.currentBg, stroke: "none" },
    R2("rect",{x:5,y:5,width:14,height:14,rx:3})),

  // The ground treatment, resolved against the live (possibly re-hued) theme.
  groundCss: (theme, bg) => "linear-gradient(180deg, " + theme.paper + " 0%, " + bg + " 58%, " + theme.linen + " 100%)",

  // ---- the world ----
  // The animated backdrop. Pure in (theme, t, progress, utils) — no Math.random and no Date,
  // which is what lets film_stage re-evaluate it deterministically on every seek. All geometry
  // was resolved at generation time from the spec's layer list, so the numbers below are
  // literals and the render page runs no RNG at all.
  World: (theme, t, p, u) => {
    var W = u.W, H = u.H;
    return R("g", null,
    R("g",null,Array.from({length:14}).map(function(_,i){return R("line",{key:"v"+i,x1:W*i/14,y1:0,x2:W*i/14,y2:H,stroke:rgba(theme.slate,0.07),strokeWidth:W*0});}).concat(Array.from({length:24}).map(function(_,i){return R("line",{key:"h"+i,x1:0,y1:H*i/24,x2:W,y2:H*i/24,stroke:rgba(theme.slate,0.05),strokeWidth:W*0});}))),
    R("g",{transform:"rotate("+(-70+Math.sin(t*0.06)*6)+" "+(W*0.7)+" "+(H*0.4)+")"},
      R("rect",{x:W*0.7-W*0.22/2,y:-H*0.2,width:W*0.22,height:H*1.5,fill:rgba(theme.indigo,0.1)})),
    R("g",null,[{x:0.05,y:0.81,ph:5.25,r:5.8},{x:0.11,y:0.18,ph:2.69,r:4.84},{x:0.73,y:0.92,ph:5.08,r:4.71},{x:0.69,y:0.91,ph:3.43,r:2.67},{x:0.27,y:0.83,ph:5.88,r:2.82},{x:0.49,y:0.54,ph:1.19,r:2.51},{x:0.59,y:0.41,ph:4.37,r:2.68},{x:0.92,y:0.25,ph:2.23,r:4.91},{x:0.22,y:0.56,ph:1.19,r:4.58},{x:0.93,y:0.28,ph:5.39,r:5.65},{x:0.47,y:0.88,ph:0.12,r:5.61},{x:0.58,y:0.12,ph:1.06,r:3.73},{x:0.54,y:0.11,ph:5.73,r:4.53},{x:0.51,y:0.01,ph:3.56,r:3.51},{x:0.26,y:0.48,ph:5.56,r:2.43},{x:0.43,y:0.75,ph:3.88,r:4.48}].map(function(m,i){return R("circle",{key:i,cx:W*m.x+Math.sin(t*0.16+m.ph)*W*0.06,cy:(H*m.y+((t*8+i*90)%(H*0.6)))%H,r:m.r,fill:rgba(theme.clay,0.16)});}))
    );
  },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
