// DEEP FIELD — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-08.js, template "DeepField").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Orbitron / body Lexend. Camera set ["zoomOut","pushR","drop","pushL","zoomIn","pushU"].
// Entrances: title "rise", items "pop".
// Owns the Scroll:feed, Typing:caret, Ring:ring mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "deep-field-article",
  label: "Deep Field",

  // ---- type ----
  display: "Orbitron", displayFallback: "system-ui, sans-serif",
  body: "Lexend", bodyFallback: "system-ui, sans-serif",
  mono: "Space Mono",
  chrome: false,
  devanagari: "Noto Sans Devanagari",
  maxScenes: 18,
  em: 0.66,
  titleLine: 1.1, titleSpace: "0.01em",
  titlePreset: "rise", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ bg: t.bg || "#0b1020", surface: "#141b30", rule: "#283354", inkMuted: "#8b96b8", ink: "#f2f5fc", accent: t.accent || "#5ce1ff", accent2: t.accent2 || "#ff9f5c", accentInk: "#050810" }),
  accents: ["accent","accent2","bg"],
  groundKey: "bg", inkKey: "accentInk", paperKey: "ink",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 86,
      "kicker": {
        "v": "outline",
        "c": "accent"
      }
    },
    "statement": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 610,
      "size": 98
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 540,
      "size": 60,
      "bodySize": 38,
      "ch": 54,
      "lh": 1.52,
      "weight": 400,
      "dim": 0.92,
      "kicker": {
        "v": "bare",
        "c": "accent2"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 360,
      "size": 70,
      "ch": 25,
      "lh": 1.22,
      "markSize": 210
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 255,
      "size": 70,
      "swap": "quote",
      "card": {
        "v": "glow",
        "bg": "surface",
        "glow": "accent",
        "r": 14,
        "line": "inkMuted"
      },
      "chips": {
        "v": "outline",
        "colors": [
          "accent",
          "accent2",
          "inkMuted"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 330,
      "size": 64,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 14,
        "h": 640,
        "labelSize": 42
      },
      "tilts": [
        0,
        0,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 390,
      "size": 66,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 150,
      "rule": false,
      "glowNums": true
    },
    "cta": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "accent2",
      "world": true,
      "top": 470,
      "size": 80,
      "align": "left",
      "btn": {
        "v": "glow",
        "bg": "accentInk",
        "c": "ink"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["zoomOut","pushR","drop","pushL","zoomIn","pushU"], camMul: 7, camOff: 1,
  mag: {"rot":0.3,"driftX":7,"driftY":7,"driftZ":0.05,"slide":0.22,"inn":0.24,"zin":0.34,"zout":0.3},
  ambient: 1.6,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"feed","Typing":"caret","Ring":"ring"},

  strings: {
    brandName: "Deep Field",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.3, strokeLinecap: "round", strokeLinejoin: "round" }, R2("path", { d: "M4 15l14-9 3 5-14 9zM8 18l-2 3" })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "radial-gradient(90% 48% at 26% 6%, " + rgba(theme.accent, 0.16) + " 0%, transparent 62%), " + bg),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, E = u.ease, inv = theme.currentBg !== theme.bg;
      const tint = inv ? theme.accentInk : theme.inkMuted, pier = H - 300;
      const cyc = (t % 20) / 20, tri = cyc < 0.5 ? cyc * 2 : 2 - cyc * 2;
      const alt = -68 + E.inOut(tri) * 56;
      const drift = (t * 3) % 360;
      const satc = (t % 26) / 26;
      return R("g", null,
        R("defs", null,
          R("radialGradient", { id: "df-neb", cx: "50%", cy: "50%" },
            R("stop", { offset: "0%", stopColor: rgba(theme.accent, 0.28) }), R("stop", { offset: "100%", stopColor: rgba(theme.accent, 0) })),
          R("radialGradient", { id: "df-neb2", cx: "50%", cy: "50%" },
            R("stop", { offset: "0%", stopColor: rgba(theme.accent2, 0.2) }), R("stop", { offset: "100%", stopColor: rgba(theme.accent2, 0) }))),
        R("circle", { cx: W * 0.28, cy: 170, r: 340, fill: "url(#df-neb)" }),
        R("circle", { cx: W * 0.82, cy: 240, r: 260, fill: "url(#df-neb2)" }),
        /* overhead: stars on a slow rotation, brighter ones twinkling */
        R("g", { transform: "rotate(" + (drift * 0.05).toFixed(2) + " " + (W / 2) + " 140)" },
          Array.from({ length: 34 }).map((_, i) => {
            const sx = ((i * 137) % W), sy = 24 + ((i * 71) % 250);
            const tw = 0.4 + 0.6 * Math.abs(Math.sin(t * (0.6 + (i % 5) * 0.3) + i));
            return R("circle", { key: "st" + i, cx: sx, cy: sy, r: 2 + (i % 4), fill: rgba(i % 7 === 0 ? theme.accent : theme.ink, 0.3 + 0.55 * tw) });
          })),
        /* a constellation drawn faintly between the brighter stars */
        R("g", { opacity: 0.5 },
          R("path", { d: "M 130 60 L 236 128 L 352 96 L 430 176 L 560 138", fill: "none", stroke: rgba(theme.accent, 0.4), strokeWidth: 2.5 }),
          [[130, 60], [236, 128], [352, 96], [430, 176], [560, 138]].map((n, i) => R("circle", { key: "cn" + i, cx: n[0], cy: n[1], r: 4 + (i % 2) * 2, fill: rgba(theme.accent, 0.85) }))),
        /* a shooting star crossing every 9s */
        (function () {
          const sc = (t % 9) / 9;
          if (sc > 0.16) return null;
          const k = sc / 0.16, sx = 940 - k * 620, sy = 40 + k * 210;
          return R("g", { opacity: Math.sin(k * Math.PI) },
            R("line", { x1: sx + 90, y1: sy - 30, x2: sx, y2: sy, stroke: rgba(theme.ink, 0.75), strokeWidth: 4, strokeLinecap: "round" }),
            R("circle", { cx: sx, cy: sy, r: 5, fill: rgba(theme.ink, 0.95) }));
        })(),
        /* a satellite crossing the star band */
        R("g", { opacity: 0.8 },
          R("circle", { cx: -40 + satc * (W + 80), cy: 90 + Math.sin(satc * Math.PI) * 40, r: 5, fill: rgba(theme.accent2, 0.95) }),
          R("line", { x1: -80 + satc * (W + 80), y1: 96 + Math.sin(satc * Math.PI) * 40, x2: -40 + satc * (W + 80), y2: 90 + Math.sin(satc * Math.PI) * 40, stroke: rgba(theme.accent2, 0.35), strokeWidth: 3 })),
        /* margin: the dome slit and a console */
        R("g", { transform: "translate(" + (W - 140) + ",1140)" },
          R("path", { d: "M -120 220 A 130 210 0 0 1 120 220 Z", fill: rgba(theme.surface, 0.6), stroke: rgba(tint, 0.4), strokeWidth: 5 }),
          R("path", { d: "M -34 220 A 44 200 0 0 1 34 220 Z", fill: rgba(theme.bg, 0.95), stroke: rgba(theme.accent, 0.5), strokeWidth: 4 }),
          Array.from({ length: 6 }).map((_, i) => R("circle", { key: "ds" + i, cx: -14 + (i % 3) * 14, cy: 60 + Math.floor(i / 3) * 40, r: 3, fill: rgba(theme.accent, 0.7) })),
          R("rect", { x: -110, y: 250, width: 220, height: 90, rx: 8, fill: rgba(theme.surface, 0.9), stroke: rgba(tint, 0.45), strokeWidth: 4 }),
          [0, 1, 2, 3, 4].map((i) => R("rect", { key: "cs" + i, x: -92 + i * 38, y: 272, width: 26, height: 20, rx: 3, fill: rgba(Math.sin(t * 2 + i * 1.3) > 0 ? theme.accent : theme.rule, 0.85) })),
          R("path", { d: "M -92 320 h 184", stroke: rgba(theme.accent2, 0.6), strokeWidth: 5 })),
        /* mid: the telescope on its mount */
        R("g", { transform: "translate(" + (W * 0.4) + "," + (pier - 40) + ")" },
          R("path", { d: "M -120 40 h 240 l -40 -80 h -160 z", fill: rgba(theme.surface, 0.9), stroke: rgba(tint, 0.45), strokeWidth: 5 }),
          R("circle", { cx: 0, cy: -50, r: 30, fill: rgba(theme.rule, 0.8), stroke: rgba(tint, 0.4), strokeWidth: 4 }),
          R("g", { transform: "rotate(" + alt.toFixed(2) + " 0 -50)" },
            R("rect", { x: -34, y: -420, width: 68, height: 380, rx: 14, fill: rgba(theme.surface, 0.96), stroke: rgba(theme.accent, 0.5), strokeWidth: 5 }),
            R("rect", { x: -34, y: -420, width: 68, height: 46, rx: 10, fill: rgba(theme.accent, 0.5) }),
            R("circle", { cx: 0, cy: -400, r: 22, fill: rgba(theme.accent, 0.7) }),
            R("rect", { x: 34, y: -320, width: 40, height: 96, rx: 8, fill: rgba(theme.rule, 0.9), stroke: rgba(tint, 0.4), strokeWidth: 3 }),
            R("rect", { x: -30, y: 20, width: 60, height: 120, rx: 8, fill: rgba(theme.accent2, 0.6) }),
            R("line", { x1: 0, y1: -374, x2: 0, y2: -70, stroke: rgba(theme.accent, 0.16), strokeWidth: 3 })),
          R("path", { d: "M -140 40 L -104 240 M 140 40 L 104 240 M -104 240 h 208", stroke: rgba(tint, 0.45), strokeWidth: 8, strokeLinecap: "round" })),
        /* floor: pier, cable runs, a spec board */
        R("line", { x1: 0, y1: pier, x2: W, y2: pier, stroke: rgba(tint, 0.5), strokeWidth: 7 }),
        R("rect", { x: 0, y: pier, width: W, height: H - pier, fill: rgba(theme.surface, 0.45) }),
        R("path", { d: "M -30 " + (H - 70) + " q 240 " + (-60 + Math.sin(t * 0.8) * 12).toFixed(1) + " 500 6 q 250 62 540 -20", fill: "none", stroke: rgba(theme.accent, 0.3), strokeWidth: 9, strokeLinecap: "round" }),
        /* a guide-scope monitor, its field drifting with the tracking */
        R("g", { transform: "translate(" + (W * 0.72) + "," + (H - 160) + ")" },
          R("rect", { x: -150, y: -120, width: 300, height: 230, rx: 10, fill: rgba(theme.surface, 0.95), stroke: rgba(tint, 0.45), strokeWidth: 5 }),
          R("rect", { x: -128, y: -100, width: 256, height: 168, rx: 6, fill: rgba(theme.accentInk, 0.75) }),
          Array.from({ length: 12 }).map((_, i) => R("circle", { key: "gs" + i, cx: -110 + ((i * 61 + t * 9) % 236), cy: -84 + ((i * 43) % 136), r: 2 + (i % 3), fill: rgba(theme.accent, 0.5 + (i % 4) * 0.12) })),
          R("path", { d: "M 0 -100 v 168 M -128 -16 h 256", stroke: rgba(theme.accent, 0.3), strokeWidth: 2 }),
          R("circle", { cx: Math.sin(t * 0.4) * 16, cy: -16 + Math.cos(t * 0.4) * 10, r: 12, fill: "none", stroke: rgba(theme.accent2, 0.9), strokeWidth: 3 }),
          R("rect", { x: -128, y: 80, width: 90, height: 10, rx: 5, fill: rgba(theme.accent, 0.6) })),
        /* a cable drum, a step ladder and a flask on the pier */
        R("g", { opacity: 0.8, transform: "translate(" + (W * 0.44) + "," + (H - 90) + ")" },
          R("circle", { r: 46, fill: rgba(theme.surface, 0.5), stroke: rgba(tint, 0.45), strokeWidth: 4 }),
          R("g", { transform: "rotate(" + ((t * 20) % 360).toFixed(1) + ")" },
            R("path", { d: "M -46 0 h 92 M 0 -46 v 92", stroke: rgba(theme.accent, 0.35), strokeWidth: 4 })),
          R("circle", { r: 15, fill: rgba(theme.accent2, 0.7) })),
        R("g", { opacity: 0.6, transform: "translate(" + (W * 0.2) + "," + (H - 60) + ")" },
          R("line", { x1: -46, y1: 0, x2: -14, y2: -190, stroke: rgba(tint, 0.6), strokeWidth: 8 }),
          R("line", { x1: 46, y1: 0, x2: 14, y2: -190, stroke: rgba(tint, 0.6), strokeWidth: 8 }),
          [0, 1, 2, 3].map((i) => R("line", { key: "rg" + i, x1: -38 + i * 6, y1: -30 - i * 42, x2: 38 - i * 6, y2: -30 - i * 42, stroke: rgba(tint, 0.5), strokeWidth: 6 }))),
        R("g", { transform: "translate(" + (W * 0.32) + "," + (H - 74) + ")" },
          R("path", { d: "M -22 0 h 44 v -74 h -44 z", fill: rgba(theme.accent2, 0.55), stroke: rgba(tint, 0.4), strokeWidth: 3 }),
          R("rect", { x: -14, y: -92, width: 28, height: 20, rx: 4, fill: rgba(tint, 0.6) }),
          R("rect", { x: -18, y: -50, width: 36, height: 10, rx: 3, fill: rgba(theme.accent, 0.5) })),
        R("g", { opacity: 0.75, transform: "translate(180," + (H - 150) + ")" },
          R("rect", { x: -110, y: -80, width: 220, height: 130, rx: 6, fill: rgba(theme.surface, 0.8), stroke: rgba(tint, 0.4), strokeWidth: 4 }),
          [0, 1, 2].map((i) => R("line", { key: "sb" + i, x1: -86, y1: -50 + i * 34, x2: 40 + (i % 2) * 46, y2: -50 + i * 34, stroke: rgba(theme.accent, 0.5), strokeWidth: 5 }))),
        [0, 1, 2, 3, 4, 5].map((i) => {
          const ph = (t * (0.12 + i * 0.02) + i * 0.18) % 1;
          return R("circle", { key: "dt" + i, cx: 200 + i * 160 + Math.sin(t * 0.7 + i) * 34, cy: H - ph * (H - 200), r: 2.5 + (i % 2), fill: rgba(theme.accent, 0.26 * (1 - ph)) });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
