// DUNE CAMP — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-6.js, template "DuneCamp").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Amiri / body Tajawal. Camera set ["pushL","zoomOut","drop","pushR","zoomIn","pushU"].
// Entrances: title "drowse", items "rise".
// Owns the Scroll:ticker, Ring:gauge, Typing:caret, Swipe:swipe mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "dune-camp",
  label: "Dune Camp",

  // ---- type ----
  display: "Amiri", displayFallback: "serif",
  body: "Tajawal", bodyFallback: "sans-serif",
  mono: null,
  em: 0.58,
  titleLine: 1.08, titleSpace: "0",
  titlePreset: "drowse", itemPreset: "rise",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ dusk: t.dusk || "#241d3e", sand: t.sand || "#e0b878", ember2: "#e8703c", night: "#151030", cream2: "#f4ecdc" }),
  accents: ["sand","ember2","dusk"],
  groundKey: "dusk", inkKey: "night", paperKey: "cream2",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "dusk",
      "fg": "cream2",
      "hi": "sand",
      "world": true,
      "top": 330,
      "size": 122,
      "kicker": {
        "v": "bare",
        "c": "sand"
      }
    },
    "statement": {
      "bg": "night",
      "fg": "cream2",
      "hi": "ember2",
      "world": true,
      "top": 630,
      "size": 148
    },
    "feature": {
      "bg": "dusk",
      "fg": "cream2",
      "hi": "sand",
      "world": true,
      "top": 250,
      "size": 98,
      "card": {
        "v": "glow",
        "bg": "night",
        "glow": "sand",
        "r": 22,
        "line": "cream2"
      },
      "chips": {
        "v": "outline",
        "colors": [
          "sand",
          "ember2"
        ],
        "text": "night"
      }
    },
    "montage": {
      "bg": "night",
      "fg": "cream2",
      "hi": "sand",
      "world": true,
      "top": 258,
      "size": 94,
      "tile": {
        "bg": "dusk",
        "line": "cream2",
        "label": "sand",
        "r": 18,
        "glow": "sand"
      },
      "tilts": [
        -2,
        1.5,
        2,
        -1.5
      ]
    },
    "stats": {
      "bg": "dusk",
      "fg": "cream2",
      "hi": "sand",
      "world": true,
      "cols": [
        "sand",
        "ember2",
        "cream2"
      ],
      "num": 150,
      "glowNums": true
    },
    "cta": {
      "bg": "sand",
      "fg": "night",
      "hi": "ember2",
      "world": false,
      "top": 500,
      "size": 118,
      "btn": {
        "v": "pill",
        "bg": "night",
        "c": "cream2"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "dusk",
      "fg": "cream2",
      "hi": "sand",
      "cardBg": "#312752",
      "line": "cream2",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["pushL","zoomOut","drop","pushR","zoomIn","pushU"], camMul: 5, camOff: 2,
  mag: {"rot":0.4,"driftY":9,"inn":0.3,"driftZ":0.035},
  ambient: 1.6,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"ticker","Ring":"gauge","Typing":"caret","Swipe":"swipe"},

  strings: {
    brandName: "Dune Camp",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round", strokeLinejoin: "round" }, R2("path", { d: "M3 20l9-16 9 16zM8 20l4-7 4 7" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      Array.from({ length: 22 }).map((_, i) => R("circle", { key: "s" + i, cx: (i * 167 + 40) % u.W, cy: (i * 211 + 60) % (u.H * 0.5), r: 1.6 + (i % 3) * 0.7, fill: rgba(theme.cream2, 0.3 + 0.55 * Math.abs(Math.sin(t * 1.5 + i * 2.3))) })),
      R("circle", { cx: u.W - 210, cy: 250, r: 62, fill: rgba(theme.cream2, 0.9) }),
      R("circle", { cx: u.W - 240, cy: 236, r: 56, fill: theme.dusk }),
      R("path", { d: "M -20 " + (u.H - 470) + " q 260 -130 520 -30 q 280 108 560 -40 L " + (u.W + 20) + " " + (u.H + 20) + " L -20 " + (u.H + 20) + " Z", fill: rgba(theme.sand, 0.45) }),
      R("path", { d: "M -20 " + (u.H - 300) + " q 220 -110 470 -20 q 300 100 590 -50 L " + (u.W + 20) + " " + (u.H + 20) + " L -20 " + (u.H + 20) + " Z", fill: theme.sand }),
      (function () {
        const ph = ((t * 0.07) % 1);
        return R("g", null, [0, 1, 2].map((i) => {
          const cx = -180 + (ph + i * 0.09) * (u.W + 380);
          const bob = Math.sin(t * 2.6 + i) * 5;
          return R("g", { key: i, transform: "translate(" + cx + "," + (u.H - 430 + bob) + ") scale(" + (0.9 - i * 0.08) + ")" },
            R("path", { d: "M -56 0 q 8 -40 26 -46 q 12 -32 26 0 q 20 8 26 46 z", fill: rgba(theme.night, 0.92) }),
            R("path", { d: "M 46 -36 q 22 -12 24 -46 q 2 -18 -12 -14 q -14 4 -14 22", fill: "none", stroke: rgba(theme.night, 0.92), strokeWidth: 11, strokeLinecap: "round" }),
            [-40, -14, 16, 40].map((ox, k) => R("line", { key: k, x1: ox, y1: -2, x2: ox + Math.sin(t * 4 + k) * 7, y2: 46, stroke: rgba(theme.night, 0.92), strokeWidth: 8, strokeLinecap: "round" })));
        }));
      })(),
      (function () {
        const fl = 1 + Math.sin(t * 8) * 0.2;
        return R("g", { transform: "translate(210," + (u.H - 250) + ")" },
          R("polygon", { points: "0,-150 96,0 -96,0", fill: rgba(theme.night, 0.9) }),
          R("polygon", { points: "0,-118 40,0 -40,0", fill: rgba(theme.ember2, 0.35) }),
          R("ellipse", { cx: 150, cy: -6, rx: 26 * fl, ry: 34 * fl, fill: rgba(theme.ember2, 0.85) }),
          R("ellipse", { cx: 150, cy: 2, rx: 12 * fl, ry: 18 * fl, fill: rgba(theme.sand, 0.95) }),
          Array.from({ length: 4 }).map((_, i) => {
            const q = (t * 0.7 + i * 0.25) % 1;
            return R("circle", { key: i, cx: 150 + Math.sin(q * 7 + i) * 22, cy: -40 - q * 180, r: 3.4, fill: rgba(theme.ember2, 0.8 * (1 - q)) });
          }));
      })()),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
