// ENDGAME — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-1.js, template "Endgame").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display DM Serif Display / body DM Sans. Camera set ["zoomIn","pushL","drop","pushR","zoomOut","hopU"].
// Entrances: title "drowse", items "flip".
// Owns the Scroll:board, Toggle:check, Typing:typewriter, Morph:flap mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "endgame",
  label: "Endgame",

  // ---- type ----
  display: "DM Serif Display", displayFallback: "serif",
  body: "DM Sans", bodyFallback: "sans-serif",
  mono: null,
  em: 0.54,
  titleLine: 1.08, titleSpace: "0",
  titlePreset: "drowse", itemPreset: "flip",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ board: t.board || "#efe6d8", walnut: "#6b4a2f", ink: "#221c16", check: t.check || "#b3452e", sage: "#7d8c69" }),
  accents: ["check","board"],
  groundKey: "board", inkKey: "ink", paperKey: "board",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "board",
      "fg": "ink",
      "hi": "check",
      "world": true,
      "top": 340,
      "size": 122,
      "kicker": {
        "v": "bare",
        "c": "walnut"
      }
    },
    "statement": {
      "bg": "ink",
      "fg": "board",
      "hi": "check",
      "world": false,
      "top": 630,
      "size": 148
    },
    "feature": {
      "bg": "board",
      "fg": "ink",
      "hi": "check",
      "world": true,
      "top": 250,
      "size": 96,
      "card": {
        "v": "frame",
        "bg": "walnut",
        "r": 10,
        "line": "board"
      },
      "chips": {
        "v": "outline",
        "colors": [
          "check",
          "walnut"
        ],
        "text": "board"
      }
    },
    "montage": {
      "bg": "ink",
      "fg": "board",
      "hi": "check",
      "world": false,
      "top": 258,
      "size": 92,
      "tile": {
        "bg": "board",
        "line": "ink",
        "label": "board",
        "r": 8
      },
      "tilts": [
        0,
        0,
        0,
        0
      ]
    },
    "stats": {
      "bg": "board",
      "fg": "ink",
      "hi": "check",
      "world": true,
      "cols": [
        "check",
        "walnut",
        "sage"
      ],
      "num": 150
    },
    "cta": {
      "bg": "walnut",
      "fg": "board",
      "hi": "check",
      "world": false,
      "top": 500,
      "size": 118,
      "btn": {
        "v": "block",
        "bg": "board",
        "c": "ink"
      },
      "logoShape": "rounded"
    },
    "app": {
      "bg": "board",
      "fg": "ink",
      "hi": "check",
      "cardBg": "#faf5ec",
      "line": "ink",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["zoomIn","pushL","drop","pushR","zoomOut","hopU"], camMul: 5, camOff: 2,
  mag: {"rot":0.5,"inn":0.26,"driftX":5},
  ambient: 1.5,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"board","Toggle":"check","Typing":"typewriter","Morph":"flap"},

  strings: {
    brandName: "Endgame",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: theme.currentBg }, R2("path", { d: "M8 21h8M9 19h6l-1-5 3-4-3-6-5 3 1 4-2 3z" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      (function () {
        const sq = 84, cells = [];
        for (let r = 0; r < 5; r++) for (let c = 0; c < 5; c++) if ((r + c) % 2 === 0) cells.push(R("rect", { key: r + "-" + c, x: u.W - 440 + c * sq, y: u.H - 440 + r * sq, width: sq, height: sq, fill: rgba(theme.walnut, 0.3) }));
        return R("g", null, cells, R("rect", { x: u.W - 440, y: u.H - 440, width: sq * 5 + 20, height: sq * 5 + 20, fill: "none", stroke: rgba(theme.walnut, 0.5), strokeWidth: 6, transform: "translate(-10,-10)" }));
      })(),
      (function () {
        const hop = (t * 0.5) % 1;
        const moves = [[0, 0], [1, 2], [3, 3], [2, 1], [0, 0]];
        const mi = Math.min(3, Math.floor(hop * 4)), mf = hop * 4 - mi;
        const ex = u.ease.inOut(u.clamp01(mf));
        const x = u.W - 440 + (moves[mi][0] + (moves[mi + 1][0] - moves[mi][0]) * ex) * 84 + 42;
        const y = u.H - 440 + (moves[mi][1] + (moves[mi + 1][1] - moves[mi][1]) * ex) * 84 + 42 - Math.sin(ex * Math.PI) * 60;
        return R("g", { transform: "translate(" + x + "," + y + ")" },
          R("path", { d: "M -18 26 h36 M -14 20 h28 l-4 -18 8 -12 -10 -18 -16 8 4 14 -8 10 z", fill: theme.check, stroke: theme.ink, strokeWidth: 3, strokeLinejoin: "round" }));
      })(),
      R("g", { transform: "translate(170,240)" },
        R("rect", { x: -90, y: -40, width: 180, height: 90, rx: 10, fill: "none", stroke: rgba(theme.ink, 0.45), strokeWidth: 5 }),
        R("line", { x1: 0, y1: -40, x2: 0, y2: 50, stroke: rgba(theme.ink, 0.45), strokeWidth: 4 }),
        R("line", { x1: -45, y1: 0, x2: -45 + Math.cos(t * 2.2) * 24, y2: Math.sin(t * 2.2) * 24, stroke: theme.check, strokeWidth: 4, strokeLinecap: "round" }),
        R("line", { x1: 45, y1: 0, x2: 45 + Math.cos(t * 0.4 + 2) * 22, y2: Math.sin(t * 0.4 + 2) * 22, stroke: rgba(theme.ink, 0.6), strokeWidth: 4, strokeLinecap: "round" })),
      [0, 1, 2].map((i) => R("text", { key: i, x: 90 + i * 56, y: u.H - 180, fontFamily: '"DM Serif Display", serif', fontSize: 40, fill: rgba(theme.ink, 0.25 + (Math.floor(t * 0.7) % 3 === i ? 0.4 : 0)) }, ["♟", "♞", "♛"][i]))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
