// ESCAPEMENT — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-6.js, template "Escapement").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Cormorant Garamond / body Inter Tight. Camera set ["zoomIn","pushL","drop","spin","pushR","zoomOut"].
// Entrances: title "drowse", items "rise".
// Owns the Ring:ring, Typing:terminal, Toggle:dial, Morph:flap mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "escapement",
  label: "Escapement",

  // ---- type ----
  display: "Cormorant Garamond", displayFallback: "serif",
  body: "Inter Tight", bodyFallback: "sans-serif",
  mono: null,
  em: 0.44,
  titleLine: 1.04, titleSpace: "0.02em",
  titlePreset: "drowse", itemPreset: "rise",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ deep: t.deep || "#152030", brass: t.brass || "#d0a75c", ruby: "#c0384f", silverw: "#dce4ec", ink: "#101a26" }),
  accents: ["brass","deep"],
  groundKey: "deep", inkKey: "ink", paperKey: "silverw",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "deep",
      "fg": "silverw",
      "hi": "brass",
      "world": true,
      "top": 330,
      "size": 126,
      "kicker": {
        "v": "outline",
        "c": "brass"
      }
    },
    "statement": {
      "bg": "ink",
      "fg": "silverw",
      "hi": "brass",
      "world": true,
      "top": 630,
      "size": 152
    },
    "feature": {
      "bg": "deep",
      "fg": "silverw",
      "hi": "brass",
      "world": true,
      "top": 250,
      "size": 100,
      "card": {
        "v": "glow",
        "bg": "ink",
        "glow": "brass",
        "r": 14,
        "line": "silverw"
      },
      "chips": {
        "v": "outline",
        "colors": [
          "brass",
          "ruby"
        ],
        "text": "ink"
      }
    },
    "montage": {
      "bg": "ink",
      "fg": "silverw",
      "hi": "brass",
      "world": true,
      "top": 258,
      "size": 96,
      "tile": {
        "bg": "deep",
        "line": "silverw",
        "label": "brass",
        "r": 10,
        "glow": "brass"
      },
      "tilts": [
        -1.5,
        1,
        1.5,
        -1
      ]
    },
    "stats": {
      "bg": "deep",
      "fg": "silverw",
      "hi": "brass",
      "world": true,
      "cols": [
        "brass",
        "ruby",
        "silverw"
      ],
      "num": 152,
      "glowNums": true
    },
    "cta": {
      "bg": "ink",
      "fg": "silverw",
      "hi": "brass",
      "world": true,
      "top": 500,
      "size": 120,
      "btn": {
        "v": "glow",
        "bg": "brass",
        "c": "ink"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "deep",
      "fg": "silverw",
      "hi": "brass",
      "cardBg": "#1e2c3e",
      "line": "silverw",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["zoomIn","pushL","drop","spin","pushR","zoomOut"], camMul: 5, camOff: 3,
  mag: {"rot":0.6,"inn":0.24,"driftX":5},
  ambient: 1.5,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Ring":"ring","Typing":"terminal","Toggle":"dial","Morph":"flap"},

  strings: {
    brandName: "Escapement",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round" }, R2("circle", { cx: 12, cy: 12, r: 8 }), R2("path", { d: "M12 8v4l3 2M12 2v2M12 20v2M2 12h2M20 12h2" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      (function () {
        const gear = (cx, cy, r, teeth, spd, col, key) => R("g", { key, transform: "translate(" + cx + "," + cy + ") rotate(" + (t * spd) + ")" },
          Array.from({ length: teeth }).map((_, i) => R("rect", { key: i, x: -5, y: -r - 12, width: 10, height: 16, rx: 3, fill: col, transform: "rotate(" + (i * 360 / teeth) + ")" })),
          R("circle", { r, fill: "none", stroke: col, strokeWidth: 9 }),
          R("circle", { r: r * 0.3, fill: "none", stroke: col, strokeWidth: 6 }),
          Array.from({ length: 5 }).map((_, i) => R("line", { key: "s" + i, x1: 0, y1: 0, x2: Math.cos(i * 1.256) * r * 0.9, y2: Math.sin(i * 1.256) * r * 0.9, stroke: col, strokeWidth: 4 })));
        return R("g", null,
          gear(u.W - 190, u.H - 430, 96, 18, 26, rgba(theme.brass, 0.85), "g1"),
          gear(u.W - 330, u.H - 300, 58, 12, -44, rgba(theme.brass, 0.55), "g2"),
          gear(u.W - 100, u.H - 250, 44, 10, -58, rgba(theme.silverw, 0.4), "g3"));
      })(),
      (function () {
        const osc = Math.sin(t * 5) * 155;
        return R("g", { transform: "translate(220," + (u.H - 480) + ") rotate(" + osc + ")" },
          R("circle", { r: 84, fill: "none", stroke: theme.silverw, strokeWidth: 10 }),
          R("line", { x1: -84, y1: 0, x2: 84, y2: 0, stroke: theme.silverw, strokeWidth: 7 }),
          R("line", { x1: 0, y1: -84, x2: 0, y2: 84, stroke: theme.silverw, strokeWidth: 7 }),
          [0, 90, 180, 270].map((a) => R("circle", { key: a, cx: Math.cos(a * Math.PI / 180) * 84, cy: Math.sin(a * Math.PI / 180) * 84, r: 9, fill: theme.ruby })),
          R("circle", { r: 12, fill: theme.brass }));
      })(),
      (function () {
        const coils = [];
        for (let i = 0; i < 46; i++) {
          const a = i * 0.42, r = 6 + i * 2.1 + Math.sin(t * 2) * 1.4;
          coils.push((i ? "L" : "M") + (Math.cos(a) * r) + " " + (Math.sin(a) * r));
        }
        return R("path", { d: coils.join(" "), fill: "none", stroke: rgba(theme.silverw, 0.35), strokeWidth: 3, transform: "translate(200,270)" });
      })(),
      R("g", { transform: "translate(" + (u.W - 150) + ",230)" },
        R("circle", { r: 56, fill: "none", stroke: rgba(theme.brass, 0.6), strokeWidth: 8 }),
        R("circle", { r: 56, fill: rgba(theme.silverw, 0.06) }),
        R("rect", { x: -18, y: 52, width: 36, height: 54, rx: 10, fill: rgba(theme.brass, 0.5) })),
      Array.from({ length: 3 }).map((_, i) => R("circle", { key: "j" + i, cx: 150 + i * 90, cy: u.H - 220, r: 8, fill: theme.ruby, opacity: 0.5 + 0.4 * Math.abs(Math.sin(t * 2 + i)) }))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
