// FESTIVAL — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/world-pack-2.js, template "FestivalStage").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Bungee / body Rubik. Camera set ["hopU","spin","pushL","zoomIn","pushR","drop"].
// Entrances: title "bounce", items "pop".
// Owns the Notify:pop, Swipe:swipe, Cursor:slider, Toggle:dial mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "festival-stage",
  label: "Festival",

  // ---- type ----
  display: "Bungee", displayFallback: "sans-serif",
  body: "Rubik", bodyFallback: "sans-serif",
  mono: null,
  em: 0.8,
  titleLine: 1.12, titleSpace: "0",
  titlePreset: "bounce", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ night: t.night || "#191227", violet: t.violet || "#8f5cff", hot: "#ff4f9a", lime: "#c8f04f", paper: "#f6f2ff", ink: "#120d1e" }),
  accents: ["lime","hot","violet"],
  groundKey: "night", inkKey: "ink", paperKey: "paper",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "night",
      "fg": "paper",
      "hi": "lime",
      "world": true,
      "top": 340,
      "size": 112,
      "upper": true,
      "kicker": {
        "v": "pill",
        "bg": "hot",
        "c": "paper"
      }
    },
    "statement": {
      "bg": "ink",
      "fg": "paper",
      "hi": "hot",
      "world": false,
      "top": 620,
      "size": 132,
      "upper": true
    },
    "feature": {
      "bg": "night",
      "fg": "paper",
      "hi": "violet",
      "world": true,
      "top": 246,
      "size": 86,
      "upper": true,
      "card": {
        "v": "glow",
        "bg": "#120d1e",
        "glow": "hot",
        "r": 20,
        "line": "paper"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "hot",
          "lime",
          "violet"
        ],
        "text": "ink"
      }
    },
    "montage": {
      "bg": "ink",
      "fg": "paper",
      "hi": "lime",
      "world": false,
      "top": 256,
      "size": 86,
      "upper": true,
      "tile": {
        "bg": "#191227",
        "line": "paper",
        "label": "paper",
        "r": 16,
        "glow": "violet"
      },
      "tilts": [
        -2.5,
        2,
        2.5,
        -2
      ]
    },
    "stats": {
      "bg": "night",
      "fg": "paper",
      "hi": "hot",
      "world": true,
      "cols": [
        "lime",
        "hot",
        "violet"
      ],
      "num": 150,
      "upper": true,
      "glowNums": true
    },
    "cta": {
      "bg": "ink",
      "fg": "paper",
      "hi": "lime",
      "world": false,
      "top": 500,
      "size": 110,
      "upper": true,
      "btn": {
        "v": "glow",
        "bg": "lime",
        "c": "ink"
      },
      "logoShape": "circle"
    }
  },

  // ---- camera + motion ----
  cams: ["hopU","spin","pushL","zoomIn","pushR","drop"], camMul: 5, camOff: 3,
  mag: {"rot":1.5,"driftX":11,"driftZ":0.075},
  ambient: 2,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Notify":"pop","Swipe":"swipe","Cursor":"slider","Toggle":"dial"},

  strings: {
    brandName: "Festival",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round", strokeLinejoin: "round" }, R2("path", { d: "M9 18V6l10-2v12" }), R2("circle", { cx: 6.5, cy: 18, r: 2.5 }), R2("circle", { cx: 16.5, cy: 16, r: 2.5 })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      [0, 1].map((i) => {
        const a = Math.sin(t * (0.7 + i * 0.23) + i * 2) * 34 + (i ? -18 : 18);
        const c = i ? theme.hot : theme.violet;
        return R("polygon", { key: i, points: `${240 + i * 600},-40 ${240 + i * 600 + 60},-40 ${240 + i * 600 + 60 + a * 8},${u.H - 420} ${240 + i * 600 + a * 8 - 220},${u.H - 420}`, fill: rgba(c, 0.22) });
      }),
      Array.from({ length: 14 }).map((_, i) => {
        const cx = (i * 83 + Math.sin(t + i) * 30 + u.W) % u.W;
        const cy = ((t * (90 + (i % 4) * 34) + i * 230) % (u.H + 140)) - 70;
        const c = [theme.hot, theme.lime, theme.violet, theme.paper][i % 4];
        return R("rect", { key: "c" + i, x: cx, y: cy, width: 12, height: 18, rx: 2, fill: c, opacity: 0.8, transform: `rotate(${t * 120 + i * 40} ${cx + 6} ${cy + 9})` });
      }),
      R("path", { d: `M -20 ${u.H - 240} Q 140 ${u.H - 330} 300 ${u.H - 250} T 620 ${u.H - 260} T 940 ${u.H - 245} L ${u.W + 20} ${u.H - 250} L ${u.W + 20} ${u.H + 20} L -20 ${u.H + 20} Z`, fill: theme.ink }),
      [0, 1, 2, 3, 4, 5, 6].map((i) => R("line", { key: "a" + i, x1: 90 + i * 150, y1: u.H - 260 - (i % 2) * 24, x2: 90 + i * 150 + Math.sin(t * 2.2 + i) * 16, y2: u.H - 350 - (i % 3) * 26, stroke: theme.ink, strokeWidth: 12, strokeLinecap: "round" }))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
