// FIELD NOTE — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-04.js, template "FieldNote").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Bree Serif / body Karla. Camera set ["hopU","pushR","drop","pushL","zoomIn","zoomOut"].
// Entrances: title "bounce", items "pop".
// Owns the Scroll:feed, Typing:hand, Ring:gauge mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "field-note",
  label: "Field Note",

  // ---- type ----
  display: "Bree Serif", displayFallback: "Georgia, serif",
  body: "Karla", bodyFallback: "system-ui, sans-serif",
  mono: "IBM Plex Mono",
  chrome: false,
  devanagari: "Noto Serif Devanagari",
  maxScenes: 18,
  em: 0.54,
  titleLine: 1.06, titleSpace: "-0.01em",
  titlePreset: "bounce", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({
      bg: t.bg || "#e7edec", surface: "#f8fbfa", rule: "#c2ceca", inkMuted: "#68746f",
      ink: "#131816", accent: t.accent || "#2f7a72", accent2: t.accent2 || "#c9903a", accentInk: "#f8fbfa",
    }),
  accents: ["accent","accent2","surface"],
  groundKey: "bg", inkKey: "ink", paperKey: "accentInk",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 106,
      "kicker": {
        "v": "pill",
        "bg": "accent",
        "c": "accentInk"
      }
    },
    "statement": {
      "bg": "ink",
      "fg": "surface",
      "hi": "accent2",
      "world": true,
      "top": 610,
      "size": 118
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 540,
      "size": 76,
      "bodySize": 38,
      "ch": 54,
      "lh": 1.54,
      "weight": 400,
      "dim": 0.9,
      "kicker": {
        "v": "bare",
        "c": "accent"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 360,
      "size": 86,
      "ch": 25,
      "lh": 1.16,
      "markSize": 210
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 255,
      "size": 90,
      "swap": "quote",
      "card": {
        "v": "tilt",
        "bg": "surface",
        "r": 14,
        "line": "inkMuted"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "accent",
          "accent2",
          "inkMuted"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 330,
      "size": 84,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 14,
        "h": 640,
        "labelSize": 42
      },
      "tilts": [
        -1,
        1,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 390,
      "size": 86,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 146
    },
    "cta": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "surface",
      "world": true,
      "top": 470,
      "size": 102,
      "align": "left",
      "btn": {
        "v": "pill",
        "bg": "accentInk",
        "c": "surface"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["hopU","pushR","drop","pushL","zoomIn","zoomOut"], camMul: 3, camOff: 5,
  mag: {"rot":0.6,"driftX":8,"driftY":8,"driftZ":0.04,"slide":0.24,"inn":0.2,"zin":0.34,"zout":0.3},
  ambient: 1.65,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"feed","Typing":"hand","Ring":"gauge"},

  strings: {
    brandName: "Field Note",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.2, strokeLinecap: "round" },
      R2("path", { d: "M12 4v16" }), R2("path", { d: "M12 8c4-4 8-3 8-3s-1 5-5 6M12 14c-4-4-8-3-8-3s1 5 5 6" })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "linear-gradient(178deg, " + rgba(theme.surface, 0.92) + " 0%, " + bg + " 48%, " + rgba(theme.accent, 0.2) + " 100%)"),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, E = u.ease, inv = theme.currentBg !== theme.bg;
      const tint = inv ? theme.surface : theme.inkMuted;
      const bank = H - 430, water = H - 300;
      const cyc = (t % 6) / 6;
      const leg = Math.floor(cyc * 3), lt = E.inOut(Math.min(1, (cyc * 3 - leg) / 0.55));
      const pts = [[240, bank - 120], [760, bank - 220], [520, bank - 60], [240, bank - 120]];
      const a0 = pts[leg], a1 = pts[leg + 1];
      const dx = a0[0] + (a1[0] - a0[0]) * lt, dy = a0[1] + (a1[1] - a0[1]) * lt;
      const wing = (t * 40) % 24;
      const hedge = (t * 9) % 300;
      return R("g", null,
        R("defs", null,
          R("pattern", { id: "fn-ripple", width: 180, height: 60, patternUnits: "userSpaceOnUse", patternTransform: "translate(" + ((t * 22) % 180).toFixed(1) + ",0)" },
            R("path", { d: "M0 30 q 45 -14 90 0 q 45 14 90 0", fill: "none", stroke: rgba(theme.accent, inv ? 0.2 : 0.28), strokeWidth: 3 }))),
        /* a canopy of branches hanging into the top band */
        R("g", { transform: "translate(0," + (Math.sin(t * 0.5) * 4).toFixed(2) + ")" },
          R("path", { d: "M -40 30 q 210 66 380 -12 q 160 -74 320 6 q 150 74 300 -10", fill: "none", stroke: rgba(theme.accent, 0.5), strokeWidth: 11, strokeLinecap: "round" }),
          [0, 1, 2, 3, 4, 5, 6].map((i) => {
            const lx = 50 + i * 150, ly = 54 + Math.sin(i * 1.2) * 30 + Math.sin(t * 1.1 + i) * 5;
            return R("path", { key: "cl" + i, d: "M 0 0 q 30 -24 52 6 q -26 28 -52 -6 z", fill: rgba(theme.accent, 0.3 + (i % 3) * 0.09), transform: "translate(" + lx + "," + ly.toFixed(1) + ") rotate(" + (36 + i * 26 + Math.sin(t + i) * 6).toFixed(1) + ")" });
          })),
        /* far bank, hedges and a gate */
        R("g", { opacity: 0.5, transform: "translate(" + (-hedge).toFixed(1) + ",0)" },
          R("path", { d: "M 0 " + (bank - 40) + " q 130 -80 270 -20 q 140 66 280 -14 q 140 -70 280 -6 L " + (W + 400) + " " + bank + " L 0 " + bank + " Z", fill: rgba(theme.accent, 0.3) }),
          R("g", { transform: "translate(" + (W * 0.75) + "," + (bank - 30) + ")" },
            R("line", { x1: -70, y1: 0, x2: -70, y2: -90, stroke: rgba(tint, 0.6), strokeWidth: 7 }),
            R("line", { x1: 70, y1: 0, x2: 70, y2: -90, stroke: rgba(tint, 0.6), strokeWidth: 7 }),
            R("path", { d: "M -70 -70 h 140 M -70 -34 h 140 M -70 -70 L 70 -34", stroke: rgba(tint, 0.5), strokeWidth: 5 }))),
        /* the water */
        R("rect", { x: 0, y: water, width: W, height: H - water, fill: rgba(theme.accent, 0.16) }),
        R("rect", { x: 0, y: water, width: W, height: H - water, fill: "url(#fn-ripple)" }),
        R("line", { x1: 0, y1: water, x2: W, y2: water, stroke: rgba(tint, 0.4), strokeWidth: 4 }),
        [0, 1, 2].map((i) => R("ellipse", { key: "st" + i, cx: 150 + i * 330, cy: water + 60 + (i % 2) * 40, rx: 70 - i * 8, ry: 22, fill: rgba(tint, 0.4) })),
        /* lily pads drifting, and a fish rising every few seconds */
        [0, 1, 2, 3].map((i) => {
          const lx = 120 + i * 260 + Math.sin(t * 0.4 + i) * 30;
          const ly = water + 90 + (i % 2) * 70;
          return R("g", { key: "lp" + i },
            R("ellipse", { cx: lx, cy: ly, rx: 54 - i * 4, ry: 20, fill: rgba(theme.accent, 0.4) }),
            R("path", { d: "M " + lx + " " + ly + " l " + (26 - i * 3) + " -12", stroke: rgba(theme.accent, 0.55), strokeWidth: 4 }),
            i % 2 === 0 ? R("circle", { cx: lx + 20, cy: ly - 22, r: 9, fill: rgba(theme.accent2, 0.75) }) : null);
        }),
        (function () {
          const cyc2 = (t % 7) / 7;
          const up = cyc2 < 0.16 ? Math.sin((cyc2 / 0.16) * Math.PI) : 0;
          const fx = 700;
          return R("g", null,
            R("path", { d: "M " + (fx - 26) + " " + (water + 40 - up * 60) + " q 26 -18 52 0 q -26 20 -52 0 z", fill: rgba(theme.accent2, 0.85 * up) }),
            [0, 1, 2].map((i) => R("ellipse", { key: "rp" + i, cx: fx, cy: water + 44, rx: (30 + i * 44) * (up > 0 ? 1 : cyc2 < 0.5 ? (cyc2 - 0.16) * 4 : 0), ry: (9 + i * 12) * 0.34, fill: "none", stroke: rgba(theme.surface, 0.5 * (1 - i * 0.3) * (cyc2 < 0.6 ? 1 : 0)), strokeWidth: 3 })));
        })(),
        /* a punt moored at the near bank */
        R("g", { transform: "translate(" + (W - 260) + "," + (water + 150) + ") rotate(" + (Math.sin(t * 0.8) * 1.4).toFixed(2) + ")" },
          R("path", { d: "M -190 0 q 26 44 190 44 q 164 0 190 -44 z", fill: rgba(theme.accent2, 0.5), stroke: rgba(tint, 0.45), strokeWidth: 4 }),
          R("path", { d: "M -160 6 h 320", stroke: rgba(tint, 0.35), strokeWidth: 4 }),
          R("path", { d: "M -40 0 v -20 h 80 v 20", fill: "none", stroke: rgba(tint, 0.45), strokeWidth: 5 }),
          R("path", { d: "M 120 -6 l 150 -150", stroke: rgba(tint, 0.55), strokeWidth: 7, strokeLinecap: "round" })),
        /* a heron working the shallows */
        (function () {
          const step = (t % 9) / 9;
          const hx = 200 + step * 240;
          const neck = Math.sin(t * 0.9) * 0.5 + 0.5;
          const leg = Math.sin(t * 1.6) * 10;
          return R("g", { transform: "translate(" + hx.toFixed(1) + "," + (water + 40) + ")" },
            R("path", { d: "M 0 0 v -90 M 24 0 v -84", stroke: rgba(tint, 0.6), strokeWidth: 5, strokeLinecap: "round" }),
            R("path", { d: "M " + leg.toFixed(1) + " 0 h 22", stroke: rgba(tint, 0.5), strokeWidth: 5, strokeLinecap: "round" }),
            R("ellipse", { cx: 12, cy: -116, rx: 46, ry: 28, fill: rgba(theme.surface, inv ? 0.5 : 0.9), stroke: rgba(tint, 0.45), strokeWidth: 3 }),
            R("path", { d: "M 44 -132 q 40 " + (-30 + neck * 44).toFixed(1) + " 34 " + (-70 + neck * 60).toFixed(1) + "", fill: "none", stroke: rgba(theme.surface, inv ? 0.6 : 0.95), strokeWidth: 9, strokeLinecap: "round" }),
            R("circle", { cx: 78, cy: (-202 + neck * 60), r: 12, fill: rgba(theme.surface, inv ? 0.6 : 0.95) }),
            R("path", { d: "M 88 " + (-204 + neck * 60) + " l 40 8 l -40 8 z", fill: rgba(theme.accent2, 0.9) }),
            R("path", { d: "M -34 -120 q 46 -26 84 -6", fill: "none", stroke: rgba(tint, 0.4), strokeWidth: 4 }));
        })(),
        /* reeds along the bank */
        R("g", null,
          Array.from({ length: 22 }).map((_, i) => {
            const rx2 = 20 + i * 50 + (i % 3) * 10;
            const hgt = 120 + ((i * 31) % 7) * 34;
            const lean = Math.sin(t * 1.3 + i * 0.6) * (14 + (i % 4) * 5);
            return R("g", { key: "rd" + i },
              R("path", { d: "M " + rx2 + " " + (water + 20) + " q " + (lean * 0.5).toFixed(1) + " " + (-hgt * 0.55).toFixed(1) + " " + lean.toFixed(1) + " " + (-hgt).toFixed(1), fill: "none", stroke: rgba(theme.accent, 0.4 + (i % 3) * 0.12), strokeWidth: 5, strokeLinecap: "round" }),
              i % 4 === 0 ? R("ellipse", { cx: rx2 + lean, cy: water + 20 - hgt, rx: 7, ry: 20, fill: rgba(theme.accent2, 0.7), transform: "rotate(" + (lean * 0.6).toFixed(1) + " " + (rx2 + lean).toFixed(1) + " " + (water + 20 - hgt).toFixed(1) + ")" }) : null);
          })),
        /* specimen jars and a marker post */
        R("g", { transform: "translate(" + (W - 160) + ",1120)" },
          R("rect", { x: -110, y: 60, width: 220, height: 18, rx: 4, fill: rgba(tint, 0.55) }),
          [0, 1, 2].map((i) => R("g", { key: "jr" + i },
            R("rect", { x: -92 + i * 66, y: -30, width: 50, height: 90, rx: 8, fill: rgba(theme.accent, 0.2), stroke: rgba(tint, 0.5), strokeWidth: 3 }),
            R("rect", { x: -96 + i * 66, y: -40, width: 58, height: 14, rx: 4, fill: rgba(theme.accent2, 0.75) }),
            R("path", { d: "M " + (-84 + i * 66) + " " + (30 + Math.sin(t * 1.2 + i) * 3) + " h 34", stroke: rgba(theme.accent, 0.7), strokeWidth: 5 }))),
          R("g", { transform: "translate(30,-90) rotate(" + (Math.sin(t * 0.7) * 1.6).toFixed(2) + ")" },
            R("line", { x1: 0, y1: 0, x2: 0, y2: 150, stroke: rgba(tint, 0.6), strokeWidth: 7 }),
            R("rect", { x: -54, y: -54, width: 108, height: 54, rx: 5, fill: rgba(theme.accent2, 0.7) }),
            R("rect", { x: -38, y: -36, width: 68, height: 10, rx: 5, fill: rgba(theme.ink, 0.35) }))),
        /* the dragonfly */
        R("g", { transform: "translate(" + dx.toFixed(1) + "," + dy.toFixed(1) + ") rotate(" + ((a1[0] - a0[0]) > 0 ? 8 : -8) + ")" },
          R("ellipse", { cx: 0, cy: 0, rx: 8, ry: 34, fill: rgba(theme.accent, 0.9) }),
          R("circle", { cx: 0, cy: -38, r: 12, fill: rgba(theme.accent2, 0.95) }),
          [-1, 1].map((sx) => R("g", { key: "wg" + sx },
            R("ellipse", { cx: sx * 44, cy: -16, rx: 44, ry: 9, fill: rgba(theme.surface, 0.5), stroke: rgba(tint, 0.35), strokeWidth: 2, strokeDasharray: "10 6", strokeDashoffset: wing }),
            R("ellipse", { cx: sx * 40, cy: 6, rx: 40, ry: 8, fill: rgba(theme.surface, 0.42), stroke: rgba(tint, 0.3), strokeWidth: 2, strokeDasharray: "10 6", strokeDashoffset: -wing }))),
          R("path", { d: "M 0 34 v 26", stroke: rgba(theme.accent, 0.7), strokeWidth: 4, strokeLinecap: "round" })),
        /* midges */
        [0, 1, 2, 3, 4, 5, 6].map((i) => {
          const ph = (t * (0.5 + i * 0.08) + i * 0.14) % 1;
          const mx = 120 + i * 140 + Math.sin(t * 3 + i * 2) * 40;
          return R("circle", { key: "mg" + i, cx: mx, cy: bank - 200 + Math.cos(t * 2.4 + i) * 90, r: 3, fill: rgba(tint, 0.35 + 0.25 * Math.sin(ph * 6.28)) });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
