// FRONT COLUMN — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-03.js, template "FrontColumn").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Bitter / body Asap. Camera set ["pushR","zoomIn","pushL","hopU","zoomOut","drop"].
// Entrances: title "rise", items "pop".
// Owns the Scroll:feed, Typing:caret, Ring:gauge mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "front-column",
  label: "Front Column",

  // ---- type ----
  display: "Bitter", displayFallback: "Georgia, serif",
  body: "Asap", bodyFallback: "system-ui, sans-serif",
  mono: "IBM Plex Mono",
  chrome: false,
  devanagari: "Noto Serif Devanagari",
  maxScenes: 18,
  em: 0.54,
  titleLine: 1.06, titleSpace: "-0.01em",
  titlePreset: "rise", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({
      bg: t.bg || "#e9edf0", surface: "#f9fbfc", rule: "#c4ccd2", inkMuted: "#69727a",
      ink: "#141719", accent: t.accent || "#26456e", accent2: t.accent2 || "#e0a13c", accentInk: "#f9fbfc",
    }),
  accents: ["accent","accent2","bg"],
  groundKey: "bg", inkKey: "ink", paperKey: "accentInk",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 112,
      "kicker": {
        "v": "outline",
        "c": "accent"
      }
    },
    "statement": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "accent2",
      "world": true,
      "top": 610,
      "size": 124
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 540,
      "size": 78,
      "bodySize": 38,
      "ch": 54,
      "lh": 1.52,
      "weight": 400,
      "dim": 0.9,
      "kicker": {
        "v": "bare",
        "c": "accent"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 360,
      "size": 88,
      "ch": 25,
      "lh": 1.16,
      "markSize": 220
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 255,
      "size": 92,
      "swap": "quote",
      "card": {
        "v": "frame",
        "bg": "surface",
        "r": 10,
        "line": "inkMuted"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "accent",
          "accent2",
          "inkMuted"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 330,
      "size": 86,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 10,
        "h": 640,
        "labelSize": 42
      },
      "tilts": [
        0,
        0,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 390,
      "size": 88,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 148,
      "rule": true
    },
    "cta": {
      "bg": "ink",
      "fg": "surface",
      "hi": "accent2",
      "world": true,
      "top": 470,
      "size": 104,
      "align": "left",
      "btn": {
        "v": "pill",
        "bg": "accent2",
        "c": "ink"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["pushR","zoomIn","pushL","hopU","zoomOut","drop"], camMul: 3, camOff: 1,
  mag: {"rot":0.4,"driftX":9,"driftY":6,"driftZ":0.04,"slide":0.26,"inn":0.2,"zin":0.34,"zout":0.3},
  ambient: 1.6,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"feed","Typing":"caret","Ring":"gauge"},

  strings: {
    brandName: "Front Column",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.4, strokeLinecap: "round", strokeLinejoin: "round" },
      R2("circle", { cx: 6, cy: 17, r: 3.5 }), R2("circle", { cx: 18, cy: 17, r: 3.5 }), R2("path", { d: "M6 17l5-9h5l2 9M9 8h5" })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "linear-gradient(180deg, " + rgba(theme.accent2, 0.18) + " 0%, " + rgba(theme.surface, 0.9) + " 26%, " + bg + " 60%, " + rgba(theme.rule, 0.5) + " 100%)"),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, inv = theme.currentBg !== theme.bg;
      const tint = inv ? theme.surface : theme.inkMuted;
      const kerb = H - 280;
      const cyc = (t % 13) / 13, bx = -260 + cyc * (W + 520);
      const wheel = (bx / 44) * 57.3;
      const bounce = Math.sin(t * 7) * 4;
      const rail = (t * 40) % 120, lamp = (t * 22) % 460;
      return R("g", null,
        R("defs", null,
          R("linearGradient", { id: "fc-haze", x1: "0%", y1: "0%", x2: "0%", y2: "100%" },
            R("stop", { offset: "0%", stopColor: rgba(theme.accent2, 0.22) }),
            R("stop", { offset: "100%", stopColor: rgba(theme.accent2, 0) }))),
        R("rect", { x: 0, y: kerb - 720, width: W, height: 420, fill: "url(#fc-haze)" }),
        /* dawn sky: three clouds on their own drifts, two fading stars */
        R("g", { opacity: 0.7 },
          [0, 1, 2].map((i) => {
            const cxp = ((i * 460 - (t * (7 + i * 4)) % 460) % (W + 500)) - 250;
            const cyp = 90 + i * 62;
            return R("g", { key: "cd" + i, transform: "translate(" + cxp.toFixed(1) + "," + cyp + ")" },
              R("path", { d: "M -120 0 q 10 -46 62 -38 q 20 -44 78 -26 q 54 -12 62 34 q 34 4 30 30 z", fill: rgba(theme.surface, 0.75 - i * 0.14) }),
              R("path", { d: "M -120 0 h 232", stroke: rgba(theme.accent2, 0.24), strokeWidth: 3 }));
          }),
          [0, 1].map((i) => R("circle", { key: "st" + i, cx: 700 + i * 190, cy: 70 + i * 54, r: 4, fill: rgba(theme.accent, 0.3 + 0.4 * Math.abs(Math.sin(t * 0.8 + i * 2))) }))),
        /* terrace roofline */
        R("g", { opacity: 0.34 },
          [0, 1, 2, 3, 4, 5].map((i) => {
            const rx2 = ((i * 230 - (t * 9) % 230) % (W + 230)) - 115;
            const hgt = 250 + (i % 3) * 90;
            return R("g", { key: "hs" + i },
              R("rect", { x: rx2, y: kerb - hgt, width: 190, height: hgt, fill: rgba(theme.accent, 0.3) }),
              R("rect", { x: rx2 + 40, y: kerb - hgt + 60, width: 44, height: 60, fill: rgba(theme.accent2, 0.5) }),
              R("rect", { x: rx2 + 110, y: kerb - hgt + 60, width: 44, height: 60, fill: rgba(theme.accent, 0.4) }));
          })),
        /* a shuttered shop with an awning and a paper stand */
        R("g", { transform: "translate(" + (W - 220) + "," + (kerb - 40) + ")" },
          R("rect", { x: -180, y: -420, width: 360, height: 420, rx: 6, fill: rgba(theme.accent, 0.14), stroke: rgba(tint, 0.4), strokeWidth: 4 }),
          R("path", { d: "M -200 -420 h 400 l -30 90 h -340 z", fill: rgba(theme.accent2, 0.55) }),
          [0, 1, 2, 3, 4].map((i) => R("rect", { key: "aw" + i, x: -200 + i * 80, y: -420, width: 40, height: 90, fill: rgba(theme.surface, 0.35) })),
          R("g", { transform: "translate(150,-300) rotate(" + (Math.sin(t * 1.2) * 5).toFixed(2) + ")" },
            R("line", { x1: 0, y1: -30, x2: 0, y2: 0, stroke: rgba(tint, 0.5), strokeWidth: 4 }),
            R("rect", { x: -54, y: 0, width: 108, height: 54, rx: 5, fill: rgba(theme.accent, 0.8) }),
            R("rect", { x: -36, y: 20, width: 72, height: 10, rx: 5, fill: rgba(theme.accent2, 0.9) })),
          R("g", { transform: "translate(-60,-10)" },
            R("path", { d: "M -80 0 h 160 l -14 -120 h -132 z", fill: rgba(tint, 0.45) }),
            [0, 1, 2].map((i) => R("rect", { key: "pp" + i, x: -60 + i * 44, y: -170 + (i % 2) * 12, width: 38, height: 56, rx: 3, fill: rgba(theme.surface, inv ? 0.5 : 0.94), stroke: rgba(tint, 0.35), strokeWidth: 2, transform: "rotate(" + (-6 + i * 6) + ")" })))),
        /* lamp posts, closer */
        [0, 1, 2].map((i) => {
          const lx = ((i * 460 - lamp) % (W + 460)) - 230;
          return R("g", { key: "lp" + i, opacity: 0.7 },
            R("line", { x1: lx, y1: kerb, x2: lx, y2: kerb - 430, stroke: rgba(tint, 0.65), strokeWidth: 8 }),
            R("path", { d: "M " + lx + " " + (kerb - 430) + " q 0 -40 46 -40", fill: "none", stroke: rgba(tint, 0.6), strokeWidth: 7 }),
            R("circle", { cx: lx + 52, cy: kerb - 462, r: 20, fill: rgba(theme.accent2, 0.9) }),
            R("circle", { cx: lx + 52, cy: kerb - 462, r: 58, fill: rgba(theme.accent2, 0.16) }));
        }),
        /* a car parked across the road, in the far plane */
        R("g", { opacity: 0.42 },
          (function () {
            const px = ((-(t * 5) % 1400) + 1400) % 1400 - 200;
            return R("g", { transform: "translate(" + px.toFixed(1) + "," + (kerb - 140) + ")" },
              R("path", { d: "M -150 0 h 300 v -46 l -60 -44 h -150 l -60 44 z", fill: rgba(theme.accent, 0.6) }),
              R("circle", { cx: -86, cy: 6, r: 26, fill: rgba(theme.ink, 0.6) }),
              R("circle", { cx: 86, cy: 6, r: 26, fill: rgba(theme.ink, 0.6) }));
          })()),
        /* railings */
        R("g", { opacity: 0.5, transform: "translate(" + (-rail).toFixed(1) + ",0)" },
          Array.from({ length: 12 }).map((_, i) => R("line", { key: "rl" + i, x1: i * 120, y1: kerb - 40, x2: i * 120, y2: kerb - 190, stroke: rgba(tint, 0.55), strokeWidth: 6 })),
          R("line", { x1: 0, y1: kerb - 190, x2: W + 240, y2: kerb - 190, stroke: rgba(tint, 0.5), strokeWidth: 6 })),
        /* kerb and bundles */
        R("line", { x1: 0, y1: kerb, x2: W, y2: kerb, stroke: rgba(tint, 0.6), strokeWidth: 7 }),
        R("rect", { x: 0, y: kerb, width: W, height: H - kerb, fill: rgba(theme.rule, 0.28) }),
        [0, 1].map((i) => R("g", { key: "bd" + i, transform: "translate(" + (W - 300 + i * 170) + "," + (kerb - 10) + ")" },
          R("rect", { x: -70, y: -76, width: 140, height: 76, rx: 5, fill: rgba(theme.surface, inv ? 0.45 : 0.92), stroke: rgba(tint, 0.4), strokeWidth: 3 }),
          R("path", { d: "M -70 -40 h 140 M 0 -76 v 76", stroke: rgba(theme.accent, 0.5), strokeWidth: 4 }))),
        /* a pillar box and a bus stop on the pavement */
        R("g", { transform: "translate(300," + (kerb - 6) + ")" },
          R("path", { d: "M -46 0 h 92 v -132 a 46 46 0 0 0 -92 0 z", fill: rgba(theme.accent, 0.85) }),
          R("rect", { x: -30, y: -104, width: 60, height: 14, rx: 4, fill: rgba(theme.accentInk, 0.6) }),
          R("path", { d: "M -46 -34 h 92", stroke: rgba(theme.accentInk, 0.35), strokeWidth: 4 })),
        R("g", { transform: "translate(640," + (kerb - 6) + ")" },
          R("line", { x1: 0, y1: 0, x2: 0, y2: -300, stroke: rgba(tint, 0.6), strokeWidth: 7 }),
          R("rect", { x: -54, y: -374, width: 108, height: 74, rx: 8, fill: rgba(theme.accent, 0.8) }),
          R("rect", { x: -34, y: -352, width: 68, height: 12, rx: 6, fill: rgba(theme.accentInk, 0.5) })),
        /* a vent breathing on the kerb */
        R("g", null,
          R("rect", { x: 830, y: kerb - 8, width: 120, height: 16, rx: 4, fill: rgba(tint, 0.5) }),
          [0, 1, 2].map((i) => {
            const ph = ((t * 0.34 + i * 0.34) % 1);
            const sw = Math.sin(t * 1.1 + i * 2) * 22;
            return R("path", { key: "vs" + i, d: "M " + (860 + i * 30) + " " + (kerb - 20) + " q " + sw.toFixed(1) + " -70 " + (sw * 0.4).toFixed(1) + " -140", fill: "none", stroke: rgba(tint, 0.3 * (1 - ph)), strokeWidth: 15, strokeLinecap: "round", transform: "translate(0," + (-ph * 150).toFixed(1) + ")" });
          })),
        /* puddles holding the lamplight */
        [0, 1].map((i) => R("ellipse", { key: "pd" + i, cx: 200 + i * 520, cy: kerb + 90 + i * 40, rx: 110 - i * 20, ry: 16, fill: rgba(theme.accent2, 0.2 + 0.08 * Math.sin(t * 1.3 + i)) })),
        /* the bicycle */
        R("g", { transform: "translate(" + bx.toFixed(1) + "," + (kerb + bounce).toFixed(1) + ")" },
          R("ellipse", { cx: 0, cy: 8, rx: 120, ry: 12, fill: rgba(theme.ink, 0.18) }),
          [-72, 72].map((wx, i) => R("g", { key: "wl" + i, transform: "translate(" + wx + ",-52) rotate(" + wheel.toFixed(1) + ")" },
            R("circle", { r: 52, fill: "none", stroke: rgba(theme.ink, 0.85), strokeWidth: 7 }),
            R("path", { d: "M -52 0 h 104 M 0 -52 v 104 M -37 -37 l 74 74 M 37 -37 l -74 74", stroke: rgba(theme.ink, 0.35), strokeWidth: 3 }))),
          R("path", { d: "M -72 -52 L -6 -52 L 34 -132 L 72 -52 M -6 -52 L 34 -132 M -6 -52 L 6 -128 L 34 -132", fill: "none", stroke: rgba(theme.accent, 0.9), strokeWidth: 9, strokeLinejoin: "round" }),
          R("path", { d: "M 6 -128 q -34 -6 -44 10", fill: "none", stroke: rgba(theme.ink, 0.8), strokeWidth: 7, strokeLinecap: "round" }),
          R("rect", { x: -116, y: -152 + bounce, width: 96, height: 62, rx: 5, fill: rgba(theme.surface, inv ? 0.5 : 0.95), stroke: rgba(tint, 0.45), strokeWidth: 3 }),
          R("path", { d: "M -116 " + (-124 + bounce) + " h 96", stroke: rgba(theme.accent, 0.6), strokeWidth: 4 }),
          R("path", { d: "M -20 -140 q 44 -10 58 30 q -30 22 -58 -30 z", fill: rgba(theme.accent2, 0.7) })),
        /* near plane */
        [0, 1].map((i) => {
          const bc = ((t / (9 + i * 3)) % 1);
          const bxp = W - 30 - bc * 300, byp = 520 + i * 130 + Math.sin(bc * Math.PI * 4 + i) * 80;
          const flap = Math.sin(t * 8 + i * 2) * 0.7;
          return R("path", { key: "br" + i, d: "M -24 0 q 12 " + (-16 - flap * 14).toFixed(1) + " 24 0 q 12 " + (-16 + flap * 14).toFixed(1) + " 24 0", fill: "none", stroke: rgba(tint, 0.5), strokeWidth: 4, strokeLinecap: "round", transform: "translate(" + bxp.toFixed(1) + "," + byp.toFixed(1) + ")" });
        }),
        [0, 1, 2, 3].map((i) => {
          const ph = (t * (0.2 + i * 0.04) + i * 0.23) % 1;
          return R("circle", { key: "ds" + i, cx: 90 + i * 250 + Math.sin(t * 1.2 + i) * 46, cy: H - ph * (H + 160), r: 4 + (i % 2) * 3, fill: rgba(tint, 0.26 * (1 - ph)) });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
