// GROOVE CRATE — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-1.js, template "GrooveCrate").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Righteous / body Mulish. Camera set ["spin","pushL","zoomIn","pushD","pushR","hopU"].
// Entrances: title "stamp", items "streak".
// Owns the Scroll:stack, Cursor:slider, Morph:flap, Notify:drop mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "groove-crate",
  label: "Groove Crate",

  // ---- type ----
  display: "Righteous", displayFallback: "sans-serif",
  body: "Mulish", bodyFallback: "sans-serif",
  mono: null,
  em: 0.58,
  titleLine: 1.04, titleSpace: "0",
  titlePreset: "stamp", itemPreset: "streak",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ wax: t.wax || "#17141a", tang: t.tang || "#ff8c42", rose: "#ff5d8f", cream: "#f2ead9", teal: "#3fb8af" }),
  accents: ["tang","cream","rose"],
  groundKey: "wax", inkKey: "wax", paperKey: "cream",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "wax",
      "fg": "cream",
      "hi": "tang",
      "world": true,
      "top": 320,
      "size": 122,
      "upper": true,
      "kicker": {
        "v": "outline",
        "c": "rose"
      }
    },
    "statement": {
      "bg": "rose",
      "fg": "wax",
      "hi": "cream",
      "world": false,
      "top": 630,
      "size": 150,
      "upper": true
    },
    "feature": {
      "bg": "wax",
      "fg": "cream",
      "hi": "tang",
      "world": true,
      "top": 250,
      "size": 98,
      "upper": true,
      "card": {
        "v": "tilt",
        "bg": "#0f0d11",
        "r": 18,
        "line": "cream"
      },
      "chips": {
        "v": "square",
        "colors": [
          "tang",
          "rose",
          "teal"
        ],
        "text": "wax"
      }
    },
    "montage": {
      "bg": "#0f0d11",
      "fg": "cream",
      "hi": "rose",
      "world": false,
      "top": 258,
      "size": 94,
      "upper": true,
      "tile": {
        "bg": "wax",
        "line": "cream",
        "label": "tang",
        "r": 14
      },
      "tilts": [
        -3,
        2.5,
        2,
        -2.5
      ]
    },
    "stats": {
      "bg": "wax",
      "fg": "cream",
      "hi": "tang",
      "world": true,
      "cols": [
        "tang",
        "rose",
        "teal"
      ],
      "num": 152,
      "upper": true
    },
    "cta": {
      "bg": "teal",
      "fg": "wax",
      "hi": "cream",
      "world": false,
      "top": 500,
      "size": 120,
      "upper": true,
      "btn": {
        "v": "block",
        "bg": "wax",
        "c": "cream"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "wax",
      "fg": "cream",
      "hi": "tang",
      "cardBg": "#1e1a22",
      "line": "cream",
      "world": true,
      "upper": true
    }
  },

  // ---- camera + motion ----
  cams: ["spin","pushL","zoomIn","pushD","pushR","hopU"], camMul: 7, camOff: 1,
  mag: {"rot":1.4,"skew":2,"driftX":8},
  ambient: 1.9,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"stack","Cursor":"slider","Morph":"flap","Notify":"drop"},

  strings: {
    brandName: "Groove Crate",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5 }, R2("circle", { cx: 12, cy: 12, r: 9 }), R2("circle", { cx: 12, cy: 12, r: 1.5, fill: theme.currentBg })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      R("g", { transform: "translate(220," + (u.H - 430) + ")" },
        [92, 72, 52].map((r, i) => R("circle", { key: i, r, fill: "none", stroke: rgba(theme.cream, 0.22), strokeWidth: 3 })),
        R("circle", { r: 110, fill: "none", stroke: rgba(theme.cream, 0.35), strokeWidth: 5 }),
        R("circle", { r: 34, fill: theme.tang }),
        R("line", { x1: 0, y1: 0, x2: Math.cos(t * 2.4) * 100, y2: Math.sin(t * 2.4) * 100, stroke: rgba(theme.cream, 0.5), strokeWidth: 4, strokeLinecap: "round" })),
      R("g", { transform: "translate(430," + (u.H - 560) + ") rotate(" + (24 + Math.sin(t * 0.8) * 6) + ")" },
        R("line", { x1: 0, y1: 0, x2: 0, y2: 200, stroke: theme.teal, strokeWidth: 9, strokeLinecap: "round" }),
        R("circle", { r: 16, fill: theme.teal }),
        R("rect", { x: -9, y: 196, width: 18, height: 34, rx: 6, fill: theme.rose })),
      Array.from({ length: 5 }).map((_, i) => R("rect", { key: i, x: u.W - 320 + i * 26, y: 220 - (i % 2) * 8 + Math.sin(t * 1.3 + i) * 6, width: 20, height: 190, rx: 4, fill: rgba([theme.tang, theme.rose, theme.teal, theme.cream][i % 4], 0.55), transform: "rotate(" + (i - 2) * 3 + " " + (u.W - 320 + i * 26) + " 320)" })),
      [0, 1, 2].map((i) => {
        const eq = Math.abs(Math.sin(t * (2 + i * 0.7) + i));
        return R("rect", { key: "q" + i, x: 90 + i * 40, y: 240 - eq * 100, width: 26, height: eq * 100 + 20, rx: 8, fill: rgba(theme.tang, 0.4 + eq * 0.3) });
      })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
