// HIVE & HONEY — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-1.js, template "HiveHoney").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Fredoka / body Quicksand. Camera set ["hopU","pushR","zoomIn","pushL","drop","zoomOut"].
// Entrances: title "bounce", items "pop".
// Owns the Toggle:check, Ring:gauge, DragDrop:drag, Morph:roll mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "hive-and-honey",
  label: "Hive & Honey",

  // ---- type ----
  display: "Fredoka", displayFallback: "sans-serif",
  body: "Quicksand", bodyFallback: "sans-serif",
  mono: null,
  em: 0.58,
  titleLine: 1.08, titleSpace: "0",
  titlePreset: "bounce", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ honey: t.honey || "#f7c948", comb: "#7a4f16", cream: t.cream || "#fff8e8", ink: "#3a2c14", leaf: "#8aa34f" }),
  accents: ["comb","honey","cream"],
  groundKey: "cream", inkKey: "ink", paperKey: "cream",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "cream",
      "fg": "ink",
      "hi": "comb",
      "world": true,
      "top": 330,
      "size": 124,
      "kicker": {
        "v": "pill",
        "bg": "honey",
        "c": "ink"
      }
    },
    "statement": {
      "bg": "honey",
      "fg": "ink",
      "hi": "cream",
      "world": false,
      "top": 630,
      "size": 150
    },
    "feature": {
      "bg": "cream",
      "fg": "ink",
      "hi": "comb",
      "world": true,
      "top": 250,
      "size": 98,
      "card": {
        "v": "tilt",
        "bg": "comb",
        "r": 24,
        "line": "cream"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "honey",
          "leaf"
        ],
        "text": "ink"
      }
    },
    "montage": {
      "bg": "comb",
      "fg": "cream",
      "hi": "honey",
      "world": false,
      "top": 258,
      "size": 94,
      "tile": {
        "bg": "cream",
        "line": "ink",
        "label": "cream",
        "r": 20
      },
      "tilts": [
        -3,
        2.5,
        2,
        -2.5
      ]
    },
    "stats": {
      "bg": "cream",
      "fg": "ink",
      "hi": "comb",
      "world": true,
      "cols": [
        "comb",
        "leaf",
        "ink"
      ],
      "num": 152
    },
    "cta": {
      "bg": "ink",
      "fg": "cream",
      "hi": "honey",
      "world": false,
      "top": 500,
      "size": 122,
      "btn": {
        "v": "pill",
        "bg": "honey",
        "c": "ink"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "cream",
      "fg": "ink",
      "hi": "comb",
      "cardBg": "#ffffff",
      "line": "ink",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["hopU","pushR","zoomIn","pushL","drop","zoomOut"], camMul: 3, camOff: 1,
  mag: {"rot":1.3,"driftX":9},
  ambient: 1.8,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Toggle":"check","Ring":"gauge","DragDrop":"drag","Morph":"roll"},

  strings: {
    brandName: "Hive & Honey",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinejoin: "round" }, R2("path", { d: "M12 3l6 3.5v7L12 17l-6-3.5v-7zM12 17v4" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      (function () {
        const hex = (cx, cy, r) => { let d = ""; for (let i = 0; i < 6; i++) { const a = Math.PI / 3 * i - Math.PI / 6; d += (i ? "L" : "M") + (cx + Math.cos(a) * r) + " " + (cy + Math.sin(a) * r) + " "; } return d + "Z"; };
        const cells = [[u.W - 160, 220], [u.W - 60, 280], [u.W - 160, 340], [u.W - 260, 280], [u.W - 60, 400], [u.W - 160, 460]];
        return R("g", null, cells.map(([x, y], i) => {
          const e = u.ease.outBack(u.clamp01(u.seg(p, 0.05 + i * 0.06, 0.25 + i * 0.06)));
          return R("path", { key: i, d: hex(x, y, 62), fill: i % 2 ? rgba(theme.honey, 0.55) : "none", stroke: theme.comb, strokeWidth: 5, opacity: e, transform: "scale(" + e + ")", "transform-origin": x + "px " + y + "px" });
        }));
      })(),
      [0, 1].map((i) => {
        const a = t * (1.1 + i * 0.3) + i * 2.4;
        const bx = 260 + Math.sin(a) * 170, by = u.H - 620 + Math.sin(a * 2) * 90;
        return R("g", { key: "bee" + i, transform: "translate(" + bx + "," + by + ") rotate(" + Math.cos(a) * 24 + ")" },
          R("ellipse", { rx: 26, ry: 18, fill: theme.honey, stroke: theme.ink, strokeWidth: 4 }),
          R("path", { d: "M -8 -16 v32 M 6 -17 v34", stroke: theme.ink, strokeWidth: 5 }),
          R("ellipse", { cx: -4, cy: -22, rx: 14, ry: 9, fill: rgba("#ffffff", 0.75) }));
      }),
      (function () {
        const dr = (t * 0.4) % 1;
        return R("g", null,
          R("path", { d: "M 100 " + (u.H - 360) + " h 150", stroke: theme.comb, strokeWidth: 10, strokeLinecap: "round" }),
          R("circle", { cx: 175, cy: u.H - 350 + dr * 220, r: 13 * (1 - dr * 0.4), fill: theme.honey, opacity: 1 - dr * 0.7 }));
      })()),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
