// INK & PANEL — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-5.js, template "InkPanel").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Bangers / body Lexend. Camera set ["pushR","spin","pushL","zoomIn","hopU","drop"].
// Entrances: title "slam", items "pop".
// Owns the Typing:typewriter, Morph:flap, DragDrop:assemble, Scroll:stack mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "ink-and-panel",
  label: "Ink & Panel",

  // ---- type ----
  display: "Bangers", displayFallback: "cursive",
  body: "Lexend", bodyFallback: "sans-serif",
  mono: null,
  em: 0.48,
  titleLine: 1.02, titleSpace: "0.03em",
  titlePreset: "slam", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ bristol: t.bristol || "#f6f4ec", inkk: "#1a1a1e", action: t.action || "#e8402e", cyan: "#3cb8e8", yellow: "#f2c14b" }),
  accents: ["action","yellow","bristol"],
  groundKey: "bristol", inkKey: "inkk", paperKey: "bristol",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bristol",
      "fg": "inkk",
      "hi": "action",
      "world": true,
      "top": 310,
      "size": 132,
      "upper": true,
      "kicker": {
        "v": "tag",
        "bg": "yellow",
        "c": "inkk"
      }
    },
    "statement": {
      "bg": "action",
      "fg": "bristol",
      "hi": "yellow",
      "world": false,
      "top": 620,
      "size": 156,
      "upper": true
    },
    "feature": {
      "bg": "bristol",
      "fg": "inkk",
      "hi": "action",
      "world": true,
      "top": 248,
      "size": 102,
      "upper": true,
      "card": {
        "v": "frame",
        "bg": "inkk",
        "r": 6,
        "line": "bristol"
      },
      "chips": {
        "v": "square",
        "colors": [
          "action",
          "cyan",
          "yellow"
        ],
        "text": "inkk"
      }
    },
    "montage": {
      "bg": "inkk",
      "fg": "bristol",
      "hi": "yellow",
      "world": false,
      "top": 256,
      "size": 98,
      "upper": true,
      "tile": {
        "bg": "bristol",
        "line": "inkk",
        "label": "bristol",
        "r": 4
      },
      "tilts": [
        -3,
        2.5,
        2,
        -2.5
      ]
    },
    "stats": {
      "bg": "bristol",
      "fg": "inkk",
      "hi": "action",
      "world": true,
      "cols": [
        "action",
        "cyan",
        "inkk"
      ],
      "num": 154,
      "upper": true,
      "rule": true
    },
    "cta": {
      "bg": "yellow",
      "fg": "inkk",
      "hi": "action",
      "world": false,
      "top": 490,
      "size": 126,
      "upper": true,
      "btn": {
        "v": "block",
        "bg": "inkk",
        "c": "bristol"
      },
      "logoShape": "rounded"
    },
    "app": {
      "bg": "bristol",
      "fg": "inkk",
      "hi": "action",
      "cardBg": "#ffffff",
      "line": "inkk",
      "world": true,
      "upper": true
    }
  },

  // ---- camera + motion ----
  cams: ["pushR","spin","pushL","zoomIn","hopU","drop"], camMul: 7, camOff: 1,
  mag: {"skew":4,"rot":1.3,"inn":0.17},
  ambient: 1.9,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Typing":"typewriter","Morph":"flap","DragDrop":"assemble","Scroll":"stack"},

  strings: {
    brandName: "Ink & Panel",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinejoin: "round" }, R2("path", { d: "M4 4h16v16H4zM4 12h16M12 4v8" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      (function () {
        const dr = u.seg(p, 0.05, 0.5);
        const L = 2200;
        return R("g", null,
          R("rect", { x: u.W - 420, y: 200, width: 340, height: 460, fill: "none", stroke: theme.inkk, strokeWidth: 5, strokeDasharray: String(L), strokeDashoffset: String(L * (1 - dr)) }),
          R("line", { x1: u.W - 420, y1: 400, x2: u.W - 80, y2: 400, stroke: theme.inkk, strokeWidth: 5, opacity: dr > 0.6 ? 1 : 0 }),
          R("line", { x1: u.W - 250, y1: 400, x2: u.W - 250, y2: 660, stroke: theme.inkk, strokeWidth: 5, opacity: dr > 0.8 ? 1 : 0 }));
      })(),
      Array.from({ length: 30 }).map((_, i) => R("circle", { key: i, cx: u.W - 400 + (i % 6) * 24, cy: 224 + Math.floor(i / 6) * 24, r: 4.5 - (i % 6) * 0.5, fill: rgba(theme.cyan, 0.6) })),
      (function () {
        const burst = u.ease.outBack(u.clamp01(u.seg(p, 0.4, 0.62)));
        const px = 230, py = u.H - 480;
        let pts = "";
        for (let k = 0; k < 20; k++) { const a = k * Math.PI / 10; const r = k % 2 ? 70 : 130; pts += (px + Math.cos(a) * r * burst) + "," + (py + Math.sin(a) * r * burst) + " "; }
        return R("g", null,
          R("polygon", { points: pts, fill: theme.yellow, stroke: theme.inkk, strokeWidth: 5, opacity: burst }),
          R("text", { x: px, y: py + 16, textAnchor: "middle", fontFamily: '"Bangers", cursive', fontSize: 54 * burst, fill: theme.action, stroke: theme.inkk, strokeWidth: 1.5, transform: "rotate(-8 " + px + " " + py + ")" }, "POW!"));
      })(),
      [0, 1, 2, 3, 4].map((i) => R("line", { key: "sl" + i, x1: 80, y1: 240 + i * 30 - 60, x2: 80 + 200 + ((t * 500 + i * 80) % 180), y2: 240 + i * 30 - 60, stroke: rgba(theme.inkk, 0.6 - i * 0.1), strokeWidth: 6 - i, strokeLinecap: "round", transform: "rotate(-16 80 240)" })),
      R("circle", { cx: 160, cy: u.H - 220, r: 30, fill: "none", stroke: theme.action, strokeWidth: 6, strokeDasharray: "8 10", transform: "rotate(" + t * 80 + " 160 " + (u.H - 220) + ")" })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
