// LAB RECORD — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-04.js, template "LabRecord").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Cinzel / body Lato. Camera set ["zoomIn","pushL","drop","pushR","pushU","zoomOut"].
// Entrances: title "rise", items "pop".
// Owns the Scroll:feed, Typing:terminal, Ring:ring mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "lab-record",
  label: "Lab Record",

  // ---- type ----
  display: "Cinzel", displayFallback: "Georgia, serif",
  body: "Lato", bodyFallback: "system-ui, sans-serif",
  mono: "IBM Plex Mono",
  chrome: false,
  devanagari: "Noto Serif Devanagari",
  maxScenes: 18,
  em: 0.58,
  titleLine: 1.16, titleSpace: "0.03em",
  titlePreset: "rise", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({
      bg: t.bg || "#131a18", surface: "#1d2624", rule: "#31403c", inkMuted: "#8fa39d",
      ink: "#eef5f2", accent: t.accent || "#54e0b0", accent2: t.accent2 || "#e0b054", accentInk: "#08110f",
    }),
  accents: ["accent","accent2","surface"],
  groundKey: "bg", inkKey: "accentInk", paperKey: "ink",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 88,
      "upper": true,
      "kicker": {
        "v": "outline",
        "c": "accent"
      }
    },
    "statement": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 610,
      "size": 100,
      "upper": true
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 540,
      "size": 66,
      "bodySize": 38,
      "ch": 54,
      "lh": 1.54,
      "weight": 400,
      "dim": 0.92,
      "kicker": {
        "v": "bare",
        "c": "accent2"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 360,
      "size": 72,
      "ch": 24,
      "lh": 1.22,
      "markSize": 190
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 255,
      "size": 74,
      "upper": true,
      "swap": "body",
      "card": {
        "v": "glow",
        "bg": "surface",
        "glow": "accent",
        "r": 14,
        "line": "inkMuted"
      },
      "chips": {
        "v": "outline",
        "colors": [
          "accent",
          "accent2",
          "ink"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 330,
      "size": 70,
      "upper": true,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 14,
        "h": 640,
        "labelSize": 36
      },
      "tilts": [
        0,
        0,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 390,
      "size": 74,
      "upper": true,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 148,
      "glowNums": true
    },
    "cta": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "surface",
      "world": true,
      "top": 470,
      "size": 86,
      "upper": true,
      "align": "left",
      "btn": {
        "v": "glow",
        "bg": "accentInk",
        "c": "ink"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["zoomIn","pushL","drop","pushR","pushU","zoomOut"], camMul: 7, camOff: 2,
  mag: {"rot":0.25,"driftX":5,"driftY":6,"driftZ":0.05,"slide":0.2,"inn":0.22,"zin":0.36,"zout":0.3},
  ambient: 1.5,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"feed","Typing":"terminal","Ring":"ring"},

  strings: {
    brandName: "Lab Record",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.2, strokeLinecap: "round", strokeLinejoin: "round" },
      R2("path", { d: "M9 3h6v6l4 10H5l4-10z" }), R2("path", { d: "M7 15h10" })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "radial-gradient(100% 55% at 50% 100%, " + rgba(theme.accent, 0.16) + " 0%, transparent 60%), " + bg),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, inv = theme.currentBg !== theme.bg;
      const tint = inv ? theme.surface : theme.inkMuted;
      const bench = H - 290;
      const drum = (t * 90) % 360;
      const styl = (Math.sin(t * 0.55) * 0.5 + 0.5);
      const drip = (t * 0.8) % 1;
      return R("g", null,
        R("defs", null,
          R("pattern", { id: "lr-peg", width: 46, height: 46, patternUnits: "userSpaceOnUse" },
            R("circle", { cx: 23, cy: 23, r: 3.5, fill: rgba(theme.rule, inv ? 0.4 : 0.9) })),
          R("radialGradient", { id: "lr-hood", cx: "50%", cy: "50%" },
            R("stop", { offset: "0%", stopColor: rgba(theme.accent, 0.24) }),
            R("stop", { offset: "100%", stopColor: rgba(theme.accent, 0) }))),
        R("rect", { x: 0, y: 0, width: W, height: bench - 300, fill: "url(#lr-peg)", opacity: 0.5 }),
        /* a reagent shelf across the top band, one flask working */
        R("g", { opacity: 0.72 },
          R("rect", { x: 40, y: 250, width: W - 80, height: 16, rx: 4, fill: rgba(tint, 0.6) }),
          [0, 1, 2, 3, 4, 5, 6].map((i) => {
            const hgt = 92 + ((i * 41) % 4) * 34;
            const wdt = 44 + (i % 3) * 14;
            const x = 90 + i * 132;
            return R("g", { key: "rg" + i },
              R("rect", { x: x, y: 250 - hgt, width: wdt, height: hgt, rx: 7, fill: rgba(i % 3 === 0 ? theme.accent : theme.accent2, 0.24), stroke: rgba(tint, 0.5), strokeWidth: 3 }),
              R("rect", { x: x + wdt * 0.25, y: 250 - hgt - 16, width: wdt * 0.5, height: 18, rx: 4, fill: rgba(tint, 0.6) }),
              R("rect", { x: x + 6, y: 250 - hgt * 0.45, width: wdt - 12, height: 12, rx: 3, fill: rgba(theme.surface, 0.35) }),
              i === 3 ? [0, 1, 2].map((j) => {
                const ph = ((t * 0.7 + j * 0.34) % 1);
                return R("circle", { key: "bb" + j, cx: x + wdt / 2 + Math.sin(t * 2 + j) * 8, cy: 240 - ph * (hgt - 30), r: 4 + ph * 3, fill: rgba(theme.accent, 0.7 * (1 - ph)) });
              }) : null);
          })),
        /* tools hung on the pegboard, above the copy */
        R("g", { opacity: 0.55 },
          [0, 1, 2].map((i) => R("g", { key: "tl" + i, transform: "translate(" + (W - 170 + (i - 1) * 62) + ",300) rotate(" + (Math.sin(t * 0.7 + i) * 1.5).toFixed(2) + ")" },
            R("line", { x1: 0, y1: 0, x2: 0, y2: 86 + (i % 3) * 30, stroke: rgba(tint, 0.6), strokeWidth: 6 }),
            i % 2 === 0
              ? R("path", { d: "M -22 " + (86 + (i % 3) * 30) + " h 44 l -8 44 h -28 z", fill: rgba(theme.accent2, 0.6) })
              : R("circle", { cx: 0, cy: 108 + (i % 3) * 30, r: 20, fill: "none", stroke: rgba(theme.accent, 0.6), strokeWidth: 6 })))),
        /* a centrifuge on the shelf, spinning up between runs */
        R("g", { transform: "translate(" + (W - 190) + ",1080)" },
          R("ellipse", { cx: 0, cy: 92, rx: 130, ry: 20, fill: rgba(theme.accentInk, 0.5) }),
          R("path", { d: "M -120 90 h 240 l -18 -140 h -204 z", fill: rgba(theme.surface, inv ? 0.4 : 0.94), stroke: rgba(tint, 0.5), strokeWidth: 4 }),
          R("ellipse", { cx: 0, cy: -50, rx: 104, ry: 34, fill: rgba(theme.accentInk, 0.6), stroke: rgba(tint, 0.45), strokeWidth: 3 }),
          R("g", { transform: "rotate(" + ((t * 620) % 360).toFixed(1) + ")" },
            [0, 1, 2, 3].map((i) => R("ellipse", { key: "rt" + i, cx: Math.cos(i * 1.571) * 62, cy: -50 + Math.sin(i * 1.571) * 20, rx: 16, ry: 8, fill: rgba(theme.accent, 0.7) }))),
          R("rect", { x: -80, y: 24, width: 60, height: 16, rx: 4, fill: rgba(theme.accent, 0.55) }),
          R("circle", { cx: 62, cy: 32, r: 9, fill: rgba(theme.accent2, Math.sin(t * 4) > 0 ? 0.95 : 0.3) })),
        /* a whiteboard of readings beside it */
        R("g", { opacity: 0.6, transform: "translate(200,1060)" },
          R("rect", { x: -150, y: -110, width: 300, height: 220, rx: 6, fill: rgba(theme.surface, inv ? 0.22 : 0.9), stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          [0, 1, 2, 3].map((i) => R("line", { key: "wl" + i, x1: -120, y1: -70 + i * 44, x2: 20 + (i % 2) * 90, y2: -70 + i * 44, stroke: rgba(tint, 0.45), strokeWidth: 5 })),
          R("path", { d: "M -120 60 " + Array.from({ length: 8 }).map((_, i) => "L " + (-120 + i * 34) + " " + (60 - Math.abs(Math.sin(i * 0.8 + t * 0.3)) * 46)).join(" "), fill: "none", stroke: rgba(theme.accent, 0.8), strokeWidth: 4 })),
        /* the bench */
        R("line", { x1: 0, y1: bench, x2: W, y2: bench, stroke: rgba(tint, 0.6), strokeWidth: 8 }),
        R("rect", { x: 0, y: bench, width: W, height: H - bench, fill: rgba(theme.surface, 0.4) }),
        /* burette on a stand, dripping into a flask */
        R("g", { transform: "translate(180," + bench + ")" },
          R("rect", { x: -70, y: -8, width: 140, height: 16, rx: 4, fill: rgba(tint, 0.6) }),
          R("line", { x1: 0, y1: -8, x2: 0, y2: -430, stroke: rgba(tint, 0.55), strokeWidth: 8 }),
          R("line", { x1: 0, y1: -300, x2: 74, y2: -300, stroke: rgba(tint, 0.5), strokeWidth: 6 }),
          R("rect", { x: 62, y: -430, width: 26, height: 130, rx: 6, fill: rgba(theme.accent, 0.3), stroke: rgba(tint, 0.5), strokeWidth: 3 }),
          R("circle", { cx: 75, cy: -292 + drip * 200, r: 7, fill: rgba(theme.accent, 0.9) }),
          R("path", { d: "M 52 -80 h 46 l 30 80 h -106 z", fill: rgba(theme.accent2, 0.24), stroke: rgba(tint, 0.5), strokeWidth: 3 }),
          R("path", { d: "M 36 -20 h 78 l 8 20 h -94 z", fill: rgba(theme.accent2, 0.5) })),
        /* sample rack */
        R("g", { transform: "translate(" + (W - 200) + "," + bench + ")" },
          R("rect", { x: -120, y: -30, width: 240, height: 26, rx: 5, fill: rgba(tint, 0.5) }),
          [0, 1, 2, 3, 4].map((i) => R("rect", { key: "tb" + i, x: -104 + i * 44, y: -120, width: 26, height: 96, rx: 12, fill: rgba(i % 2 ? theme.accent : theme.accent2, 0.55), stroke: rgba(tint, 0.45), strokeWidth: 3 }))),
        /* the chart recorder */
        R("g", { transform: "translate(" + (W * 0.52) + "," + (bench - 20) + ")" },
          R("rect", { x: -230, y: -190, width: 460, height: 190, rx: 10, fill: rgba(theme.surface, 0.95), stroke: rgba(tint, 0.5), strokeWidth: 4 }),
          R("rect", { x: -206, y: -168, width: 412, height: 128, rx: 6, fill: rgba(theme.accentInk, 0.5) }),
          /* the trace already drawn */
          R("path", { d: "M -196 -104 " + Array.from({ length: 12 }).map((_, i) => "L " + (-196 + i * 34) + " " + (-104 + Math.sin(i * 0.9 + t * 0.4) * 34)).join(" "), fill: "none", stroke: rgba(theme.accent, 0.9), strokeWidth: 4 }),
          /* drum and stylus */
          R("g", { transform: "translate(190,-104) rotate(" + drum.toFixed(1) + ")" },
            R("circle", { r: 30, fill: "none", stroke: rgba(theme.accent2, 0.8), strokeWidth: 8 }),
            R("path", { d: "M -30 0 h 60", stroke: rgba(theme.accent2, 0.5), strokeWidth: 5 })),
          R("g", { transform: "translate(" + (-196 + styl * 380).toFixed(1) + ",-168)" },
            R("line", { x1: 0, y1: 0, x2: 0, y2: 128, stroke: rgba(theme.accent, 0.5), strokeWidth: 3 }),
            R("path", { d: "M -12 -14 h 24 l -12 26 z", fill: rgba(theme.ink, 0.9) })),
          R("rect", { x: -206, y: -22, width: 130, height: 14, rx: 7, fill: rgba(theme.accent, 0.6) })),
        /* a magnetic stirrer, its bar spinning and the liquid swirling */
        R("g", { transform: "translate(" + (W * 0.2) + "," + (bench - 6) + ")" },
          R("rect", { x: -80, y: -44, width: 160, height: 44, rx: 8, fill: rgba(theme.surface, inv ? 0.4 : 0.92), stroke: rgba(tint, 0.5), strokeWidth: 4 }),
          R("circle", { cx: -52, cy: -22, r: 9, fill: rgba(theme.accent, 0.9) }),
          R("path", { d: "M -46 -44 h 92 l 14 -104 h -120 z", fill: rgba(theme.accent, 0.18), stroke: rgba(tint, 0.45), strokeWidth: 3 }),
          R("g", { transform: "translate(0,-58) rotate(" + ((t * 720) % 360).toFixed(1) + ")" },
            R("rect", { x: -26, y: -5, width: 52, height: 10, rx: 5, fill: rgba(theme.accent2, 0.9) })),
          R("path", { d: "M -34 -74 q 34 " + (10 + Math.sin(t * 3) * 6).toFixed(1) + " 68 0", fill: "none", stroke: rgba(theme.accent, 0.5), strokeWidth: 4 })),
        /* vapour */
        [0, 1, 2, 3, 4].map((i) => {
          const ph = (t * (0.16 + i * 0.03) + i * 0.2) % 1;
          return R("circle", { key: "vp" + i, cx: 200 + i * 190 + Math.sin(t * 0.9 + i) * 40, cy: bench - ph * 700, r: 14 + ph * 40, fill: rgba(theme.accent, 0.08 * (1 - ph)) });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
