// LONG TAIL — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-08.js, template "LongTail").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Krona One / body Kumbh Sans. Camera set ["pushR","zoomIn","pushL","pushU","zoomOut","drop"].
// Entrances: title "rise", items "rise".
// Owns the Scroll:feed, Typing:hand, Ring:gauge mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "long-tail",
  label: "Long Tail",

  // ---- type ----
  display: "Krona One", displayFallback: "system-ui, sans-serif",
  body: "Kumbh Sans", bodyFallback: "system-ui, sans-serif",
  mono: "Space Mono",
  chrome: false,
  devanagari: "Noto Sans Devanagari",
  maxScenes: 18,
  em: 0.74,
  titleLine: 1.2, titleSpace: "-0.01em",
  titlePreset: "rise", itemPreset: "rise",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ bg: t.bg || "#eeeae1", surface: "#fbf9f4", rule: "#cac3b5", inkMuted: "#6c665b", ink: "#14120d", accent: t.accent || "#8c3f2f", accent2: t.accent2 || "#3f6c8c", accentInk: "#fbf9f4" }),
  accents: ["accent","accent2","bg"],
  groundKey: "bg", inkKey: "ink", paperKey: "accentInk",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 74,
      "kicker": {
        "v": "bare",
        "c": "accent"
      }
    },
    "statement": {
      "bg": "ink",
      "fg": "surface",
      "hi": "accent2",
      "world": true,
      "top": 610,
      "size": 86
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 540,
      "size": 48,
      "bodySize": 38,
      "ch": 54,
      "lh": 1.52,
      "weight": 400,
      "dim": 0.92,
      "kicker": {
        "v": "bare",
        "c": "accent2"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 360,
      "size": 58,
      "ch": 25,
      "lh": 1.3,
      "markSize": 210
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 255,
      "size": 58,
      "swap": "quote",
      "card": {
        "v": "paper",
        "bg": "surface",
        "glow": "accent",
        "r": 6,
        "line": "inkMuted"
      },
      "chips": {
        "v": "outline",
        "colors": [
          "accent",
          "accent2",
          "inkMuted"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 330,
      "size": 52,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 6,
        "h": 640,
        "labelSize": 42
      },
      "tilts": [
        0,
        0,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 390,
      "size": 54,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 150,
      "rule": true
    },
    "cta": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "accent2",
      "world": true,
      "top": 470,
      "size": 68,
      "align": "left",
      "btn": {
        "v": "pill",
        "bg": "ink",
        "c": "accentInk"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["pushR","zoomIn","pushL","pushU","zoomOut","drop"], camMul: 5, camOff: 3,
  mag: {"rot":0.12,"driftX":7,"driftY":5,"driftZ":0.035,"slide":0.24,"inn":0.2,"zin":0.28,"zout":0.26},
  ambient: 1.4,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"feed","Typing":"hand","Ring":"gauge"},

  strings: {
    brandName: "Long Tail",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.3, strokeLinecap: "round", strokeLinejoin: "round" }, R2("path", { d: "M2 14h4l2-8 3 14 3-10 2 4h6" })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "linear-gradient(178deg, " + rgba(theme.surface, 0.95) + " 0%, " + bg + " 46%, " + rgba(theme.rule, 0.42) + " 100%)"),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, inv = theme.currentBg !== theme.bg;
      const tint = inv ? theme.surface : theme.inkMuted, floor = H - 290;
      const drum = (t * 42) % 360;
      const quake = Math.max(0, Math.sin(t * 0.5 - 1)) * Math.max(0, Math.sin(t * 3.4));
      const styl = Math.sin(t * 4.6) * (4 + quake * 30);
      return R("g", null,
        R("defs", null,
          R("pattern", { id: "lt-chart", width: 44, height: 44, patternUnits: "userSpaceOnUse" },
            R("path", { d: "M44 0H0v44", fill: "none", stroke: rgba(theme.accent, inv ? 0.12 : 0.2), strokeWidth: 1.6 }))),
        R("rect", { x: 0, y: 0, width: W, height: H, fill: "url(#lt-chart)" }),
        /* overhead: pipework and a clock band */
        R("g", { opacity: 0.6 },
          [0, 1].map((i) => R("path", { key: "pp" + i, d: "M -20 " + (70 + i * 76) + " h " + (W + 40), stroke: rgba(tint, 0.55), strokeWidth: 18 - i * 4, strokeLinecap: "round" })),
          [0, 1, 2, 3, 4].map((i) => R("rect", { key: "fl" + i, x: 100 + i * 200, y: 58 - 4, width: 30, height: 100, rx: 4, fill: rgba(tint, 0.4) })),
          R("g", { transform: "translate(" + (W - 150) + ",190)" },
            R("circle", { r: 58, fill: rgba(theme.surface, 0.92), stroke: rgba(tint, 0.5), strokeWidth: 5 }),
            R("line", { x1: 0, y1: 0, x2: Math.cos(t * 0.1 - 1.57) * 26, y2: Math.sin(t * 0.1 - 1.57) * 26, stroke: rgba(tint, 0.8), strokeWidth: 5 }),
            R("line", { x1: 0, y1: 0, x2: Math.cos(t * 1.05 - 1.57) * 42, y2: Math.sin(t * 1.05 - 1.57) * 42, stroke: rgba(theme.accent, 0.9), strokeWidth: 3 })),
          R("rect", { x: 60, y: 244, width: W - 120, height: 14, rx: 4, fill: rgba(tint, 0.5) })),
        /* a gauge cluster on the pipework, needles drifting */
        R("g", { opacity: 0.8 },
          [0, 1, 2].map((i) => R("g", { key: "gg" + i, transform: "translate(" + (200 + i * 150) + ",176)" },
            R("circle", { r: 34, fill: rgba(theme.surface, 0.94), stroke: rgba(tint, 0.5), strokeWidth: 4 }),
            R("path", { d: "M -24 8 A 26 26 0 0 1 24 8", fill: "none", stroke: rgba(theme.accent2, 0.5), strokeWidth: 4 }),
            R("line", { x1: 0, y1: 4, x2: Math.sin((Math.sin(t * (0.5 + i * 0.2) + i) * 0.9)) * 24, y2: 4 - Math.cos((Math.sin(t * (0.5 + i * 0.2) + i) * 0.9)) * 24, stroke: rgba(theme.accent, 0.9), strokeWidth: 4, strokeLinecap: "round" }),
            R("circle", { r: 5, cy: 4, fill: rgba(theme.accent, 0.9) }),
            R("line", { x1: 0, y1: -34, x2: 0, y2: -58, stroke: rgba(tint, 0.45), strokeWidth: 4 })))),
        /* a pendant lamp swinging on the same draught as the pipes */
        R("g", { transform: "translate(" + (W - 330) + ",84) rotate(" + (Math.sin(t * 0.75) * 2.2).toFixed(2) + ")" },
          R("line", { x1: 0, y1: 0, x2: 0, y2: 100, stroke: rgba(tint, 0.45), strokeWidth: 4 }),
          R("path", { d: "M -48 100 h 96 l -20 46 h -56 z", fill: rgba(theme.accent, 0.55) }),
          R("circle", { cx: 0, cy: 158, r: 14 + Math.sin(t * 1.5) * 2, fill: rgba(theme.accent2, 0.8) })),
        /* margin: the drum and stylus */
        R("g", { transform: "translate(" + (W - 160) + ",1140)" },
          R("rect", { x: -132, y: -180, width: 264, height: 380, rx: 10, fill: rgba(theme.surface, inv ? 0.32 : 0.94), stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          R("g", { transform: "translate(0,-30)" },
            R("circle", { r: 96, fill: rgba(theme.rule, 0.5), stroke: rgba(tint, 0.5), strokeWidth: 5 }),
            R("g", { transform: "rotate(" + drum.toFixed(1) + ")" },
              Array.from({ length: 8 }).map((_, i) => R("line", { key: "sp" + i, x1: 0, y1: 0, x2: Math.cos(i * 0.785) * 92, y2: Math.sin(i * 0.785) * 92, stroke: rgba(tint, 0.3), strokeWidth: 4 })),
              R("path", { d: "M -92 0 " + Array.from({ length: 12 }).map((_, i) => "L " + (-92 + i * 16) + " " + (Math.sin(i * 1.2 + t) * (6 + (i % 4) * 5)).toFixed(1)).join(" "), fill: "none", stroke: rgba(theme.accent, 0.9), strokeWidth: 3 })),
            R("circle", { r: 14, fill: rgba(theme.accent2, 0.9) })),
          R("g", { transform: "translate(0,-30)" },
            R("line", { x1: 132, y1: 0, x2: 96, y2: styl.toFixed(2), stroke: rgba(theme.ink, 0.8), strokeWidth: 6, strokeLinecap: "round" }),
            R("circle", { cx: 96, cy: styl, r: 7, fill: rgba(theme.accent, 0.95) })),
          R("rect", { x: -110, y: 110, width: 220, height: 70, rx: 6, fill: rgba(theme.accentInk, 0.12), stroke: rgba(tint, 0.35), strokeWidth: 3 }),
          R("path", { d: "M -96 145 " + Array.from({ length: 14 }).map((_, i) => "L " + (-96 + i * 14) + " " + (145 - Math.abs(Math.sin(i * 0.8 + t * 0.6)) * (10 + quake * 22)).toFixed(1)).join(" "), fill: "none", stroke: rgba(theme.accent2, 0.8), strokeWidth: 3 })),
        /* floor: instrument rack, chair, coiled cable */
        R("line", { x1: 0, y1: floor, x2: W, y2: floor, stroke: rgba(tint, 0.55), strokeWidth: 8 }),
        R("rect", { x: 0, y: floor, width: W, height: H - floor, fill: rgba(theme.rule, 0.3) }),
        R("g", { transform: "translate(190," + (floor + 10) + ")" },
          R("rect", { x: -120, y: -260, width: 240, height: 260, rx: 8, fill: rgba(theme.surface, inv ? 0.35 : 0.92), stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          [0, 1, 2, 3].map((i) => R("g", { key: "in" + i },
            R("rect", { x: -100, y: -240 + i * 62, width: 200, height: 48, rx: 5, fill: rgba(theme.accentInk, 0.1), stroke: rgba(tint, 0.35), strokeWidth: 3 }),
            R("rect", { x: -88, y: -226 + i * 62, width: 60 + (i % 3) * 40, height: 20, rx: 3, fill: rgba(i % 2 ? theme.accent : theme.accent2, 0.6) }),
            R("circle", { cx: 78, cy: -216 + i * 62, r: 8, fill: rgba(theme.accent, Math.sin(t * 1.6 + i) > 0 ? 0.9 : 0.25) })))),
        /* a wall map with a pulsing epicentre and range rings */
        R("g", { opacity: 0.72, transform: "translate(" + (W * 0.68) + "," + (floor + 74) + ") scale(0.74)" },
          R("rect", { x: -180, y: -150, width: 360, height: 300, rx: 6, fill: rgba(theme.accent2, 0.1), stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          R("path", { d: "M -150 60 q 70 -70 140 -30 q 80 44 160 -20", fill: "none", stroke: rgba(tint, 0.45), strokeWidth: 5 }),
          R("path", { d: "M -150 -50 q 90 -50 170 6 q 70 48 130 4", fill: "none", stroke: rgba(tint, 0.3), strokeWidth: 4 }),
          (function () {
            const ph = (t % 4) / 4;
            return R("g", null,
              [0, 1, 2].map((i) => R("circle", { key: "rr" + i, cx: 40, cy: -10, r: (26 + i * 44) * (0.5 + ph * 0.8), fill: "none", stroke: rgba(theme.accent, 0.5 * (1 - ph) * (1 - i * 0.28)), strokeWidth: 4 })),
              R("circle", { cx: 40, cy: -10, r: 11, fill: rgba(theme.accent, 0.9) }));
          })(),
          [0, 1, 2].map((i) => R("rect", { key: "st" + i, x: -140 + i * 96, y: 96, width: 14, height: 14, rx: 3, fill: rgba(theme.accent2, 0.75) }))),
        /* a chart roll on its spool, a filing tray and a mug */
        R("g", { transform: "translate(" + (W - 250) + "," + (H - 96) + ")" },
          R("circle", { r: 46, fill: rgba(theme.surface, inv ? 0.45 : 0.96), stroke: rgba(tint, 0.45), strokeWidth: 4 }),
          R("g", { transform: "rotate(" + ((t * 26) % 360).toFixed(1) + ")" },
            R("path", { d: "M -46 0 h 92 M 0 -46 v 92", stroke: rgba(theme.accent, 0.4), strokeWidth: 4 })),
          R("circle", { r: 13, fill: rgba(theme.accent2, 0.85) }),
          R("path", { d: "M -46 12 h -" + (70 + (Math.sin(t * 0.4) * 0.5 + 0.5) * 80).toFixed(0), stroke: rgba(theme.surface, inv ? 0.5 : 0.98), strokeWidth: 20, strokeLinecap: "round" }),
          R("path", { d: "M -56 12 h -" + (60 + (Math.sin(t * 0.4) * 0.5 + 0.5) * 70).toFixed(0), stroke: rgba(theme.accent, 0.5), strokeWidth: 3 })),
        R("g", { opacity: 0.8, transform: "translate(" + (W * 0.34) + "," + (H - 84) + ")" },
          [0, 1, 2].map((i) => R("g", { key: "tr" + i },
            R("rect", { x: -84, y: -i * 30, width: 168, height: 22, rx: 4, fill: "none", stroke: rgba(tint, 0.5), strokeWidth: 4 }),
            R("rect", { x: -66, y: -i * 30 + 6, width: 90 - i * 18, height: 8, rx: 3, fill: rgba(i % 2 ? theme.accent : theme.accent2, 0.6) }))),
          R("path", { d: "M 128 6 h 54 l -8 -46 h -38 z", fill: rgba(theme.surface, inv ? 0.5 : 0.94), stroke: rgba(tint, 0.45), strokeWidth: 3 }),
          R("path", { d: "M 182 -30 q 22 4 18 16 q -4 12 -20 10", fill: "none", stroke: rgba(tint, 0.45), strokeWidth: 4 })),
        R("g", { opacity: 0.7, transform: "translate(" + (W * 0.42) + "," + (floor + 96) + ")" },
          R("ellipse", { cx: 0, cy: -96, rx: 70, ry: 20, fill: rgba(theme.accent2, 0.4), stroke: rgba(tint, 0.4), strokeWidth: 4 }),
          R("path", { d: "M 0 -86 v 66 M -50 -20 h 100 M -46 -20 l -14 24 M 46 -20 l 14 24", stroke: rgba(tint, 0.55), strokeWidth: 8, strokeLinecap: "round" })),
        [0, 1, 2].map((i) => R("circle", { key: "cc" + i, cx: W * 0.78, cy: floor + 70, r: 30 + i * 18, fill: "none", stroke: rgba(theme.ink, 0.35), strokeWidth: 8 })),
        [0, 1, 2, 3, 4, 5].map((i) => {
          const ph = (t * (0.1 + i * 0.02) + i * 0.18) % 1;
          return R("circle", { key: "du" + i, cx: 180 + i * 160 + Math.sin(t * 0.6 + i) * 30, cy: floor - ph * 660, r: 3 + (i % 3) * 2, fill: rgba(tint, 0.26 * (1 - ph)) });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
