// METRO LINE — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/world-pack-4.js, template "MetroLine").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Barlow Condensed / body Barlow. Camera set ["pushL","pushU","zoomOut","pushR","pushD","zoomIn"].
// Entrances: title "streak", items "rise".
// Owns the Scroll:board, Notify:drop, Morph:flap, Ring:bar mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "metro-line",
  label: "Metro Line",

  // ---- type ----
  display: "Barlow Condensed", displayFallback: "sans-serif",
  body: "Barlow", bodyFallback: "sans-serif",
  mono: null,
  em: 0.44,
  titleLine: 1.04, titleSpace: "0.01em",
  titlePreset: "streak", itemPreset: "rise",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ paper: t.paper || "#f4f4f0", red: t.red || "#d9363e", blue: "#2f6db5", green: "#3f9b57", yellow: "#e8b820", ink: "#1d1d1b" }),
  accents: ["red","yellow","blue"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "paper",
      "fg": "ink",
      "hi": "red",
      "world": true,
      "top": 300,
      "size": 138,
      "upper": true,
      "kicker": {
        "v": "tag",
        "bg": "red",
        "c": "paper"
      }
    },
    "statement": {
      "bg": "ink",
      "fg": "paper",
      "hi": "yellow",
      "world": false,
      "top": 640,
      "size": 160,
      "upper": true
    },
    "feature": {
      "bg": "paper",
      "fg": "ink",
      "hi": "blue",
      "world": true,
      "top": 248,
      "size": 104,
      "upper": true,
      "card": {
        "v": "frame",
        "bg": "ink",
        "r": 14,
        "line": "paper"
      },
      "chips": {
        "v": "square",
        "colors": [
          "red",
          "blue",
          "green"
        ],
        "text": "paper"
      }
    },
    "montage": {
      "bg": "ink",
      "fg": "paper",
      "hi": "yellow",
      "world": false,
      "top": 258,
      "size": 100,
      "upper": true,
      "tile": {
        "bg": "paper",
        "line": "ink",
        "label": "paper",
        "r": 10
      },
      "tilts": [
        0,
        0,
        0,
        0
      ]
    },
    "stats": {
      "bg": "paper",
      "fg": "ink",
      "hi": "red",
      "world": true,
      "cols": [
        "red",
        "blue",
        "green"
      ],
      "num": 158,
      "upper": true,
      "rule": true
    },
    "cta": {
      "bg": "red",
      "fg": "paper",
      "hi": "yellow",
      "world": false,
      "top": 500,
      "size": 132,
      "upper": true,
      "btn": {
        "v": "block",
        "bg": "paper",
        "c": "red"
      },
      "logoShape": "rounded"
    },
    "app": {
      "bg": "paper",
      "fg": "ink",
      "hi": "red",
      "cardBg": "#ffffff",
      "line": "ink",
      "world": true,
      "upper": true
    }
  },

  // ---- camera + motion ----
  cams: ["pushL","pushU","zoomOut","pushR","pushD","zoomIn"], camMul: 7, camOff: 1,
  mag: {"rot":0,"skew":0,"slide":0.32,"driftX":5,"driftY":4,"driftZ":0.035},
  ambient: 1.8,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"board","Notify":"drop","Morph":"flap","Ring":"bar"},

  strings: {
    brandName: "Metro Line",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round" }, R2("rect", { x: 5, y: 3, width: 14, height: 14, rx: 3 }), R2("path", { d: "M5 11h14M8 21l1.5-4M16 21l-1.5-4" }), R2("circle", { cx: 9, cy: 14, r: 0.5 }), R2("circle", { cx: 15, cy: 14, r: 0.5 })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      [["red", "M -20 400 L 300 400 L 460 560 L 460 900"], ["blue", "M 1100 620 L 700 620 L 560 760 L 200 760 L 60 900"], ["green", "M 200 -20 L 200 260 L 420 480 L 1000 480"], ["yellow", "M 900 -20 L 900 300 L 760 440 L 760 1100"]].map(([k, d], i) =>
        R("path", { key: k, d, fill: "none", stroke: rgba(theme[k], 0.5), strokeWidth: 16, strokeLinecap: "round" })),
      [[300, 400], [460, 560], [700, 620], [560, 760], [200, 260], [420, 480], [900, 300], [760, 440]].map(([x, y], i) =>
        R("circle", { key: "s" + i, cx: x, cy: y, r: 13, fill: "#fff", stroke: theme.ink, strokeWidth: 5 })),
      (function () {
        const ph = (t * 0.16) % 1;
        const pts = [[-20, 400], [300, 400], [460, 560], [460, 900]];
        const segs = 3, f = ph * segs, si = Math.min(segs - 1, Math.floor(f)), sf = f - si;
        const x = pts[si][0] + (pts[si + 1][0] - pts[si][0]) * sf, y = pts[si][1] + (pts[si + 1][1] - pts[si][1]) * sf;
        return R("g", null, R("rect", { x: x - 26, y: y - 15, width: 52, height: 30, rx: 8, fill: theme.red }), R("rect", { x: x - 16, y: y - 7, width: 12, height: 12, rx: 3, fill: "#fff" }), R("rect", { x: x + 4, y: y - 7, width: 12, height: 12, rx: 3, fill: "#fff" }));
      })(),
      R("path", { d: `M 60 ${u.H - 240} h ${((t * 140) % 300) + 60}`, stroke: theme.ink, strokeWidth: 8, strokeLinecap: "round", opacity: 0.25 })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
