// MOLTEN STUDIO — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-5.js, template "MoltenStudio").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Comfortaa / body Livvic. Camera set ["zoomIn","pushU","drop","pushL","zoomOut","pushR"].
// Entrances: title "drowse", items "pop".
// Owns the Ring:gauge, Typing:hand, Notify:drop, Morph:fade mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "molten-studio",
  label: "Molten Studio",

  // ---- type ----
  display: "Comfortaa", displayFallback: "sans-serif",
  body: "Livvic", bodyFallback: "sans-serif",
  mono: null,
  em: 0.6,
  titleLine: 1.1, titleSpace: "0",
  titlePreset: "drowse", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ shop: t.shop || "#1c1512", molten: t.molten || "#ff9633", aqua: "#6fd8d0", sand: "#e8dcc4", ink: "#14100c" }),
  accents: ["molten","aqua","shop"],
  groundKey: "shop", inkKey: "ink", paperKey: "sand",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "shop",
      "fg": "sand",
      "hi": "molten",
      "world": true,
      "top": 330,
      "size": 116,
      "kicker": {
        "v": "outline",
        "c": "aqua"
      }
    },
    "statement": {
      "bg": "ink",
      "fg": "sand",
      "hi": "molten",
      "world": false,
      "top": 630,
      "size": 142
    },
    "feature": {
      "bg": "shop",
      "fg": "sand",
      "hi": "molten",
      "world": true,
      "top": 250,
      "size": 94,
      "card": {
        "v": "glow",
        "bg": "ink",
        "glow": "molten",
        "r": 22,
        "line": "sand"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "molten",
          "aqua"
        ],
        "text": "ink"
      }
    },
    "montage": {
      "bg": "ink",
      "fg": "sand",
      "hi": "aqua",
      "world": false,
      "top": 258,
      "size": 90,
      "tile": {
        "bg": "shop",
        "line": "sand",
        "label": "aqua",
        "r": 18,
        "glow": "molten"
      },
      "tilts": [
        -2,
        1.5,
        2,
        -1.5
      ]
    },
    "stats": {
      "bg": "shop",
      "fg": "sand",
      "hi": "molten",
      "world": true,
      "cols": [
        "molten",
        "aqua",
        "sand"
      ],
      "num": 148,
      "glowNums": true
    },
    "cta": {
      "bg": "ink",
      "fg": "sand",
      "hi": "molten",
      "world": true,
      "top": 500,
      "size": 112,
      "btn": {
        "v": "glow",
        "bg": "molten",
        "c": "ink"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "shop",
      "fg": "sand",
      "hi": "molten",
      "cardBg": "#2a1f18",
      "line": "sand",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["zoomIn","pushU","drop","pushL","zoomOut","pushR"], camMul: 5, camOff: 2,
  mag: {"rot":0.5,"driftY":8,"inn":0.26},
  ambient: 1.7,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Ring":"gauge","Typing":"hand","Notify":"drop","Morph":"fade"},

  strings: {
    brandName: "Molten Studio",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round" }, R2("path", { d: "M12 3c3 4 6 7 6 11a6 6 0 0 1-12 0c0-4 3-7 6-11z" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      R("rect", { x: u.W - 300, y: u.H - 480, width: 240, height: 300, rx: 20, fill: rgba(theme.ink, 0.9), stroke: rgba(theme.sand, 0.25), strokeWidth: 3 }),
      R("ellipse", { cx: u.W - 180, cy: u.H - 330, rx: 74, ry: 90, fill: theme.molten, opacity: 0.85 + Math.sin(t * 3) * 0.12 }),
      R("ellipse", { cx: u.W - 180, cy: u.H - 330, rx: 44, ry: 56, fill: "#ffd9a0", opacity: 0.9 }),
      (function () {
        const puls = 1 + Math.sin(t * 2.2) * 0.12;
        return R("g", { transform: "translate(240," + (u.H - 520) + ") rotate(18)" },
          R("line", { x1: 0, y1: 0, x2: 360, y2: 0, stroke: rgba(theme.sand, 0.55), strokeWidth: 9, strokeLinecap: "round" }),
          R("circle", { cx: -20, r: 34 * puls, fill: theme.molten }),
          R("circle", { cx: -26, cy: -8, r: 12 * puls, fill: "#ffe0b0", opacity: 0.85 }));
      })(),
      [0, 1, 2].map((i) => R("path", { key: i, d: "M " + (u.W - 260 + i * 60) + " " + (u.H - 500) + " q 10 -30 -4 -60 q -12 -28 2 -56", fill: "none", stroke: rgba(theme.molten, 0.3 - i * 0.07), strokeWidth: 10, strokeLinecap: "round", transform: "translate(0," + (-((t * 70 + i * 45) % 140)) + ")" })),
      R("line", { x1: 80, y1: 320, x2: 460, y2: 320, stroke: rgba(theme.sand, 0.35), strokeWidth: 6 }),
      [0, 1, 2].map((i) => {
        const sh = ((t * 120) % 700) - 100;
        return R("g", { key: "o" + i, transform: "translate(" + (150 + i * 120) + ",290)" },
          R("circle", { r: 26 + (i % 2) * 8, fill: "none", stroke: [theme.aqua, theme.molten, theme.sand][i], strokeWidth: 4, opacity: 0.8 }),
          R("circle", { r: 26 + (i % 2) * 8, fill: rgba([theme.aqua, theme.molten, theme.sand][i], 0.14) }),
          R("circle", { cx: -8, cy: -10, r: 5, fill: rgba("#ffffff", Math.abs(sh - (150 + i * 120)) < 60 ? 0.8 : 0.25) }));
      })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
