// NEON LEDGER — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by the KEYFRAME admin template generator (src/templates/emit.js) from a validated
// TemplateSpec. Do not hand-edit: regenerating the template overwrites this file. To change the
// design, edit the spec on the template record and regenerate.
//
// Every executable line below was written by emit.js, not by the design model — the model
// supplied only the data (palette, per-beat look, camera set, world layer list). See the
// comment at the top of src/templates/emit.js for why that boundary exists.
//
//   slug        neon-ledger
//   renderer    film-neon-ledger
//   display     Bricolage Grotesque / body Space Grotesk
//   ground      #0a0d1a (navy), dark
//   world       grid, glow, motes

const stage = require("../film_stage");

const SKIN = {
  id: "neon-ledger",
  label: "Neon Ledger",

  // ---- type ----
  display: "Bricolage Grotesque", displayFallback: "system-ui, sans-serif",
  body: "Space Grotesk", bodyFallback: "system-ui, sans-serif",
  mono: "IBM Plex Mono",
  em: 0.52,
  titleLine: 1.02, titleSpace: "-0.02em",
  titlePreset: "slam", itemPreset: "rise",

  // ---- palette ----
  // Called with {} for the authored defaults. film_stage.buildTheme then hue-maps the brand's
  // accents onto `accents` slot by slot at their authored luminance and rotates every other
  // stop onto the brand's lead hue — so a customer's brand recolours the whole design, not just
  // the headline. That is why every colour below is a ROLE the theme resolves, and why the
  // world and ground read `theme.<role>` rather than baking hexes.
  palette: (t) => ({ navy: t.navy || "#0a0d1a", slate: t.slate || "#161b33", neonPurple: t.neonPurple || "#6C4CF1", cyan: t.cyan || "#00f0ff", paper: t.paper || "#f3f5fc", ink: t.ink || "#060810" }),
  accents: ["neonPurple","cyan","paper"],
  groundKey: "navy", inkKey: "ink", paperKey: "paper",
  dark: true,

  // ---- per-beat look ----
  // `world` is load-bearing, not decoration: each beat's copy colour is authored against its
  // OWN field, so a beat that says false is drawn on its flat bg and a beat that says true is
  // drawn over the animated backdrop.
  look: {
    "hook": {
      "bg": "navy",
      "fg": "paper",
      "hi": "cyan",
      "world": true,
      "top": 880,
      "size": 136,
      "upper": false,
      "align": "left",
      "kicker": {
        "v": "pill",
        "c": "neonPurple"
      }
    },
    "statement": {
      "bg": "slate",
      "fg": "paper",
      "hi": "cyan",
      "world": false,
      "top": 600,
      "size": 160,
      "upper": false,
      "align": "left"
    },
    "feature": {
      "bg": "paper",
      "fg": "ink",
      "hi": "neonPurple",
      "world": false,
      "top": 250,
      "size": 104,
      "upper": false,
      "align": "left",
      "card": {
        "v": "glow",
        "bg": "navy",
        "r": 24,
        "glow": "neonPurple"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "neonPurple",
          "slate"
        ],
        "text": "paper"
      }
    },
    "montage": {
      "bg": "navy",
      "fg": "paper",
      "hi": "cyan",
      "world": true,
      "top": 280,
      "size": 100,
      "upper": false,
      "align": "left",
      "tile": {
        "bg": "slate",
        "line": "neonPurple",
        "label": "paper",
        "r": 20,
        "labelSize": 28
      }
    },
    "stats": {
      "bg": "slate",
      "fg": "paper",
      "hi": "cyan",
      "world": true,
      "top": 380,
      "size": 104,
      "upper": false,
      "align": "left",
      "cols": [
        "cyan",
        "neonPurple",
        "paper"
      ],
      "num": 170
    },
    "cta": {
      "bg": "navy",
      "fg": "paper",
      "hi": "cyan",
      "world": true,
      "top": 900,
      "size": 120,
      "upper": false,
      "align": "center",
      "btn": {
        "v": "glow",
        "bg": "neonPurple",
        "c": "paper"
      },
      "logoShape": "square"
    },
    "app": {
      "bg": "slate",
      "fg": "paper",
      "hi": "cyan",
      "world": false,
      "top": 380,
      "size": 100,
      "upper": false,
      "align": "left",
      "cardBg": "navy",
      "line": "neonPurple"
    }
  },

  // ---- camera + motion ----
  // Indexed (sceneIndex * camMul + camOff) % 6 by film_stage, so adjacent scenes take different
  // camera moves rather than the whole film sharing one.
  cams: ["zoomIn","pushL","drop","pushU","pushR","zoomOut"], camMul: 3, camOff: 2,
  mag: {"x":1,"y":0.5,"rot":0.5,"skew":0,"zin":0.4,"zout":0.3,"driftX":6,"driftY":5,"driftZ":0.04,"slide":0.2,"inn":0.2,"out":0.8},
  ambient: 1.3,
  energy: 1.1,
  badge: "outline",

  // ---- the mechanics this pack owns ----
  // A beat that ends up holding no picture is expressed as one of these instead of shipping a
  // bare text slide. A pack that declares none renders only the six authored acts.
  variants: {"feature":"Code","montage":"Scroll","stats":"Ring"},

  strings: {"brandName":"Neon Ledger"},

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.4, strokeLinecap: "round", strokeLinejoin: "round" },
    R2("path",{d:"M6 18 L6 11 M12 18 L12 5 M18 18 L18 8"})),

  // The ground treatment, resolved against the live (possibly re-hued) theme.
  groundCss: (theme, bg) => "linear-gradient(160deg, " + theme.slate + " 0%, " + bg + " 58%, " + theme.navy + " 100%)",

  // ---- the world ----
  // The animated backdrop. Pure in (theme, t, progress, utils) — no Math.random and no Date,
  // which is what lets film_stage re-evaluate it deterministically on every seek. All geometry
  // was resolved at generation time from the spec's layer list, so the numbers below are
  // literals and the render page runs no RNG at all.
  World: (theme, t, p, u) => {
    var W = u.W, H = u.H;
    return R("g", null,
    R("g",null,Array.from({length:8}).map(function(_,i){return R("line",{key:"v"+i,x1:W*i/8,y1:0,x2:W*i/8,y2:H,stroke:rgba(theme.neonPurple,0.15),strokeWidth:W*0.01});}).concat(Array.from({length:14}).map(function(_,i){return R("line",{key:"h"+i,x1:0,y1:H*i/14,x2:W,y2:H*i/14,stroke:rgba(theme.neonPurple,0.11),strokeWidth:W*0.01});}))),
    R("circle",{cx:W*0.82,cy:H*0.22,r:W*0.56*(1+0.05*Math.sin(t*0.8+0.4)),fill:rgba(theme.cyan,0.01)}),
    R("circle",{cx:W*0.82,cy:H*0.22,r:W*0.46*(1+0.05*Math.sin(t*0.8+0.8)),fill:rgba(theme.cyan,0.02)}),
    R("circle",{cx:W*0.82,cy:H*0.22,r:W*0.37*(1+0.04*Math.sin(t*0.8+1.2)),fill:rgba(theme.cyan,0.03)}),
    R("circle",{cx:W*0.82,cy:H*0.22,r:W*0.28*(1+0.04*Math.sin(t*0.8+1.6)),fill:rgba(theme.cyan,0.05)}),
    R("circle",{cx:W*0.82,cy:H*0.22,r:W*0.19*(1+0.03*Math.sin(t*0.8+2)),fill:rgba(theme.cyan,0.07)}),
    R("circle",{cx:W*0.82,cy:H*0.22,r:W*0.09*(1+0.02*Math.sin(t*0.8+2.4)),fill:rgba(theme.cyan,0.14)}),
    R("g",null,[{x:0.48,y:0.8,ph:3.9,r:3.21},{x:0.83,y:1,ph:3.29,r:5.34},{x:0.42,y:0.63,ph:3.32,r:2.22},{x:0.99,y:0.44,ph:1.94,r:4.16},{x:0.77,y:0.83,ph:0.23,r:2.07},{x:0.32,y:0.96,ph:4.34,r:4.52},{x:0.06,y:0.67,ph:5.62,r:4.79},{x:0.37,y:0.59,ph:3.85,r:3.27},{x:0.69,y:0.85,ph:1.48,r:5.27},{x:0.72,y:0.97,ph:5.48,r:5.76},{x:0.77,y:0.89,ph:0.31,r:2.38},{x:0.42,y:0.4,ph:2.7,r:4.76},{x:0.35,y:0.07,ph:5.95,r:2.07},{x:0.32,y:0.59,ph:5.76,r:3.55},{x:0.13,y:0.62,ph:5.55,r:2.68},{x:0.32,y:0.24,ph:2.21,r:3.27},{x:0.78,y:0.73,ph:1.75,r:4.32},{x:0.7,y:0.23,ph:4.25,r:2.62},{x:0.42,y:0.96,ph:0.39,r:5.43},{x:0.21,y:0.28,ph:3.53,r:3.18},{x:0.22,y:0.82,ph:5.52,r:3.59},{x:0.46,y:0.56,ph:2.85,r:2.73},{x:0.43,y:0.41,ph:4.54,r:2.35},{x:0.32,y:0.54,ph:6.27,r:4.38}].map(function(m,i){return R("circle",{key:i,cx:W*m.x+Math.sin(t*0.48+m.ph)*W*0.1,cy:(H*m.y+((t*24+i*90)%(H*0.6)))%H,r:m.r,fill:rgba(theme.paper,0.35)});}))
    );
  },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
