// PIXEL PET — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/world-pack-3.js, template "PixelPet").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Silkscreen / body IBM Plex Mono. Camera set ["pushD","pushL","zoomIn","pushU","pushR","spin"].
// Entrances: title "slam", items "pop".
// Owns the Cursor:keys, Ring:bar, Notify:side, DragDrop:drag mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "pixel-pet",
  label: "Pixel Pet",

  // ---- type ----
  display: "Silkscreen", displayFallback: "monospace",
  body: "IBM Plex Mono", bodyFallback: "monospace",
  mono: null,
  em: 0.72,
  titleLine: 1.3, titleSpace: "0",
  titlePreset: "slam", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ mint: t.mint || "#cfe8b8", shade: "#a8c890", dark: t.dark || "#274029", accent: "#e07a3f", paper: "#f2f8e8", ink: "#1c2e1e" }),
  accents: ["accent","mint","dark"],
  groundKey: "mint", inkKey: "ink", paperKey: "paper",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "mint",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 84,
      "upper": true,
      "kicker": {
        "v": "outline",
        "c": "dark",
        "r": 0
      }
    },
    "statement": {
      "bg": "dark",
      "fg": "mint",
      "hi": "accent",
      "world": false,
      "top": 660,
      "size": 92,
      "upper": true
    },
    "feature": {
      "bg": "mint",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 246,
      "size": 66,
      "upper": true,
      "card": {
        "v": "frame",
        "bg": "dark",
        "r": 6,
        "line": "mint"
      },
      "chips": {
        "v": "square",
        "colors": [
          "dark",
          "accent"
        ],
        "text": "paper"
      }
    },
    "montage": {
      "bg": "dark",
      "fg": "mint",
      "hi": "accent",
      "world": false,
      "top": 260,
      "size": 64,
      "upper": true,
      "tile": {
        "bg": "#1c2e1e",
        "line": "mint",
        "label": "mint",
        "r": 4,
        "glow": "mint",
        "labelSize": 30
      },
      "tilts": [
        0,
        0,
        0,
        0
      ]
    },
    "stats": {
      "bg": "mint",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "cols": [
        "dark",
        "accent",
        "ink"
      ],
      "num": 108,
      "rule": true,
      "upper": true
    },
    "cta": {
      "bg": "dark",
      "fg": "mint",
      "hi": "accent",
      "world": false,
      "top": 560,
      "size": 84,
      "upper": true,
      "btn": {
        "v": "block",
        "bg": "accent",
        "c": "paper"
      },
      "logoShape": "rounded"
    }
  },

  // ---- camera + motion ----
  cams: ["pushD","pushL","zoomIn","pushU","pushR","spin"], camMul: 7, camOff: 1,
  mag: {"rot":0,"skew":0,"slide":0.3,"inn":0.15,"driftX":2,"driftY":2,"driftZ":0.02},
  ambient: 1.9,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Cursor":"keys","Ring":"bar","Notify":"side","DragDrop":"drag"},

  strings: {
    brandName: "Pixel Pet",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: theme.currentBg }, R2("path", { d: "M6 4h4v4H6zM14 4h4v4h-4zM4 10h16v6H4zM8 16h8v4H8z" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      Array.from({ length: 60 }).map((_, i) => {
        const gx = (i % 10) * 120, gy = Math.floor(i / 10) * 340;
        return R("rect", { key: "g" + i, x: gx + 40, y: gy + 60, width: 8, height: 8, fill: rgba(theme.dark, 0.12) });
      }),
      (function () {
        const hop = Math.abs(Math.sin(t * 3)) * 40;
        const px = u.W / 2 + Math.sin(t * 0.5) * 220;
        return R("g", { transform: `translate(${px},${u.H - 420 - hop}) scale(6)`, fill: theme.dark },
          R("path", { d: "M2 2h2v2H2zM10 2h2v2h-2zM2 4h12v6H2zM0 6h2v2H0zM14 6h2v2h-2zM4 10h2v2H4zM10 10h2v2h-2z" }),
          R("rect", { x: 5, y: 6, width: 2, height: 2, fill: theme.mint }),
          R("rect", { x: 9, y: 6, width: 2, height: 2, fill: theme.mint }));
      })(),
      (function () {
        const ph = (t * 0.8) % 1;
        return R("g", { transform: `translate(${u.W / 2 + Math.sin(t * 0.5) * 220 + 90},${u.H - 560 - ph * 160}) scale(${3 - ph})`, opacity: 1 - ph, fill: theme.accent },
          R("path", { d: "M2 0h2v2H2zM6 0h2v2H6zM0 2h10v2H0zM2 4h6v2H2zM4 6h2v2H4z" }));
      })(),
      [0, 1, 2].map((i) => R("rect", { key: "c" + i, x: 160 + i * 330 + Math.floor(t * 2) % 2 * 8, y: u.H - 250, width: 14, height: 14, fill: theme.shade })),
      R("rect", { x: 0, y: ((t * 200) % (u.H + 300)) - 150, width: u.W, height: 90, fill: rgba("#ffffff", 0.06) })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
