// PROOF STEPS — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-08.js, template "ProofSteps").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Space Mono / body Atkinson Hyperlegible. Camera set ["pushU","zoomIn","pushL","drop","zoomOut","pushR"].
// Entrances: title "machete", items "rise".
// Owns the Scroll:board, Typing:terminal, Ring:gauge mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "proof-steps",
  label: "Proof Steps",

  // ---- type ----
  display: "Space Mono", displayFallback: "ui-monospace, monospace",
  body: "Atkinson Hyperlegible", bodyFallback: "system-ui, sans-serif",
  mono: "Space Mono",
  chrome: false,
  devanagari: "Noto Sans Devanagari",
  maxScenes: 18,
  em: 0.58,
  titleLine: 1.14, titleSpace: "-0.02em",
  titlePreset: "machete", itemPreset: "rise",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ bg: t.bg || "#eef0ef", surface: "#fbfcfc", rule: "#c9cdcc", inkMuted: "#6b7170", ink: "#111413", accent: t.accent || "#2f6f5f", accent2: t.accent2 || "#c98a2f", accentInk: "#fbfcfc" }),
  accents: ["accent","accent2","bg"],
  groundKey: "bg", inkKey: "ink", paperKey: "accentInk",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 84,
      "kicker": {
        "v": "square",
        "bg": "accent",
        "c": "accentInk"
      }
    },
    "statement": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "accent2",
      "world": true,
      "top": 610,
      "size": 96
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 540,
      "size": 58,
      "bodySize": 38,
      "ch": 54,
      "lh": 1.52,
      "weight": 400,
      "dim": 0.92,
      "kicker": {
        "v": "bare",
        "c": "accent2"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 360,
      "size": 68,
      "ch": 25,
      "lh": 1.2,
      "markSize": 210
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 255,
      "size": 68,
      "swap": "body",
      "card": {
        "v": "frame",
        "bg": "surface",
        "glow": "accent",
        "r": 6,
        "line": "inkMuted"
      },
      "chips": {
        "v": "square",
        "colors": [
          "accent",
          "accent2",
          "inkMuted"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 330,
      "size": 62,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 6,
        "h": 640,
        "labelSize": 42
      },
      "tilts": [
        0,
        0,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 390,
      "size": 64,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 150,
      "rule": true
    },
    "cta": {
      "bg": "ink",
      "fg": "surface",
      "hi": "accent2",
      "world": true,
      "top": 470,
      "size": 78,
      "align": "left",
      "btn": {
        "v": "block",
        "bg": "accent2",
        "c": "ink"
      },
      "logoShape": "rounded"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["pushU","zoomIn","pushL","drop","zoomOut","pushR"], camMul: 5, camOff: 2,
  mag: {"rot":0.14,"driftX":5,"driftY":6,"driftZ":0.03,"slide":0.2,"inn":0.2,"zin":0.28,"zout":0.26},
  ambient: 1.45,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"board","Typing":"terminal","Ring":"gauge"},

  strings: {
    brandName: "Proof Steps",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.3, strokeLinecap: "round", strokeLinejoin: "round" }, R2("path", { d: "M12 3v10M6 21l6-8 6 8" })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "radial-gradient(96% 52% at 50% 4%, " + rgba(theme.surface, 0.96) + " 0%, transparent 60%), " + bg),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, inv = theme.currentBg !== theme.bg;
      const tint = inv ? theme.surface : theme.inkMuted, bench = H - 290;
      const beat = Math.sin((t / 2) * Math.PI * 2), swing = beat * 20;
      const steps = Math.floor(t / 1) % 12;
      const tick = Math.abs(beat) > 0.97 ? 1 : 0;
      return R("g", null,
        R("defs", null,
          R("pattern", { id: "ps-grid", width: 60, height: 60, patternUnits: "userSpaceOnUse" },
            R("path", { d: "M60 0H0v60", fill: "none", stroke: rgba(theme.rule, inv ? 0.24 : 0.7), strokeWidth: 2 }))),
        R("rect", { x: 0, y: 0, width: W, height: H, fill: "url(#ps-grid)" }),
        /* overhead: a truss of rules and clamp lamps */
        R("g", { opacity: 0.66 },
          R("rect", { x: -20, y: 40, width: W + 40, height: 20, rx: 5, fill: rgba(tint, 0.5) }),
          Array.from({ length: 22 }).map((_, i) => R("line", { key: "rl" + i, x1: 30 + i * 48, y1: 60, x2: 30 + i * 48, y2: 60 + (i % 5 === 0 ? 40 : 22), stroke: rgba(tint, 0.55), strokeWidth: i % 5 === 0 ? 4 : 3 })),
          [0, 1, 2].map((i) => R("g", { key: "cl" + i, transform: "translate(" + (150 + i * 170) + ",60) rotate(" + (Math.sin(t * 0.6 + i) * 1.6).toFixed(2) + ")" },
            R("line", { x1: 0, y1: 0, x2: 0, y2: 96, stroke: rgba(tint, 0.5), strokeWidth: 4 }),
            R("path", { d: "M -40 96 h 80 l -18 44 h -44 z", fill: rgba(theme.accent, 0.55) }),
            R("circle", { cx: 0, cy: 152, r: 13 + tick * 3, fill: rgba(theme.accent2, 0.75 + 0.2 * tick) })))),
        /* a pegboard of set squares and dividers under the truss */
        R("g", { opacity: 0.62 },
          [0, 1, 2].map((i) => R("g", { key: "sq" + i, transform: "translate(" + (620 + i * 130) + ",130) rotate(" + (Math.sin(t * 0.6 + i * 1.3) * 1.8).toFixed(2) + ")" },
            R("line", { x1: 0, y1: -22, x2: 0, y2: 0, stroke: rgba(tint, 0.45), strokeWidth: 3 }),
            i === 1
              ? R("g", null,
                  R("path", { d: "M 0 0 l -34 96 M 0 0 l 34 96", stroke: rgba(theme.accent2, 0.7), strokeWidth: 6, strokeLinecap: "round" }),
                  R("path", { d: "M -20 56 h 40", stroke: rgba(tint, 0.45), strokeWidth: 4 }))
              : R("g", null,
                  R("path", { d: "M -44 0 h 88 l -88 96 z", fill: "none", stroke: rgba(theme.accent, 0.6), strokeWidth: 5 }),
                  R("path", { d: "M -30 22 h 20 v 20", fill: "none", stroke: rgba(tint, 0.4), strokeWidth: 4 })))),
          R("rect", { x: 560, y: 106, width: 400, height: 12, rx: 4, fill: rgba(tint, 0.5) })),
        /* a plumb bob hanging dead still while everything else moves */
        R("g", { transform: "translate(1006,118)" },
          R("line", { x1: 0, y1: 0, x2: 0, y2: 108, stroke: rgba(tint, 0.55), strokeWidth: 3 }),
          R("path", { d: "M -14 108 h 28 l -14 52 z", fill: rgba(theme.accent2, 0.85) }),
          R("circle", { cx: 0, cy: 108, r: 6, fill: rgba(tint, 0.7) })),
        /* margin: the escapement, stepping one tooth per swing */
        R("g", { transform: "translate(" + (W - 160) + ",1310)" },
          R("rect", { x: -122, y: -200, width: 244, height: 400, rx: 8, fill: rgba(theme.surface, inv ? 0.3 : 0.92), stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          R("g", { transform: "translate(0,-70) rotate(" + (steps * 30).toFixed(1) + ")" },
            R("circle", { r: 74, fill: "none", stroke: rgba(theme.accent, 0.8), strokeWidth: 8 }),
            Array.from({ length: 12 }).map((_, i) => R("path", { key: "th" + i, d: "M " + (Math.cos(i * 0.524) * 74).toFixed(1) + " " + (Math.sin(i * 0.524) * 74).toFixed(1) + " l " + (Math.cos(i * 0.524 + 0.4) * 20).toFixed(1) + " " + (Math.sin(i * 0.524 + 0.4) * 20).toFixed(1), stroke: rgba(theme.accent, 0.7), strokeWidth: 6, strokeLinecap: "round" })),
            R("circle", { r: 12, fill: rgba(theme.accent2, 0.9) })),
          R("g", { transform: "rotate(" + swing.toFixed(2) + " 0 -190)" },
            R("line", { x1: 0, y1: -190, x2: 0, y2: 40, stroke: rgba(theme.ink, 0.8), strokeWidth: 6, strokeLinecap: "round" }),
            R("path", { d: "M -34 -20 l 34 -22 l 34 22 l -34 22 z", fill: rgba(theme.accent2, 0.85) }),
            R("circle", { cx: 0, cy: 56, r: 24, fill: rgba(theme.accent, 0.85) })),
          R("rect", { x: -70, y: 128, width: 140, height: 44, rx: 6, fill: rgba(theme.ink, 0.82) }),
          R("text", { x: 0, y: 160, textAnchor: "middle", fontFamily: '"Space Mono", monospace', fontSize: 26, fill: rgba(theme.accent2, 0.95) }, "Q" + String(steps + 1).padStart(2, "0"))),
        /* a lemma board, ticked off one line at a time */
        R("g", { transform: "translate(" + (W - 200) + "," + (H - 200) + ")" },
          R("rect", { x: -170, y: -150, width: 340, height: 300, rx: 8, fill: rgba(theme.surface, inv ? 0.32 : 0.94), stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          R("rect", { x: -170, y: -150, width: 340, height: 40, rx: 8, fill: rgba(theme.accent, 0.28) }),
          [0, 1, 2, 3, 4].map((i) => {
            const done = ((Math.floor(t / 2.4) % 6) > i) ? 1 : 0;
            return R("g", { key: "lm" + i },
              R("rect", { x: -146, y: -84 + i * 48, width: 24, height: 24, rx: 5, fill: done ? rgba(theme.accent, 0.85) : "none", stroke: rgba(tint, 0.5), strokeWidth: 3 }),
              done ? R("path", { d: "M -140 " + (-72 + i * 48) + " l 6 7 l 11 -13", fill: "none", stroke: rgba(theme.accentInk, 0.95), strokeWidth: 4, strokeLinecap: "round" }) : null,
              R("rect", { x: -108, y: -76 + i * 48, width: 150 + (i % 3) * 40, height: 9, rx: 4, fill: rgba(tint, done ? 0.55 : 0.28) }));
          })),
        /* a drawing arm sweeping an arc, a pencil tin and a cup */
        R("g", { opacity: 0.8, transform: "translate(" + (W * 0.5) + "," + (H - 130) + ")" },
          R("circle", { r: 20, fill: rgba(theme.accent, 0.55), stroke: rgba(tint, 0.45), strokeWidth: 4 }),
          R("g", { transform: "rotate(" + (Math.sin(t * 0.45) * 46).toFixed(2) + ")" },
            R("line", { x1: 0, y1: 0, x2: 0, y2: -178, stroke: rgba(tint, 0.6), strokeWidth: 7, strokeLinecap: "round" }),
            R("circle", { cx: 0, cy: -178, r: 9, fill: rgba(theme.accent2, 0.9) })),
          R("path", { d: "M -110 -46 A 118 118 0 0 1 110 -46", fill: "none", stroke: rgba(theme.accent, 0.3), strokeWidth: 3, strokeDasharray: "12 10" })),
        R("g", { transform: "translate(" + (W * 0.32) + "," + (H - 84) + ")" },
          R("path", { d: "M -34 0 h 68 l -6 -66 h -56 z", fill: rgba(theme.accent2, 0.4), stroke: rgba(tint, 0.45), strokeWidth: 4 }),
          [0, 1, 2, 3].map((i) => R("line", { key: "pn" + i, x1: -18 + i * 12, y1: -66, x2: -24 + i * 14, y2: -66 - (30 + (i % 3) * 18), stroke: rgba(i % 2 ? theme.accent : theme.ink, 0.7), strokeWidth: 6, strokeLinecap: "round" }))),
        R("g", { opacity: 0.85, transform: "translate(" + (W * 0.42) + "," + (H - 76) + ")" },
          R("path", { d: "M -28 0 h 56 l -6 -50 h -44 z", fill: rgba(theme.surface, inv ? 0.5 : 0.96), stroke: rgba(tint, 0.45), strokeWidth: 3 }),
          R("path", { d: "M 28 -38 q 22 4 18 16 q -4 12 -20 10", fill: "none", stroke: rgba(tint, 0.45), strokeWidth: 4 }),
          [0, 1].map((i) => {
            const ph = ((t * 0.42 + i * 0.5) % 1);
            return R("path", { key: "sm" + i, d: "M " + (-10 + i * 20) + " -56 q " + (Math.sin(t * 1.3 + i * 2) * 10).toFixed(1) + " -32 0 -62", fill: "none", stroke: rgba(tint, 0.22 * (1 - ph)), strokeWidth: 6, strokeLinecap: "round", transform: "translate(0," + (-ph * 70).toFixed(1) + ")" });
          })),
        /* floor: bench, plaque, proof sheets, caliper */
        R("line", { x1: 0, y1: bench, x2: W, y2: bench, stroke: rgba(tint, 0.55), strokeWidth: 8 }),
        R("rect", { x: 0, y: bench, width: W, height: H - bench, fill: rgba(theme.rule, 0.3) }),
        R("g", { transform: "translate(200," + (bench + 10) + ")" },
          Array.from({ length: 5 }).map((_, i) => R("rect", { key: "sh" + i, x: -110 + (i % 2) * 12, y: -20 - i * 20, width: 220 - (i % 2) * 20, height: 16, rx: 2, fill: rgba(theme.surface, inv ? 0.45 : 0.97), stroke: rgba(tint, 0.32), strokeWidth: 2 })),
          R("rect", { x: -60, y: 40, width: 120, height: 40, rx: 5, fill: rgba(theme.accent, 0.4), stroke: rgba(tint, 0.4), strokeWidth: 3 })),
        R("g", { opacity: 0.8, transform: "translate(" + (W * 0.5) + "," + (bench + 90) + ") rotate(-4)" },
          R("rect", { x: -170, y: -14, width: 340, height: 28, rx: 6, fill: rgba(tint, 0.55) }),
          R("rect", { x: (-150 + (Math.sin(t * 0.5) * 0.5 + 0.5) * 200).toFixed(1), y: -34, width: 30, height: 68, rx: 4, fill: rgba(theme.accent2, 0.8) }),
          R("rect", { x: -170, y: -34, width: 26, height: 68, rx: 4, fill: rgba(theme.accent, 0.7) })),
        [0, 1, 2, 3, 4, 5].map((i) => {
          const ph = (t * (0.1 + i * 0.02) + i * 0.17) % 1;
          return R("circle", { key: "mo" + i, cx: 160 + i * 160 + Math.sin(t * 0.6 + i) * 32, cy: bench - ph * 660, r: 3 + (i % 3) * 2, fill: rgba(theme.accent, 0.24 * (1 - ph)) });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
