// RAINY WINDOW — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/world-pack-3.js, template "RainyWindow").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Merriweather / body Public Sans. Camera set ["zoomOut","pushD","pushL","zoomIn","pushR","hopU"].
// Entrances: title "drowse", items "rise".
// Owns the Typing:typewriter, Scroll:feed, Ring:ring, Notify:drop mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "rainy-window",
  label: "Rainy Window",

  // ---- type ----
  display: "Merriweather", displayFallback: "serif",
  body: "Public Sans", bodyFallback: "sans-serif",
  mono: null,
  em: 0.56,
  titleLine: 1.14, titleSpace: "0",
  titlePreset: "drowse", itemPreset: "rise",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ slate: t.slate || "#2c3440", glass: "#39424f", bokeh: t.bokeh || "#f2b552", drop: "#7ac7e0", paper: "#eef1f2", ink: "#1a2027" }),
  accents: ["bokeh","drop","slate"],
  groundKey: "slate", inkKey: "ink", paperKey: "paper",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "slate",
      "fg": "paper",
      "hi": "bokeh",
      "world": true,
      "top": 320,
      "size": 112,
      "kicker": {
        "v": "bare",
        "c": "drop"
      }
    },
    "statement": {
      "bg": "ink",
      "fg": "paper",
      "hi": "drop",
      "world": false,
      "top": 640,
      "size": 136
    },
    "feature": {
      "bg": "slate",
      "fg": "paper",
      "hi": "bokeh",
      "world": true,
      "top": 248,
      "size": 90,
      "card": {
        "v": "frame",
        "bg": "glass",
        "r": 22,
        "line": "paper"
      },
      "chips": {
        "v": "outline",
        "colors": [
          "bokeh",
          "drop",
          "paper"
        ],
        "text": "ink"
      }
    },
    "montage": {
      "bg": "ink",
      "fg": "paper",
      "hi": "bokeh",
      "world": false,
      "top": 258,
      "size": 90,
      "tile": {
        "bg": "glass",
        "line": "paper",
        "label": "paper",
        "r": 16
      },
      "tilts": [
        -1.5,
        1,
        1.5,
        -1
      ]
    },
    "stats": {
      "bg": "slate",
      "fg": "paper",
      "hi": "drop",
      "world": true,
      "cols": [
        "bokeh",
        "drop",
        "paper"
      ],
      "num": 148
    },
    "cta": {
      "bg": "ink",
      "fg": "paper",
      "hi": "bokeh",
      "world": false,
      "top": 500,
      "size": 112,
      "btn": {
        "v": "pill",
        "bg": "bokeh",
        "c": "ink"
      },
      "logoShape": "circle"
    }
  },

  // ---- camera + motion ----
  cams: ["zoomOut","pushD","pushL","zoomIn","pushR","hopU"], camMul: 3, camOff: 1,
  mag: {"rot":0.4,"driftX":5,"driftY":5,"inn":0.28,"driftZ":0.04},
  ambient: 1.6,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Typing":"typewriter","Scroll":"feed","Ring":"ring","Notify":"drop"},

  strings: {
    brandName: "Rainy Window",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round" }, R2("path", { d: "M12 3c3 4 6 7 6 11a6 6 0 0 1-12 0c0-4 3-7 6-11Z" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      [0, 1, 2, 3, 4, 5, 6].map((i) => {
        const bx = (i * 167 + 80) % u.W, by = 300 + (i * 229) % (u.H * 0.5);
        const pulse = 0.5 + 0.3 * Math.sin(t * 0.9 + i * 1.7);
        const c = i % 3 === 0 ? theme.bokeh : i % 3 === 1 ? theme.drop : "#e8788a";
        return R("circle", { key: "bk" + i, cx: bx, cy: by, r: 34 + (i % 3) * 22, fill: rgba(c, 0.16 * pulse * 2) });
      }),
      Array.from({ length: 12 }).map((_, i) => {
        const dx = (i * 89 + 50) % u.W + Math.sin(i * 5) * 20;
        const dy = ((t * (180 + (i % 5) * 60) + i * 340) % (u.H + 260)) - 130;
        return R("g", { key: "d" + i },
          R("line", { x1: dx, y1: dy - 60, x2: dx, y2: dy - 14, stroke: rgba(theme.drop, 0.35), strokeWidth: 3 }),
          R("circle", { cx: dx, cy: dy, r: 5 + (i % 3) * 2, fill: rgba(theme.drop, 0.7) }));
      }),
      R("path", { d: `M ${u.W * 0.12} 0 q ${Math.sin(t * 0.6) * 8} ${u.H * 0.3} -14 ${u.H * 0.62}`, stroke: rgba(theme.drop, 0.28), strokeWidth: 7, fill: "none", strokeLinecap: "round" }),
      R("path", { d: `M ${u.W * 0.88} 0 q ${-Math.sin(t * 0.5) * 10} ${u.H * 0.4} 10 ${u.H * 0.7}`, stroke: rgba(theme.drop, 0.22), strokeWidth: 5, fill: "none", strokeLinecap: "round" })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
