// ROOT PATH — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-01.js, template "RootPath").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Chakra Petch / body Sarabun. Camera set ["drop","pushR","spin","pushL","hopU","zoomIn"].
// Entrances: title "slam", items "rise".
// Owns the Ring:ring, Scroll:board, Typing:hand mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "root-path",
  label: "Root Path",

  // ---- type ----
  display: "Chakra Petch", displayFallback: "\"Helvetica Neue\", sans-serif",
  body: "Sarabun", bodyFallback: "system-ui, sans-serif",
  mono: "Space Mono",
  chrome: false,
  devanagari: "Noto Sans Devanagari",
  maxScenes: 18,
  em: 0.52,
  titleLine: 1.04, titleSpace: "-0.015em",
  titlePreset: "slam", itemPreset: "rise",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({
      bg: t.bg || "#141210", surface: "#1e1a16", rule: "#3a322a", inkMuted: "#9c9186",
      ink: "#f0eae2", accent: t.accent || "#f2a33c", accent2: t.accent2 || "#5fb0a8", accentInk: "#120f0c",
    }),
  accents: ["accent","bg","accent2"],
  groundKey: "bg", inkKey: "accentInk", paperKey: "ink",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 310,
      "size": 90,
      "upper": true,
      "kicker": {
        "v": "pill",
        "bg": "accent",
        "c": "accentInk"
      }
    },
    "statement": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 610,
      "size": 104,
      "upper": true
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 550,
      "size": 74,
      "bodySize": 38,
      "ch": 50,
      "lh": 1.5,
      "weight": 400,
      "dim": 0.9,
      "kicker": {
        "v": "bare",
        "c": "accent2"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 370,
      "size": 82,
      "ch": 24,
      "lh": 1.14,
      "markSize": 200
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 250,
      "size": 80,
      "upper": true,
      "swap": "quote",
      "card": {
        "v": "tilt",
        "bg": "surface",
        "r": 16,
        "line": "inkMuted"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "accent",
          "accent2"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 330,
      "size": 76,
      "upper": true,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 16,
        "h": 640,
        "labelSize": 40
      },
      "tilts": [
        -1.5,
        1.5,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 390,
      "size": 78,
      "upper": true,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 150
    },
    "cta": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 470,
      "size": 90,
      "upper": true,
      "align": "left",
      "btn": {
        "v": "pill",
        "bg": "accent",
        "c": "accentInk"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "surface",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["drop","pushR","spin","pushL","hopU","zoomIn"], camMul: 3, camOff: 5,
  mag: {"rot":0.5,"driftX":8,"driftY":7,"driftZ":0.04,"slide":0.24,"inn":0.2,"zin":0.36,"zout":0.3},
  ambient: 1.5,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Ring":"ring","Scroll":"board","Typing":"hand"},

  strings: {
    brandName: "Root Path",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.4, strokeLinecap: "round", strokeLinejoin: "round" },
      R2("path", { d: "M12 3v6M12 15v6M5 12h14" }), R2("circle", { cx: 12, cy: 12, r: 3 })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, a = (t / 16) * Math.PI * 2;
      const cx = W * 0.6 + Math.cos(a) * (W * 0.3), cy = H * 0.79 + Math.sin(a * 2) * (H * 0.085);
      const tilt = Math.cos(a) * 9, alt = 0.6 + 0.4 * (Math.sin(a * 2) * 0.5 + 0.5);
      const rotor = (t * 900) % 360;
      const ridge = (t * 11) % 360;
      const route = H * 0.79;
      return R("g", null,
        R("defs", null,
          R("pattern", { id: "rp-grid", width: 96, height: 96, patternUnits: "userSpaceOnUse", patternTransform: "translate(" + ((t * 7) % 96).toFixed(1) + ",0)" },
            R("path", { d: "M48 40v16M40 48h16", stroke: rgba(theme.rule, 0.9), strokeWidth: 2 }),
            R("circle", { cx: 0, cy: 0, r: 2, fill: rgba(theme.accent, 0.25) })),
          R("radialGradient", { id: "rp-glow", cx: "50%", cy: "50%" },
            R("stop", { offset: "0%", stopColor: rgba(theme.accent, 0.26) }),
            R("stop", { offset: "100%", stopColor: rgba(theme.accent, 0) }))),
        R("rect", { x: 0, y: 0, width: W, height: H, fill: "url(#rp-grid)" }),
        R("circle", { cx: W * 0.22, cy: 340, r: 440, fill: "url(#rp-glow)" }),
        /* ridges, two speeds */
        R("path", { d: "M " + (-ridge) + " " + (H - 470) + " q 200 -140 420 -20 q 220 120 460 -60 q 220 -160 460 20 L " + (W + 400) + " " + H + " L " + (-ridge) + " " + H + " Z", fill: rgba(theme.surface, 0.5) }),
        R("path", { d: "M " + (-ridge * 1.8) + " " + (H - 330) + " q 260 -120 520 10 q 240 110 520 -50 L " + (W + 600) + " " + H + " L " + (-ridge * 1.8) + " " + H + " Z", fill: rgba(theme.rule, 0.5) }),
        /* three contour lines threading the corridor */
        [0, 1, 2].map((i) => R("path", { key: "c" + i, d: "M 0 " + (H * 0.66 + i * 190) + " q " + (W * 0.3) + " " + (-80 - i * 14) + " " + (W * 0.55) + " 16 q " + (W * 0.25) + " 90 " + (W * 0.45) + " -26", fill: "none", stroke: rgba(theme.rule, 0.8), strokeWidth: 2 })),
        /* the route the drone is flying, and its waypoints */
        R("path", { d: "M 40 " + (route + 120) + " Q " + (W * 0.3) + " " + (route - 150) + " " + (W * 0.6) + " " + route + " T " + (W - 30) + " " + (route + 90), fill: "none", stroke: rgba(theme.accent, 0.34), strokeWidth: 4, strokeDasharray: "22 20", strokeDashoffset: (-(t * 40) % 42).toFixed(1) }),
        [0, 1, 2, 3, 4].map((i) => {
          const wx = 110 + i * ((W - 220) / 4), wy = route + 110 - Math.sin(i * 0.9) * 130;
          const ph = ((t * 0.55 + i * 0.2) % 1);
          const live = Math.floor((t * 0.55) % 5) === i;
          return R("g", { key: "wp" + i },
            R("circle", { cx: wx, cy: wy, r: 9, fill: rgba(live ? theme.accent : theme.accent2, 0.9) }),
            R("circle", { cx: wx, cy: wy, r: 9 + ph * 62, fill: "none", stroke: rgba(theme.accent2, 0.34 * (1 - ph)), strokeWidth: 3 }));
        }),
        /* beacon masts along the floor, blinking out of phase */
        [0, 1, 2].map((i) => {
          const mx = 180 + i * 360, blink = Math.sin(t * 2.2 + i * 2.1) > 0.55 ? 1 : 0.16;
          return R("g", { key: "bm" + i },
            R("line", { x1: mx, y1: H - 120, x2: mx, y2: H - 300 - (i % 2) * 70, stroke: rgba(theme.inkMuted, 0.45), strokeWidth: 5 }),
            R("path", { d: "M " + (mx - 26) + " " + (H - 120) + " l 26 -40 l 26 40 z", fill: "none", stroke: rgba(theme.inkMuted, 0.35), strokeWidth: 4 }),
            R("circle", { cx: mx, cy: H - 306 - (i % 2) * 70, r: 10, fill: rgba(theme.accent, blink) }),
            R("circle", { cx: mx, cy: H - 306 - (i % 2) * 70, r: 26, fill: "none", stroke: rgba(theme.accent, 0.3 * blink), strokeWidth: 3 }));
        }),
        /* the aircraft */
        R("ellipse", { cx: cx, cy: H - 150, rx: 120 * alt, ry: 16 * alt, fill: rgba(theme.accentInk, 0.5) }),
        R("g", { transform: "translate(" + cx.toFixed(1) + "," + cy.toFixed(1) + ") rotate(" + tilt.toFixed(2) + ")" },
          [-1, 1].map((sx) => [-1, 1].map((sy) => R("line", { key: "a" + sx + sy, x1: 0, y1: 0, x2: sx * 74, y2: sy * 52, stroke: rgba(theme.inkMuted, 0.7), strokeWidth: 7, strokeLinecap: "round" }))),
          [-1, 1].map((sx) => [-1, 1].map((sy) => R("circle", { key: "r" + sx + sy, cx: sx * 74, cy: sy * 52, r: 40, fill: "none", stroke: rgba(theme.accent, 0.35), strokeWidth: 5, strokeDasharray: "26 14", transform: "rotate(" + (rotor * (sx * sy)).toFixed(1) + " " + sx * 74 + " " + sy * 52 + ")" }))),
          R("path", { d: "M -52 -22 L 52 -22 L 40 18 L -40 18 Z", fill: rgba(theme.surface, 0.96), stroke: rgba(theme.inkMuted, 0.5), strokeWidth: 2.5 }),
          R("path", { d: "M -52 -22 L 52 -22 L 44 -6 L -44 -6 Z", fill: rgba(theme.ink, 0.14) }),
          R("circle", { cx: 0, cy: 4, r: 11, fill: rgba(theme.accent, 0.95) }),
          R("circle", { cx: 0, cy: 4, r: 24, fill: "none", stroke: rgba(theme.accent, 0.3), strokeWidth: 3 }),
          R("path", { d: "M 0 20 L -34 96 L 34 96 Z", fill: rgba(theme.accent, 0.12) }),
          R("line", { x1: 0, y1: 18, x2: 0, y2: 40, stroke: rgba(theme.accent2, 0.7), strokeWidth: 4, strokeLinecap: "round" })),
        /* near plane: motes and streaks */
        [0, 1, 2, 3, 4, 5, 6].map((i) => {
          const ph = (t * (0.14 + i * 0.025) + i * 0.16) % 1;
          return R("circle", { key: "m" + i, cx: 70 + i * 155 + Math.sin(t * 0.9 + i) * 40, cy: H - ph * (H + 200), r: 4 + (i % 3) * 3, fill: rgba(theme.accent2, 0.3 * (1 - ph)) });
        }),
        [0, 1, 2].map((i) => {
          const ph = (t * (0.5 + i * 0.12) + i * 0.33) % 1;
          const y = H - ph * (H + 260);
          return R("line", { key: "st" + i, x1: 260 + i * 300, y1: y, x2: 260 + i * 300, y2: y + 70, stroke: rgba(theme.accent, 0.34 * (1 - ph)), strokeWidth: 3, strokeLinecap: "round" });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
