// SECOND SEASON — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-09.js, template "SecondSeason").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Chonburi / body Prompt. Camera set ["drop","pushR","hopU","zoomIn","pushL","zoomOut"].
// Entrances: title "slam", items "pop".
// Owns the Scroll:feed, Typing:hand, Ring:ring mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "second-season",
  label: "Second Season",

  // ---- type ----
  display: "Chonburi", displayFallback: "Georgia, serif",
  body: "Prompt", bodyFallback: "system-ui, sans-serif",
  mono: "IBM Plex Mono",
  chrome: false,
  devanagari: "Noto Serif Devanagari",
  maxScenes: 18,
  em: 0.62,
  titleLine: 1.02, titleSpace: "-0.01em",
  titlePreset: "slam", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ bg: t.bg || "#f0ebe6", surface: "#fcf9f6", rule: "#ccc3ba", inkMuted: "#6e675f", ink: "#16120f", accent: t.accent || "#e0673a", accent2: t.accent2 || "#3a6b7a", accentInk: "#fcf9f6" }),
  accents: ["accent","accent2","bg"],
  groundKey: "bg", inkKey: "ink", paperKey: "accentInk",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 100,
      "kicker": {
        "v": "pill",
        "bg": "accent",
        "c": "accentInk"
      }
    },
    "statement": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "accent2",
      "world": true,
      "top": 610,
      "size": 112
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 540,
      "size": 74,
      "bodySize": 38,
      "ch": 54,
      "lh": 1.54,
      "weight": 400,
      "dim": 0.9,
      "kicker": {
        "v": "bare",
        "c": "accent"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 360,
      "size": 84,
      "ch": 25,
      "lh": 1.08,
      "markSize": 220
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 255,
      "size": 84,
      "swap": "quote",
      "card": {
        "v": "tilt",
        "bg": "surface",
        "glow": "accent",
        "r": 14,
        "line": "inkMuted"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "accent",
          "accent2",
          "inkMuted"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 330,
      "size": 78,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 14,
        "h": 640,
        "labelSize": 42
      },
      "tilts": [
        -2,
        2,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 390,
      "size": 80,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 148,
      "rule": true
    },
    "cta": {
      "bg": "ink",
      "fg": "surface",
      "hi": "accent2",
      "world": true,
      "top": 470,
      "size": 94,
      "align": "left",
      "btn": {
        "v": "pill",
        "bg": "accent",
        "c": "accentInk"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["drop","pushR","hopU","zoomIn","pushL","zoomOut"], camMul: 3, camOff: 5,
  mag: {"rot":0.7,"driftX":8,"driftY":8,"driftZ":0.045,"slide":0.28,"inn":0.18,"zin":0.36,"zout":0.32},
  ambient: 1.7,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"feed","Typing":"hand","Ring":"ring"},

  strings: {
    brandName: "Second Season",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.4, strokeLinecap: "round", strokeLinejoin: "round" }, R2("path", { d: "M3 9l2-5h14l2 5zM3 9c2 3 4 3 6 0 2 3 4 3 6 0 2 3 4 3 6 0M6 9v11h12V9" })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "linear-gradient(180deg, " + rgba(theme.surface, 0.94) + " 0%, " + bg + " 44%, " + rgba(theme.accent, 0.16) + " 100%)"),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, E = u.ease, inv = theme.currentBg !== theme.bg;
      const tint = inv ? theme.surface : theme.inkMuted, ground = H - 280;
      const cyc = (t % 12) / 12, tri = cyc < 0.5 ? cyc * 2 : 2 - cyc * 2;
      const out = E.inOut(tri);
      const reach = 110 + out * 250;
      const crank = out * 900;
      return R("g", null,
        R("defs", null,
          R("pattern", { id: "ss-stripe", width: 84, height: 84, patternUnits: "userSpaceOnUse" },
            R("rect", { x: 0, y: 0, width: 42, height: 84, fill: rgba(theme.accent, 0.5) }),
            R("rect", { x: 42, y: 0, width: 42, height: 84, fill: rgba(theme.surface, 0.85) }))),
        /* overhead: bunting and a signboard */
        R("g", null,
          R("path", { d: "M -20 60 q " + (W / 2) + " " + (74 + Math.sin(t * 0.7) * 10).toFixed(1) + " " + (W + 40) + " 10", fill: "none", stroke: rgba(tint, 0.5), strokeWidth: 4 }),
          Array.from({ length: 10 }).map((_, i) => {
            const bx = 50 + i * ((W - 100) / 9);
            const by = 60 + Math.sin((i / 9) * Math.PI) * (62 + Math.sin(t * 0.7) * 8) - (i / 9) * 50;
            return R("path", { key: "bt" + i, d: "M -20 0 h 40 l -20 42 z", fill: rgba(i % 3 === 0 ? theme.accent : (i % 3 === 1 ? theme.accent2 : tint), 0.6), transform: "translate(" + bx.toFixed(1) + "," + by.toFixed(1) + ") rotate(" + (Math.sin(t * 1.4 + i * 0.6) * 5).toFixed(2) + ")" });
          })),
        R("g", { transform: "translate(" + (W - 250) + ",200) rotate(" + (Math.sin(t * 0.8) * 1.4).toFixed(2) + ")" },
          R("rect", { x: -110, y: 0, width: 220, height: 76, rx: 8, fill: rgba(theme.accent2, 0.6), stroke: rgba(tint, 0.4), strokeWidth: 4 }),
          R("rect", { x: -84, y: 22, width: 130, height: 12, rx: 6, fill: rgba(theme.surface, 0.7) }),
          R("rect", { x: -84, y: 46, width: 84, height: 10, rx: 5, fill: rgba(theme.surface, 0.45) })),
        /* mid: the awning, its crank and the shadow it throws */
        R("g", { transform: "translate(" + (W - 72) + ",1400) scale(1.16)" },
          R("rect", { x: -40, y: -40, width: 80, height: 26, rx: 6, fill: rgba(tint, 0.6) }),
          R("path", { d: "M 0 -14 h -" + reach.toFixed(0) + " l 30 96 h " + (reach - 60).toFixed(0) + " z", fill: "url(#ss-stripe)", stroke: rgba(tint, 0.35), strokeWidth: 4 }),
          R("path", { d: "M " + (-reach + 30).toFixed(0) + " 82 " + Array.from({ length: 8 }).map((_, i) => "q 18 " + (16 + Math.sin(t * 2 + i) * 7).toFixed(1) + " 36 0").join(" "), fill: "none", stroke: rgba(theme.accent, 0.8), strokeWidth: 10 }),
          R("line", { x1: 0, y1: -14, x2: (-reach + 24).toFixed(0), y2: 60, stroke: rgba(tint, 0.4), strokeWidth: 4 }),
          R("g", { transform: "translate(-24,150) rotate(" + crank.toFixed(1) + ")" },
            R("circle", { r: 22, fill: "none", stroke: rgba(theme.accent2, 0.8), strokeWidth: 6 }),
            R("path", { d: "M 0 0 h 22", stroke: rgba(theme.accent2, 0.7), strokeWidth: 6 }),
            R("circle", { cx: 22, cy: 0, r: 7, fill: rgba(theme.accent, 0.9) })),
          R("path", { d: "M 0 " + (ground - 1090) + " h -" + (reach * 0.9).toFixed(0) + " l -60 40 h " + (reach * 0.9 + 60).toFixed(0) + " z", fill: rgba(theme.ink, 0.08) })),
        /* a neighbouring stall behind, drifting on parallax */
        R("g", { opacity: 0.34, transform: "translate(" + (-((t * 6) % 320)).toFixed(1) + ",0)" },
          [0, 1, 2].map((i) => R("g", { key: "ns" + i },
            R("path", { d: "M " + (60 + i * 320) + " " + (ground - 210) + " h 240 l -20 44 h -200 z", fill: rgba(theme.accent2, 0.5) }),
            R("path", { d: "M " + (80 + i * 320) + " " + (ground - 166) + " v 166 M " + (280 + i * 320) + " " + (ground - 166) + " v 166", stroke: rgba(tint, 0.5), strokeWidth: 6 }),
            R("rect", { x: 96 + i * 320, y: ground - 96, width: 170, height: 14, rx: 4, fill: rgba(tint, 0.45) })))),
        /* a string of garlic hung along the frame */
        R("g", { transform: "translate(0,286)" },
          R("path", { d: "M 40 0 q " + (W / 2 - 40) + " " + (34 + Math.sin(t * 0.8) * 6).toFixed(1) + " " + (W - 80) + " 0", fill: "none", stroke: rgba(tint, 0.45), strokeWidth: 4 }),
          [0, 1, 2, 3, 4, 5, 6, 7].map((i) => {
            const gx = 80 + i * ((W - 160) / 7);
            const gy = Math.sin((i / 7) * Math.PI) * (28 + Math.sin(t * 0.8) * 5);
            return R("g", { key: "gl" + i, transform: "translate(" + gx.toFixed(1) + "," + gy.toFixed(1) + ") rotate(" + (Math.sin(t * 1.2 + i * 0.7) * 4).toFixed(2) + ")" },
              R("ellipse", { cx: 0, cy: 40, rx: 28, ry: 36, fill: rgba(theme.surface, 0.92), stroke: rgba(tint, 0.5), strokeWidth: 4 }),
              R("path", { d: "M -14 30 q 14 -18 28 0", fill: "none", stroke: rgba(tint, 0.35), strokeWidth: 3 }),
              R("path", { d: "M 0 6 v -22", stroke: rgba(theme.accent2, 0.8), strokeWidth: 5 }));
          })),
        /* a barrow wheeled past the front of the stall */
        (function () {
          const bx = ((t * 34) % (W + 560)) - 280;
          const wl = (bx / 26) * 57.3;
          return R("g", { opacity: 0.7, transform: "translate(" + bx.toFixed(1) + "," + (H - 96) + ")" },
            R("path", { d: "M -110 -60 h 220 l -26 60 h -168 z", fill: rgba(theme.accent2, 0.5), stroke: rgba(tint, 0.45), strokeWidth: 4 }),
            R("path", { d: "M 110 -60 l 76 -34", stroke: rgba(tint, 0.55), strokeWidth: 8, strokeLinecap: "round" }),
            [0, 1, 2].map((i) => R("circle", { key: "pr" + i, cx: -60 + i * 54, cy: -76, r: 20, fill: rgba(i % 2 ? theme.accent : theme.accent2, 0.7) })),
            R("g", { transform: "translate(-70,0) rotate(" + wl.toFixed(1) + ")" },
              R("circle", { r: 26, fill: "none", stroke: rgba(tint, 0.6), strokeWidth: 6 }),
              R("path", { d: "M -26 0 h 52", stroke: rgba(tint, 0.5), strokeWidth: 5 })));
        })(),
        /* a sack of produce and a cat under the trestle */
        R("g", { transform: "translate(" + (W * 0.82) + "," + (ground + 60) + ")" },
          R("path", { d: "M -50 0 q -14 -90 20 -110 q 30 -18 60 4 q 30 22 16 106 z", fill: rgba(theme.accent2, 0.42), stroke: rgba(tint, 0.45), strokeWidth: 4 }),
          R("path", { d: "M -14 -108 q 20 -20 44 -2", fill: "none", stroke: rgba(tint, 0.4), strokeWidth: 5 })),
        R("g", { opacity: 0.6, transform: "translate(" + (W * 0.2) + "," + (H - 52) + ") scale(1," + (1 + Math.sin(t * 0.9) * 0.03).toFixed(3) + ")" },
          R("path", { d: "M -56 0 q -8 -42 28 -50 q 40 -8 58 18 q 12 20 -4 32 z", fill: rgba(tint, 0.6) }),
          R("path", { d: "M 20 -32 l 6 -16 l 11 12 z", fill: rgba(tint, 0.6) }),
          R("path", { d: "M -56 0 q -28 -12 -36 4 q 16 8 36 -4 z", fill: rgba(tint, 0.5) })),
        /* floor: crates, scales, a chalk board */
        R("line", { x1: 0, y1: ground, x2: W, y2: ground, stroke: rgba(tint, 0.55), strokeWidth: 8 }),
        R("rect", { x: 0, y: ground, width: W, height: H - ground, fill: rgba(theme.rule, 0.34) }),
        [0, 1, 2].map((i) => R("g", { key: "cr" + i, transform: "translate(" + (150 + i * 200) + "," + (ground + 40) + ") rotate(" + (-2 + i * 2) + ")" },
          R("path", { d: "M -74 0 h 148 v -84 h -148 z", fill: "none", stroke: rgba(tint, 0.55), strokeWidth: 5 }),
          R("path", { d: "M -74 -42 h 148", stroke: rgba(tint, 0.35), strokeWidth: 4 }),
          [0, 1, 2, 3].map((j) => R("circle", { key: "fr" + j, cx: -50 + j * 34, cy: -96 - (j % 2) * 14, r: 20, fill: rgba(j % 2 ? theme.accent : theme.accent2, 0.6) })))),
        R("g", { transform: "translate(" + (W * 0.62) + "," + (ground + 30) + ")" },
          R("path", { d: "M -50 0 h 100 l -12 -40 h -76 z", fill: rgba(tint, 0.55) }),
          R("line", { x1: 0, y1: -40, x2: 0, y2: -140, stroke: rgba(tint, 0.6), strokeWidth: 7 }),
          R("g", { transform: "rotate(" + (Math.sin(t * 1.1) * 7).toFixed(2) + " 0 -140)" },
            R("line", { x1: -84, y1: -140, x2: 84, y2: -140, stroke: rgba(theme.accent2, 0.85), strokeWidth: 8, strokeLinecap: "round" }),
            [-84, 84].map((sx, i) => R("g", { key: "pn" + i, transform: "translate(" + sx + ",-140)" },
              R("line", { x1: 0, y1: 0, x2: 0, y2: 40, stroke: rgba(tint, 0.5), strokeWidth: 3 }),
              R("path", { d: "M -34 40 q 34 26 68 0 z", fill: rgba(theme.accent, i ? 0.6 : 0.4), stroke: rgba(tint, 0.45), strokeWidth: 3 }))))),
        R("g", { opacity: 0.85, transform: "translate(" + (W - 220) + "," + (H - 110) + ") rotate(-3)" },
          R("rect", { x: -100, y: -110, width: 200, height: 220, rx: 6, fill: rgba(theme.ink, 0.82), stroke: rgba(theme.accent, 0.5), strokeWidth: 6 }),
          [0, 1, 2, 3].map((i) => R("line", { key: "ch" + i, x1: -74, y1: -66 + i * 50, x2: 30 + (i % 2) * 40, y2: -66 + i * 50, stroke: rgba(theme.surface, 0.62 - i * 0.08), strokeWidth: 6, strokeLinecap: "round" }))),
        [0, 1, 2, 3, 4].map((i) => {
          const lc = ((t / (7 + i * 1.2)) % 1);
          const lx = 120 + i * 210 + Math.sin(lc * Math.PI * 6 + i) * 110;
          return R("path", { key: "lf" + i, d: "M 0 0 q 24 -20 42 4 q -20 24 -42 -4 z", fill: rgba(i % 2 ? theme.accent2 : theme.accent, 0.45), transform: "translate(" + lx.toFixed(1) + "," + (-60 + lc * (H + 120)).toFixed(1) + ") rotate(" + (lc * 800 + i * 60).toFixed(1) + ")" });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
