// SLOW READER — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-02.js, template "SlowReader").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Vollkorn / body Alegreya Sans. Camera set ["zoomOut","drop","pushL","zoomIn","pushD","pushR"].
// Entrances: title "drowse", items "rise".
// Owns the Typing:typewriter, Scroll:feed, Ring:gauge mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "slow-reader",
  label: "Slow Reader",

  // ---- type ----
  display: "Vollkorn", displayFallback: "Georgia, serif",
  body: "Alegreya Sans", bodyFallback: "system-ui, sans-serif",
  mono: "IBM Plex Mono",
  chrome: false,
  devanagari: "Noto Serif Devanagari",
  maxScenes: 18,
  em: 0.52,
  titleLine: 1.08, titleSpace: "-0.01em",
  titlePreset: "drowse", itemPreset: "rise",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({
      bg: t.bg || "#191410", surface: "#241d17", rule: "#3d322a", inkMuted: "#9a8b7c",
      ink: "#f3ece1", accent: t.accent || "#d8a24e", accent2: t.accent2 || "#8fa07a", accentInk: "#171208",
    }),
  accents: ["accent","accent2","surface"],
  groundKey: "bg", inkKey: "accentInk", paperKey: "ink",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 310,
      "size": 118,
      "kicker": {
        "v": "bare",
        "c": "accent"
      }
    },
    "statement": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 610,
      "size": 130
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 540,
      "size": 84,
      "bodySize": 39,
      "ch": 54,
      "lh": 1.58,
      "weight": 400,
      "dim": 0.92,
      "kicker": {
        "v": "bare",
        "c": "accent2"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 360,
      "size": 94,
      "ch": 25,
      "lh": 1.18,
      "markSize": 230
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 255,
      "size": 98,
      "swap": "body",
      "card": {
        "v": "glow",
        "bg": "surface",
        "glow": "accent",
        "r": 16,
        "line": "inkMuted"
      },
      "chips": {
        "v": "outline",
        "colors": [
          "accent",
          "accent2",
          "ink"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 330,
      "size": 88,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 16,
        "h": 640,
        "labelSize": 42
      },
      "tilts": [
        -1,
        1,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 390,
      "size": 90,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 148,
      "glowNums": true
    },
    "cta": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "surface",
      "world": true,
      "top": 470,
      "size": 110,
      "align": "left",
      "btn": {
        "v": "pill",
        "bg": "accentInk",
        "c": "ink"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["zoomOut","drop","pushL","zoomIn","pushD","pushR"], camMul: 5, camOff: 3,
  mag: {"rot":0.3,"driftX":5,"driftY":8,"driftZ":0.05,"slide":0.18,"inn":0.26,"zin":0.28,"zout":0.3},
  ambient: 1.3,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Typing":"typewriter","Scroll":"feed","Ring":"gauge"},

  strings: {
    brandName: "Slow Reader",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.2, strokeLinecap: "round", strokeLinejoin: "round" },
      R2("circle", { cx: 12, cy: 13, r: 8 }), R2("path", { d: "M12 9v4l3 2M12 5V3" })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "radial-gradient(80% 60% at 22% 10%, " + rgba(theme.accent, 0.22) + " 0%, transparent 64%), " + bg),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, onAccent = theme.currentBg === theme.accent;
      const tint = onAccent ? theme.accentInk : theme.inkMuted;
      const swing = Math.sin(t * (Math.PI * 2 / 4)) * 5.5;
      const anchorX = W - 78, chain = 1120;
      const sec = Math.floor(t) % 60;
      return R("g", null,
        R("defs", null,
          R("pattern", { id: "sr-weave", width: 40, height: 40, patternUnits: "userSpaceOnUse" },
            R("path", { d: "M0 20h40M20 0v40", stroke: rgba(theme.rule, onAccent ? 0.3 : 0.75), strokeWidth: 1.5 })),
          R("linearGradient", { id: "sr-ray", x1: "0%", y1: "0%", x2: "60%", y2: "100%" },
            R("stop", { offset: "0%", stopColor: rgba(theme.accent, 0.26) }),
            R("stop", { offset: "100%", stopColor: rgba(theme.accent, 0) }))),
        R("rect", { x: 0, y: 0, width: W, height: H, fill: "url(#sr-weave)" }),
        /* the window the light is coming from */
        R("g", { opacity: 0.55 },
          R("rect", { x: 60, y: -40, width: 430, height: 268, rx: 6, fill: rgba(theme.accent, 0.14), stroke: rgba(tint, 0.5), strokeWidth: 6 }),
          R("line", { x1: 275, y1: -40, x2: 275, y2: 228, stroke: rgba(tint, 0.45), strokeWidth: 5 }),
          R("line", { x1: 60, y1: 110, x2: 490, y2: 110, stroke: rgba(tint, 0.45), strokeWidth: 5 }),
          R("rect", { x: 40, y: 228, width: 470, height: 18, rx: 4, fill: rgba(tint, 0.6) })),
        /* a curtain in the left margin, breathing */
        R("path", { d: "M 0 -20 q " + (34 + Math.sin(t * 0.6) * 12).toFixed(1) + " 300 " + (10 + Math.sin(t * 0.5) * 8).toFixed(1) + " 620 q " + (-24 + Math.cos(t * 0.7) * 10).toFixed(1) + " 320 14 700 L 0 " + H + " Z", fill: rgba(theme.accent2, 0.16), stroke: rgba(tint, 0.22), strokeWidth: 3 }),
        /* window rays */
        R("path", { d: "M -40 0 L 300 0 L 760 " + H + " L -40 " + H + " Z", fill: "url(#sr-ray)", opacity: 0.8 + 0.2 * Math.sin(t * 0.4) }),
        R("path", { d: "M 340 0 L 470 0 L 900 " + H + " L 640 " + H + " Z", fill: "url(#sr-ray)", opacity: 0.5 + 0.2 * Math.cos(t * 0.5) }),
        /* shelf and books, low */
        R("g", { opacity: 0.5 },
          R("line", { x1: 0, y1: H - 210, x2: W, y2: H - 210, stroke: rgba(tint, 0.5), strokeWidth: 6 }),
          [0, 1, 2, 3, 4, 5].map((i) => R("rect", { key: "bk" + i, x: 70 + i * 122 + (i % 3) * 10, y: H - 210 - (86 + (i % 4) * 30), width: 30 + (i % 3) * 12, height: 86 + (i % 4) * 30, rx: 3, fill: rgba(tint, 0.3 + (i % 3) * 0.06) })),
          R("rect", { x: W - 300, y: H - 262, width: 190, height: 52, rx: 5, fill: rgba(theme.accent2, 0.35) })),
        /* the watch on its chain */
        R("g", { transform: "translate(" + anchorX + ",-40) rotate(" + swing.toFixed(2) + ")" },
          Array.from({ length: 16 }).map((_, i) => R("circle", { key: "ch" + i, cx: 0, cy: 60 + i * ((chain - 60) / 16), r: 7, fill: "none", stroke: rgba(tint, 0.5), strokeWidth: 3 })),
          R("g", { transform: "translate(0," + chain + ")" },
            R("circle", { r: 84, fill: rgba(theme.surface, onAccent ? 0.5 : 0.96), stroke: rgba(theme.accent, 0.85), strokeWidth: 7 }),
            R("circle", { r: 66, fill: "none", stroke: rgba(tint, 0.35), strokeWidth: 3 }),
            Array.from({ length: 12 }).map((_, i) => R("line", { key: "mk" + i, x1: Math.cos(i * Math.PI / 6) * 68, y1: Math.sin(i * Math.PI / 6) * 68, x2: Math.cos(i * Math.PI / 6) * 80, y2: Math.sin(i * Math.PI / 6) * 80, stroke: rgba(tint, 0.55), strokeWidth: 4 })),
            R("line", { x1: 0, y1: 0, x2: Math.cos((t * 0.03) * Math.PI * 2 - Math.PI / 2) * 44, y2: Math.sin((t * 0.03) * Math.PI * 2 - Math.PI / 2) * 44, stroke: rgba(tint, 0.9), strokeWidth: 7, strokeLinecap: "round" }),
            R("line", { x1: 0, y1: 0, x2: Math.cos((sec / 60) * Math.PI * 2 - Math.PI / 2) * 72, y2: Math.sin((sec / 60) * Math.PI * 2 - Math.PI / 2) * 72, stroke: rgba(theme.accent2, 0.95), strokeWidth: 4, strokeLinecap: "round" }),
            R("circle", { r: 8, fill: rgba(theme.accent, 0.95) }),
            R("path", { d: "M -18 -104 h 36 l -6 -22 h -24 z", fill: rgba(theme.accent, 0.9) }))),
        /* the desk, and what is on it */
        R("line", { x1: -20, y1: 1420, x2: 720, y2: 1420, stroke: rgba(tint, 0.5), strokeWidth: 7, strokeLinecap: "round" }),
        R("rect", { x: -20, y: 1420, width: 740, height: 22, fill: rgba(tint, 0.28) }),
        /* a cup, with steam that keeps rising */
        R("g", { transform: "translate(258,1420) scale(1.28)" },
          R("path", { d: "M -52 -74 h 104 l -10 74 h -84 z", fill: rgba(theme.surface, onAccent ? 0.5 : 0.92), stroke: rgba(tint, 0.5), strokeWidth: 4 }),
          R("path", { d: "M 52 -60 q 40 6 34 30 q -6 22 -38 20", fill: "none", stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          R("path", { d: "M -52 -74 h 104 l -4 -14 h -96 z", fill: rgba(theme.accent, 0.5) }),
          [0, 1, 2].map((i) => {
            const ph = ((t * 0.42 + i * 0.34) % 1);
            const sw = Math.sin(t * 1.4 + i * 2) * 18;
            return R("path", { key: "sm" + i, d: "M " + (-22 + i * 22) + " -92 q " + sw.toFixed(1) + " -60 " + (sw * 0.4).toFixed(1) + " -120 q " + (-sw).toFixed(1) + " -56 0 -110", fill: "none", stroke: rgba(onAccent ? theme.accentInk : theme.ink, 0.26 * (1 - ph)), strokeWidth: 7, strokeLinecap: "round", transform: "translate(0," + (-ph * 150).toFixed(1) + ") scale(1," + (0.7 + ph * 0.5).toFixed(2) + ")" });
          })),
        /* inkwell, pen, and a candle that flickers */
        R("g", { transform: "translate(500,1420) scale(1.2)" },
          R("path", { d: "M -40 0 h 80 l -8 -62 h -64 z", fill: rgba(theme.ink, 0.85), stroke: rgba(tint, 0.4), strokeWidth: 3 }),
          R("path", { d: "M 10 -62 l 96 -150 l 16 12 l -92 150 z", fill: rgba(theme.accent2, 0.75) }),
          R("path", { d: "M 106 -212 l 16 12 l 8 -26 z", fill: rgba(tint, 0.7) })),
        R("g", { transform: "translate(104,1420) scale(1.2)" },
          R("rect", { x: -22, y: -104, width: 44, height: 104, rx: 5, fill: rgba(theme.surface, onAccent ? 0.5 : 0.9), stroke: rgba(tint, 0.45), strokeWidth: 3 }),
          R("path", { d: "M 0 -104 q " + (Math.sin(t * 6) * 7).toFixed(1) + " -26 0 -46 q " + (-Math.sin(t * 6) * 7).toFixed(1) + " 20 0 46", fill: rgba(theme.accent, 0.85 + 0.15 * Math.sin(t * 9)) }),
          R("circle", { cx: 0, cy: -126, r: 44 + Math.sin(t * 5) * 5, fill: rgba(theme.accent, 0.12) })),
        /* motes */
        [0, 1, 2, 3, 4, 5, 6, 7, 8].map((i) => {
          const ph = (t * (0.07 + i * 0.014) + i * 0.12) % 1;
          return R("circle", { key: "mo" + i, cx: 100 + i * 108 + Math.sin(t * 0.5 + i) * 40, cy: H - ph * (H + 120), r: 3 + (i % 3) * 2, fill: rgba(theme.accent, 0.34 * (1 - ph)) });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
