// SLOW SUNDAY — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-05.js, template "SlowSunday").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Grandstander / body Sen. Camera set ["drop","zoomOut","pushL","hopU","zoomIn","pushR"].
// Entrances: title "bounce", items "pop".
// Owns the Scroll:feed, Typing:caret, Ring:ring mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "slow-sunday",
  label: "Slow Sunday",

  // ---- type ----
  display: "Grandstander", displayFallback: "system-ui, sans-serif",
  body: "Sen", bodyFallback: "system-ui, sans-serif",
  mono: "IBM Plex Mono",
  chrome: false,
  devanagari: "Noto Sans Devanagari",
  maxScenes: 18,
  em: 0.62,
  titleLine: 1.04, titleSpace: "-0.01em",
  titlePreset: "bounce", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({
      bg: t.bg || "#f1e7e6", surface: "#fbf6f5", rule: "#d6c5c3", inkMuted: "#726466",
      ink: "#1b1517", accent: t.accent || "#8a4a6a", accent2: t.accent2 || "#d8a13c", accentInk: "#fbf6f5",
    }),
  accents: ["accent2","accent","bg"],
  groundKey: "bg", inkKey: "ink", paperKey: "accentInk",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 112,
      "kicker": {
        "v": "pill",
        "bg": "accent",
        "c": "accentInk"
      }
    },
    "statement": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "accent2",
      "world": true,
      "top": 610,
      "size": 124
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 540,
      "size": 88,
      "bodySize": 38,
      "ch": 54,
      "lh": 1.54,
      "weight": 400,
      "dim": 0.9,
      "kicker": {
        "v": "bare",
        "c": "accent"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 360,
      "size": 96,
      "ch": 26,
      "lh": 1.12,
      "markSize": 230
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 255,
      "size": 96,
      "swap": "body",
      "card": {
        "v": "tilt",
        "bg": "surface",
        "r": 18,
        "line": "inkMuted"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "accent",
          "accent2",
          "inkMuted"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 330,
      "size": 90,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 18,
        "h": 640,
        "labelSize": 46
      },
      "tilts": [
        -1.5,
        1.5,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 390,
      "size": 92,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 148
    },
    "cta": {
      "bg": "ink",
      "fg": "surface",
      "hi": "accent2",
      "world": true,
      "top": 470,
      "size": 108,
      "align": "left",
      "btn": {
        "v": "pill",
        "bg": "accent2",
        "c": "ink"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["drop","zoomOut","pushL","hopU","zoomIn","pushR"], camMul: 5, camOff: 5,
  mag: {"rot":0.6,"driftX":7,"driftY":8,"driftZ":0.045,"slide":0.22,"inn":0.22,"zin":0.34,"zout":0.3},
  ambient: 1.45,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"feed","Typing":"caret","Ring":"ring"},

  strings: {
    brandName: "Slow Sunday",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.4, strokeLinecap: "round" },
      R2("circle", { cx: 12, cy: 12, r: 9 }), R2("circle", { cx: 12, cy: 12, r: 2.5 })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "linear-gradient(178deg, " + rgba(theme.accent2, 0.16) + " 0%, " + rgba(theme.surface, 0.9) + " 30%, " + bg + " 64%, " + rgba(theme.rule, 0.44) + " 100%)"),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, inv = theme.currentBg !== theme.bg;
      const tint = inv ? theme.surface : theme.inkMuted;
      const board = H - 300;
      const spin = (t * 200) % 360;
      const side = (t % 40) / 40;
      const arm = -18 + side * 24;
      return R("g", null,
        R("defs", null,
          R("pattern", { id: "ss2-blind", width: 12, height: 44, patternUnits: "userSpaceOnUse" },
            R("rect", { x: 0, y: 0, width: 12, height: 28, fill: rgba(theme.rule, inv ? 0.14 : 0.5) })),
          R("linearGradient", { id: "ss2-beam", x1: "0%", y1: "0%", x2: "70%", y2: "100%" },
            R("stop", { offset: "0%", stopColor: rgba(theme.accent2, 0.24) }),
            R("stop", { offset: "100%", stopColor: rgba(theme.accent2, 0) }))),
        /* blinds and the beam they cut */
        R("rect", { x: 0, y: 0, width: W, height: 270, fill: "url(#ss2-blind)" }),
        R("rect", { x: 0, y: 264, width: W, height: 14, fill: rgba(tint, 0.5) }),
        /* a shelf above the blinds line: records, a clock, a plant */
        R("g", { opacity: 0.7 },
          R("rect", { x: 60, y: 210, width: W - 120, height: 16, rx: 5, fill: rgba(tint, 0.6) }),
          [0, 1, 2, 3, 4, 5, 6].map((i) => R("rect", { key: "sv" + i, x: 100 + i * 96 + (i % 3) * 8, y: 210 - (86 + (i % 3) * 22), width: 22 + (i % 2) * 8, height: 86 + (i % 3) * 22, rx: 3, fill: rgba(i % 3 === 0 ? theme.accent : (i % 3 === 1 ? theme.accent2 : tint), 0.5) })),
          R("g", { transform: "translate(" + (W - 190) + ",150)" },
            R("circle", { r: 56, fill: rgba(theme.surface, 0.85), stroke: rgba(tint, 0.55), strokeWidth: 5 }),
            R("line", { x1: 0, y1: 0, x2: Math.cos(t * 0.1 - 1.57) * 26, y2: Math.sin(t * 0.1 - 1.57) * 26, stroke: rgba(tint, 0.8), strokeWidth: 6, strokeLinecap: "round" }),
            R("line", { x1: 0, y1: 0, x2: Math.cos(t * 1.05 - 1.57) * 42, y2: Math.sin(t * 1.05 - 1.57) * 42, stroke: rgba(theme.accent, 0.9), strokeWidth: 4, strokeLinecap: "round" }))),
        R("path", { d: "M 60 278 L 420 278 L 800 " + H + " L -120 " + H + " Z", fill: "url(#ss2-beam)" }),
        /* a framed print on the wall, in the margin */
        R("g", { transform: "translate(" + (W - 150) + ",1100) rotate(" + (Math.sin(t * 0.5) * 1).toFixed(2) + ")" },
          R("rect", { x: -104, y: -120, width: 208, height: 260, rx: 5, fill: rgba(theme.surface, 0.7), stroke: rgba(tint, 0.55), strokeWidth: 6 }),
          R("circle", { cx: -20, cy: -20, r: 52, fill: rgba(theme.accent, 0.45) }),
          R("path", { d: "M -80 100 q 60 -110 96 -30 q 24 -50 64 30 z", fill: rgba(theme.accent2, 0.5) })),
        /* the sideboard */
        R("line", { x1: 0, y1: board, x2: W, y2: board, stroke: rgba(tint, 0.55), strokeWidth: 8 }),
        R("rect", { x: 0, y: board, width: W, height: H - board, fill: rgba(theme.rule, 0.34) }),
        /* the record player */
        R("g", { transform: "translate(" + (W * 0.42) + "," + (board - 10) + ")" },
          R("rect", { x: -230, y: -190, width: 460, height: 190, rx: 12, fill: rgba(theme.surface, inv ? 0.4 : 0.95), stroke: rgba(tint, 0.5), strokeWidth: 4 }),
          R("g", { transform: "translate(-60,-96)" },
            R("circle", { r: 116, fill: rgba(theme.ink, 0.86) }),
            R("g", { transform: "rotate(" + spin.toFixed(1) + ")" },
              [0, 1, 2, 3, 4].map((i) => R("circle", { key: "gv" + i, r: 34 + i * 18, fill: "none", stroke: rgba(theme.surface, 0.16), strokeWidth: 2 })),
              R("circle", { r: 40, fill: rgba(theme.accent, 0.9) }),
              R("circle", { r: 6, fill: rgba(theme.surface, 0.9) }),
              R("rect", { x: -2, y: -116, width: 4, height: 30, fill: rgba(theme.accent2, 0.7) }))),
          R("g", { transform: "translate(96,-150) rotate(" + arm.toFixed(2) + ")" },
            R("circle", { r: 22, fill: rgba(tint, 0.6) }),
            R("path", { d: "M 0 0 L -150 66", stroke: rgba(tint, 0.75), strokeWidth: 9, strokeLinecap: "round" }),
            R("path", { d: "M -150 66 l -22 16 l 6 12 l 24 -14 z", fill: rgba(theme.accent, 0.9) })),
          R("rect", { x: 150, y: -46, width: 60, height: 14, rx: 7, fill: rgba(theme.accent2, 0.7) }),
          R("circle", { cx: 190, cy: -80, r: 12, fill: rgba(theme.accent, 0.85) })),
        /* the sleeve leaning, a stack of records, a plant */
        R("g", { transform: "translate(200," + (board - 6) + ") rotate(-8)" },
          R("rect", { x: -110, y: -220, width: 220, height: 220, rx: 4, fill: rgba(theme.accent2, 0.4), stroke: rgba(tint, 0.45), strokeWidth: 4 }),
          R("circle", { cx: 0, cy: -110, r: 70, fill: rgba(theme.accent, 0.5) }),
          R("circle", { cx: 0, cy: -110, r: 16, fill: rgba(theme.surface, 0.8) })),
        R("g", { transform: "translate(" + (W - 300) + "," + board + ")" },
          [0, 1, 2, 3, 4].map((i) => R("rect", { key: "rc" + i, x: -100 + (i % 2) * 8, y: -16 - i * 14, width: 200 - (i % 2) * 14, height: 12, rx: 3, fill: rgba(i % 2 ? theme.accent : theme.accent2, 0.5), stroke: rgba(tint, 0.3), strokeWidth: 2 }))),
        R("g", { transform: "translate(" + (W - 120) + "," + (board - 4) + ")" },
          R("path", { d: "M -44 0 h 88 l -10 -70 h -68 z", fill: rgba(theme.accent, 0.5), stroke: rgba(tint, 0.4), strokeWidth: 3 }),
          [0, 1, 2].map((i) => R("path", { key: "lf" + i, d: "M 0 -70 q " + (-50 + i * 50 + Math.sin(t * 0.7 + i) * 8).toFixed(1) + " -46 " + (-24 + i * 24).toFixed(1) + " -104", fill: "none", stroke: rgba(theme.accent2, 0.7), strokeWidth: 7, strokeLinecap: "round" }))),
        /* a lamp in the corner, and the sofa in the foreground */
        R("g", { transform: "translate(" + (W - 150) + "," + (board - 6) + ")" },
          R("path", { d: "M -40 0 h 80 l -14 -40 h -52 z", fill: rgba(tint, 0.55) }),
          R("line", { x1: 0, y1: -40, x2: 0, y2: -230, stroke: rgba(tint, 0.5), strokeWidth: 7 }),
          R("path", { d: "M -76 -230 h 152 l -26 -96 h -100 z", fill: rgba(theme.accent2, 0.55), stroke: rgba(tint, 0.4), strokeWidth: 4 }),
          R("circle", { cx: 0, cy: -206, r: 24 + Math.sin(t * 1.4) * 3, fill: rgba(theme.accent2, 0.4) })),
        R("g", null,
          R("path", { d: "M -60 " + H + " v -250 q 0 -70 90 -70 h 250 q 90 0 90 70 v 250 z", fill: rgba(theme.accent, 0.28), stroke: rgba(tint, 0.35), strokeWidth: 4 }),
          R("path", { d: "M 20 " + (H - 250) + " h 260", stroke: rgba(tint, 0.28), strokeWidth: 4 }),
          R("path", { d: "M 300 " + (H - 268) + " q " + (46 + Math.sin(t * 1.5) * 30).toFixed(1) + " -70 " + (10 + Math.sin(t * 1.5) * 46).toFixed(1) + " -130", fill: "none", stroke: rgba(tint, 0.6), strokeWidth: 16, strokeLinecap: "round" })),
        R("ellipse", { cx: W * 0.62, cy: H - 90, rx: 330, ry: 60, fill: rgba(theme.accent2, 0.18) }),
        R("ellipse", { cx: W * 0.62, cy: H - 90, rx: 250, ry: 42, fill: "none", stroke: rgba(theme.accent, 0.24), strokeWidth: 6 }),
        /* dust in the beam */
        [0, 1, 2, 3, 4, 5, 6, 7].map((i) => {
          const ph = (t * (0.09 + i * 0.02) + i * 0.13) % 1;
          return R("circle", { key: "dt" + i, cx: 120 + i * 90 + Math.sin(t * 0.6 + i) * 34, cy: H - ph * (H + 140), r: 3 + (i % 3) * 2, fill: rgba(theme.accent2, 0.34 * (1 - ph)) });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
