// SNOW PEAK — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/world-pack-1.js, template "SnowPeak").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Fjalla One / body Hind. Camera set ["drop","pushR","zoomOut","pushL","hopU","zoomIn"].
// Entrances: title "rise", items "pop".
// Owns the Toggle:check, Ring:ring, DragDrop:drag, Morph:roll mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "snow-peak",
  label: "Snow Peak",

  // ---- type ----
  display: "Fjalla One", displayFallback: "sans-serif",
  body: "Hind", bodyFallback: "sans-serif",
  mono: null,
  em: 0.5,
  titleLine: 1.04, titleSpace: "0",
  titlePreset: "rise", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ ice: t.ice || "#dfeef7", pine: t.pine || "#2c4a5a", deep: "#1d3440", snow: "#ffffff", coral: "#e0685c", ink: "#20313b" }),
  accents: ["coral","ice","pine"],
  groundKey: "ice", inkKey: "ink", paperKey: "snow",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "ice",
      "fg": "ink",
      "hi": "coral",
      "world": true,
      "top": 300,
      "size": 128,
      "kicker": {
        "v": "pill",
        "bg": "ink",
        "c": "snow"
      }
    },
    "statement": {
      "bg": "pine",
      "fg": "snow",
      "hi": "ice",
      "world": false,
      "top": 630,
      "size": 154
    },
    "feature": {
      "bg": "ice",
      "fg": "ink",
      "hi": "coral",
      "world": true,
      "top": 246,
      "size": 100,
      "card": {
        "v": "frame",
        "bg": "deep",
        "r": 22,
        "line": "snow"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "coral",
          "pine"
        ],
        "text": "snow"
      }
    },
    "montage": {
      "bg": "deep",
      "fg": "snow",
      "hi": "ice",
      "world": false,
      "top": 258,
      "size": 98,
      "tile": {
        "bg": "#16272f",
        "line": "snow",
        "label": "snow",
        "r": 18
      },
      "tilts": [
        -2,
        1.5,
        2,
        -1.5
      ]
    },
    "stats": {
      "bg": "pine",
      "fg": "snow",
      "hi": "coral",
      "world": false,
      "cols": [
        "coral",
        "ice",
        "snow"
      ],
      "num": 158
    },
    "cta": {
      "bg": "ice",
      "fg": "ink",
      "hi": "coral",
      "world": true,
      "top": 470,
      "size": 124,
      "btn": {
        "v": "pill",
        "bg": "coral",
        "c": "snow"
      },
      "logoShape": "circle"
    }
  },

  // ---- camera + motion ----
  cams: ["drop","pushR","zoomOut","pushL","hopU","zoomIn"], camMul: 5, camOff: 4,
  mag: {"rot":0.6,"driftY":10},
  ambient: 1.6,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Toggle":"check","Ring":"ring","DragDrop":"drag","Morph":"roll"},

  strings: {
    brandName: "Snow Peak",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 26, height: 26, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round", strokeLinejoin: "round" }, R2("path", { d: "M3 20L10 6l4 7 2-3 5 10Z" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      R("path", { d: `M -20 ${u.H - 560} L ${u.W * 0.3} ${u.H - 1060} L ${u.W * 0.52} ${u.H - 720} L ${u.W * 0.74} ${u.H - 1160} L ${u.W + 20} ${u.H - 640} L ${u.W + 20} ${u.H + 20} L -20 ${u.H + 20} Z`, fill: theme.pine }),
      R("path", { d: `M ${u.W * 0.3 - 64} ${u.H - 954} L ${u.W * 0.3} ${u.H - 1060} L ${u.W * 0.3 + 64} ${u.H - 954} Q ${u.W * 0.3} ${u.H - 990} ${u.W * 0.3 - 64} ${u.H - 954} Z`, fill: theme.snow }),
      R("path", { d: `M ${u.W * 0.74 - 58} ${u.H - 1064} L ${u.W * 0.74} ${u.H - 1160} L ${u.W * 0.74 + 58} ${u.H - 1064} Q ${u.W * 0.74} ${u.H - 1100} ${u.W * 0.74 - 58} ${u.H - 1064} Z`, fill: theme.snow }),
      R("path", { d: `M -20 ${u.H - 300} Q ${u.W * 0.4} ${u.H - 430} ${u.W + 20} ${u.H - 260} L ${u.W + 20} ${u.H + 20} L -20 ${u.H + 20} Z`, fill: theme.deep }),
      R("line", { x1: 60, y1: 560, x2: u.W - 40, y2: 380, stroke: rgba(theme.ink, 0.4), strokeWidth: 4 }),
      R("g", { transform: `translate(${u.W - 240 - ((t * 60) % (u.W - 200))},${455 + ((t * 60) % (u.W - 200)) * 0.19 + Math.sin(t * 1.4) * 6})` },
        R("line", { x1: 0, y1: -26, x2: 0, y2: 0, stroke: theme.ink, strokeWidth: 4 }),
        R("rect", { x: -26, y: 0, width: 52, height: 40, rx: 7, fill: theme.coral }),
        R("rect", { x: -16, y: 8, width: 32, height: 16, rx: 3, fill: theme.ice })),
      Array.from({ length: 18 }).map((_, i) => {
        const sx = (i * 61 + Math.sin(t * 0.8 + i) * 40 + u.W) % u.W;
        const sy = ((t * (70 + (i % 4) * 26) + i * 210) % (u.H + 100)) - 50;
        return R("circle", { key: "f" + i, cx: sx, cy: sy, r: 3 + (i % 3) * 2, fill: rgba("#ffffff", 0.75 - (i % 3) * 0.15) });
      })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
