// SOLE DROP — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-1.js, template "SoleDrop").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Archivo Black / body Archivo. Camera set ["pushR","zoomIn","pushU","spin","pushL","drop"].
// Entrances: title "streak", items "slam".
// Owns the Cursor:keys, Notify:pop, Swipe:swipe, Ring:bar mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "sole-drop",
  label: "SOLE DROP",

  // ---- type ----
  display: "Archivo Black", displayFallback: "sans-serif",
  body: "Archivo", bodyFallback: "sans-serif",
  mono: null,
  em: 0.84,
  titleLine: 1.04, titleSpace: "0.01em",
  titlePreset: "streak", itemPreset: "slam",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ court: t.court || "#101014", volt: t.volt || "#d4f24b", chalk: "#f4f4f2", flame: "#ff5a36", ink: "#0a0a0c" }),
  accents: ["volt","flame","court"],
  groundKey: "court", inkKey: "ink", paperKey: "chalk",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "court",
      "fg": "chalk",
      "hi": "volt",
      "world": true,
      "top": 310,
      "size": 130,
      "upper": true,
      "kicker": {
        "v": "tag",
        "bg": "volt",
        "c": "ink"
      }
    },
    "statement": {
      "bg": "volt",
      "fg": "ink",
      "hi": "flame",
      "world": false,
      "top": 620,
      "size": 158,
      "upper": true
    },
    "feature": {
      "bg": "court",
      "fg": "chalk",
      "hi": "volt",
      "world": true,
      "top": 246,
      "size": 100,
      "upper": true,
      "card": {
        "v": "frame",
        "bg": "ink",
        "r": 10,
        "line": "chalk"
      },
      "chips": {
        "v": "square",
        "colors": [
          "volt",
          "flame",
          "chalk"
        ],
        "text": "ink"
      }
    },
    "montage": {
      "bg": "ink",
      "fg": "chalk",
      "hi": "volt",
      "world": false,
      "top": 256,
      "size": 96,
      "upper": true,
      "tile": {
        "bg": "court",
        "line": "chalk",
        "label": "volt",
        "r": 8
      },
      "tilts": [
        0,
        0,
        0,
        0
      ]
    },
    "stats": {
      "bg": "court",
      "fg": "chalk",
      "hi": "volt",
      "world": true,
      "cols": [
        "volt",
        "flame",
        "chalk"
      ],
      "num": 156,
      "upper": true,
      "rule": true
    },
    "cta": {
      "bg": "ink",
      "fg": "chalk",
      "hi": "volt",
      "world": true,
      "top": 490,
      "size": 126,
      "upper": true,
      "btn": {
        "v": "block",
        "bg": "volt",
        "c": "ink"
      },
      "logoShape": "rounded"
    },
    "app": {
      "bg": "court",
      "fg": "chalk",
      "hi": "volt",
      "cardBg": "#16161c",
      "line": "chalk",
      "world": true,
      "upper": true
    }
  },

  // ---- camera + motion ----
  cams: ["pushR","zoomIn","pushU","spin","pushL","drop"], camMul: 7, camOff: 2,
  mag: {"skew":5,"rot":1.1,"inn":0.17,"slide":0.3},
  ambient: 2,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Cursor":"keys","Notify":"pop","Swipe":"swipe","Ring":"bar"},

  strings: {
    brandName: "SOLE DROP",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round", strokeLinejoin: "round" }, R2("path", { d: "M3 15c4 0 6-3 8-3s3 2 7 2c2 0 3 1 3 2v2H3zM7 12l1.5 1.5M10.5 11l1.5 1.5" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      [0, 1, 2, 3].map((i) => R("line", { key: i, x1: -100 + ((t * 500 + i * 300) % (u.W + 400)), y1: 160 + i * 90, x2: 60 + ((t * 500 + i * 300) % (u.W + 400)), y2: 160 + i * 90, stroke: rgba(theme.volt, 0.5 - i * 0.09), strokeWidth: 10 - i * 2, strokeLinecap: "round" })),
      R("path", { d: "M -20 " + (u.H - 260) + " " + Array.from({ length: 12 }).map((_, i) => "l 60 " + (i % 2 ? 44 : -44)).join(" "), fill: "none", stroke: rgba(theme.flame, 0.45), strokeWidth: 12, strokeLinecap: "round", strokeLinejoin: "round" }),
      (function () {
        const bt = (t * 0.9) % 1, bx = bt * u.W;
        const by = u.H - 420 - Math.abs(Math.sin(bt * Math.PI * 3)) * 260;
        return R("g", null,
          R("circle", { cx: bx, cy: by, r: 30, fill: theme.flame }),
          R("path", { d: "M " + (bx - 30) + " " + by + " a 30 30 0 0 1 60 0 M " + bx + " " + (by - 30) + " a 30 30 0 0 0 0 60", fill: "none", stroke: theme.ink, strokeWidth: 4 }));
      })(),
      R("text", { x: u.W - 40, y: 220, textAnchor: "end", fontFamily: '"Archivo Black", sans-serif', fontSize: 150, fill: "none", stroke: rgba(theme.chalk, 0.14), strokeWidth: 2 }, String(Math.floor(t * 2) % 100).padStart(2, "0"))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
