// SPEC SHEET — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-01.js, template "SpecSheet").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Russo One / body Radio Canada. Camera set ["zoomIn","pushU","zoomOut","pushD","pushL","pushR"].
// Entrances: title "rise", items "pop".
// Owns the Ring:ring, Scroll:board, Typing:caret mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "spec-sheet",
  label: "Spec Sheet",

  // ---- type ----
  display: "Russo One", displayFallback: "\"Helvetica Neue\", sans-serif",
  body: "Radio Canada", bodyFallback: "system-ui, sans-serif",
  mono: "IBM Plex Mono",
  chrome: false,
  devanagari: "Noto Sans Devanagari",
  maxScenes: 18,
  em: 0.62,
  titleLine: 1.1, titleSpace: "0.005em",
  titlePreset: "rise", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({
      bg: t.bg || "#0f1720", surface: "#1a2732", rule: "#2f4655", inkMuted: "#93aab8",
      ink: "#ecf4f9", accent: t.accent || "#37b5ff", accent2: t.accent2 || "#7ff0cf", accentInk: "#04121b",
    }),
  accents: ["accent","accent2","surface"],
  groundKey: "bg", inkKey: "accentInk", paperKey: "ink",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 92,
      "upper": true,
      "kicker": {
        "v": "outline",
        "c": "accent2"
      }
    },
    "statement": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 600,
      "size": 108,
      "upper": true
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 560,
      "size": 68,
      "bodySize": 38,
      "ch": 50,
      "lh": 1.5,
      "weight": 400,
      "dim": 0.92,
      "kicker": {
        "v": "bare",
        "c": "accent2"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 380,
      "size": 72,
      "ch": 24,
      "lh": 1.2,
      "markSize": 180,
      "altLine": true
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 250,
      "size": 82,
      "upper": true,
      "swap": "body",
      "card": {
        "v": "glow",
        "bg": "surface",
        "glow": "accent",
        "r": 18,
        "line": "inkMuted"
      },
      "chips": {
        "v": "outline",
        "colors": [
          "accent",
          "accent2",
          "ink"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 330,
      "size": 78,
      "upper": true,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 18,
        "h": 640,
        "labelSize": 38
      },
      "tilts": [
        0,
        0,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 380,
      "size": 80,
      "upper": true,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 152,
      "glowNums": true
    },
    "cta": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "surface",
      "world": false,
      "top": 460,
      "size": 94,
      "upper": true,
      "align": "center",
      "btn": {
        "v": "glow",
        "bg": "accentInk",
        "c": "ink"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["zoomIn","pushU","zoomOut","pushD","pushL","pushR"], camMul: 5, camOff: 4,
  mag: {"rot":0.2,"driftX":5,"driftY":6,"driftZ":0.06,"slide":0.2,"inn":0.22,"zin":0.44,"zout":0.34},
  ambient: 1.35,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Ring":"ring","Scroll":"board","Typing":"caret"},

  strings: {
    brandName: "Spec Sheet",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.4, strokeLinecap: "round", strokeLinejoin: "round" },
      R2("path", { d: "M4 20L14 6a6 6 0 014 4L8 20z" }), R2("path", { d: "M3 20h18" })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "radial-gradient(120% 70% at 50% 96%, " + rgba(theme.accent, 0.22) + " 0%, transparent 62%), radial-gradient(100% 60% at 78% 8%, " + rgba(theme.surface, 0.9) + " 0%, transparent 70%), " + bg),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, hz = H * 0.62, vx = W * 0.5;
      const sweep = Math.sin((t / 12) * Math.PI * 2) * 34;
      const dx = W * 0.72, dy = H - 420;
      const pulse = (t % 3) / 3;
      return R("g", null,
        R("defs", null,
          R("pattern", { id: "ss-tick", width: 84, height: 84, patternUnits: "userSpaceOnUse" },
            R("path", { d: "M42 36v12M36 42h12", stroke: rgba(theme.rule, 0.55), strokeWidth: 2 })),
          R("radialGradient", { id: "ss-hz", cx: "50%", cy: "100%" },
            R("stop", { offset: "0%", stopColor: rgba(theme.accent, 0.34) }),
            R("stop", { offset: "100%", stopColor: rgba(theme.accent, 0) })),
          R("linearGradient", { id: "ss-beam", x1: "0%", y1: "0%", x2: "100%", y2: "0%" },
            R("stop", { offset: "0%", stopColor: rgba(theme.accent, 0.5) }),
            R("stop", { offset: "100%", stopColor: rgba(theme.accent, 0) }))),
        R("rect", { x: 0, y: 0, width: W, height: hz, fill: "url(#ss-tick)" }),
        R("ellipse", { cx: vx, cy: hz + 40, rx: W * 0.9, ry: 300, fill: "url(#ss-hz)" }),
        R("line", { x1: 0, y1: hz, x2: W, y2: hz, stroke: rgba(theme.accent, 0.5), strokeWidth: 3 }),
        R("g", { opacity: 0.7 },
          [-4, -3, -2, -1, 0, 1, 2, 3, 4].map((i) => R("line", { key: "p" + i, x1: vx + i * 46, y1: hz, x2: vx + i * 430, y2: H, stroke: rgba(theme.rule, 0.75), strokeWidth: 2 })),
          [0.16, 0.36, 0.62, 1].map((f, i) => R("line", { key: "h" + i, x1: 0, y1: hz + f * (H - hz), x2: W, y2: hz + f * (H - hz), stroke: rgba(theme.rule, 0.6), strokeWidth: 2 }))),
        /* dish */
        R("g", { transform: "translate(" + dx + "," + dy + ")" },
          R("ellipse", { cx: 0, cy: 176, rx: 130, ry: 20, fill: rgba(theme.accentInk, 0.6) }),
          R("path", { d: "M -18 170 L 18 170 L 10 40 L -10 40 Z", fill: rgba(theme.surface, 0.98), stroke: rgba(theme.inkMuted, 0.4), strokeWidth: 2 }),
          R("path", { d: "M -70 176 h 140", stroke: rgba(theme.inkMuted, 0.5), strokeWidth: 6, strokeLinecap: "round" }),
          R("g", { transform: "rotate(" + sweep.toFixed(2) + ")" },
            R("path", { d: "M 0 0 L 300 -150 L 300 150 Z", fill: "url(#ss-beam)", opacity: 0.75 }),
            R("path", { d: "M -104 -96 A 128 128 0 0 1 -104 96 L -58 62 A 74 74 0 0 0 -58 -62 Z", fill: rgba(theme.surface, 0.96), stroke: rgba(theme.accent, 0.55), strokeWidth: 3 }),
            R("path", { d: "M -104 -96 A 128 128 0 0 1 -80 -50 L -58 -62 A 74 74 0 0 0 -70 -78 Z", fill: rgba(theme.ink, 0.16) }),
            R("line", { x1: -74, y1: 0, x2: 30, y2: 0, stroke: rgba(theme.inkMuted, 0.7), strokeWidth: 5 }),
            R("circle", { cx: 34, cy: 0, r: 13, fill: rgba(theme.accent2, 0.95) })),
          [0, 1, 2].map((i) => {
            const ph = (pulse + i / 3) % 1;
            return R("circle", { key: "r" + i, cx: 0, cy: 0, r: 60 + ph * 300, fill: "none", stroke: rgba(theme.accent2, 0.32 * (1 - ph)), strokeWidth: 4 });
          })),
        /* near plane */
        [0, 1, 2, 3, 4, 5].map((i) => {
          const ph = (t * (0.13 + i * 0.02) + i * 0.19) % 1;
          return R("circle", { key: "b" + i, cx: 90 + i * 190 + Math.sin(t * 0.6 + i) * 34, cy: H - ph * (H + 200), r: 5 + (i % 3) * 6, fill: rgba(theme.accent, 0.2 * (1 - ph)) });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
