// STORYBOOK — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/world-pack-2.js, template "StorybookPop").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Bitter / body Nunito Sans. Camera set ["pushR","drop","zoomOut","pushL","hopU","zoomIn"].
// Entrances: title "drowse", items "pop".
// Owns the Typing:typewriter, Scroll:stack, Morph:roll, DragDrop:drag mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "storybook-pop",
  label: "Storybook",

  // ---- type ----
  display: "Bitter", displayFallback: "serif",
  body: "Nunito Sans", bodyFallback: "sans-serif",
  mono: null,
  em: 0.54,
  titleLine: 1.1, titleSpace: "0",
  titlePreset: "drowse", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ page: t.page || "#f8efdf", ink: "#37302a", ribbon: t.ribbon || "#cf4633", forest: "#3e6b4c", gold: "#d9a13b", paper: "#fffdf6" }),
  accents: ["gold","ribbon","page"],
  groundKey: "page", inkKey: "ink", paperKey: "paper",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "page",
      "fg": "ink",
      "hi": "ribbon",
      "world": true,
      "top": 300,
      "size": 116,
      "kicker": {
        "v": "outline",
        "c": "forest"
      }
    },
    "statement": {
      "bg": "forest",
      "fg": "paper",
      "hi": "gold",
      "world": false,
      "top": 630,
      "size": 140
    },
    "feature": {
      "bg": "page",
      "fg": "ink",
      "hi": "ribbon",
      "world": true,
      "top": 246,
      "size": 92,
      "card": {
        "v": "paper",
        "bg": "paper",
        "r": 10,
        "line": "ink"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "ribbon",
          "forest",
          "gold"
        ],
        "text": "paper"
      }
    },
    "montage": {
      "bg": "ink",
      "fg": "paper",
      "hi": "gold",
      "world": false,
      "top": 258,
      "size": 92,
      "tile": {
        "bg": "paper",
        "line": "ink",
        "label": "gold",
        "r": 10
      },
      "tilts": [
        -3,
        2.5,
        2,
        -2.5
      ]
    },
    "stats": {
      "bg": "forest",
      "fg": "paper",
      "hi": "gold",
      "world": false,
      "cols": [
        "gold",
        "page",
        "paper"
      ],
      "num": 152
    },
    "cta": {
      "bg": "ribbon",
      "fg": "paper",
      "hi": "gold",
      "world": false,
      "top": 500,
      "size": 118,
      "btn": {
        "v": "pill",
        "bg": "paper",
        "c": "ribbon"
      },
      "logoShape": "circle"
    }
  },

  // ---- camera + motion ----
  cams: ["pushR","drop","zoomOut","pushL","hopU","zoomIn"], camMul: 3, camOff: 1,
  mag: {"rot":0.9,"driftY":8,"inn":0.27},
  ambient: 1.5,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Typing":"typewriter","Scroll":"stack","Morph":"roll","DragDrop":"drag"},

  strings: {
    brandName: "Storybook",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 25, height: 25, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round", strokeLinejoin: "round" }, R2("path", { d: "M12 6c-2-2-5-2-8-1v14c3-1 6-1 8 1 2-2 5-2 8-1V5c-3-1-6-1-8 1Zv14" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      R("g", { transform: `translate(${u.W / 2},${u.H - 430})` },
        R("path", { d: "M0 0 C -180 -60 -420 -40 -470 20 L -470 120 C -420 60 -180 80 0 130 Z", fill: theme.paper, stroke: rgba(theme.ink, 0.25), strokeWidth: 3 }),
        R("path", { d: "M0 0 C 180 -60 420 -40 470 20 L 470 120 C 420 60 180 80 0 130 Z", fill: theme.page, stroke: rgba(theme.ink, 0.25), strokeWidth: 3 }),
        [0, 1, 2, 3].map((i) => R("line", { key: "l" + i, x1: -400, y1: 4 + i * 26, x2: -80, y2: 26 + i * 26, stroke: rgba(theme.ink, 0.22), strokeWidth: 5, strokeLinecap: "round" })),
        (function () {
          const ph = (t * 0.35) % 1, e = ph < 0.5 ? ph * 2 : 2 - ph * 2;
          return R("path", { d: `M0 0 C ${120 - e * 240} ${-160} ${300 - e * 600} ${-140} ${420 - e * 840} 20 L 0 130 Z`, fill: rgba(theme.paper, 0.92), stroke: rgba(theme.ink, 0.2), strokeWidth: 2 });
        })(),
        R("rect", { x: -10, y: 0, width: 20, height: 150, rx: 6, fill: theme.ribbon })),
      Array.from({ length: 10 }).map((_, i) => {
        const sx = u.W / 2 + Math.sin(t * (0.4 + i * 0.09) + i * 2.4) * (u.W * 0.36);
        const sy = u.H - 560 - ((t * (26 + i * 6) + i * 130) % 900);
        return R("path", { key: "sp" + i, d: `M ${sx} ${sy - 8} L ${sx + 3} ${sy - 2} L ${sx + 9} ${sy} L ${sx + 3} ${sy + 2} L ${sx} ${sy + 8} L ${sx - 3} ${sy + 2} L ${sx - 9} ${sy} L ${sx - 3} ${sy - 2} Z`, fill: theme.gold, opacity: 0.5 + 0.4 * Math.abs(Math.sin(t * 2 + i)) });
      })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
