// STRING & SKY — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-5.js, template "StringSky").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Grandstander / body Sofia Sans. Camera set ["hopU","pushR","zoomOut","pushL","zoomIn","drop"].
// Entrances: title "bounce", items "pop".
// Owns the Toggle:check, Ring:bar, Notify:pop, Morph:roll mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "string-and-sky",
  label: "String & Sky",

  // ---- type ----
  display: "Grandstander", displayFallback: "cursive",
  body: "Sofia Sans", bodyFallback: "sans-serif",
  mono: null,
  em: 0.62,
  titleLine: 1.05, titleSpace: "0",
  titlePreset: "bounce", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ sky: t.sky || "#a8d8ea", kite: t.kite || "#e84855", sun: "#f2b13c", grass: "#5a9e54", navy: "#23364a" }),
  accents: ["kite","sun","sky"],
  groundKey: "sky", inkKey: "navy", paperKey: "sky",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "sky",
      "fg": "navy",
      "hi": "kite",
      "world": true,
      "top": 330,
      "size": 122,
      "kicker": {
        "v": "pill",
        "bg": "kite",
        "c": "sky"
      }
    },
    "statement": {
      "bg": "navy",
      "fg": "sky",
      "hi": "sun",
      "world": false,
      "top": 630,
      "size": 146
    },
    "feature": {
      "bg": "sky",
      "fg": "navy",
      "hi": "kite",
      "world": true,
      "top": 250,
      "size": 96,
      "card": {
        "v": "tilt",
        "bg": "navy",
        "r": 20,
        "line": "sky"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "kite",
          "grass",
          "sun"
        ],
        "text": "navy"
      }
    },
    "montage": {
      "bg": "navy",
      "fg": "sky",
      "hi": "sun",
      "world": false,
      "top": 258,
      "size": 92,
      "tile": {
        "bg": "sky",
        "line": "navy",
        "label": "navy",
        "r": 16
      },
      "tilts": [
        -3,
        2.5,
        2,
        -2.5
      ]
    },
    "stats": {
      "bg": "sky",
      "fg": "navy",
      "hi": "kite",
      "world": true,
      "cols": [
        "kite",
        "grass",
        "navy"
      ],
      "num": 150
    },
    "cta": {
      "bg": "sun",
      "fg": "navy",
      "hi": "kite",
      "world": false,
      "top": 500,
      "size": 118,
      "btn": {
        "v": "pill",
        "bg": "navy",
        "c": "sky"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "sky",
      "fg": "navy",
      "hi": "kite",
      "cardBg": "#eef6fa",
      "line": "navy",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["hopU","pushR","zoomOut","pushL","zoomIn","drop"], camMul: 3, camOff: 2,
  mag: {"rot":1,"driftX":10,"driftY":9},
  ambient: 1.8,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Toggle":"check","Ring":"bar","Notify":"pop","Morph":"roll"},

  strings: {
    brandName: "String & Sky",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinejoin: "round", strokeLinecap: "round" }, R2("path", { d: "M12 2l7 7-7 7-7-7zM12 16c0 3-2 4-4 5" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      [0, 1].map((i) => {
        const kx = 260 + i * 420 + Math.sin(t * (0.7 + i * 0.2)) * 60;
        const ky = 300 + i * 140 + Math.cos(t * (0.9 - i * 0.2)) * 40;
        const c = i ? theme.sun : theme.kite;
        return R("g", { key: i },
          R("line", { x1: kx, y1: ky + 60, x2: 120 + i * 500, y2: u.H - 120, stroke: rgba(theme.navy, 0.35), strokeWidth: 3 }),
          R("g", { transform: "translate(" + kx + "," + ky + ") rotate(" + (Math.sin(t * 1.1 + i) * 12 + 8) + ")" },
            R("polygon", { points: "0,-64 44,0 0,64 -44,0", fill: c, stroke: theme.navy, strokeWidth: 4 }),
            R("line", { x1: 0, y1: -64, x2: 0, y2: 64, stroke: rgba(theme.navy, 0.4), strokeWidth: 3 }),
            R("line", { x1: -44, y1: 0, x2: 44, y2: 0, stroke: rgba(theme.navy, 0.4), strokeWidth: 3 }),
            R("path", { d: "M 0 64 q " + (14 + Math.sin(t * 5 + i) * 12) + " 36 0 62 q -" + (14 + Math.cos(t * 4.6 + i) * 12) + " 30 0 58", fill: "none", stroke: c, strokeWidth: 4, strokeLinecap: "round" }),
            [80, 128].map((yy, k) => R("polygon", { key: k, points: "0," + yy + " 12," + (yy + 10) + " 0," + (yy + 20) + " -12," + (yy + 10), fill: k ? theme.grass : theme.sun, transform: "rotate(" + Math.sin(t * 5 + k) * 20 + " 0 " + (yy + 10) + ")" }))));
      }),
      [0, 1, 2].map((i) => {
        const cx = ((t * (18 + i * 8) + i * 400) % (u.W + 360)) - 180;
        return R("g", { key: "c" + i, transform: "translate(" + cx + "," + (170 + i * 120) + ")", opacity: 0.85 - i * 0.2 },
          R("ellipse", { rx: 100, ry: 30, fill: "#ffffff" }), R("ellipse", { cx: 60, cy: -18, rx: 60, ry: 24, fill: "#ffffff" }));
      }),
      R("circle", { cx: u.W - 150, cy: 170, r: 64, fill: theme.sun, opacity: 0.9 }),
      R("path", { d: "M -20 " + (u.H - 110) + " q " + (u.W / 4) + " -40 " + (u.W / 2) + " 0 t " + (u.W / 2 + 40) + " 0 L " + (u.W + 20) + " " + (u.H + 20) + " L -20 " + (u.H + 20) + " Z", fill: theme.grass }),
      Array.from({ length: 8 }).map((_, i) => R("path", { key: "g" + i, d: "M " + (60 + i * 140) + " " + (u.H - 120) + " q 4 -22 12 -30", fill: "none", stroke: rgba(theme.navy, 0.3), strokeWidth: 4, strokeLinecap: "round" }))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
