// TIDE POOL LAB — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-5.js, template "TidePoolLab").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Shrikhand / body Poppins. Camera set ["zoomIn","pushD","hopU","pushL","zoomOut","pushR"].
// Entrances: title "rise", items "pop".
// Owns the Ring:bar, Scroll:feed, Toggle:check, Typing:hand mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "tide-pool-lab",
  label: "Tide Pool Lab",

  // ---- type ----
  display: "Shrikhand", displayFallback: "cursive",
  body: "Poppins", bodyFallback: "sans-serif",
  mono: null,
  em: 0.68,
  titleLine: 1.1, titleSpace: "0",
  titlePreset: "rise", itemPreset: "pop",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ sand: t.sand || "#f0e6cc", rock: "#4a5258", anemone: t.anemone || "#f27d98", seafoam: "#8fd8c8", ink: "#2a3238" }),
  accents: ["anemone","seafoam","sand"],
  groundKey: "sand", inkKey: "ink", paperKey: "sand",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "sand",
      "fg": "ink",
      "hi": "anemone",
      "world": true,
      "top": 320,
      "size": 108,
      "kicker": {
        "v": "pill",
        "bg": "seafoam",
        "c": "ink"
      }
    },
    "statement": {
      "bg": "rock",
      "fg": "sand",
      "hi": "seafoam",
      "world": false,
      "top": 630,
      "size": 132
    },
    "feature": {
      "bg": "sand",
      "fg": "ink",
      "hi": "anemone",
      "world": true,
      "top": 250,
      "size": 88,
      "card": {
        "v": "frame",
        "bg": "rock",
        "r": 22,
        "line": "sand"
      },
      "chips": {
        "v": "pill",
        "colors": [
          "anemone",
          "seafoam"
        ],
        "text": "ink"
      }
    },
    "montage": {
      "bg": "rock",
      "fg": "sand",
      "hi": "anemone",
      "world": false,
      "top": 258,
      "size": 86,
      "tile": {
        "bg": "sand",
        "line": "ink",
        "label": "ink",
        "r": 18
      },
      "tilts": [
        -2.5,
        2,
        1.5,
        -2
      ]
    },
    "stats": {
      "bg": "sand",
      "fg": "ink",
      "hi": "anemone",
      "world": true,
      "cols": [
        "anemone",
        "seafoam",
        "rock"
      ],
      "num": 144
    },
    "cta": {
      "bg": "seafoam",
      "fg": "ink",
      "hi": "anemone",
      "world": false,
      "top": 500,
      "size": 106,
      "btn": {
        "v": "pill",
        "bg": "ink",
        "c": "sand"
      },
      "logoShape": "circle"
    },
    "app": {
      "bg": "sand",
      "fg": "ink",
      "hi": "anemone",
      "cardBg": "#faf4e4",
      "line": "ink",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["zoomIn","pushD","hopU","pushL","zoomOut","pushR"], camMul: 5, camOff: 1,
  mag: {"rot":0.8,"driftY":8},
  ambient: 1.6,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Ring":"bar","Scroll":"feed","Toggle":"check","Typing":"hand"},

  strings: {
    brandName: "Tide Pool Lab",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinecap: "round", strokeLinejoin: "round" }, R2("path", { d: "M12 3l2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      R("ellipse", { cx: u.W / 2 + 60, cy: u.H - 330, rx: 360, ry: 110, fill: rgba(theme.seafoam, 0.5) }),
      R("ellipse", { cx: u.W / 2 + 60, cy: u.H - 330, rx: 360, ry: 110, fill: "none", stroke: theme.rock, strokeWidth: 14 }),
      [0, 1].map((i) => R("ellipse", { key: i, cx: u.W / 2 - 60 + i * 220, cy: u.H - 330, rx: 30 + ((t * 36 + i * 40) % 110), ry: 8 + ((t * 36 + i * 40) % 110) * 0.2, fill: "none", stroke: rgba("#ffffff", 0.4 * (1 - ((t * 36 + i * 40) % 110) / 110)), strokeWidth: 3 })),
      (function () {
        const sx = u.W / 2 - 140, sy = u.H - 340, ro = Math.sin(t * 0.6) * 14;
        let ptsr = "";
        for (let k = 0; k < 10; k++) { const a = k * Math.PI / 5 - Math.PI / 2; const r = k % 2 ? 22 : 52; ptsr += (sx + Math.cos(a) * r) + "," + (sy + Math.sin(a) * r * 0.8) + " "; }
        return R("polygon", { points: ptsr, fill: theme.anemone, stroke: rgba(theme.ink, 0.4), strokeWidth: 3, transform: "rotate(" + ro + " " + sx + " " + sy + ")" });
      })(),
      R("g", { transform: "translate(" + (u.W / 2 + 170) + "," + (u.H - 330) + ")" },
        Array.from({ length: 10 }).map((_, k) => {
          const a = (k / 10) * Math.PI * 2;
          const wob = Math.sin(t * 2.4 + k) * 8;
          return R("line", { key: k, x1: 0, y1: 0, x2: Math.cos(a) * (34 + wob), y2: Math.sin(a) * (26 + wob) * 0.7 - 8, stroke: theme.seafoam, strokeWidth: 6, strokeLinecap: "round" });
        }),
        R("circle", { r: 13, fill: rgba(theme.ink, 0.5) })),
      (function () {
        const cph = (t * 0.2) % 1;
        const cx2 = 140 + cph * (u.W - 280), flip = Math.floor(t * 0.2) % 2 ? 1 : -1;
        return R("g", { transform: "translate(" + (flip > 0 ? cx2 : u.W - cx2) + "," + (u.H - 170) + ") scale(" + flip + ",1)" },
          R("ellipse", { rx: 30, ry: 20, fill: theme.anemone }),
          R("circle", { cx: -12, cy: -22, r: 5, fill: theme.ink }), R("circle", { cx: 12, cy: -22, r: 5, fill: theme.ink }),
          R("path", { d: "M -12 -18 v -10 M 12 -18 v -10", stroke: theme.ink, strokeWidth: 3 }),
          [-1, 1].map((s) => [0, 1, 2].map((k) => R("path", { key: s + "-" + k, d: "M " + (s * 26) + " " + (k * 6 - 4) + " l " + (s * (16 + Math.sin(t * 8 + k) * 5)) + " " + (8 + k * 3), fill: "none", stroke: theme.anemone, strokeWidth: 5, strokeLinecap: "round" }))),
          R("path", { d: "M 24 -20 a 10 10 0 0 1 14 -6", fill: "none", stroke: theme.anemone, strokeWidth: 6, strokeLinecap: "round" }));
      })(),
      Array.from({ length: 5 }).map((_, i) => R("circle", { key: "p" + i, cx: 130 + i * 60, cy: 240 + (i % 2) * 40, r: 4 + (i % 3), fill: rgba(theme.rock, 0.35) }))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
