// TWENTY MOVES — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/mega-pack-5.js, template "TwentyMoves").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Russo One / body Geologica. Camera set ["pushL","zoomIn","spin","pushR","pushU","drop"].
// Entrances: title "slam", items "slam".
// Owns the Cursor:keys, Ring:ring, Scroll:ticker, Toggle:dial mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "twenty-moves",
  label: "Twenty Moves",

  // ---- type ----
  display: "Russo One", displayFallback: "sans-serif",
  body: "Geologica", bodyFallback: "sans-serif",
  mono: null,
  em: 0.62,
  titleLine: 1.04, titleSpace: "0.02em",
  titlePreset: "slam", itemPreset: "slam",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({ mat: t.mat || "#1e2024", cube: t.cube || "#ffcb2e", blue: "#3d7bff", white: "#f4f4f6", ink: "#141518" }),
  accents: ["cube","white","mat"],
  groundKey: "mat", inkKey: "ink", paperKey: "white",
  dark: true,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "mat",
      "fg": "white",
      "hi": "cube",
      "world": true,
      "top": 310,
      "size": 118,
      "upper": true,
      "kicker": {
        "v": "tag",
        "bg": "cube",
        "c": "ink"
      }
    },
    "statement": {
      "bg": "cube",
      "fg": "ink",
      "hi": "white",
      "world": false,
      "top": 630,
      "size": 146,
      "upper": true
    },
    "feature": {
      "bg": "mat",
      "fg": "white",
      "hi": "cube",
      "world": true,
      "top": 248,
      "size": 94,
      "upper": true,
      "card": {
        "v": "frame",
        "bg": "ink",
        "r": 12,
        "line": "white"
      },
      "chips": {
        "v": "square",
        "colors": [
          "cube",
          "blue",
          "white"
        ],
        "text": "ink"
      }
    },
    "montage": {
      "bg": "ink",
      "fg": "white",
      "hi": "cube",
      "world": false,
      "top": 258,
      "size": 92,
      "upper": true,
      "tile": {
        "bg": "mat",
        "line": "white",
        "label": "cube",
        "r": 8
      },
      "tilts": [
        -2,
        2,
        1.5,
        -2
      ]
    },
    "stats": {
      "bg": "mat",
      "fg": "white",
      "hi": "cube",
      "world": true,
      "cols": [
        "cube",
        "blue",
        "white"
      ],
      "num": 150,
      "upper": true,
      "rule": true
    },
    "cta": {
      "bg": "blue",
      "fg": "white",
      "hi": "cube",
      "world": false,
      "top": 500,
      "size": 114,
      "upper": true,
      "btn": {
        "v": "block",
        "bg": "ink",
        "c": "white"
      },
      "logoShape": "rounded"
    },
    "app": {
      "bg": "mat",
      "fg": "white",
      "hi": "cube",
      "cardBg": "#282b31",
      "line": "white",
      "world": true,
      "upper": true
    }
  },

  // ---- camera + motion ----
  cams: ["pushL","zoomIn","spin","pushR","pushU","drop"], camMul: 7, camOff: 1,
  mag: {"skew":4,"rot":1.2,"inn":0.16},
  ambient: 2,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Cursor":"keys","Ring":"ring","Scroll":"ticker","Toggle":"dial"},

  strings: {
    brandName: "Twenty Moves",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.5, strokeLinejoin: "round" }, R2("path", { d: "M12 2l9 5v10l-9 5-9-5V7zM12 2v10M3 7l9 5 9-5" })),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => R("g", null,
      (function () {
        const cols = [theme.cube, theme.blue, "#3fbf5a", "#e8402e", theme.white, "#ff8a3d"];
        const s = 52, ox = u.W - 380, oy = u.H - 520;
        const cells = [];
        for (let r = 0; r < 3; r++) for (let c = 0; c < 3; c++) {
          const idx = Math.floor(t * 1.4 + r * 3 + c) % 6;
          cells.push(R("polygon", { key: "t" + r + c, points: (ox + (c - r) * s * 0.9) + "," + (oy + (c + r) * s * 0.5) + " " + (ox + (c - r + 1) * s * 0.9) + "," + (oy + (c + r + 1) * s * 0.5) + " " + (ox + (c - r) * s * 0.9) + "," + (oy + (c + r + 2) * s * 0.5) + " " + (ox + (c - r - 1) * s * 0.9) + "," + (oy + (c + r + 1) * s * 0.5), fill: cols[idx], stroke: theme.ink, strokeWidth: 4 }));
        }
        for (let r = 0; r < 3; r++) for (let c = 0; c < 3; c++) {
          const idx = Math.floor(t * 1.1 + r + c * 2) % 6;
          cells.push(R("rect", { key: "l" + r + c, x: ox - 3 * s * 0.9 + c * s * 0.9 - 8, y: oy + s + r * s * 0.9 + c * s * 0.5 - 40, width: s * 0.8, height: s * 0.8, fill: cols[idx], stroke: theme.ink, strokeWidth: 4, transform: "skewY(28)" }));
        }
        return R("g", null, cells);
      })(),
      R("text", { x: 90, y: 300, fontFamily: '"Russo One", sans-serif', fontSize: 88, fill: rgba(theme.white, 0.16) }, (6 + Math.floor(Math.abs(Math.sin(t * 0.7)) * 3)) + "." + String(Math.floor((t * 100) % 100)).padStart(2, "0")),
      ["R", "U'", "F2", "D", "L'"].map((mv, i) => R("text", { key: i, x: 90 + i * 110, y: u.H - 200, fontFamily: '"Russo One", sans-serif', fontSize: 40, fill: Math.floor(t * 2.5) % 5 === i ? theme.cube : rgba(theme.white, 0.3) }, mv)),
      R("line", { x1: 80, y1: u.H - 170, x2: 80 + 520 * (0.3 + Math.abs(Math.sin(t * 0.5)) * 0.7), y2: u.H - 170, stroke: theme.blue, strokeWidth: 6, strokeLinecap: "round" })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
