// WIRE COPY — skin for the shared FilmKit stage (services/film_stage.js).
//
// GENERATED by scripts/gen-film-skins.js from the handoff source
// (templete-design/keyframe-handoff/source/article-pack-03.js, template "WireCopy").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Zilla Slab / body Source Sans 3. Camera set ["pushL","pushU","pushR","drop","zoomIn","pushD"].
// Entrances: title "machete", items "rise".
// Owns the Scroll:board, Typing:terminal, Ring:bar mechanics.
//
// palette / icon / World below are the AUTHORED functions, emitted verbatim — the world in
// particular is re-evaluated per seek against an SVG-DOM shim, so the backdrop is not a
// reinterpretation of the original, it IS the original.

const stage = require("../film_stage");

const SKIN = {
  id: "wire-copy",
  label: "Wire Copy",

  // ---- type ----
  display: "Zilla Slab", displayFallback: "Georgia, serif",
  body: "Source Sans 3", bodyFallback: "system-ui, sans-serif",
  mono: "IBM Plex Mono",
  chrome: false,
  devanagari: "Noto Serif Devanagari",
  maxScenes: 18,
  em: 0.52,
  titleLine: 1.05, titleSpace: "-0.015em",
  titlePreset: "machete", itemPreset: "rise",

  // ---- palette ----
  // The authored function. Called with {} to get the design's own defaults; the brand's
  // accents are then hue-mapped onto `accents` slot by slot at their authored luminance,
  // and every other stop rotates onto the brand's lead hue — so a brand recolours the whole
  // world, not just the headline.
  palette: (t) => ({
      bg: t.bg || "#eae5da", surface: "#f8f5ee", rule: "#c9c1b1", inkMuted: "#6e685c",
      ink: "#16150f", accent: t.accent || "#b4302b", accent2: t.accent2 || "#3f5a6b", accentInk: "#f8f5ee",
    }),
  accents: ["accent","accent2","ink"],
  groundKey: "bg", inkKey: "ink", paperKey: "accentInk",
  dark: false,

  // ---- per-beat look (verbatim) ----
  look: {
    "hook": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 300,
      "size": 108,
      "kicker": {
        "v": "tag",
        "bg": "accent",
        "c": "accentInk"
      }
    },
    "statement": {
      "bg": "ink",
      "fg": "surface",
      "hi": "accent",
      "world": true,
      "top": 610,
      "size": 120
    },
    "body": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 540,
      "size": 74,
      "bodySize": 38,
      "ch": 54,
      "lh": 1.52,
      "weight": 400,
      "dim": 0.9,
      "kicker": {
        "v": "bare",
        "c": "accent"
      }
    },
    "quote": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 360,
      "size": 84,
      "ch": 25,
      "lh": 1.16,
      "markSize": 210,
      "rule": true
    },
    "feature": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 255,
      "size": 88,
      "swap": "body",
      "card": {
        "v": "paper",
        "bg": "surface",
        "r": 6,
        "line": "inkMuted"
      },
      "chips": {
        "v": "square",
        "colors": [
          "accent",
          "accent2",
          "inkMuted"
        ],
        "text": "accentInk"
      }
    },
    "montage": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent2",
      "world": true,
      "top": 330,
      "size": 82,
      "labelsOnly": true,
      "tile": {
        "bg": "rule",
        "line": "inkMuted",
        "label": "ink",
        "r": 6,
        "h": 640,
        "labelSize": 40
      },
      "tilts": [
        0,
        0,
        0,
        0
      ]
    },
    "stats": {
      "bg": "bg",
      "fg": "ink",
      "hi": "accent",
      "world": true,
      "top": 390,
      "size": 84,
      "cols": [
        "accent",
        "accent2",
        "ink"
      ],
      "num": 146,
      "rule": true
    },
    "cta": {
      "bg": "accent",
      "fg": "accentInk",
      "hi": "ink",
      "world": true,
      "top": 470,
      "size": 102,
      "align": "left",
      "btn": {
        "v": "block",
        "bg": "ink",
        "c": "accentInk"
      },
      "logoShape": "rounded"
    },
    "app": {
      "bg": "surface",
      "fg": "ink",
      "hi": "accent",
      "cardBg": "bg",
      "line": "inkMuted",
      "world": true
    }
  },

  // ---- camera + motion ----
  cams: ["pushL","pushU","pushR","drop","zoomIn","pushD"], camMul: 5, camOff: 2,
  mag: {"rot":0.15,"driftX":6,"driftY":5,"driftZ":0.03,"slide":0.22,"inn":0.16,"zin":0.3,"zout":0.24},
  ambient: 1.7,
  energy: 1,
  badge: "circle",
  

  // ---- the mechanics this pack owns ----
  // The handoff's promise is that no two templates share a mechanism. A pack that does not
  // declare a mechanic here never renders it.
  variants: {"Scroll":"board","Typing":"terminal","Ring":"bar"},

  strings: {
    brandName: "Wire Copy",
  },

  // The chrome mark, rendered once at build time.
  icon: (theme, fg, R2) => R2("svg", { width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: theme.currentBg, strokeWidth: 2.4, strokeLinecap: "round", strokeLinejoin: "round" },
      R2("path", { d: "M4 7h16v7H4zM7 14v6h10v-6" }), R2("path", { d: "M8 17h8" })),

  groundCss: (theme, bg) => (bg !== theme.bg ? bg : "linear-gradient(178deg, " + rgba(theme.surface, 0.9) + " 0%, " + bg + " 44%, " + rgba(theme.rule, 0.5) + " 100%)"),

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, progress, utils); no
  // Math.random and no Date, which is what lets it be re-evaluated deterministically on
  // every seek.
  World: (theme, t, p, u) => {
      const W = u.W, H = u.H, inv = theme.currentBg !== theme.bg;
      const tint = inv ? theme.surface : theme.inkMuted;
      const rule = inv ? theme.surface : theme.rule;
      const deck = H - 300;
      const feed = (t * 46) % 520;
      const spool = (t * 150) % 360;
      const tape = 0.2 + 0.8 * ((t % 9) / 9);
      return R("g", null,
        R("defs", null,
          R("pattern", { id: "wc-blind", width: 12, height: 46, patternUnits: "userSpaceOnUse" },
            R("rect", { x: 0, y: 0, width: 12, height: 30, fill: rgba(rule, inv ? 0.1 : 0.4) })),
          R("radialGradient", { id: "wc-glow", cx: "50%", cy: "50%" },
            R("stop", { offset: "0%", stopColor: rgba(theme.accent, 0.18) }),
            R("stop", { offset: "100%", stopColor: rgba(theme.accent, 0) }))),
        /* the city through the window, behind the blinds */
        R("g", { opacity: 0.4 },
          [0, 1, 2, 3, 4, 5, 6].map((i) => {
            const bh = 90 + ((i * 53) % 5) * 34;
            return R("rect", { key: "ct" + i, x: 30 + i * 150, y: 250 - bh, width: 96, height: bh, fill: rgba(theme.accent2, 0.55) });
          }),
          [0, 1, 2, 3, 4, 5, 6, 7, 8].map((i) => R("rect", { key: "wn" + i, x: 54 + i * 118, y: 190 - (i % 3) * 34, width: 16, height: 20, fill: rgba(theme.accent2, Math.sin(t * 0.7 + i * 2) > 0.4 ? 0.9 : 0.3) }))),
        R("rect", { x: 0, y: 0, width: W, height: 250, fill: "url(#wc-blind)" }),
        R("rect", { x: 0, y: 244, width: W, height: 14, fill: rgba(tint, 0.5) }),
        /* ceiling fan, turning */
        R("g", { transform: "translate(" + (W - 250) + ",300)" },
          R("line", { x1: 0, y1: -50, x2: 0, y2: 0, stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          R("g", { transform: "rotate(" + ((t * 190) % 360).toFixed(1) + ")" },
            [0, 1, 2].map((i) => R("ellipse", { key: "fb" + i, cx: Math.cos(i * 2.094) * 66, cy: Math.sin(i * 2.094) * 66 * 0.32, rx: 60, ry: 13, fill: rgba(tint, 0.4), transform: "rotate(" + (i * 120) + ")" }))),
          R("circle", { r: 14, fill: rgba(tint, 0.6) })),
        R("circle", { cx: W * 0.8, cy: 360, r: 380, fill: "url(#wc-glow)" }),
        /* wall clocks, each running its own hour */
        [0, 1, 2].map((i) => R("g", { key: "cl" + i, transform: "translate(" + (W - 240 + i * 96) + ",180)", opacity: 0.6 },
          R("circle", { r: 40, fill: "none", stroke: rgba(tint, 0.6), strokeWidth: 5 }),
          R("line", { x1: 0, y1: 0, x2: Math.cos(t * 0.1 + i * 2) * 22, y2: Math.sin(t * 0.1 + i * 2) * 22, stroke: rgba(tint, 0.7), strokeWidth: 4, strokeLinecap: "round" }),
          R("line", { x1: 0, y1: 0, x2: Math.cos(t * 1.05 + i) * 32, y2: Math.sin(t * 1.05 + i) * 32, stroke: rgba(theme.accent, 0.8), strokeWidth: 3, strokeLinecap: "round" }))),
        /* strip light overhead */
        R("g", { opacity: 0.6 },
          R("line", { x1: 180, y1: 250, x2: 180, y2: 296, stroke: rgba(tint, 0.5), strokeWidth: 4 }),
          R("line", { x1: 780, y1: 250, x2: 780, y2: 296, stroke: rgba(tint, 0.5), strokeWidth: 4 }),
          R("rect", { x: 140, y: 296, width: 680, height: 34, rx: 8, fill: rgba(theme.surface, inv ? 0.3 : 0.9), stroke: rgba(tint, 0.45), strokeWidth: 4 }),
          R("rect", { x: 160, y: 330, width: 640, height: 10, fill: rgba(theme.accent2, 0.3) })),
        /* pinboard of clippings in the margin */
        R("g", { transform: "translate(" + (W - 118) + ",1190)" },
          R("rect", { x: -112, y: -220, width: 224, height: 440, rx: 6, fill: rgba(theme.accent2, 0.12), stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          [0, 1, 2, 3].map((i) => {
            const lift = Math.sin(t * 1.1 + i * 1.7) * 3;
            return R("g", { key: "cp" + i, transform: "translate(" + (-58 + (i % 2) * 116) + "," + (-146 + Math.floor(i / 2) * 190) + ") rotate(" + (lift + (i % 2 ? 3 : -3)).toFixed(2) + ")" },
              R("rect", { x: -52, y: -60, width: 104, height: 130, rx: 3, fill: rgba(theme.surface, inv ? 0.5 : 0.95), stroke: rgba(tint, 0.3), strokeWidth: 2 }),
              R("rect", { x: -36, y: -40, width: 72, height: 10, rx: 4, fill: rgba(theme.accent, 0.7) }),
              [0, 1, 2].map((j) => R("line", { key: "cl" + j, x1: -36, y1: -14 + j * 18, x2: 36 - (j % 2) * 20, y2: -14 + j * 18, stroke: rgba(tint, 0.35), strokeWidth: 4 })),
              R("circle", { cx: 0, cy: -60, r: 6, fill: rgba(theme.accent, 0.9) }));
          })),
        /* desk row on parallax */
        R("g", { opacity: 0.4, transform: "translate(" + (-feed * 0.3).toFixed(1) + ",0)" },
          [0, 1, 2, 3].map((i) => R("rect", { key: "dk" + i, x: 60 + i * 340, y: deck - 250, width: 250, height: 14, rx: 4, fill: rgba(tint, 0.6) })),
          [0, 1, 2, 3].map((i) => R("rect", { key: "mn" + i, x: 130 + i * 340, y: deck - 340, width: 110, height: 84, rx: 6, fill: "none", stroke: rgba(tint, 0.5), strokeWidth: 5 }))),
        /* a second printer on the back row, and a chair */
        R("g", { opacity: 0.42, transform: "translate(" + (150 - feed * 0.18).toFixed(1) + "," + (deck - 210) + ") scale(0.62)" },
          R("path", { d: "M -150 0 h 300 l -18 -140 h -264 z", fill: rgba(theme.ink, 0.8) }),
          R("rect", { x: -110, y: -186, width: 220, height: 48, rx: 6, fill: rgba(theme.surface, inv ? 0.4 : 0.85) }),
          R("circle", { cx: 110, cy: -86, r: 40, fill: "none", stroke: rgba(theme.surface, 0.6), strokeWidth: 11 })),
        R("g", { opacity: 0.5, transform: "translate(" + (760 - feed * 0.3).toFixed(1) + "," + (deck - 40) + ")" },
          R("path", { d: "M -60 0 h 120 v -18 h -120 z", fill: rgba(tint, 0.6) }),
          R("path", { d: "M 44 -18 v -120 q 0 -22 -26 -22 h -30", fill: "none", stroke: rgba(tint, 0.55), strokeWidth: 9 }),
          R("path", { d: "M -30 0 l -20 40 M 30 0 l 20 40", stroke: rgba(tint, 0.5), strokeWidth: 7, strokeLinecap: "round" })),
        /* the deck */
        R("line", { x1: 0, y1: deck, x2: W, y2: deck, stroke: rgba(tint, 0.55), strokeWidth: 7 }),
        R("rect", { x: 0, y: deck, width: W, height: 22, fill: rgba(tint, 0.24) }),
        /* the tape it has paid out, snaking away */
        R("path", { d: "M 300 " + (deck - 40) + " q -90 70 -170 20 q -80 -50 -110 40", fill: "none", stroke: rgba(theme.surface, inv ? 0.5 : 0.95), strokeWidth: 16, strokeLinecap: "round", strokeDasharray: "1400", strokeDashoffset: (1400 * (1 - tape)).toFixed(0) }),
        R("path", { d: "M 300 " + (deck - 40) + " q -90 70 -170 20 q -80 -50 -110 40", fill: "none", stroke: rgba(tint, 0.35), strokeWidth: 2, strokeDasharray: "1400", strokeDashoffset: (1400 * (1 - tape)).toFixed(0) }),
        /* the teleprinter */
        R("g", { transform: "translate(380," + deck + ")" },
          R("ellipse", { cx: 0, cy: 10, rx: 190, ry: 16, fill: rgba(theme.ink, 0.2) }),
          R("path", { d: "M -160 0 h 320 l -20 -150 h -280 z", fill: rgba(theme.ink, 0.9) }),
          R("path", { d: "M -160 0 h 320 l -6 -44 h -308 z", fill: rgba(theme.surface, 0.16) }),
          R("rect", { x: -120, y: -196 - 6, width: 240, height: 54, rx: 6, fill: rgba(theme.surface, inv ? 0.4 : 0.92), stroke: rgba(tint, 0.4), strokeWidth: 3 }),
          [0, 1, 2, 3].map((i) => R("rect", { key: "ln" + i, x: -100 + i * 58, y: -180, width: 38, height: 8, rx: 4, fill: rgba(theme.accent, 0.7 - i * 0.12) })),
          R("g", { transform: "translate(120,-90) rotate(" + spool.toFixed(1) + ")" },
            R("circle", { r: 46, fill: "none", stroke: rgba(theme.surface, 0.7), strokeWidth: 12 }),
            R("path", { d: "M -46 0 h 92 M 0 -46 v 92", stroke: rgba(theme.accent, 0.6), strokeWidth: 5 })),
          R("rect", { x: -190, y: -60, width: 60, height: 60, rx: 4, fill: rgba(theme.accent2, 0.6) })),
        /* a cup, still going */
        R("g", { transform: "translate(660," + deck + ")" },
          R("path", { d: "M -40 -56 h 80 l -8 56 h -64 z", fill: rgba(theme.surface, inv ? 0.45 : 0.94), stroke: rgba(tint, 0.5), strokeWidth: 4 }),
          R("path", { d: "M 40 -44 q 30 4 26 22 q -4 17 -28 15", fill: "none", stroke: rgba(tint, 0.5), strokeWidth: 5 }),
          [0, 1, 2].map((i) => {
            const ph = ((t * 0.5 + i * 0.34) % 1);
            const sw = Math.sin(t * 1.5 + i * 2) * 14;
            return R("path", { key: "cs" + i, d: "M " + (-16 + i * 16) + " -70 q " + sw.toFixed(1) + " -46 " + (sw * 0.4).toFixed(1) + " -92", fill: "none", stroke: rgba(inv ? theme.surface : theme.ink, 0.3 * (1 - ph)), strokeWidth: 7, strokeLinecap: "round", transform: "translate(0," + (-ph * 120).toFixed(1) + ")" });
          })),
        /* in-trays stacked on the deck */
        R("g", { transform: "translate(870," + deck + ")" },
          [0, 1, 2].map((i) => R("g", { key: "it" + i },
            R("rect", { x: -76, y: -34 - i * 40, width: 152, height: 26, rx: 3, fill: "none", stroke: rgba(tint, 0.5), strokeWidth: 4 }),
            R("rect", { x: -64, y: -46 - i * 40, width: 128 - i * 14, height: 14, rx: 2, fill: rgba(theme.surface, inv ? 0.4 : 0.9) })))),
        /* spike file and tray */
        R("g", { transform: "translate(" + (W - 150) + "," + deck + ")" },
          R("line", { x1: 0, y1: 0, x2: 0, y2: -130, stroke: rgba(tint, 0.7), strokeWidth: 6 }),
          [0, 1, 2].map((i) => R("path", { key: "sp" + i, d: "M -60 " + (-30 - i * 26) + " h 120 l -10 18 h -100 z", fill: rgba(theme.surface, inv ? 0.4 : 0.9), stroke: rgba(tint, 0.35), strokeWidth: 2 })),
          R("circle", { cx: 0, cy: -134, r: 8, fill: rgba(theme.accent, 0.8) })),
        /* near plane */
        [0, 1, 2, 3, 4].map((i) => {
          const ph = (t * (0.2 + i * 0.04) + i * 0.21) % 1;
          const x = 120 + i * 210 + Math.sin(t * 1.1 + i) * 40, y = H - ph * (H + 180);
          return R("rect", { key: "tp" + i, x: x, y: y, width: 26, height: 8, rx: 4, fill: rgba(tint, 0.3 * (1 - ph)), transform: "rotate(" + (ph * 320 + i * 40).toFixed(1) + " " + x.toFixed(1) + " " + y.toFixed(1) + ")" });
        }));
    },
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
