// VIDEO EDIT RENDER EXPRESSIONS — crop geometry and FFmpeg filter-graph fragments for framing, effects and overlays
// (RENDER.md §4, §5; spike S1).
//
// WHY THIS EXISTS. The A-roll chunk renderer and the composite pass build large `-/filter_complex` scripts, and every
// effect in them has a trap measured on this ffmpeg: crop w/h are evaluated once (never animate them), crop x/y snap to
// even pixels on yuv420p unless `exact=1` (a pan then moves in 2 px steps), zoompan rounds its crop to whole pixels
// (≈1–4 px wobble), `perspective`'s frame counter `in` is 1-based, frame-based alpha fades start at alpha 0 on the
// first frame, and RGB overlays convert with BT.601 unless the base is tagged. Keeping all of that in one pure module
// means compose/aroll/composite concatenate strings instead of re-deriving the rules.
//
// CONVENTIONS. All times are integer frames at 30 fps; any seconds value is derived from frames and printed with 6
// decimals. Pads are bare names ([A-Za-z0-9_]); builders wrap them in brackets. Graph builders return
//   Fragment = { graph: string (';'-joined chains), inputs: InputSpec[], outLabel, nextInputIndex }
//   InputSpec = { role, path, format, options: string[] (input options placed before -i) }
// where `inputIndex` is the ffmpeg input index the caller will give the fragment's first extra input (in order).
// `inputArgs(spec)` turns a spec into `[...options, -protocol_whitelist file, -f <fmt>, -i file:<path>]`.
//
// CONTRACT (pure, no I/O):
//   cropForZoom({ mezz:{w,h}, output:{w,h}, cx=.5, cy=.5, zoom=1, faceYTarget=.4, exactAspect=false })
//     -> { x, y, w, h, zoom, effectiveZoom, aspectErrPx }   even w/h/x/y, inside the frame; the crop aspect is within
//        1 px of the output aspect (exactAspect: w·outH === h·outW exactly, zoom quantized to the aspect lattice).
//   staticFramingFilter({ crop, out }) -> chain
//   panExpr(keyframes:[{ src|atS, x, y }], pieceStartS) -> { x:"'expr'", y:"'expr'", segments }
//   panFramingFilter({ crop:{w,h}, keyframes, pieceStartS, out|null }) -> chain
//   zoomKExpr({ z0, z1, frames, ease }) · perspectiveZoomFilter({ crop, z0, z1, frames, out|null, ease='smoothstep', anchor })
//   freezeFilters({ holdFrames }) -> { video, audio } · speedFilters({ rate, srcFrames }) -> { video, audio, outFrames }
//   blurFillFilter({ inLabel, outLabel, out }) -> Fragment
//   splitStackFilter({ faceLabel, outLabel, out, faceCrop, side, broll:{ path, startFrame=0, frames }, inputIndex })
//   fullBrollOverlay({ baseLabel, outLabel, clip:{ path }, outInF, outOutF, fadeInF=4, fadeOutF=4, x=0, y=0, inputIndex })
//   pipOverlay({ baseLabel, outLabel, clip:{ path }, box:{x,y,w,h}, radius=24, outInF, outOutF, fadeInF, fadeOutF,
//                inputIndex, maskPath?, shadowPath? })
//   dipOverlay({ baseLabel, outLabel, out:{w,h}, jointF, halfFrames, kind:'DIP_BLACK'|'DIP_WHITE'|'FLASH' })
//   logoOverlay({ baseLabel, outLabel, logo:{ path }, box:{x,y,w}, opacity=1, show='always'|'intro_outro',
//                 totalFrames, introFrames=90, outroFrames=90, inputIndex })
//   pipMaskFiles({ box, radius }) · PIP_MASK · inputArgs · inputFormatFor · fmt6 · evenRound · evenFloor
//   COLOR_TAG_FILTER · COLOR_ARGS · FPS
// Throws EditError FX_INVALID (bug class: these inputs come from our own composition builder).

const path = require("node:path");
const { EditError } = require("../errors");

const FPS = 30;
const COLOR_TAG_FILTER = "setparams=colorspace=bt709:color_primaries=bt709:color_trc=bt709:range=tv";
const COLOR_ARGS = Object.freeze(["-colorspace", "bt709", "-color_primaries", "bt709", "-color_trc", "bt709", "-color_range", "tv"]);

// Rounded-corner PIP masks shipped in server/assets/masks (generated by scripts/video_edit_gen_masks.js from this
// table). Geometry is defined for a box whose short side is 540 px and scaled uniformly to the real box, so the corner
// radius is proportional to the box (the same look at preview540 and export1080). A box must match one shipped aspect.
const PIP_MASK = Object.freeze({
  dir: path.resolve(__dirname, "../../../assets/masks"),
  refShort: 540,
  radii: Object.freeze([24, 32]),
  aspects: Object.freeze({ "16x9": Object.freeze([960, 540]), "9x16": Object.freeze([540, 960]), "1x1": Object.freeze([540, 540]) }),
  shadow: Object.freeze({ margin: 48, sigma: 10, offsetY: 10, opacity: 0.45 }),
  aspectTolerance: 0.015,
});

const invalid = (detail) => new EditError("FX_INVALID", { status: 500, errorClass: "bug", detail });
const fmt6 = (x) => (Math.round(Number(x) * 1e6) / 1e6).toFixed(6);
const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
const evenFloor = (v) => Math.max(2, Math.floor(v / 2) * 2);
const evenRound = (v) => Math.round(v / 2) * 2;
// Shortest decimal form (≤ 6 dp): 1 → "1", 0.12 → "0.12" — so generated strings match the S1 literals.
const num = (v) => { const r = Math.round(Number(v) * 1e6) / 1e6; return Object.is(r, -0) ? "0" : String(r); };
const gcd = (a, b) => (b ? gcd(b, a % b) : a);

function posInt(v, name, { min = 1 } = {}) {
  if (!Number.isInteger(v) || v < min) throw invalid(`${name} must be an integer ≥ ${min}`);
  return v;
}
function dims(o, name) {
  if (!o || !Number.isFinite(o.w) || !Number.isFinite(o.h) || o.w < 2 || o.h < 2) throw invalid(`${name} {w,h} required`);
  return { w: Math.round(o.w), h: Math.round(o.h) };
}
function label(l, name) {
  if (typeof l !== "string" || !/^[A-Za-z0-9_]{1,64}$/.test(l)) throw invalid(`${name} must be a bare pad name`);
  return l;
}

// ---- inputs -----------------------------------------------------------------------------------------------------
const IMAGE_EXT = new Set([".png", ".jpg", ".jpeg", ".webp", ".bmp"]);
function inputFormatFor(file) {
  const ext = path.extname(String(file)).toLowerCase();
  if (IMAGE_EXT.has(ext)) return "image2";
  return { ".mp4": "mov", ".mov": "mov", ".m4v": "mov", ".webm": "matroska", ".mkv": "matroska" }[ext] || null;
}
function inputArgs(spec) {
  if (!spec || typeof spec.path !== "string" || !spec.path) throw invalid("input spec needs a path");
  const f = spec.format === undefined ? inputFormatFor(spec.path) : spec.format;
  return [...(spec.options || []), "-protocol_whitelist", "file", ...(f ? ["-f", f] : []), "-i", `file:${spec.path}`];
}
// A still (PNG mask, logo) that must produce exactly `frames` frames starting at output frame `atF`.
function stillInput(role, p, { atF = 0, frames }) {
  const options = ["-loop", "1", "-framerate", String(FPS), "-t", fmt6((frames + 1) / FPS)];
  if (atF > 0) options.push("-itsoffset", fmt6(atF / FPS));
  return { role, path: p, format: "image2", options };
}

// ---- crop geometry ----------------------------------------------------------------------------------------------
function cropForZoom({ mezz, output, cx = 0.5, cy = 0.5, zoom = 1, faceYTarget = 0.4, exactAspect = false } = {}) {
  const M = dims(mezz, "mezz"), O = dims(output, "output");
  const z = Number(zoom);
  if (!(z >= 1 && z <= 4)) throw invalid("zoom must be in [1, 4]");
  const W = M.w, H = M.h, A = O.w / O.h;
  const heightLimited = H * A <= W;
  const bw = Math.min(W, H * A), bh = bw / A;
  let w, h;
  if (exactAspect) {
    const g = gcd(O.w, O.h);
    let uw = O.w / g, uh = O.h / g;
    if (uw % 2 || uh % 2) { uw *= 2; uh *= 2; }
    const m = Math.floor(Math.min(bw / z / uw, bh / z / uh) + 1e-9);
    if (m < 1) throw invalid("mezz too small for an exact-aspect crop");
    w = m * uw; h = m * uh;
  } else if (heightLimited) {
    h = Math.min(evenFloor(bh / z + 1e-9), evenFloor(H));
    w = Math.min(Math.max(2, evenRound(h * A)), evenFloor(W));
  } else {
    w = Math.min(evenFloor(bw / z + 1e-9), evenFloor(W));
    h = Math.min(Math.max(2, evenRound(w / A)), evenFloor(H));
  }
  const fx = clamp(Number.isFinite(cx) ? cx : 0.5, 0, 1), fy = clamp(Number.isFinite(cy) ? cy : 0.5, 0, 1);
  const yt = Number.isFinite(faceYTarget) ? faceYTarget : 0.4;
  const x = clamp(evenRound(fx * W - w / 2), 0, Math.floor((W - w) / 2) * 2);
  const y = clamp(evenRound(fy * H - yt * h), 0, Math.floor((H - h) / 2) * 2);
  return {
    x, y, w, h, zoom: z,
    effectiveZoom: Math.round((heightLimited ? bh / h : bw / w) * 1e6) / 1e6,
    aspectErrPx: Math.round((heightLimited ? Math.abs(w - h * A) : Math.abs(h - w / A)) * 1e6) / 1e6,
  };
}

function cropArgs(crop) {
  for (const k of ["x", "y", "w", "h"]) if (!Number.isInteger(crop && crop[k])) throw invalid(`crop.${k} must be an integer`);
  return `crop=${crop.w}:${crop.h}:${crop.x}:${crop.y}`;
}
const scaleTo = (out) => { const o = dims(out, "out"); return `scale=${o.w}:${o.h}:flags=lanczos,setsar=1`; };

function staticFramingFilter({ crop, out } = {}) {
  return `${cropArgs(crop)},${scaleTo(out)}`;
}

// ---- pan ----------------------------------------------------------------------------------------------------------
// Piecewise smoothstep in piece-relative t (RENDER.md §4). Consecutive keyframes with equal values hold; different
// values ease with 3p²−2p³ between them. Nested if(lt()) so later segments are never evaluated early.
function axisExpr(pts, key) {
  const v = (i) => num(pts[i][key]);
  let expr = v(pts.length - 1);
  for (let i = pts.length - 2; i >= 0; i--) {
    const a = pts[i], b = pts[i + 1];
    const d = b.t - a.t;
    let seg;
    if (a[key] === b[key] || d < 1 / FPS - 1e-9) seg = v(i);
    else {
      const p = `((t-${fmt6(a.t)})/${fmt6(d)})`;
      seg = `${v(i)}+(${num(b[key] - a[key])})*(3*${p}*${p}-2*${p}*${p}*${p})`;
    }
    expr = `if(lt(t,${fmt6(b.t)}),${seg},${expr})`;
  }
  return `'round(${expr})'`;
}

function panExpr(keyframes, pieceStartS = 0) {
  if (!Array.isArray(keyframes) || !keyframes.length) throw invalid("panExpr needs keyframes");
  const base = Number(pieceStartS) || 0;
  const pts = keyframes.map((k) => {
    const src = Number.isFinite(k.atS) ? k.atS : k.src;
    if (!Number.isFinite(src) || !Number.isFinite(k.x) || !Number.isFinite(k.y)) throw invalid("keyframe needs src, x, y");
    // Snap to the frame grid so a keyframe lands exactly on a frame's t.
    return { t: Math.max(0, Math.round((src - base) * FPS) / FPS), x: Math.round(k.x), y: Math.round(k.y) };
  }).sort((a, b) => a.t - b.t);
  if (pts.length > 200) throw invalid("too many pan keyframes in one piece");
  const first = pts[0];
  if (first.t > 0) pts.unshift({ t: 0, x: first.x, y: first.y });
  return { x: axisExpr(pts, "x"), y: axisExpr(pts, "y"), segments: pts.length - 1 };
}

function panFramingFilter({ crop, keyframes, pieceStartS = 0, out = null } = {}) {
  const c = dims(crop, "crop");
  const e = panExpr(keyframes, pieceStartS);
  const chain = `crop=w=${c.w}:h=${c.h}:x=${e.x}:y=${e.y}:exact=1`;
  return out ? `${chain},${scaleTo(out)}` : chain;
}

// ---- animated zoom (S1: perspective, 1-based in) -----------------------------------------------------------------------
function zoomKExpr({ z0 = 1, z1, frames, ease = "smoothstep" } = {}) {
  posInt(frames, "frames", { min: 2 });
  if (!(z0 >= 1 && z0 <= 2) || !(z1 >= 1 && z1 <= 2)) throw invalid("zoom must be in [1, 2]");
  const p = `min(max((in-1),0)/${frames - 1},1)`;
  const shape = ease === "linear" ? p : `(3*pow(${p},2)-2*pow(${p},3))`;
  return `((1-1/(${num(z0)}+${num(z1 - z0)}*${shape}))/2)`;
}

function perspectiveZoomFilter({ crop, z0 = 1, z1, frames, out = null, ease = "smoothstep", anchor = null } = {}) {
  const K = zoomKExpr({ z0, z1, frames, ease });
  const ax = anchor && Number.isFinite(anchor.fx) ? clamp(anchor.fx, 0, 1) : 0.5;
  const ay = anchor && Number.isFinite(anchor.fy) ? clamp(anchor.fy, 0, 1) : 0.5;
  // Corner offsets 2·a·K (left/top) and 2·(1−a)·K (right/bottom) keep the anchor fixed; a = .5 gives the S1 string.
  const m = (f) => (Math.abs(f - 1) < 1e-9 ? "" : `${num(f)}*`);
  const L = m(2 * ax), R = m(2 * (1 - ax)), T = m(2 * ay), B = m(2 * (1 - ay));
  const persp = `perspective=x0='W*${L}${K}':y0='H*${T}${K}':x1='W-W*${R}${K}':y1='H*${T}${K}':`
    + `x2='W*${L}${K}':y2='H-H*${B}${K}':x3='W-W*${R}${K}':y3='H-H*${B}${K}':interpolation=linear:sense=source:eval=frame`;
  const head = crop ? `${cropArgs(crop)},` : "";
  return out ? `${head}${persp},${scaleTo(out)}` : `${head}${persp},setsar=1`;
}

// ---- freeze / speed -----------------------------------------------------------------------------------------------
function freezeFilters({ holdFrames } = {}) {
  posInt(holdFrames, "holdFrames");
  return { video: `tpad=stop_mode=clone:stop=${holdFrames}`, audio: `apad=pad_len=${holdFrames * 1600}` };
}

function atempoChain(rate) {
  const f = [];
  let r = rate;
  while (r > 2 + 1e-9) { f.push("atempo=2"); r /= 2; }
  while (r < 0.5 - 1e-9) { f.push("atempo=0.5"); r /= 0.5; }
  if (Math.abs(r - 1) > 1e-9) f.push(`atempo=${num(r)}`);
  return f.join(",");
}

function speedFilters({ rate, srcFrames } = {}) {
  const R = Number(rate);
  if (!(R >= 0.25 && R <= 4)) throw invalid("rate must be in [0.25, 4]");
  posInt(srcFrames, "srcFrames");
  const outFrames = Math.max(1, Math.round(srcFrames / R));
  // fps can drop the final frame at EOF; clone-pad then trim pins the count (plan/timeline.js length).
  const video = `setpts=(PTS-STARTPTS)/${num(R)},fps=${FPS},tpad=stop_mode=clone:stop=2,trim=end_frame=${outFrames},setpts=PTS-STARTPTS`;
  return { video, audio: atempoChain(R), outFrames };
}

// ---- A-roll layouts -------------------------------------------------------------------------------------------------
function blurFillFilter({ inLabel, outLabel, out } = {}) {
  const i = label(inLabel, "inLabel"), o = label(outLabel, "outLabel"), O = dims(out, "out");
  // Blur on a cover-cropped OW/8 × OH/8 canvas: boxblur's radius must fit half the chroma plane, which a
  // width-only `scale=OW/8:-2` breaks for landscape sources in portrait outputs (measured: EINVAL).
  const sw = Math.max(4, evenRound(O.w / 8)), sh = Math.max(4, evenRound(O.h / 8));
  const radius = Math.max(1, Math.min(10, Math.floor(Math.min(sw, sh) / 4)));
  const graph = [
    `[${i}]split=2[${o}_a][${o}_b]`,
    `[${o}_a]scale=${sw}:${sh}:force_original_aspect_ratio=increase,crop=${sw}:${sh},boxblur=${radius}:1,scale=${O.w}:${O.h},setsar=1[${o}_bg]`,
    `[${o}_b]scale=${O.w}:${O.h}:force_original_aspect_ratio=decrease:force_divisible_by=2:flags=lanczos,setsar=1[${o}_fg]`,
    `[${o}_bg][${o}_fg]overlay=(W-w)/2:(H-h)/2,setsar=1[${o}]`,
  ].join(";");
  return { graph, inputs: [], outLabel: o, nextInputIndex: null };
}

function splitStackFilter({ faceLabel, outLabel, out, faceCrop, side = "top", broll, inputIndex } = {}) {
  const f = label(faceLabel, "faceLabel"), o = label(outLabel, "outLabel"), O = dims(out, "out");
  posInt(inputIndex, "inputIndex");
  if (!broll || typeof broll.path !== "string") throw invalid("split needs broll.path");
  const frames = posInt(broll.frames, "broll.frames");
  const start = Number.isInteger(broll.startFrame) && broll.startFrame > 0 ? broll.startFrame : 0;
  const vertical = side === "top" || side === "bottom";
  if (!vertical && side !== "left" && side !== "right") throw invalid("side must be top|bottom|left|right");
  const half = vertical ? { w: O.w, h: O.h / 2 } : { w: O.w / 2, h: O.h };
  if (!Number.isInteger(half.w) || !Number.isInteger(half.h) || half.w % 2 || half.h % 2) throw invalid("split halves must be even");
  const brollFirst = side === "top" || side === "left";
  const graph = [
    `[${f}]${cropArgs(faceCrop)},scale=${half.w}:${half.h}:flags=lanczos,setsar=1,format=yuv420p[${o}_face]`,
    `[${inputIndex}:v]trim=start_frame=${start},setpts=PTS-STARTPTS,tpad=stop_mode=clone:stop=${frames},trim=end_frame=${frames},`
      + `scale=${half.w}:${half.h}:force_original_aspect_ratio=increase:flags=lanczos,crop=${half.w}:${half.h},setsar=1,format=yuv420p[${o}_br]`,
    `${brollFirst ? `[${o}_br][${o}_face]` : `[${o}_face][${o}_br]`}${vertical ? "vstack" : "hstack"}=inputs=2[${o}]`,
  ].join(";");
  return { graph, inputs: [{ role: "split_broll", path: broll.path, format: inputFormatFor(broll.path), options: [] }], outLabel: o, nextInputIndex: inputIndex + 1 };
}

// ---- composite overlays ---------------------------------------------------------------------------------------------
// Frame-based alpha fades (measured): fade in over F frames gives alpha k/F on local frame k (frame 0 transparent,
// frame F opaque); fade out starting at N−F gives 1, (F−1)/F … 1/F on the last frame.
function alphaFades(n, fadeInF, fadeOutF) {
  const f = [];
  if (fadeInF > 0) f.push(`fade=t=in:s=0:n=${fadeInF}:alpha=1`);
  if (fadeOutF > 0) f.push(`fade=t=out:s=${Math.max(0, n - fadeOutF)}:n=${fadeOutF}:alpha=1`);
  return f;
}

function spanOf({ outInF, outOutF, fadeInF = 4, fadeOutF = 4 }) {
  posInt(outInF, "outInF", { min: 0 });
  posInt(outOutF, "outOutF", { min: outInF + 1 });
  const n = outOutF - outInF;
  const fi = Math.min(posInt(fadeInF, "fadeInF", { min: 0 }), Math.floor(n / 2));
  const fo = Math.min(posInt(fadeOutF, "fadeOutF", { min: 0 }), Math.floor(n / 2));
  return { n, fi, fo };
}
const videoInput = (role, p, atF) => ({ role, path: p, format: inputFormatFor(p), options: atF > 0 ? ["-itsoffset", fmt6(atF / FPS)] : [] });

function fullBrollOverlay({ baseLabel, outLabel, clip, outInF, outOutF, fadeInF = 4, fadeOutF = 4, x = 0, y = 0, inputIndex } = {}) {
  const b = label(baseLabel, "baseLabel"), o = label(outLabel, "outLabel");
  posInt(inputIndex, "inputIndex");
  if (!clip || typeof clip.path !== "string") throw invalid("clip.path required");
  const { n, fi, fo } = spanOf({ outInF, outOutF, fadeInF, fadeOutF });
  const chain = [`trim=end_frame=${n}`, "format=yuva420p", ...alphaFades(n, fi, fo)].join(",");
  const graph = `[${inputIndex}:v]${chain}[${o}_ov];[${b}][${o}_ov]overlay=${Math.round(x)}:${Math.round(y)}:eof_action=pass[${o}]`;
  return { graph, inputs: [videoInput("broll", clip.path, outInF)], outLabel: o, nextInputIndex: inputIndex + 1 };
}

function pipMaskFiles({ box, radius = 24 } = {}) {
  const B = dims(box, "box");
  if (!PIP_MASK.radii.includes(radius)) throw invalid(`radius must be one of ${PIP_MASK.radii.join(",")}`);
  const want = B.w / B.h;
  let best = null;
  for (const [key, [rw, rh]] of Object.entries(PIP_MASK.aspects)) {
    const err = Math.abs(want / (rw / rh) - 1);
    if (!best || err < best.err) best = { key, rw, rh, err };
  }
  if (best.err > PIP_MASK.aspectTolerance) throw invalid(`PIP box ${B.w}x${B.h} matches no shipped mask aspect`);
  const s = B.w / best.rw;
  const { margin } = PIP_MASK.shadow;
  const sw = evenRound((best.rw + 2 * margin) * s), sh = evenRound((best.rh + 2 * margin) * s);
  return {
    aspectKey: best.key, scale: s,
    mask: path.join(PIP_MASK.dir, `pip_r${radius}_${best.key}.png`),
    shadow: path.join(PIP_MASK.dir, `pip_r${radius}_${best.key}_shadow.png`),
    shadowSize: { w: sw, h: sh }, shadowOffset: { x: -Math.round((sw - B.w) / 2), y: -Math.round((sh - B.h) / 2) },
  };
}

function pipOverlay({ baseLabel, outLabel, clip, box, radius = 24, outInF, outOutF, fadeInF = 4, fadeOutF = 4, inputIndex, maskPath, shadowPath } = {}) {
  const b = label(baseLabel, "baseLabel"), o = label(outLabel, "outLabel");
  posInt(inputIndex, "inputIndex");
  if (!clip || typeof clip.path !== "string") throw invalid("clip.path required");
  if (!box || !Number.isInteger(box.x) || !Number.isInteger(box.y)) throw invalid("box {x,y,w,h} integers required");
  const B = dims(box, "box");
  const { n, fi, fo } = spanOf({ outInF, outOutF, fadeInF, fadeOutF });
  const mf = pipMaskFiles({ box: B, radius });
  const ci = inputIndex, mi = inputIndex + 1, si = inputIndex + 2;
  const fades = alphaFades(n, fi, fo);
  const graph = [
    `[${ci}:v]trim=end_frame=${n},scale=${B.w}:${B.h}:flags=lanczos,setsar=1,format=yuva420p[${o}_c]`,
    `[${mi}:v]trim=end_frame=${n},scale=${B.w}:${B.h}:flags=bicubic,format=gray[${o}_m]`,
    `[${o}_c][${o}_m]alphamerge${fades.length ? "," + fades.join(",") : ""}[${o}_pa]`,
    `[${si}:v]trim=end_frame=${n},scale=${mf.shadowSize.w}:${mf.shadowSize.h}:flags=bicubic,format=yuva420p${fades.length ? "," + fades.join(",") : ""}[${o}_s]`,
    `[${b}][${o}_s]overlay=${box.x + mf.shadowOffset.x}:${box.y + mf.shadowOffset.y}:eof_action=pass[${o}_t]`,
    `[${o}_t][${o}_pa]overlay=${box.x}:${box.y}:eof_action=pass[${o}]`,
  ].join(";");
  const inputs = [
    videoInput("pip", clip.path, outInF),
    stillInput("pip_mask", maskPath || mf.mask, { atF: outInF, frames: n }),
    stillInput("pip_shadow", shadowPath || mf.shadow, { atF: outInF, frames: n }),
  ];
  return { graph, inputs, outLabel: o, nextInputIndex: inputIndex + 3 };
}

function dipOverlay({ baseLabel, outLabel, out, jointF, halfFrames, kind = "DIP_BLACK" } = {}) {
  const b = label(baseLabel, "baseLabel"), o = label(outLabel, "outLabel"), O = dims(out, "out");
  posInt(jointF, "jointF", { min: 0 });
  const T = posInt(halfFrames, "halfFrames");
  const color = { DIP_BLACK: "black", DIP_WHITE: "white", FLASH: "white@0.7" }[kind];
  if (!color) throw invalid("kind must be DIP_BLACK|DIP_WHITE|FLASH");
  const startF = Math.max(0, jointF - T);
  const graph = [
    `color=c=${color}:s=${O.w}x${O.h}:r=${FPS},format=yuva420p,trim=end_frame=${2 * T},`
      + `fade=t=in:s=0:n=${T}:alpha=1,fade=t=out:s=${T}:n=${T}:alpha=1,settb=1/${FPS},setpts=N+${startF}[${o}_d]`,
    `[${b}][${o}_d]overlay=0:0:eof_action=pass[${o}]`,
  ].join(";");
  return { graph, inputs: [], outLabel: o, nextInputIndex: null };
}

function logoOverlay({ baseLabel, outLabel, logo, box, opacity = 1, show = "always", totalFrames, introFrames = 90, outroFrames = 90, inputIndex } = {}) {
  const b = label(baseLabel, "baseLabel"), o = label(outLabel, "outLabel");
  posInt(inputIndex, "inputIndex");
  posInt(totalFrames, "totalFrames");
  if (!logo || typeof logo.path !== "string") throw invalid("logo.path required");
  if (!box || !Number.isInteger(box.x) || !Number.isInteger(box.y) || !Number.isInteger(box.w) || box.w < 2) throw invalid("box {x,y,w} integers required");
  const a = clamp(Number(opacity), 0, 1);
  let enable = "";
  if (show === "intro_outro") {
    const i = posInt(introFrames, "introFrames", { min: 0 }), e = posInt(outroFrames, "outroFrames", { min: 0 });
    enable = `:enable='lt(t,${fmt6((i - 0.5) / FPS)})+gte(t,${fmt6((totalFrames - e - 0.5) / FPS)})'`;
  } else if (show !== "always") throw invalid("show must be always|intro_outro");
  const graph = [
    `[${inputIndex}:v]trim=end_frame=${totalFrames},scale=${box.w}:-1:flags=lanczos,format=rgba${a < 1 ? `,colorchannelmixer=aa=${num(a)}` : ""}[${o}_l]`,
    `[${b}][${o}_l]overlay=${box.x}:${box.y}:eof_action=pass${enable}[${o}]`,
  ].join(";");
  return { graph, inputs: [stillInput("logo", logo.path, { frames: totalFrames })], outLabel: o, nextInputIndex: inputIndex + 1 };
}

module.exports = {
  cropForZoom, staticFramingFilter, panExpr, panFramingFilter, zoomKExpr, perspectiveZoomFilter, freezeFilters, speedFilters,
  atempoChain, blurFillFilter, splitStackFilter, fullBrollOverlay, pipOverlay, pipMaskFiles, dipOverlay, logoOverlay,
  inputArgs, inputFormatFor, fmt6, evenRound, evenFloor, PIP_MASK, COLOR_TAG_FILTER, COLOR_ARGS, FPS,
};
