// ALLOTMENT — skin for the shared long-form stage (services/lf_stage.js).
//
// GENERATED by scripts/gen-lf-skins.js from the handoff source
// (templete-design/longform-handoff/engine/lf-pack-4.js, template "Allotment").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Zilla Slab / body Source Sans 3. Camera set ["zoomOut","pushU","hopU","pushL","drop","pushR"] at stride 3/2.
// 40 scenes, 300.5s, the canonical spine unmodified.
//
// palette and World below are the AUTHORED functions, emitted verbatim. The World is
// re-evaluated per seek against an SVG-DOM shim whose entire surface is {R, rgba} plus the
// utils object — verified by evaluating all 30 authored Worlds against exactly that sandbox —
// so the backdrop is not a reinterpretation of the original, it IS the original.

const stage = require("../lf_stage");

const SKIN = {
  id: "allotment",
  label: "Allotment",

  // ---- type ----
  display: "Zilla Slab", displayFallback: "Georgia, serif",
  body: "Source Sans 3", bodyFallback: "system-ui, sans-serif",
  em: 0.6055, bodyEm: 0.549,

  // ---- palette ----
  // The authored function, called with {} for the design's own defaults. It returns the same
  // six roles on every one of the 27 films, so the stage can rely on them by name: paper and
  // ink are the type system, sageT and terraT are the alternating tinted grounds, and
  // accent/accent2 are the two a brand may take over at their authored luminance.
  palette: (t) => ({ paper: "#f2f0e0", ink: "#22301f", accent: t.accent || "#c4622c", accent2: t.accent2 || "#4d8c3f", sageT: "#e6eedc", terraT: "#f6e3cd" }),
  accents: ["accent","accent2"],
  accentOpts: ["#c4622c","#a8462c","#c49a2c"],
  accent2Opts: ["#4d8c3f","#2c7a6b","#7a8c3f"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  desk: "#1e2a1a",

  // ---- camera + motion ----
  cams: ["zoomOut","pushU","hopU","pushL","drop","pushR"],
  camStride: 3, camOff: 2,
  ambient: 1.5,

  // ---- the garnish voice ----
  // Rotated by scene index so no two consecutive frames read the same. Authored copy.
  tags: ["ALLOTMENT · PLOT 14","SIX METRES BY TWELVE","THE SHED IS THE POINT","SLUGS: ONGOING","FIRST FROST DECIDES"],
  foots: ["everything here was eaten or given away","the robin supervises all digging","plot 14, second from the tap","compost turned twice a year, badly","the shed kettle is the real amenity"],
  sides: ["DIG · SOW · WATER · EAT","SIX BY TWELVE METRES","THE ROBIN IS IN CHARGE"],

  // ---- the spine ----
  // Which renderer runs at which index. The stage owns the canonical 40-name order; this is
  // only what THIS film does differently. ["insert", i, name] splices, [i, name] substitutes.
  // Resolves to: 40 scenes.
  spineOverrides: [],

  strings: {
    brandName: "Allotment",
  },

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, utils) — no Math.random, no
  // Date, no accumulated state anywhere in the six pack files — which is what lets it be
  // re-evaluated deterministically on every seek, forwards or backwards.
  World: (th, t, u) => R("g", null,
      R("path", { d: "M -20 " + (u.H - 200) + " q 300 -30 620 -8 q 340 20 700 -20 L " + (u.W + 20) + " " + (u.H + 20) + " L -20 " + (u.H + 20) + " Z", fill: rgba("#6b5330", 0.4) }),
      Array.from({ length: 4 }).map((_, row) => R("g", { key: "r" + row },
        Array.from({ length: 7 }).map((_, k) => {
          const g = ((t * 0.12 + row * 0.2 + k * 0.05) % 1.4);
          const h = Math.min(1, g) * (46 + row * 14);
          const x = 180 + k * 160 + row * 26, y = u.H - 150 - row * 46;
          return R("g", { key: k, transform: "translate(" + x + "," + y + ")" },
            R("line", { x1: 0, y1: 0, x2: Math.sin(t * 0.9 + k) * 5, y2: -h, stroke: th.accent2, strokeWidth: 7, strokeLinecap: "round" }),
            R("path", { d: "M 0 " + (-h) + " q 34 -18 44 4 M 0 " + (-h) + " q -34 -18 -44 4", fill: "none", stroke: th.accent2, strokeWidth: 6, strokeLinecap: "round" }));
        }))),
      (function () {
        const pour = ((t * 0.3) % 1);
        return R("g", { transform: "translate(" + (u.W - 260) + ",300) rotate(" + (26 + pour * 14) + ")" },
          R("path", { d: "M -70 -40 h 120 v 90 h -120 z", fill: rgba(th.accent, 0.85), rx: 10 }),
          R("path", { d: "M 50 -20 l 90 -46 l 16 22 l -84 54 z", fill: rgba(th.accent, 0.85) }),
          R("path", { d: "M -70 -30 q -50 40 -6 70", fill: "none", stroke: rgba(th.accent, 0.85), strokeWidth: 12 }),
          Array.from({ length: 4 }).map((_, k) => R("circle", { key: k, cx: 150 + k * 8, cy: -30 + ((pour * 240 + k * 40) % 240), r: 5, fill: rgba(th.accent2, 0.6) })));
      })(),
      (function () {
        const hop = Math.sin(t * 3) > 0.85 ? -18 : 0;
        const rx = 300 + Math.sin(t * 0.3) * 120;
        return R("g", { transform: "translate(" + rx + "," + (u.H - 120 + hop) + ")" },
          R("ellipse", { rx: 22, ry: 18, fill: rgba(th.ink, 0.85) }),
          R("circle", { cx: 16, cy: -14, r: 11, fill: rgba(th.ink, 0.85) }),
          R("circle", { cx: 2, cy: 4, r: 10, fill: th.accent }),
          R("path", { d: "M 26 -15 l 14 3 l -14 4 z", fill: rgba(th.accent, 0.9) }),
          R("line", { x1: -4, y1: 16, x2: -6, y2: 30, stroke: rgba(th.ink, 0.85), strokeWidth: 4 }));
      })(),
      R("rect", { x: 90, y: u.H - 420, width: 210, height: 220, rx: 8, fill: rgba("#6b5330", 0.5) }),
      R("path", { d: "M 80 " + (u.H - 420) + " l 105 -70 l 105 70 z", fill: rgba("#6b5330", 0.65) })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
