// DAWN CHORUS — skin for the shared long-form stage (services/lf_stage.js).
//
// GENERATED by scripts/gen-lf-skins.js from the handoff source
// (templete-design/longform-handoff/engine/lf-pack-2.js, template "DawnChorus").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Fraunces / body Mulish. Camera set ["zoomOut","pushU","drop","pushR","zoomIn"] at stride 3/1.
// 40 scenes, 300.5s, 2 spine overrides.
//
// palette and World below are the AUTHORED functions, emitted verbatim. The World is
// re-evaluated per seek against an SVG-DOM shim whose entire surface is {R, rgba} plus the
// utils object — verified by evaluating all 30 authored Worlds against exactly that sandbox —
// so the backdrop is not a reinterpretation of the original, it IS the original.

const stage = require("../lf_stage");

const SKIN = {
  id: "dawn-chorus",
  label: "Dawn Chorus",

  // ---- type ----
  display: "Fraunces", displayFallback: "Georgia, serif",
  body: "Mulish", bodyFallback: "system-ui, sans-serif",
  em: 0.5997, bodyEm: 0.6493,

  // ---- palette ----
  // The authored function, called with {} for the design's own defaults. It returns the same
  // six roles on every one of the 27 films, so the stage can rely on them by name: paper and
  // ink are the type system, sageT and terraT are the alternating tinted grounds, and
  // accent/accent2 are the two a brand may take over at their authored luminance.
  palette: (t) => ({ paper: "#f3efe4", ink: "#1e2a34", accent: t.accent || "#e0913c", accent2: t.accent2 || "#4d7f8c", sageT: "#e6ece8", terraT: "#f7e6d2" }),
  accents: ["accent","accent2"],
  accentOpts: ["#e0913c","#c4573c","#8c9e4d"],
  accent2Opts: ["#4d7f8c","#5f6b8c","#3c7a5f"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  desk: "#1a2230",

  // ---- camera + motion ----
  cams: ["zoomOut","pushU","drop","pushR","zoomIn"],
  camStride: 3, camOff: 1,
  ambient: 1.4,

  // ---- the garnish voice ----
  // Rotated by scene index so no two consecutive frames read the same. Authored copy.
  tags: ["DAWN CHORUS · A BIRD FILM","FOUR AM, LOUDEST HOUR","BINOCULARS OPTIONAL","LEARN ONE SONG","GARDEN LIST OPEN"],
  foots: ["recorded before the traffic started","the robin sings all year, unprompted","feeder refilled weekly, never daily","sixty-one species, one hedge","the wren is far louder than it looks"],
  sides: ["LISTEN · LOOK · LOG","FIRST LIGHT IS THE POINT","SIXTY-ONE ON THE LIST"],

  // ---- the spine ----
  // Which renderer runs at which index. The stage owns the canonical 40-name order; this is
  // only what THIS film does differently. ["insert", i, name] splices, [i, name] substitutes.
  // Resolves to: 40 scenes.
  spineOverrides: [[2,"Wave"],[9,"Blink"]],

  strings: {
    brandName: "Dawn Chorus",
  },

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, utils) — no Math.random, no
  // Date, no accumulated state anywhere in the six pack files — which is what lets it be
  // re-evaluated deterministically on every seek, forwards or backwards.
  World: (th, t, u) => R("g", null,
      R("circle", { cx: 250, cy: 300 - Math.sin(t * 0.12) * 40, r: 130, fill: rgba(th.accent, u.dark ? 0.14 : 0.24) }),
      R("line", { x1: -20, y1: 380, x2: u.W + 20, y2: 320, stroke: rgba(th.ink, u.dark ? 0.4 : 0.35), strokeWidth: 5 }),
      [0, 1, 2, 3].map((k) => {
        const x = 520 + k * 260, y = 380 - (x / u.W) * 60;
        const hop = Math.sin(t * 2 + k * 1.7) > 0.9 ? -8 : 0;
        return R("g", { key: "w" + k, transform: "translate(" + x + "," + (y + hop) + ")" },
          R("ellipse", { cy: -16, rx: 20, ry: 15, fill: rgba(th.ink, 0.85) }),
          R("circle", { cx: 15, cy: -30, r: 10, fill: rgba(th.ink, 0.85) }),
          R("path", { d: "M 24 -31 l 14 3 l -14 4 z", fill: th.accent }),
          R("path", { d: "M -18 -14 l -22 " + (6 + (k % 2) * 4), stroke: rgba(th.ink, 0.85), strokeWidth: 7, strokeLinecap: "round" }));
      }),
      [0, 1, 2].map((k) => {
        const ph = (t * (0.08 + k * 0.03) + k * 0.34) % 1;
        const bx = ph * (u.W + 220) - 110, by = 220 + k * 150 + Math.sin(ph * 8 + k * 2) * 70;
        const fl = Math.abs(Math.sin(t * 8 + k * 2));
        return R("g", { key: "b" + k, transform: "translate(" + bx + "," + by + ")" },
          R("path", { d: "M 0 0 q -36 -" + (10 + fl * 30) + " -58 " + (6 - fl * 8), fill: "none", stroke: rgba(th.ink, 0.7), strokeWidth: 7, strokeLinecap: "round" }),
          R("path", { d: "M 0 0 q 36 -" + (10 + fl * 30) + " 58 " + (6 - fl * 8), fill: "none", stroke: rgba(th.ink, 0.7), strokeWidth: 7, strokeLinecap: "round" }));
      }),
      R("path", { d: "M -20 " + (u.H - 130) + " q 240 -70 480 -20 q 300 50 620 -40 L " + (u.W + 20) + " " + (u.H + 20) + " L -20 " + (u.H + 20) + " Z", fill: rgba(th.accent2, 0.2) })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
