// FETCH CLUB — skin for the shared long-form stage (services/lf_stage.js).
//
// GENERATED by scripts/gen-lf-skins.js from the handoff source
// (templete-design/longform-handoff/engine/lf-pack-1.js, template "FetchClub").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Baloo 2 / body Nunito. Camera set ["hopU","pushR","zoomIn","pushL","drop","spin"] at stride 5/1.
// 40 scenes, 300.5s, 2 spine overrides.
//
// palette and World below are the AUTHORED functions, emitted verbatim. The World is
// re-evaluated per seek against an SVG-DOM shim whose entire surface is {R, rgba} plus the
// utils object — verified by evaluating all 30 authored Worlds against exactly that sandbox —
// so the backdrop is not a reinterpretation of the original, it IS the original.

const stage = require("../lf_stage");

const SKIN = {
  id: "fetch-club",
  label: "Fetch Club",

  // ---- type ----
  display: "Baloo 2", displayFallback: "Georgia, serif",
  body: "Nunito", bodyFallback: "system-ui, sans-serif",
  em: 0.5722, bodyEm: 0.6441,

  // ---- palette ----
  // The authored function, called with {} for the design's own defaults. It returns the same
  // six roles on every one of the 27 films, so the stage can rely on them by name: paper and
  // ink are the type system, sageT and terraT are the alternating tinted grounds, and
  // accent/accent2 are the two a brand may take over at their authored luminance.
  palette: (t) => ({ paper: "#f6ecd9", ink: "#2c231a", accent: t.accent || "#e0762c", accent2: t.accent2 || "#4d7a63", sageT: "#e6ecdf", terraT: "#f7dfc2" }),
  accents: ["accent","accent2"],
  accentOpts: ["#e0762c","#c9552e","#e8a13c"],
  accent2Opts: ["#4d7a63","#3f6b8a","#7a6b4d"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  desk: "#2a1f16",

  // ---- camera + motion ----
  cams: ["hopU","pushR","zoomIn","pushL","drop","spin"],
  camStride: 5, camOff: 1,
  ambient: 1.7,

  // ---- the garnish voice ----
  // Rotated by scene index so no two consecutive frames read the same. Authored copy.
  tags: ["FETCH CLUB · OFF-LEASH FILM","GOOD DOGS ONLY","TAILS AT MAXIMUM","THE BALL ALWAYS COMES BACK","MUD IS A FEATURE"],
  foots: ["filmed at knee height","no ball was permanently lost","every dog here is the best dog","treat budget: unlimited","zip ties and tennis balls"],
  sides: ["SIT · STAY · SPRINT","TAIL SPEED: UNMEASURABLE","OFF-LEASH HOURS DAILY"],

  // ---- the spine ----
  // Which renderer runs at which index. The stage owns the canonical 40-name order; this is
  // only what THIS film does differently. ["insert", i, name] splices, [i, name] substitutes.
  // Resolves to: 40 scenes.
  spineOverrides: [[1,"Rain"],[2,"Problem"]],

  strings: {
    brandName: "Fetch Club",
  },

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, utils) — no Math.random, no
  // Date, no accumulated state anywhere in the six pack files — which is what lets it be
  // re-evaluated deterministically on every seek, forwards or backwards.
  World: (th, t, u) => R("g", null,
      R("path", { d: "M -40 " + (u.H - 150) + " q 300 -40 640 -10 q 380 34 700 -30 L " + (u.W + 40) + " " + (u.H + 40) + " L -40 " + (u.H + 40) + " Z", fill: rgba(th.accent2, 0.16) }),
      (function () {
        const ph = (t * 0.12) % 1, dx = -240 + ph * (u.W + 480);
        const bob = Math.abs(Math.sin(t * 5)) * 9, leg = Math.sin(t * 9);
        return R("g", { transform: "translate(" + dx + "," + (u.H - 250 - bob) + ")" },
          R("ellipse", { rx: 78, ry: 44, fill: rgba(th.ink, 0.85) }),
          R("circle", { cx: 84, cy: -34, r: 34, fill: rgba(th.ink, 0.85) }),
          R("path", { d: "M 104 -56 q 22 -30 30 -4 q -14 8 -30 4", fill: rgba(th.ink, 0.85) }),
          R("path", { d: "M 62 -58 q 18 -34 -8 -40 q -14 16 -6 40", fill: rgba(th.ink, 0.85) }),
          R("path", { d: "M -74 -18 q -46 -30 -30 -66", fill: "none", stroke: rgba(th.ink, 0.85), strokeWidth: 13, strokeLinecap: "round", transform: "rotate(" + Math.sin(t * 12) * 22 + " -74 -18)" }),
          [[-44, 0], [-14, 1], [30, 2], [58, 3]].map(([ox, k]) => R("line", { key: k, x1: ox, y1: 26, x2: ox + leg * (k % 2 ? 20 : -20), y2: 74, stroke: rgba(th.ink, 0.85), strokeWidth: 14, strokeLinecap: "round" })));
      })(),
      (function () {
        const bt = (t * 0.5) % 1, bx = bt * u.W, by = u.H - 210 - Math.abs(Math.sin(bt * Math.PI * 3)) * 300;
        return R("g", { transform: "translate(" + bx + "," + by + ") rotate(" + t * 300 + ")" },
          R("circle", { r: 26, fill: "#d8e84b" }),
          R("path", { d: "M -26 0 a 26 26 0 0 1 52 0 M -26 0 a 26 26 0 0 0 52 0", fill: "none", stroke: rgba(th.paper, 0.9), strokeWidth: 4 }));
      })(),
      Array.from({ length: 6 }).map((_, k) => {
        const ph = ((t * 0.2 + k * 0.16) % 1);
        return R("g", { key: "pw" + k, opacity: 0.3 * (1 - ph), transform: "translate(" + (120 + k * 300 - ph * 120) + "," + (u.H - 120 + (k % 2) * 34) + ") scale(0.9)" },
          R("ellipse", { rx: 15, ry: 12, fill: th.accent }),
          [-16, -5, 6, 17].map((ox, j) => R("circle", { key: j, cx: ox, cy: -17, r: 5.5, fill: th.accent })));
      }),
      R("circle", { cx: u.W - 170, cy: 220, r: 96, fill: "none", stroke: rgba(th.accent, u.dark ? 0.14 : 0.2), strokeWidth: 30, transform: "rotate(" + t * 10 + " " + (u.W - 170) + " 220)" })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
