// FIELD OF VIEW — skin for the shared long-form stage (services/lf_stage.js).
//
// GENERATED by scripts/gen-lf-skins.js from the handoff source
// (templete-design/longform-handoff/engine/lf-pack-6.js, template "FieldOfView").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Prata / body Manrope. Camera set ["zoomOut","drop","pushL","zoomIn","pushU","pushR"] at stride 5/3.
// 41 scenes, 308s, 2 spine overrides.
//
// palette and World below are the AUTHORED functions, emitted verbatim. The World is
// re-evaluated per seek against an SVG-DOM shim whose entire surface is {R, rgba} plus the
// utils object — verified by evaluating all 30 authored Worlds against exactly that sandbox —
// so the backdrop is not a reinterpretation of the original, it IS the original.

const stage = require("../lf_stage");

const SKIN = {
  id: "field-of-view",
  label: "Field of View",

  // ---- type ----
  display: "Prata", displayFallback: "Georgia, serif",
  body: "Manrope", bodyFallback: "system-ui, sans-serif",
  em: 0.7022, bodyEm: 0.6097,

  // ---- palette ----
  // The authored function, called with {} for the design's own defaults. It returns the same
  // six roles on every one of the 27 films, so the stage can rely on them by name: paper and
  // ink are the type system, sageT and terraT are the alternating tinted grounds, and
  // accent/accent2 are the two a brand may take over at their authored luminance.
  palette: (t) => ({ paper: "#e9e6f2", ink: "#080b16", accent: t.accent || "#e0c46b", accent2: t.accent2 || "#7a8ad0", sageT: "#101828", terraT: "#181022" }),
  accents: ["accent","accent2"],
  accentOpts: ["#e0c46b","#8ad6e0","#e08a9e"],
  accent2Opts: ["#7a8ad0","#5fa0a0","#a07ad0"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  desk: "#06080f",

  // ---- camera + motion ----
  cams: ["zoomOut","drop","pushL","zoomIn","pushU","pushR"],
  camStride: 5, camOff: 3,
  ambient: 1.3,

  // ---- the garnish voice ----
  // Rotated by scene index so no two consecutive frames read the same. Authored copy.
  tags: ["FIELD OF VIEW · A SKY FILM","CLEAR AFTER MIDNIGHT","RED LIGHT ONLY","SEEING: STEADY","ALL LIGHT IS OLD LIGHT"],
  foots: ["observed at 25 mm, then 9 mm","everything here happened years ago","the cloud cleared at 23:40, exactly","one hundred and thirty-four steps up","the kettle is red-lit too"],
  sides: ["DARK · ADAPT · OBSERVE","TWENTY MINUTES TO ADAPT","ALL LIGHT IS OLD LIGHT"],

  // ---- the spine ----
  // Which renderer runs at which index. The stage owns the canonical 40-name order; this is
  // only what THIS film does differently. ["insert", i, name] splices, [i, name] substitutes.
  // Resolves to: 41 scenes.
  spineOverrides: [["insert",36,"Patience"],[2,"Blink"]],

  strings: {
    brandName: "Field of View",
  },

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, utils) — no Math.random, no
  // Date, no accumulated state anywhere in the six pack files — which is what lets it be
  // re-evaluated deterministically on every seek, forwards or backwards.
  World: (th, t, u) => R("g", null,
      Array.from({ length: 30 }).map((_, k) => R("circle", { key: k, cx: (k * 149 + 40) % u.W, cy: (k * 227 + 60) % (u.H * 0.85), r: 1.4 + (k % 3) * 0.8, fill: rgba(th.paper, 0.25 + 0.5 * Math.abs(Math.sin(t * 1.2 + k * 1.9))) })),
      (function () {
        const pts = [[240, 320], [380, 250], [520, 330], [610, 220], [760, 280], [880, 210]];
        const draw = ((t * 0.14) % 1.3);
        return R("g", null,
          R("path", { d: pts.map(([x, y], i) => (i ? "L" : "M") + x + " " + y).join(" "), fill: "none", stroke: rgba(th.accent, 0.45), strokeWidth: 3, strokeDasharray: 900, strokeDashoffset: 900 * (1 - Math.min(1, draw)) }),
          pts.map(([x, y], i) => R("circle", { key: i, cx: x, cy: y, r: 6, fill: th.accent, opacity: Math.min(1, draw) * pts.length > i ? 0.95 : 0.2 })));
      })(),
      (function () {
        const mp = (t * 0.2) % 1.6;
        return mp < 1 ? R("line", { x1: u.W - mp * 1100, y1: 120 + mp * 340, x2: u.W - mp * 1100 + 150, y2: 120 + mp * 340 - 52, stroke: rgba(th.paper, 0.8 * (1 - mp)), strokeWidth: 4, strokeLinecap: "round" }) : null;
      })(),
      (function () {
        const rot = Math.sin(t * 0.2) * 16;
        return R("g", { transform: "translate(" + (u.W - 240) + "," + (u.H - 200) + ")" },
          R("path", { d: "M -170 0 a 170 150 0 0 1 340 0 z", fill: rgba(th.paper, u.dark ? 0.12 : 0.2) }),
          R("g", { transform: "rotate(" + rot + ")" },
            R("path", { d: "M -34 -140 L 34 -140 L 40 0 L -40 0 Z", fill: rgba(th.ink, 0.85) }),
            R("rect", { x: -18, y: -150, width: 36, height: 24, rx: 6, fill: rgba(th.accent, 0.7) })),
          R("rect", { x: -180, y: -6, width: 360, height: 14, rx: 6, fill: rgba(th.paper, 0.25) }));
      })(),
      R("g", { transform: "translate(200," + (u.H - 300) + ") rotate(" + (-26 + Math.sin(t * 0.4) * 4) + ")" },
        R("line", { x1: 0, y1: 0, x2: 190, y2: -150, stroke: rgba(th.accent2, 0.8), strokeWidth: 20, strokeLinecap: "round" }),
        R("path", { d: "M -56 0 L 56 0 L 24 96 L -24 96 Z", fill: rgba(th.accent2, 0.7) }),
        R("circle", { cx: 200, cy: -160, r: 13, fill: th.accent })),
      Array.from({ length: 4 }).map((_, k) => R("line", { key: "rl" + k, x1: 100, y1: 200 + k * 40, x2: 100 + 40, y2: 200 + k * 40, stroke: rgba("#ff4444", 0.3), strokeWidth: 5 }))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
