// GRAIN LINE — skin for the shared long-form stage (services/lf_stage.js).
//
// GENERATED by scripts/gen-lf-skins.js from the handoff source
// (templete-design/longform-handoff/engine/lf-pack-6.js, template "GrainLine").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Cardo / body Barlow. Camera set ["pushL","zoomIn","pushD","hopU","pushR","zoomOut"] at stride 3/1.
// 40 scenes, 300.5s, the canonical spine unmodified.
//
// palette and World below are the AUTHORED functions, emitted verbatim. The World is
// re-evaluated per seek against an SVG-DOM shim whose entire surface is {R, rgba} plus the
// utils object — verified by evaluating all 30 authored Worlds against exactly that sandbox —
// so the backdrop is not a reinterpretation of the original, it IS the original.

const stage = require("../lf_stage");

const SKIN = {
  id: "grain-line",
  label: "Grain Line",

  // ---- type ----
  display: "Cardo", displayFallback: "Georgia, serif",
  body: "Barlow", bodyFallback: "system-ui, sans-serif",
  em: 0.6632, bodyEm: 0.5761,

  // ---- palette ----
  // The authored function, called with {} for the design's own defaults. It returns the same
  // six roles on every one of the 27 films, so the stage can rely on them by name: paper and
  // ink are the type system, sageT and terraT are the alternating tinted grounds, and
  // accent/accent2 are the two a brand may take over at their authored luminance.
  palette: (t) => ({ paper: "#f4ead8", ink: "#251b13", accent: t.accent || "#b06a2c", accent2: t.accent2 || "#5f7a5f", sageT: "#e8eee2", terraT: "#f7e2c8" }),
  accents: ["accent","accent2"],
  accentOpts: ["#b06a2c","#8c4f2c","#b0902c"],
  accent2Opts: ["#5f7a5f","#4d6b8c","#7a6b5f"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  desk: "#241a12",

  // ---- camera + motion ----
  cams: ["pushL","zoomIn","pushD","hopU","pushR","zoomOut"],
  camStride: 3, camOff: 1,
  ambient: 1.5,

  // ---- the garnish voice ----
  // Rotated by scene index so no two consecutive frames read the same. Authored copy.
  tags: ["GRAIN LINE · A WORKSHOP FILM","HAND TOOLS ONLY","MEASURE ONCE, MARK TWICE","SHARP IS SAFE","NO SCREWS IN THIS ONE"],
  foots: ["cut by hand, fitted by eye","the plane iron was sharpened four times","oak, air dried for six years","one dovetail was recut. only one.","sawdust everywhere, permanently"],
  sides: ["MARK · SAW · PARE · FIT","SHARP TOOLS, SLOW HANDS","NO SCREWS, NO NAILS"],

  // ---- the spine ----
  // Which renderer runs at which index. The stage owns the canonical 40-name order; this is
  // only what THIS film does differently. ["insert", i, name] splices, [i, name] substitutes.
  // Resolves to: 40 scenes.
  spineOverrides: [],

  strings: {
    brandName: "Grain Line",
  },

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, utils) — no Math.random, no
  // Date, no accumulated state anywhere in the six pack files — which is what lets it be
  // re-evaluated deterministically on every seek, forwards or backwards.
  World: (th, t, u) => R("g", null,
      Array.from({ length: 9 }).map((_, k) => R("path", { key: "gr" + k, d: "M -20 " + (200 + k * 100) + " q 400 " + (k % 2 ? 26 : -26) + " 800 0 q 400 " + (k % 2 ? -26 : 26) + " 1160 0", fill: "none", stroke: rgba(th.accent, u.dark ? 0.07 : 0.12), strokeWidth: 8 })),
      (function () {
        const px = 200 + ((t * 130) % 620);
        return R("g", { transform: "translate(" + px + "," + (u.H - 320) + ")" },
          R("path", { d: "M -110 0 h 220 l -14 -60 h -192 z", fill: rgba(th.ink, 0.85) }),
          R("rect", { x: -40, y: -110, width: 80, height: 56, rx: 10, fill: rgba(th.accent, 0.9) }),
          Array.from({ length: 4 }).map((_, k) => {
            const q = ((t * 0.9 + k * 0.25) % 1);
            return R("path", { key: k, d: "M 0 0 q 30 -34 -4 -52 q -30 -16 -14 12", fill: "none", stroke: rgba(th.accent, 0.6 * (1 - q * 0.5)), strokeWidth: 6, transform: "translate(" + (110 + q * 120) + "," + (-q * 30) + ") rotate(" + q * 200 + ")" });
          }));
      })(),
      (function () {
        const cut = Math.min(1, ((t * 0.2) % 1.5));
        return R("g", { transform: "translate(" + (u.W - 380) + "," + (u.H - 520) + ")" },
          R("rect", { x: 0, y: 0, width: 300, height: 200, rx: 6, fill: rgba(th.accent, 0.35), stroke: rgba(th.ink, 0.5), strokeWidth: 4 }),
          [0, 1, 2].map((k) => R("path", { key: k, d: "M " + (40 + k * 90) + " 0 l 26 " + (60 * cut) + " l 30 0 l 26 " + (-60 * cut), fill: "none", stroke: rgba(th.ink, 0.65), strokeWidth: 5 })),
          R("path", { d: "M 0 0 h 300", stroke: rgba(th.ink, 0.6), strokeWidth: 4, strokeDasharray: "12 8" }));
      })(),
      Array.from({ length: 10 }).map((_, k) => {
        const ph = (t * (0.3 + (k % 3) * 0.1) + k * 0.1) % 1;
        return R("circle", { key: "dt" + k, cx: 260 + ((k * 97) % 500) + Math.sin(t + k) * 20, cy: (u.H - 300) + ph * 200, r: 3, fill: rgba(th.accent, 0.35 * (1 - ph)) });
      }),
      [0, 1].map((k) => R("g", { key: "cl" + k, transform: "translate(" + (160 + k * 200) + "," + (u.H - 170) + ")" },
        R("rect", { x: -12, y: -60, width: 24, height: 90, rx: 5, fill: rgba(th.accent2, 0.75) }),
        R("rect", { x: -60, y: -60, width: 120, height: 18, rx: 6, fill: rgba(th.accent2, 0.75) })))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
