// KILN FIRE — skin for the shared long-form stage (services/lf_stage.js).
//
// GENERATED by scripts/gen-lf-skins.js from the handoff source
// (templete-design/longform-handoff/engine/lf-pack-3.js, template "KilnFire").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Gloock / body Schibsted Grotesk. Camera set ["zoomOut","pushL","hopU","pushR","zoomIn","drop"] at stride 3/1.
// 41 scenes, 308s, 1 spine override.
//
// palette and World below are the AUTHORED functions, emitted verbatim. The World is
// re-evaluated per seek against an SVG-DOM shim whose entire surface is {R, rgba} plus the
// utils object — verified by evaluating all 30 authored Worlds against exactly that sandbox —
// so the backdrop is not a reinterpretation of the original, it IS the original.

const stage = require("../lf_stage");

const SKIN = {
  id: "kiln-fire",
  label: "Kiln Fire",

  // ---- type ----
  display: "Gloock", displayFallback: "Georgia, serif",
  body: "Schibsted Grotesk", bodyFallback: "system-ui, sans-serif",
  em: 0.6517, bodyEm: 0.6329,

  // ---- palette ----
  // The authored function, called with {} for the design's own defaults. It returns the same
  // six roles on every one of the 27 films, so the stage can rely on them by name: paper and
  // ink are the type system, sageT and terraT are the alternating tinted grounds, and
  // accent/accent2 are the two a brand may take over at their authored luminance.
  palette: (t) => ({ paper: "#f3ebde", ink: "#241d17", accent: t.accent || "#c2562c", accent2: t.accent2 || "#5f8c8c", sageT: "#e6eeee", terraT: "#f7e2d2" }),
  accents: ["accent","accent2"],
  accentOpts: ["#c2562c","#a8402e","#c28a2c"],
  accent2Opts: ["#5f8c8c","#7a8c5f","#5f6b8c"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  desk: "#231b16",

  // ---- camera + motion ----
  cams: ["zoomOut","pushL","hopU","pushR","zoomIn","drop"],
  camStride: 3, camOff: 1,
  ambient: 1.5,

  // ---- the garnish voice ----
  // Rotated by scene index so no two consecutive frames read the same. Authored copy.
  tags: ["KILN FIRE · A CLAY FILM","CONE SIX, TWELVE HOURS","CENTRED, EVENTUALLY","MUD UNDER THE NAILS","THE KILN DECIDES"],
  foots: ["thrown badly, then better, then well","the kiln opened at 40 degrees","three cracked, one survived, worth it","glaze recipe scaled from grams","the wheel has run since 1987"],
  sides: ["CENTRE · OPEN · PULL","SLOW HANDS, WET CLAY","TWELVE HOURS TO CONE SIX"],

  // ---- the spine ----
  // Which renderer runs at which index. The stage owns the canonical 40-name order; this is
  // only what THIS film does differently. ["insert", i, name] splices, [i, name] substitutes.
  // Resolves to: 41 scenes.
  spineOverrides: [["insert",36,"Patience"]],

  strings: {
    brandName: "Kiln Fire",
  },

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, utils) — no Math.random, no
  // Date, no accumulated state anywhere in the six pack files — which is what lets it be
  // re-evaluated deterministically on every seek, forwards or backwards.
  World: (th, t, u) => R("g", null,
      (function () {
        const grow = ((t * 0.14) % 1), wob = Math.sin(t * 9) * 3;
        const wpx = u.W - 280, wpy = u.H - 280;
        return R("g", { transform: "translate(" + wpx + "," + wpy + ")" },
          R("ellipse", { cy: 34, rx: 160, ry: 30, fill: rgba(th.ink, 0.5), transform: "rotate(" + wob + ")" }),
          R("path", { d: "M -70 24 q -18 -" + (70 + grow * 110) + " 10 -" + (110 + grow * 140) + " l " + (120 + wob) + " 0 q 28 " + (36 + grow * 26) + " 10 " + (110 + grow * 140) + " z", fill: th.accent, opacity: 0.92, transform: "scaleX(" + (0.7 + grow * 0.3) + ")" }),
          R("ellipse", { cy: 24 - (110 + grow * 140), rx: 62 * (0.7 + grow * 0.3), ry: 14, fill: rgba(th.ink, 0.35) }));
      })(),
      R("g", { transform: "translate(240," + (u.H - 320) + ")" },
        R("rect", { x: -130, y: -160, width: 260, height: 300, rx: 24, fill: rgba(th.ink, 0.7) }),
        R("rect", { x: -84, y: -110, width: 168, height: 200, rx: 14, fill: rgba(th.accent, 0.5 + Math.sin(t * 2.4) * 0.25) }),
        R("rect", { x: -84, y: -110, width: 168, height: 200, rx: 14, fill: "none", stroke: rgba(th.paper, 0.3), strokeWidth: 4 }),
        Array.from({ length: 3 }).map((_, k) => R("circle", { key: k, cx: -46 + k * 46, cy: -20 + Math.sin(t * 3 + k) * 6, r: 14, fill: rgba("#ffd9a0", 0.6) }))),
      (function () {
        const bend = Math.min(1, ((t * 0.1) % 1.4));
        return R("g", { transform: "translate(150,260)" },
          R("path", { d: "M 0 90 Q " + (bend * 40) + " 40 " + (bend * 70) + " " + (10 + bend * 30), fill: "none", stroke: rgba(th.accent, 0.8), strokeWidth: 14, strokeLinecap: "round" }),
          R("text", { x: 100, y: 80, fontFamily: '"Schibsted Grotesk", sans-serif', fontSize: 26, fill: rgba(th.ink, u.dark ? 0.5 : 0.55) }, "cone 6 \u00b7 1222\u00b0"));
      })(),
      R("path", { d: "M 90 " + (u.H - 150) + " " + Array.from({ length: 9 }).map((_, k) => "l 46 " + (k % 2 ? 24 : -24)).join(" "), fill: "none", stroke: rgba(th.accent2, 0.45), strokeWidth: 6, strokeLinecap: "round" })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
