// KNIFE & BOARD — skin for the shared long-form stage (services/lf_stage.js).
//
// GENERATED by scripts/gen-lf-skins.js from the handoff source
// (templete-design/longform-handoff/engine/lf-pack-1.js, template "KnifeBoard").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Bitter / body Figtree. Camera set ["pushL","zoomIn","pushD","pushR","hopU","zoomOut"] at stride 5/3.
// 40 scenes, 300.5s, the canonical spine unmodified.
//
// palette and World below are the AUTHORED functions, emitted verbatim. The World is
// re-evaluated per seek against an SVG-DOM shim whose entire surface is {R, rgba} plus the
// utils object — verified by evaluating all 30 authored Worlds against exactly that sandbox —
// so the backdrop is not a reinterpretation of the original, it IS the original.

const stage = require("../lf_stage");

const SKIN = {
  id: "knife-and-board",
  label: "Knife & Board",

  // ---- type ----
  display: "Bitter", displayFallback: "Georgia, serif",
  body: "Figtree", bodyFallback: "system-ui, sans-serif",
  em: 0.6383, bodyEm: 0.6295,

  // ---- palette ----
  // The authored function, called with {} for the design's own defaults. It returns the same
  // six roles on every one of the 27 films, so the stage can rely on them by name: paper and
  // ink are the type system, sageT and terraT are the alternating tinted grounds, and
  // accent/accent2 are the two a brand may take over at their authored luminance.
  palette: (t) => ({ paper: "#f7efe2", ink: "#241c18", accent: t.accent || "#c33f34", accent2: t.accent2 || "#5c7a3a", sageT: "#e7ecdd", terraT: "#f8e0cf" }),
  accents: ["accent","accent2"],
  accentOpts: ["#c33f34","#a8402e","#d9622c"],
  accent2Opts: ["#5c7a3a","#3f6b5a","#8c6a2c"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  desk: "#1c1614",

  // ---- camera + motion ----
  cams: ["pushL","zoomIn","pushD","pushR","hopU","zoomOut"],
  camStride: 5, camOff: 3,
  ambient: 1.8,

  // ---- the garnish voice ----
  // Rotated by scene index so no two consecutive frames read the same. Authored copy.
  tags: ["KNIFE & BOARD · KITCHEN FILM","MISE EN PLACE FIRST","SALT, FAT, ACID, NERVE","COOKED, NOT PLATED","TASTE AS YOU GO"],
  foots: ["everything here was eaten","the board has scars, and history","seasoning is not a suggestion","one pot, one pan, no gadgets","recipe written on a napkin"],
  sides: ["CHOP · SEAR · REST","SHARP KNIVES, CALM HANDS","DINNER IN FORTY MINUTES"],

  // ---- the spine ----
  // Which renderer runs at which index. The stage owns the canonical 40-name order; this is
  // only what THIS film does differently. ["insert", i, name] splices, [i, name] substitutes.
  // Resolves to: 40 scenes.
  spineOverrides: [],

  strings: {
    brandName: "Knife & Board",
  },

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, utils) — no Math.random, no
  // Date, no accumulated state anywhere in the six pack files — which is what lets it be
  // re-evaluated deterministically on every seek, forwards or backwards.
  World: (th, t, u) => R("g", null,
      R("rect", { x: u.W - 620, y: u.H - 250, width: 560, height: 40, rx: 20, fill: rgba("#b98a52", 0.85) }),
      (function () {
        const ch = Math.abs(Math.sin(t * 4)), kx = u.W - 400 + ((t * 30) % 180);
        return R("g", { transform: "translate(" + kx + "," + (u.H - 260 - ch * 130) + ") rotate(" + (-16 + ch * 22) + ")" },
          R("path", { d: "M -8 0 L 130 0 L 150 30 L -8 30 Z", fill: rgba("#d8dde2", 0.95) }),
          R("rect", { x: -86, y: 4, width: 82, height: 24, rx: 10, fill: rgba(th.ink, 0.9) }));
      })(),
      Array.from({ length: 7 }).map((_, k) => {
        const ph = (t * 0.5 + k * 0.14) % 1;
        const x = u.W - 380 + ph * 200, y = u.H - 250 - Math.sin(ph * Math.PI) * 200;
        return R("path", { key: "h" + k, d: "M 0 0 q 14 -12 26 0 q -12 14 -26 0", fill: rgba(th.accent2, 0.8 - ph * 0.4), transform: "translate(" + x + "," + y + ") rotate(" + (ph * 300 + k * 40) + ")" });
      }),
      (function () {
        const wob = Math.sin(t * 7) * 2;
        return R("g", { transform: "translate(250," + (u.H - 240) + ")" },
          R("path", { d: "M -110 -40 h 220 l -16 90 q -8 26 -94 26 q -86 0 -94 -26 z", fill: rgba(th.ink, 0.85) }),
          R("ellipse", { cy: -40, rx: 112, ry: 18, fill: rgba(th.accent, 0.6), transform: "rotate(" + wob + ")" }),
          R("rect", { x: 100, y: -50, width: 70, height: 16, rx: 8, fill: rgba(th.ink, 0.85) }),
          [0, 1, 2].map((k) => {
            const ph = (t * 0.3 + k * 0.33) % 1;
            return R("path", { key: k, d: "M " + (-50 + k * 50) + " " + (-70 - ph * 420) + " q 24 -46 0 -92 q -24 -46 0 -92", fill: "none", stroke: rgba(th.paper, 0.22 * (1 - ph)), strokeWidth: 16, strokeLinecap: "round" });
          }),
          [0, 1, 2, 3].map((k) => R("circle", { key: "b" + k, cx: -60 + k * 40, cy: -46 + Math.sin(t * 6 + k * 2) * 6, r: 5 + (k % 2) * 3, fill: rgba(th.paper, 0.35) })));
      })()),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
