// LEDGER & LIFT — skin for the shared long-form stage (services/lf_stage.js).
//
// GENERATED by scripts/gen-lf-skins.js from the handoff source
// (templete-design/longform-handoff/engine/lf-pack-2.js, template "LedgerLift").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Sora / body Inter Tight. Camera set ["pushU","zoomIn","pushR","drop","pushL","zoomOut"] at stride 3/2.
// 41 scenes, 308s, 2 spine overrides.
//
// palette and World below are the AUTHORED functions, emitted verbatim. The World is
// re-evaluated per seek against an SVG-DOM shim whose entire surface is {R, rgba} plus the
// utils object — verified by evaluating all 30 authored Worlds against exactly that sandbox —
// so the backdrop is not a reinterpretation of the original, it IS the original.

const stage = require("../lf_stage");

const SKIN = {
  id: "ledger-and-lift",
  label: "Ledger & Lift",

  // ---- type ----
  display: "Sora", displayFallback: "system-ui, sans-serif",
  body: "Inter Tight", bodyFallback: "system-ui, sans-serif",
  em: 0.6902, bodyEm: 0.6034,

  // ---- palette ----
  // The authored function, called with {} for the design's own defaults. It returns the same
  // six roles on every one of the 27 films, so the stage can rely on them by name: paper and
  // ink are the type system, sageT and terraT are the alternating tinted grounds, and
  // accent/accent2 are the two a brand may take over at their authored luminance.
  palette: (t) => ({ paper: "#e9eef4", ink: "#0e131a", accent: t.accent || "#3ce08c", accent2: t.accent2 || "#5a7cff", sageT: "#161f28", terraT: "#1c1a26" }),
  accents: ["accent","accent2"],
  accentOpts: ["#3ce08c","#e0c43c","#ff6b6b"],
  accent2Opts: ["#5a7cff","#9b5aff","#3cc4e0"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  desk: "#0c1016",

  // ---- camera + motion ----
  cams: ["pushU","zoomIn","pushR","drop","pushL","zoomOut"],
  camStride: 3, camOff: 2,
  ambient: 1.7,

  // ---- the garnish voice ----
  // Rotated by scene index so no two consecutive frames read the same. Authored copy.
  tags: ["LEDGER & LIFT · A MONEY FILM","COMPOUNDING IS THE WHOLE TRICK","BORING BEATS CLEVER","AUTOMATE, THEN IGNORE","FEES ARE THE ENEMY"],
  foots: ["all figures net of fees","past performance proves nothing","the boring fund won again","automated on payday, untouched since","no timing was attempted here"],
  sides: ["EARN · AUTOMATE · WAIT","FEES COMPOUND TOO","THIRTY YEARS, NOT THIRTY DAYS"],

  // ---- the spine ----
  // Which renderer runs at which index. The stage owns the canonical 40-name order; this is
  // only what THIS film does differently. ["insert", i, name] splices, [i, name] substitutes.
  // Resolves to: 41 scenes.
  spineOverrides: [["insert",36,"Patience"],[2,"Blink"]],

  strings: {
    brandName: "Ledger & Lift",
  },

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, utils) — no Math.random, no
  // Date, no accumulated state anywhere in the six pack files — which is what lets it be
  // re-evaluated deterministically on every seek, forwards or backwards.
  World: (th, t, u) => R("g", null,
      Array.from({ length: 5 }).map((_, k) => R("line", { key: "g" + k, x1: 0, y1: 220 + k * 180, x2: u.W, y2: 220 + k * 180, stroke: rgba(th.paper, 0.06), strokeWidth: 2 })),
      (function () {
        const n = 14, prog = (t * 0.16) % 1.3;
        return R("g", { transform: "translate(" + (u.W - 700) + "," + (u.H - 300) + ")" },
          Array.from({ length: n }).map((_, k) => {
            const shown = k / n < prog;
            const up = ((k * 7) % 3) !== 0;
            const h = 40 + ((k * 53) % 130), y = -(k * 12) - h / 2;
            return R("g", { key: k, opacity: shown ? 1 : 0.12 },
              R("line", { x1: k * 44, y1: y - h / 2 - 18, x2: k * 44, y2: y + h / 2 + 18, stroke: rgba(up ? th.accent : "#ff6b6b", 0.8), strokeWidth: 3 }),
              R("rect", { x: k * 44 - 11, y: y - h / 2, width: 22, height: h, rx: 4, fill: rgba(up ? th.accent : "#ff6b6b", 0.85) }));
          }));
      })(),
      (function () {
        const tilt = Math.sin(t * 0.7) * 12;
        return R("g", { transform: "translate(240," + (u.H - 420) + ") rotate(" + tilt * 0.4 + ")" },
          R("rect", { x: -170, y: -104, width: 340, height: 208, rx: 26, fill: rgba(th.accent2, 0.85), transform: "skewY(" + tilt * 0.2 + ")" }),
          R("rect", { x: -140, y: -60, width: 76, height: 54, rx: 10, fill: rgba("#ffd86b", 0.9) }),
          R("rect", { x: -140, y: 34, width: 200, height: 14, rx: 7, fill: rgba(th.paper, 0.55) }),
          R("circle", { cx: 110, cy: 56, r: 26, fill: rgba(th.paper, 0.25) }));
      })(),
      Array.from({ length: 5 }).map((_, k) => {
        const ph = (t * 0.4 + k * 0.2) % 1;
        return R("ellipse", { key: "c" + k, cx: 180 + k * 90, cy: 220 + ph * (u.H - 560), rx: 26, ry: 26 * Math.abs(Math.cos(ph * 8 + k)), fill: rgba("#ffd86b", 0.8 - ph * 0.4) });
      }),
      R("text", { x: u.W - 90, y: 240, textAnchor: "end", fontFamily: '"Inter Tight", sans-serif', fontSize: 30, fill: rgba(th.accent, 0.6) }, "+" + (7 + Math.floor(Math.abs(Math.sin(t * 0.3)) * 4)) + ".2% YTD")),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
