// LOFT NOTES — skin for the shared long-form stage (services/lf_stage.js).
//
// GENERATED by scripts/gen-lf-skins.js from the handoff source
// (templete-design/longform-handoff/engine/lf-pack-3.js, template "LoftNotes").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Righteous / body Mulish. Camera set ["spin","pushL","zoomIn","pushD","pushR","hopU"] at stride 5/2.
// 40 scenes, 300.5s, 1 spine override.
//
// palette and World below are the AUTHORED functions, emitted verbatim. The World is
// re-evaluated per seek against an SVG-DOM shim whose entire surface is {R, rgba} plus the
// utils object — verified by evaluating all 30 authored Worlds against exactly that sandbox —
// so the backdrop is not a reinterpretation of the original, it IS the original.

const stage = require("../lf_stage");

const SKIN = {
  id: "loft-notes",
  label: "Loft Notes",

  // ---- type ----
  display: "Righteous", displayFallback: "system-ui, sans-serif",
  body: "Mulish", bodyFallback: "system-ui, sans-serif",
  em: 0.6157, bodyEm: 0.6493,

  // ---- palette ----
  // The authored function, called with {} for the design's own defaults. It returns the same
  // six roles on every one of the 27 films, so the stage can rely on them by name: paper and
  // ink are the type system, sageT and terraT are the alternating tinted grounds, and
  // accent/accent2 are the two a brand may take over at their authored luminance.
  palette: (t) => ({ paper: "#f2ebdd", ink: "#1a1420", accent: t.accent || "#e0603c", accent2: t.accent2 || "#3fb8a8", sageT: "#1f2a2a", terraT: "#2a1c22" }),
  accents: ["accent","accent2"],
  accentOpts: ["#e0603c","#e0a03c","#e03c78"],
  accent2Opts: ["#3fb8a8","#6a5fd0","#a8b83f"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  desk: "#140f18",

  // ---- camera + motion ----
  cams: ["spin","pushL","zoomIn","pushD","pushR","hopU"],
  camStride: 5, camOff: 2,
  ambient: 1.8,

  // ---- the garnish voice ----
  // Rotated by scene index so no two consecutive frames read the same. Authored copy.
  tags: ["LOFT NOTES · A LISTENING FILM","SIDE B IS THE TEST","ONE ALBUM, START TO END","NO SHUFFLE IN THIS HOUSE","FORTY MINUTES, PHONE DOWN"],
  foots: ["recorded on the good turntable","the stylus was replaced last month","side two is where the risks are","nobody skipped a single track","the sleeve notes were read aloud"],
  sides: ["DROP · SIT · LISTEN","ALBUMS, NOT PLAYLISTS","FORTY MINUTES UNINTERRUPTED"],

  // ---- the spine ----
  // Which renderer runs at which index. The stage owns the canonical 40-name order; this is
  // only what THIS film does differently. ["insert", i, name] splices, [i, name] substitutes.
  // Resolves to: 40 scenes.
  spineOverrides: [[2,"Wave"]],

  strings: {
    brandName: "Loft Notes",
  },

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, utils) — no Math.random, no
  // Date, no accumulated state anywhere in the six pack files — which is what lets it be
  // re-evaluated deterministically on every seek, forwards or backwards.
  World: (th, t, u) => R("g", null,
      R("g", { transform: "translate(" + (u.W - 320) + "," + (u.H - 340) + ")" },
        R("circle", { r: 250, fill: rgba(th.ink, u.dark ? 0.55 : 0.2) }),
        [216, 178, 140, 104].map((r, k) => R("circle", { key: k, r: r, fill: "none", stroke: rgba(th.paper, 0.13), strokeWidth: 3 })),
        R("g", { transform: "rotate(" + t * 60 + ")" },
          R("circle", { r: 82, fill: th.accent }),
          R("circle", { r: 12, fill: rgba(th.ink, 0.8) }),
          R("path", { d: "M -60 0 A 60 60 0 0 1 60 0", fill: "none", stroke: rgba(th.paper, 0.35), strokeWidth: 5 }))),
      (function () {
        const ang = 22 + Math.sin(t * 0.25) * 5;
        return R("g", { transform: "translate(" + (u.W - 90) + "," + (u.H - 620) + ") rotate(" + ang + ")" },
          R("line", { x1: 0, y1: 0, x2: 0, y2: 320, stroke: rgba(th.accent2, 0.9), strokeWidth: 10, strokeLinecap: "round" }),
          R("circle", { r: 20, fill: th.accent2 }),
          R("rect", { x: -12, y: 314, width: 24, height: 44, rx: 8, fill: th.accent }));
      })(),
      Array.from({ length: 16 }).map((_, k) => {
        const h = 24 + Math.abs(Math.sin(t * 2.6 + k * 0.5)) * 130 + Math.abs(Math.sin(t * 4.3 + k)) * 44;
        return R("rect", { key: "eq" + k, x: 120 + k * 46, y: u.H - 150 - h, width: 26, height: h, rx: 10, fill: rgba(k % 4 === 0 ? th.accent : th.accent2, 0.55 + (k % 3) * 0.12) });
      }),
      Array.from({ length: 5 }).map((_, k) => R("rect", { key: "sl" + k, x: 120 + k * 30, y: 200 - (k % 2) * 12, width: 24, height: 210, rx: 4, fill: rgba([th.accent, th.accent2, th.paper][k % 3], 0.4), transform: "rotate(" + (k - 2) * 3 + " " + (132 + k * 30) + " 300)" }))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
