// NINE LIVES — skin for the shared long-form stage (services/lf_stage.js).
//
// GENERATED by scripts/gen-lf-skins.js from the handoff source
// (templete-design/longform-handoff/engine/lf-pack-1.js, template "NineLives").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Playfair Display / body Karla. Camera set ["zoomOut","drop","pushL","zoomIn","pushU"] at stride 3/2.
// 40 scenes, 300.5s, 9 spine overrides.
//
// palette and World below are the AUTHORED functions, emitted verbatim. The World is
// re-evaluated per seek against an SVG-DOM shim whose entire surface is {R, rgba} plus the
// utils object — verified by evaluating all 30 authored Worlds against exactly that sandbox —
// so the backdrop is not a reinterpretation of the original, it IS the original.

const stage = require("../lf_stage");

const SKIN = {
  id: "nine-lives",
  label: "Nine Lives",

  // ---- type ----
  display: "Playfair Display", displayFallback: "Georgia, serif",
  body: "Karla", bodyFallback: "system-ui, sans-serif",
  em: 0.6092, bodyEm: 0.5853,

  // ---- palette ----
  // The authored function, called with {} for the design's own defaults. It returns the same
  // six roles on every one of the 27 films, so the stage can rely on them by name: paper and
  // ink are the type system, sageT and terraT are the alternating tinted grounds, and
  // accent/accent2 are the two a brand may take over at their authored luminance.
  palette: (t) => ({ paper: "#f4eee4", ink: "#241f28", accent: t.accent || "#b9647a", accent2: t.accent2 || "#5f7f8c", sageT: "#e4e9ea", terraT: "#f3e2e4" }),
  accents: ["accent","accent2"],
  accentOpts: ["#b9647a","#9c5f8c","#c07a5a"],
  accent2Opts: ["#5f7f8c","#6b7a5f","#7a6b8c"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  desk: "#1e1a22",

  // ---- camera + motion ----
  cams: ["zoomOut","drop","pushL","zoomIn","pushU"],
  camStride: 3, camOff: 2,
  ambient: 1.2,

  // ---- the garnish voice ----
  // Rotated by scene index so no two consecutive frames read the same. Authored copy.
  tags: ["NINE LIVES · A CAT FILM","SUNBEAM DEPARTMENT","NAP ARCHITECTURE","THE COUNTER IS THEIRS NOW","STAFF: ONE CAT"],
  foots: ["filmed between naps, quietly","the yarn lost this argument","sunbeam moves, cat follows","consent negotiated hourly","purring measured at 26 hz"],
  sides: ["SLEEP · STRETCH · JUDGE","SIXTEEN HOURS A DAY","THE BOX WON AGAIN"],

  // ---- the spine ----
  // Which renderer runs at which index. The stage owns the canonical 40-name order; this is
  // only what THIS film does differently. ["insert", i, name] splices, [i, name] substitutes.
  // Resolves to: 40 scenes.
  spineOverrides: [[1,"Breathe"],[2,"Problem"],[4,"Wave"],[9,"Blink"],[28,"Accordion"],[32,"Gauge"],[33,"TearOff"],[34,"Bloom"],[35,"Patience"]],

  strings: {
    brandName: "Nine Lives",
  },

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, utils) — no Math.random, no
  // Date, no accumulated state anywhere in the six pack files — which is what lets it be
  // re-evaluated deterministically on every seek, forwards or backwards.
  World: (th, t, u) => R("g", null,
      R("polygon", { points: "260,-20 620,-20 " + (420 + Math.sin(t * 0.2) * 40) + "," + u.H + " " + (60 + Math.sin(t * 0.2) * 40) + "," + u.H, fill: rgba("#ffe8b0", u.dark ? 0.05 : 0.16) }),
      (function () {
        const br = 1 + Math.sin(t * 1.1) * 0.02, ear = Math.sin(t * 4) > 0.86 ? -14 : 0;
        const cx = u.W - 300, cy = u.H - 230;
        return R("g", { transform: "translate(" + cx + "," + cy + ") scale(" + br + ")" },
          R("path", { d: "M -150 0 q -20 -110 90 -120 q 130 -12 170 60 q 30 60 -40 60 z", fill: rgba(th.ink, 0.88) }),
          R("circle", { cx: 96, cy: -104, r: 46, fill: rgba(th.ink, 0.88) }),
          R("path", { d: "M 62 -138 l 6 -46 l 34 26 z", fill: rgba(th.ink, 0.88), transform: "rotate(" + ear + " 68 -140)" }),
          R("path", { d: "M 118 -142 l 22 -40 l 22 34 z", fill: rgba(th.ink, 0.88) }),
          R("path", { d: "M -150 0 q -80 6 -96 -70", fill: "none", stroke: rgba(th.ink, 0.88), strokeWidth: 22, strokeLinecap: "round", transform: "rotate(" + Math.sin(t * 1.6) * 12 + " -150 0)" }),
          R("ellipse", { cy: 8, rx: 190, ry: 16, fill: rgba(th.ink, 0.2) }));
      })(),
      (function () {
        const un = (t * 0.16) % 1, bx = 220 - un * 90;
        return R("g", null,
          R("path", { d: "M " + bx + " " + (u.H - 160) + " q 160 -30 300 24 q 120 46 240 -10", fill: "none", stroke: rgba(th.accent, 0.55), strokeWidth: 7, strokeDasharray: 1200, strokeDashoffset: 1200 * (1 - un) }),
          R("g", { transform: "translate(" + bx + "," + (u.H - 160) + ") rotate(" + t * 90 + ")" },
            R("circle", { r: 40 * (1 - un * 0.35), fill: th.accent }),
            R("path", { d: "M -34 -12 q 34 24 68 -6 M -30 14 q 30 -30 62 -10", fill: "none", stroke: rgba(th.paper, 0.6), strokeWidth: 4 })));
      })(),
      Array.from({ length: 12 }).map((_, k) => R("circle", { key: k, cx: 300 + ((k * 61) % 360) + Math.sin(t * 0.5 + k) * 30, cy: 160 + ((k * 97) % 620) + Math.cos(t * 0.4 + k * 1.3) * 26, r: 2.4, fill: rgba("#ffe8b0", 0.5) }))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
