// SLOW POUR — skin for the shared long-form stage (services/lf_stage.js).
//
// GENERATED by scripts/gen-lf-skins.js from the handoff source
// (templete-design/longform-handoff/engine/lf-pack-4.js, template "SlowPour").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Alfa Slab One / body Karla. Camera set ["zoomIn","pushL","drop","pushR","zoomOut","hopU"] at stride 5/1.
// 40 scenes, 300.5s, 1 spine override.
//
// palette and World below are the AUTHORED functions, emitted verbatim. The World is
// re-evaluated per seek against an SVG-DOM shim whose entire surface is {R, rgba} plus the
// utils object — verified by evaluating all 30 authored Worlds against exactly that sandbox —
// so the backdrop is not a reinterpretation of the original, it IS the original.

const stage = require("../lf_stage");

const SKIN = {
  id: "slow-pour",
  label: "Slow Pour",

  // ---- type ----
  display: "Alfa Slab One", displayFallback: "Georgia, serif",
  body: "Karla", bodyFallback: "system-ui, sans-serif",
  em: 0.7492, bodyEm: 0.5853,

  // ---- palette ----
  // The authored function, called with {} for the design's own defaults. It returns the same
  // six roles on every one of the 27 films, so the stage can rely on them by name: paper and
  // ink are the type system, sageT and terraT are the alternating tinted grounds, and
  // accent/accent2 are the two a brand may take over at their authored luminance.
  palette: (t) => ({ paper: "#f6ecdd", ink: "#231a15", accent: t.accent || "#c4622c", accent2: t.accent2 || "#6b8c7a", sageT: "#e6eee8", terraT: "#f7e0c8" }),
  accents: ["accent","accent2"],
  accentOpts: ["#c4622c","#a04a2c","#c48a3c"],
  accent2Opts: ["#6b8c7a","#5f6b8c","#8c7a5f"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  desk: "#1d1512",

  // ---- camera + motion ----
  cams: ["zoomIn","pushL","drop","pushR","zoomOut","hopU"],
  camStride: 5, camOff: 1,
  ambient: 1.6,

  // ---- the garnish voice ----
  // Rotated by scene index so no two consecutive frames read the same. Authored copy.
  tags: ["SLOW POUR · A COFFEE FILM","NINETY-FOUR DEGREES","1:16, ALWAYS","GRIND FRESH OR DO NOT BOTHER","THREE MINUTES, NO RUSHING"],
  foots: ["brewed at 1:16, weighed to the gram","the kettle has a gooseneck for a reason","beans roasted nine days ago","third pour is where it goes wrong","the scale is the only honest tool"],
  sides: ["GRIND · BLOOM · POUR · WAIT","NINETY-FOUR DEGREES EXACTLY","THREE MINUTES, START TO CUP"],

  // ---- the spine ----
  // Which renderer runs at which index. The stage owns the canonical 40-name order; this is
  // only what THIS film does differently. ["insert", i, name] splices, [i, name] substitutes.
  // Resolves to: 40 scenes.
  spineOverrides: [[2,"Blink"]],

  strings: {
    brandName: "Slow Pour",
  },

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, utils) — no Math.random, no
  // Date, no accumulated state anywhere in the six pack files — which is what lets it be
  // re-evaluated deterministically on every seek, forwards or backwards.
  World: (th, t, u) => R("g", null,
      (function () {
        const spiral = [];
        const turns = 3.2, steps = 90, prog = ((t * 0.28) % 1);
        for (let i = 0; i < steps * prog; i++) {
          const a = (i / steps) * Math.PI * 2 * turns, r = 12 + (i / steps) * 70;
          spiral.push((i ? "L" : "M") + (Math.cos(a) * r) + " " + (Math.sin(a) * r * 0.42));
        }
        return R("g", { transform: "translate(" + (u.W - 280) + "," + (u.H - 400) + ")" },
          R("path", { d: "M -120 0 q 0 130 120 130 q 120 0 120 -130 z", fill: rgba(th.ink, 0.16) }),
          R("ellipse", { rx: 122, ry: 34, fill: rgba(th.accent, 0.35) }),
          R("path", { d: spiral.join(" "), fill: "none", stroke: rgba(th.paper, 0.75), strokeWidth: 5, strokeLinecap: "round" }),
          Array.from({ length: 8 }).map((_, k) => R("circle", { key: k, cx: Math.cos(t * 2 + k) * (30 + (k % 3) * 24), cy: Math.sin(t * 2 + k) * 14, r: 5 + (k % 3) * 3, fill: rgba("#c49a6b", 0.5) })));
      })(),
      (function () {
        const tilt = 34 + Math.sin(t * 0.8) * 5;
        return R("g", { transform: "translate(" + (u.W - 430) + "," + (u.H - 640) + ") rotate(" + tilt + ")" },
          R("path", { d: "M -60 0 h 120 v 96 q 0 24 -24 24 h -72 q -24 0 -24 -24 z", fill: rgba(th.ink, 0.8) }),
          R("path", { d: "M 56 10 q 90 -10 116 96", fill: "none", stroke: rgba(th.ink, 0.8), strokeWidth: 13 }),
          R("path", { d: "M -60 20 q -54 40 -6 66", fill: "none", stroke: rgba(th.ink, 0.8), strokeWidth: 11 }));
      })(),
      Array.from({ length: 6 }).map((_, k) => {
        const ph = (t * 0.4 + k * 0.16) % 1;
        return R("circle", { key: "d" + k, cx: 260, cy: 300 + ph * (u.H - 560), r: 6 * (1 - ph * 0.4), fill: rgba(th.accent, 0.6 * (1 - ph)) });
      }),
      R("g", { transform: "translate(200," + (u.H - 220) + ")" },
        R("rect", { x: -110, y: -14, width: 220, height: 34, rx: 12, fill: rgba(th.ink, 0.7) }),
        R("text", { y: 12, textAnchor: "middle", fontFamily: '"Karla", sans-serif', fontSize: 26, fill: rgba(th.paper, 0.9) }, (14 + Math.floor(Math.abs(Math.sin(t * 0.5)) * 240)) + " g")),
      R("path", { d: "M 130 300 q 26 -60 -6 -120 q -26 -56 6 -110", fill: "none", stroke: rgba(th.paper, u.dark ? 0.12 : 0.18), strokeWidth: 12, strokeLinecap: "round" })),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
