// STEEP & STEAM — skin for the shared long-form stage (services/lf_stage.js).
//
// GENERATED by scripts/gen-lf-skins.js from the handoff source
// (templete-design/longform-handoff/engine/lf-pack-5.js, template "SteepSteam").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Marcellus / body Mukta. Camera set ["zoomOut","pushU","zoomIn","pushL","drop","pushR"] at stride 3/1.
// 41 scenes, 308s, 2 spine overrides.
//
// palette and World below are the AUTHORED functions, emitted verbatim. The World is
// re-evaluated per seek against an SVG-DOM shim whose entire surface is {R, rgba} plus the
// utils object — verified by evaluating all 30 authored Worlds against exactly that sandbox —
// so the backdrop is not a reinterpretation of the original, it IS the original.

const stage = require("../lf_stage");

const SKIN = {
  id: "steep-and-steam",
  label: "Steep & Steam",

  // ---- type ----
  display: "Marcellus", displayFallback: "Georgia, serif",
  body: "Mukta", bodyFallback: "system-ui, sans-serif",
  em: 0.6072, bodyEm: 0.5473,

  // ---- palette ----
  // The authored function, called with {} for the design's own defaults. It returns the same
  // six roles on every one of the 27 films, so the stage can rely on them by name: paper and
  // ink are the type system, sageT and terraT are the alternating tinted grounds, and
  // accent/accent2 are the two a brand may take over at their authored luminance.
  palette: (t) => ({ paper: "#f6f2e8", ink: "#232a20", accent: t.accent || "#7a8c3f", accent2: t.accent2 || "#a8763c", sageT: "#e8eee0", terraT: "#f6e8d6" }),
  accents: ["accent","accent2"],
  accentOpts: ["#7a8c3f","#5f7a52","#8c8c3f"],
  accent2Opts: ["#a8763c","#8c5f3c","#3c7a8c"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  desk: "#1b1f18",

  // ---- camera + motion ----
  cams: ["zoomOut","pushU","zoomIn","pushL","drop","pushR"],
  camStride: 3, camOff: 1,
  ambient: 1.3,

  // ---- the garnish voice ----
  // Rotated by scene index so no two consecutive frames read the same. Authored copy.
  tags: ["STEEP & STEAM · A TEA FILM","SEVENTY DEGREES, NOT MORE","NINE STEEPS FROM ONE LEAF","THE THIRD IS THE TRUTH","NO WIFI PASSWORD"],
  foots: ["water at seventy, measured every time","the third steep is where it opens up","leaves used nine times, then composted","clay pot seasoned over eleven years","silence is part of the service"],
  sides: ["WARM · RINSE · STEEP · POUR","SEVENTY DEGREES EXACTLY","NINE STEEPS, ONE LEAF"],

  // ---- the spine ----
  // Which renderer runs at which index. The stage owns the canonical 40-name order; this is
  // only what THIS film does differently. ["insert", i, name] splices, [i, name] substitutes.
  // Resolves to: 41 scenes.
  spineOverrides: [["insert",36,"Patience"],[2,"Wave"]],

  strings: {
    brandName: "Steep & Steam",
  },

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, utils) — no Math.random, no
  // Date, no accumulated state anywhere in the six pack files — which is what lets it be
  // re-evaluated deterministically on every seek, forwards or backwards.
  World: (th, t, u) => R("g", null,
      (function () {
        const arc = [];
        const prog = ((t * 0.4) % 1.3);
        for (let i = 0; i < 40 * Math.min(1, prog); i++) { const q = i / 40; arc.push((i ? "L" : "M") + (q * 200) + " " + (Math.pow(q, 2) * 220)); }
        return R("g", { transform: "translate(" + (u.W - 620) + "," + (u.H - 620) + ")" },
          R("path", { d: "M -70 0 h 150 v 90 q 0 26 -30 26 h -90 q -30 0 -30 -26 z", fill: rgba(th.accent2, 0.85) }),
          R("path", { d: "M 80 20 q 70 -6 96 80", fill: "none", stroke: rgba(th.accent2, 0.85), strokeWidth: 12 }),
          R("path", { d: arc.join(" "), fill: "none", stroke: rgba(th.paper, 0.6), strokeWidth: 6, strokeLinecap: "round", transform: "translate(176,96)" }));
      })(),
      R("g", { transform: "translate(" + (u.W - 300) + "," + (u.H - 260) + ")" },
        R("path", { d: "M -100 0 a 100 68 0 0 0 200 0 z", fill: rgba(th.accent, 0.7) }),
        R("ellipse", { rx: 100, ry: 20, fill: rgba(th.ink, 0.25) }),
        [0, 1, 2].map((k) => {
          const ph = (t * 0.22 + k * 0.33) % 1;
          return R("path", { key: k, d: "M " + (-40 + k * 40) + " " + (-30 - ph * 420) + " q 26 -44 0 -88 q -26 -44 0 -88", fill: "none", stroke: rgba(th.paper, 0.2 * (1 - ph)), strokeWidth: 13, strokeLinecap: "round" });
        })),
      [0, 1, 2, 3, 4].map((k) => {
        const open = Math.min(1, ((t * 0.2 + k * 0.14) % 1.6));
        return R("path", { key: "lf" + k, d: "M 0 0 q " + (30 + open * 40) + " -" + (12 + open * 26) + " " + (66 + open * 40) + " 4 q -" + (30 + open * 30) + " " + (18 + open * 22) + " -" + (66 + open * 40) + " -4 z", fill: rgba(th.accent, 0.35 + open * 0.3), transform: "translate(" + (170 + k * 90) + "," + (u.H - 300 + (k % 2) * 60) + ") rotate(" + (k * 40 + Math.sin(t + k) * 8) + ")" });
      }),
      R("circle", { cx: 240, cy: 280, r: 74, fill: "none", stroke: rgba(th.accent2, 0.4), strokeWidth: 4, strokeDasharray: 465, strokeDashoffset: 465 * (1 - ((t * 0.16) % 1)) }),
      R("text", { x: 240, y: 292, textAnchor: "middle", fontFamily: '"Marcellus", serif', fontSize: 40, fill: rgba(th.ink, u.dark ? 0.5 : 0.55) }, "\u8336")),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
