// TIDE TABLE — skin for the shared long-form stage (services/lf_stage.js).
//
// GENERATED by scripts/gen-lf-skins.js from the handoff source
// (templete-design/longform-handoff/engine/lf-pack-2.js, template "TideTable").
// Edit the handoff source and re-run the generator rather than editing this file.
//
// Display Chonburi / body Prompt. Camera set ["pushL","zoomOut","pushU","drop","pushR","zoomIn"] at stride 5/2.
// 40 scenes, 300.5s, 1 spine override.
//
// palette and World below are the AUTHORED functions, emitted verbatim. The World is
// re-evaluated per seek against an SVG-DOM shim whose entire surface is {R, rgba} plus the
// utils object — verified by evaluating all 30 authored Worlds against exactly that sandbox —
// so the backdrop is not a reinterpretation of the original, it IS the original.

const stage = require("../lf_stage");

const SKIN = {
  id: "tide-table",
  label: "Tide Table",

  // ---- type ----
  display: "Chonburi", displayFallback: "Georgia, serif",
  body: "Prompt", bodyFallback: "system-ui, sans-serif",
  em: 0.7352, bodyEm: 0.6366,

  // ---- palette ----
  // The authored function, called with {} for the design's own defaults. It returns the same
  // six roles on every one of the 27 films, so the stage can rely on them by name: paper and
  // ink are the type system, sageT and terraT are the alternating tinted grounds, and
  // accent/accent2 are the two a brand may take over at their authored luminance.
  palette: (t) => ({ paper: "#f6f1e2", ink: "#14262e", accent: t.accent || "#e8763c", accent2: t.accent2 || "#2c8c9e", sageT: "#e2eeec", terraT: "#f8e4cd" }),
  accents: ["accent","accent2"],
  accentOpts: ["#e8763c","#e0b03c","#e05a7a"],
  accent2Opts: ["#2c8c9e","#3c6b9e","#2c9e7a"],
  groundKey: "paper", inkKey: "ink", paperKey: "paper",
  desk: "#0e2028",

  // ---- camera + motion ----
  cams: ["pushL","zoomOut","pushU","drop","pushR","zoomIn"],
  camStride: 5, camOff: 2,
  ambient: 1.5,

  // ---- the garnish voice ----
  // Rotated by scene index so no two consecutive frames read the same. Authored copy.
  tags: ["TIDE TABLE · A COAST FILM","LOW AT 06:12","SAND IN EVERYTHING","SWIM BEFORE BREAKFAST","THE SEA DECIDES"],
  foots: ["timed against the tide, not the clock","water was 14 degrees and worth it","the parasol lost, twice","everything here smells of salt","the last swim was the best one"],
  sides: ["SWIM · DRY · SWIM AGAIN","CHECK THE TIDE FIRST","FOURTEEN DEGREES, FINE"],

  // ---- the spine ----
  // Which renderer runs at which index. The stage owns the canonical 40-name order; this is
  // only what THIS film does differently. ["insert", i, name] splices, [i, name] substitutes.
  // Resolves to: 40 scenes.
  spineOverrides: [[2,"Wave"]],

  strings: {
    brandName: "Tide Table",
  },

  // ---- the world ----
  // The authored animated backdrop, verbatim. Pure in (theme, t, utils) — no Math.random, no
  // Date, no accumulated state anywhere in the six pack files — which is what lets it be
  // re-evaluated deterministically on every seek, forwards or backwards.
  World: (th, t, u) => R("g", null,
      R("circle", { cx: u.W - 260, cy: 210, r: 88, fill: rgba(th.accent, u.dark ? 0.2 : 0.32) }),
      Array.from({ length: 6 }).map((_, k) => R("line", { key: "gl" + k, x1: u.W - 260, y1: 210, x2: u.W - 260 + Math.cos(t * 0.4 + k) * 220, y2: 210 + Math.sin(t * 0.4 + k) * 220, stroke: rgba(th.accent, 0.08), strokeWidth: 26, strokeLinecap: "round" })),
      [0, 1, 2, 3].map((k) => R("path", { key: "w" + k, d: "M -80 " + (u.H - 320 + k * 74) + " " + Array.from({ length: 8 }).map((_, s) => "q 90 " + (s % 2 ? 26 : -26) + " 180 0").join(" "), fill: "none", stroke: rgba(k === 0 ? th.paper : th.accent2, 0.55 - k * 0.1), strokeWidth: 10 - k * 1.6, strokeLinecap: "round", transform: "translate(" + (-((t * (52 + k * 20)) % 360)) + ",0)" })),
      R("rect", { x: -40, y: u.H - 130, width: u.W + 80, height: 200, fill: rgba("#e8d8b0", 0.6) }),
      (function () {
        const sp = t * 22;
        return R("g", { transform: "translate(260," + (u.H - 330) + ")" },
          R("line", { x1: 0, y1: 0, x2: 0, y2: 230, stroke: rgba(th.ink, 0.7), strokeWidth: 9 }),
          R("g", { transform: "rotate(" + sp + ")" },
            [0, 1, 2, 3, 4, 5].map((k) => R("path", { key: k, d: "M 0 0 L 108 -26 L 108 26 Z", fill: rgba(k % 2 ? th.accent : th.paper, 0.9), transform: "rotate(" + k * 60 + ")" }))),
          R("circle", { r: 12, fill: rgba(th.ink, 0.8) }));
      })(),
      [0, 1].map((k) => R("path", { key: "g" + k, d: "M " + (620 + k * 240 + Math.sin(t * 0.7 + k) * 90) + " " + (240 + k * 90 + Math.cos(t * 0.8 + k) * 30) + " q 18 -20 36 0 q 18 -20 36 0", fill: "none", stroke: rgba(th.ink, 0.55), strokeWidth: 5, strokeLinecap: "round" }))),
};

module.exports = {
  buildComposition: (opts) => stage.build(SKIN, opts),
  STRINGS: { ...stage.BASE_STRINGS, ...SKIN.strings },
  SKIN,
};
